Logging Panel  Interface Board: crc.c File Reference
crc.c File Reference
#include "crc.h"
Functions
void Calc_CRC (uint16_t nbits, uint8_t thebits)
uint8_t Calc_CRC_Array (uint16_t Count, const uint8_t Bytes[])
uint8_t Calc_CRC_Uplink (uint16_t Count, const uint8_t Bytes[])
void Reset_CRC_Value (void)
uint8_t Get_CRC_Value (void)
Variables
static uint8_t CRCVal
Detailed Description
Company: Hunting Titan
File Name: crc.c
Summary: These files calculate the CRC for the different communication functions.
Description: These files calculate the CRC for the different communication functions. No state machine is used here. These functions are called directly as needed.
Definition in file crc.c.
Function Documentation
Calc_CRC()
void Calc_CRC (uint16_t nbits, uint8_t thebits)
Function: void CalcCRC(uint16_t nbits, uint8_t thebits)
Summary: Function to calculate the CRC for a number of data bits.
Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 55 of file crc.c.
Referenced by Calc_CRC_Array(), Calc_CRC_Uplink(), and FSK_Tasks().
Calc_CRC_Array()
uint8_t Calc_CRC_Array (uint16_t Count, const uint8_t Bytes[])
Function: uint8_t Calc_CRC__Array(uint16_t Count, uint8_t Bytes[ ])
Summary: Function to calculate the CRC of an array of bytes. This function uses the function CalcCRC to complete this task.
Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 92 of file crc.c.
Calc_CRC_Uplink()
uint8_t Calc_CRC_Uplink (uint16_t Count, const uint8_t Bytes[])
Function: uint8_t Calc_CRC_Uplink(uint16_t Count, uint8_t Bytes[ ])
Summary: Function to calculate the CRC from a received PerfSwitch message.
Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 116 of file crc.c.
Get_CRC_Value()
uint8_t Get_CRC_Value (void)
Function: uint8_t Get_CRC_Value(void)
Summary: Function to return a previously calculated CRC value.
Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 157 of file crc.c.
Referenced by FSK_Tasks().
Reset_CRC_Value()
void Reset_CRC_Value (void)
Function: void Reset_CRC_Value(void)
Summary: Function to reset the calculate CRC value (CRCVal).
Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 141 of file crc.c.
Referenced by Calc_CRC_Array(), Calc_CRC_Uplink(), and FSK_Tasks().
Variable Documentation
CRCVal
uint8_t CRCVal static
Definition at line 36 of file crc.c.
Referenced by Calc_CRC(), Calc_CRC_Array(), Calc_CRC_Uplink(), Get_CRC_Value(), and Reset_CRC_Value().