Logging Panel  Interface Board: fifo.c File Reference
fifo.c File Reference
#include "fifo.h"
Functions
static void Fifo_Init (TFifo *ptrFifo, uint8_t *ptrBuffer, uint16_t Length)
void Init_Fifo (void)
uint8_t Fifo_Put (TFifo *ptrFifo, uint8_t Data)
uint8_t Fifo_Get (TFifo *ptrFifo)
uint8_t Fifo_Length (TFifo *ptrFifo)
Variables
TFifo RX_FIFO
TFifo TX_FIFO
static uint8_t FifoRxBuffer [FIFO_RX_SIZE]
static uint8_t FifoTxBuffer [FIFO_TX_SIZE]
Detailed Description
Company: Hunting Titan
File Name: fifo.c
Summary: This file contains the functions to initialize a FIFO buffer or add/retrieve an entry from the buffer.
Description: This file contains the functions to initialize a FIFO buffer or add/retrieve an entry from the buffer. No state machine is used here. These functions are called directly as needed.
Definition in file fifo.c.
Function Documentation
Fifo_Get()
uint8_t Fifo_Get (TFifo * ptrFifo)
Function: uint8_t Fifo_Get(TFifo *ptrFifo)
Summary: Function to retrieve the oldest entry from a Fifo. It also provides a check for an empty Fifo.
Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 160 of file fifo.c.
Referenced by ValidateComm().
Fifo_Init()
static void Fifo_Init (TFifo * ptrFifo, uint8_t * ptrBuffer, uint16_t Length) static
Function: void Fifo_Init(TFifo *ptrFifo, uint8_t *ptrBuffer, uint16_t Length)
Summary: Function to initialize a Fifo.
Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 70 of file fifo.c.
Referenced by Init_Fifo().
Fifo_Length()
uint8_t Fifo_Length (TFifo * ptrFifo)
Function: uint8_t Fifo_Length(TFifo *ptrFifo)
Summary: Function to find the length of the buffer.
Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 202 of file fifo.c.
Referenced by HID_Tasks().
Fifo_Put()
uint8_t Fifo_Put (TFifo * ptrFifo, uint8_t Data)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data)
Summary: Function to put a byte of data into a Fifo. It also provides a check for a full Fifo.
Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 117 of file fifo.c.
Referenced by HID_Tasks().
Init_Fifo()
void Init_Fifo (void)
Function: void Init_Fifo(void)
Summary: Function to initialize the Tx and Rx FIFOs.
Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 100 of file fifo.c.
Referenced by APP_Initialize().
Variable Documentation
FifoRxBuffer
uint8_t FifoRxBuffer[FIFO_RX_SIZE] static
Definition at line 50 of file fifo.c.
Referenced by Init_Fifo().
FifoTxBuffer
uint8_t FifoTxBuffer[FIFO_TX_SIZE] static
Definition at line 51 of file fifo.c.
Referenced by Init_Fifo().
RX_FIFO
TFifo RX_FIFO
Definition at line 47 of file fifo.c.
Referenced by HID_Tasks(), Init_Fifo(), and ValidateComm().
TX_FIFO
TFifo TX_FIFO
Definition at line 48 of file fifo.c.
Referenced by Init_Fifo().