Logging Panel  Interface Board: gamma.c File Reference
gamma.c File Reference
#include "gamma.h"
#include "report.h"
#include "switches.h"
#include "nvm_fs.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <math.h>
#include <xc.h>
#include "system_config.h"
#include "system_definitions.h"
Functions
static void SPI_2_EventHandler (DRV_SPI_BUFFER_EVENT event, DRV_SPI_BUFFER_HANDLE bufferHandle, void *context)
void GAMMA_Tasks (void)
void GAMMA_Init (void)
void GAMMA_Counts (void)
void GAMMA_Gain (void)
Variables
GAMMA_DATA GAM
Detailed Description
Company: Hunting Titan
File Name: gamma.c
Summary: This file contains the state machine code for the GAMMA operation.
Description: This file contains the state machine code for the GAMMA operation. Once started, the GAMMA detects a change in the gamma detector line. The count is incremented and the amount updated once per second. Each second starts a new count.
Definition in file gamma.c.
Function Documentation
GAMMA_Counts()
void GAMMA_Counts (void)
Function: void GAMMA_Counts (void)
Summary: Track the gamma counts as the wire-line tool travels in the well.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 207 of file gamma.c.
Referenced by APP_Tasks().
GAMMA_Gain()
void GAMMA_Gain (void)
Function: void GAMMA_Gain (void)
Summary: Function to adjust the gain settings for the gamma detector first stage.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 250 of file gamma.c.
Referenced by GAMMA_Tasks().
GAMMA_Init()
void GAMMA_Init (void)
Function: void GAMMA_Init(void)
Summary: This function initializes the gamma variables.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 180 of file gamma.c.
Referenced by GAMMA_Tasks().
GAMMA_Tasks()
void GAMMA_Tasks (void)
Function:
void GAMMA_Tasks(void)
Summary: GAMMA_Tasks function
Description: This routine is the GAMMA_Tasks function. It defines the GAMMA_Tasks state machine and core logic. This machine is used to monitor the gamma counts.
Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this.
Parameters: None.
Returns: None.
Remarks: This routine must be called from the APP_Tasks() routine.
Example: GAMMA_Tasks()
Definition at line 98 of file gamma.c.
Referenced by APP_Tasks().
SPI_2_EventHandler()
static void SPI_2_EventHandler (DRV_SPI_BUFFER_EVENT event, DRV_SPI_BUFFER_HANDLE bufferHandle, void * context) static
Definition at line 71 of file gamma.c.
Referenced by GAMMA_Gain().
Variable Documentation
GAM
GAMMA_DATA GAM
Definition at line 62 of file gamma.c.
Referenced by Execute_Protocol_A(), GAMMA_Counts(), GAMMA_Gain(), GAMMA_Init(), GAMMA_Tasks(), NVM_FS_Tasks(), SPI_2_EventHandler(), and TIMER_Tasks().