Logging Panel  Interface Board: gamma.h File Reference
gamma.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "../system_definitions.h"
Data Structures
struct GAMMA_DATA
Enumerations
enum GAM_STATES {
GAM_STATE_INIT =0 , GAM_STATE_INIT_SPI_GAM , GAM_STATE_GAIN_ADJ , GAM_STATE_SPI_WRITE_WAIT ,
GAM_STATE_IDLE
}
Functions
void GAMMA_Init (void)
void GAMMA_Counts (void)
void GAMMA_Gain (void)
void GAMMA_Tasks (void)
Variables
GAMMA_DATA GAM
Detailed Description
Company: Hunting Titan
File Name: gamma.h
Summary: This header file provides prototypes and definitions for gamma.c.
Description: This header file provides function prototypes and data type definitions for gamma.c. These are required by the system to track the gamma counts.
Definition in file gamma.h.
Enumeration Type Documentation
GAM_STATES
enum GAM_STATES
Enumerator
GAM_STATE_INIT
Application's state machine's initial state.
GAM_STATE_INIT_SPI_GAM
Open SPI port for GAM gain pot and initialize GAM to minimum gain.
GAM_STATE_GAIN_ADJ
Adjust gamma gain per the switch setting.
GAM_STATE_SPI_WRITE_WAIT
Wait until the SPI write has completed.
GAM_STATE_IDLE
Move the state machine to idle.
Definition at line 56 of file gamma.h.
Function Documentation
GAMMA_Counts()
void GAMMA_Counts (void)
Function: void GAMMA_Counts(void)
Summary: Function to track the counts from the gamma detector.
Description: Function to track the counts from the gamma detector. When a transition from the gamma detector is detected, a flag is set in system interrupt. One gamma count causes two interrupts. This is accounted for. The count is then transferred to the REPORT array for later transmission to the host.
Precondition: None.
Parameters: None.
Returns None.
Remarks None.
Example: GAMMA_Counts()
Function: void GAMMA_Counts (void)
Summary: Track the gamma counts as the wire-line tool travels in the well.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 207 of file gamma.c.
Referenced by APP_Tasks().
GAMMA_Gain()
void GAMMA_Gain (void)
Function: void GAMMA_Gain(void)
Summary: Function to track the gain setting for the gamma detector first stage.
Description: Function to track the gain setting for the gamma detector. When the STATUS_LED
button is pressed, it will toggle through ten different gain settings. The gain of the first stage is adjusted. The gain setting is sent to the host PC for display.
Precondition: None.
Parameters: None.
Returns None.
Remarks None.
Example: GAMMA_Gain()
Function: void GAMMA_Gain (void)
Summary: Function to adjust the gain settings for the gamma detector first stage.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 250 of file gamma.c.
Referenced by GAMMA_Tasks().
GAMMA_Init()
void GAMMA_Init (void)
Function: void GAMMA_Init(void)
Summary: Function to initialize the gamma variables.
Description: Function to initialize the gamma variables. These variables are used to track the gamma counts.
Precondition: None.
Parameters: None.
Returns None.
Remarks None.
Example: GAMMA_Init()
Function: void GAMMA_Init(void)
Summary: This function initializes the gamma variables.
Remarks: Refer to the gamma.h interface header for function usage details.
Definition at line 180 of file gamma.c.
Referenced by GAMMA_Tasks().
GAMMA_Tasks()
void GAMMA_Tasks (void)
Function:
void GAMMA_Tasks(void)
Summary: GAMMA_Tasks function
Description: This routine is the GAMMA_Tasks function. It defines the GAMMA_Tasks state machine and core logic. This machine is used to monitor the gamma counts.
Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this.
Parameters: None.
Returns: None.
Remarks: This routine must be called from the APP_Tasks() routine.
Example: GAMMA_Tasks()
Definition at line 98 of file gamma.c.
Referenced by APP_Tasks().
Variable Documentation
GAM
GAMMA_DATA GAM extern
Definition at line 62 of file gamma.c.
Referenced by Execute_Protocol_A(), GAMMA_Counts(), GAMMA_Gain(), GAMMA_Init(), GAMMA_Tasks(), NVM_FS_Tasks(), SPI_2_EventHandler(), and TIMER_Tasks().