Logging Panel  Interface Board: hid.c File Reference
hid.c File Reference
#include "system_definitions.h"
#include "hid.h"
#include "commands.h"
#include "commmodule.h"
#include "fifo.h"
Functions
USB_DEVICE_HID_EVENT_RESPONSE APP_USBDeviceHIDEventHandler (USB_DEVICE_HID_INDEX iHID, USB_DEVICE_HID_EVENT event, void *eventData, uintptr_t userData)
void APP_USBDeviceEventHandler (USB_DEVICE_EVENT event, void *eventData, uintptr_t context)
void HID_Initialize (void)
void HID_Tasks (void)
Variables
uint8_t receiveDataBuffer[64] APP_MAKE_BUFFER_DMA_READY
APP_DATA appData
Detailed Description
Company: Hunting Titan
File Name: hid.c
Summary: This file contains the source code for the USB HID tasks and functions.
Description: This file contains the source code for the USB HID tasks and functions. It implements the logic of the HID's state machine and it may call API routines of other MPLAB Harmony modules in the system, such as drivers, system services, and middleware. This code is taken from the "hid_basic" example project in Harmony v2.06. It has been modified for use here. These functions work with the host to transfer data to the host in 10mS increments. This is controlled in timers.c. While the system is configured to received data, no data or commands are received from the host. The task is configured to assume the data received is 0X81H. This allows for proper operation of the HID functions. Callback and event handler functions monitor the USB for changes and configuration data from the host.
Definition in file hid.c.
Function Documentation
APP_USBDeviceEventHandler()
void APP_USBDeviceEventHandler (USB_DEVICE_EVENT event, void * eventData, uintptr_t context)
Function: void APP_USBDeviceEventHandler (USB_DEVICE_EVENT event, void * eventData, uintptr_t context)
Summary: Function to track USB device events.
Description: Function to track USB device events. Events such as when USB power is detected and removed and when the host has configured the HID connection.
Precondition: None.
Parameters: None.
Returns None.
Remarks None.
Example: void APP_USBDeviceEventHandler (USB_DEVICE_EVENT event, void * eventData, uintptr_t context)
Definition at line 204 of file hid.c.
Referenced by HID_Tasks().
APP_USBDeviceHIDEventHandler()
USB_DEVICE_HID_EVENT_RESPONSE APP_USBDeviceHIDEventHandler (USB_DEVICE_HID_INDEX iHID, USB_DEVICE_HID_EVENT event, void * eventData, uintptr_t userData)
Function: USB_DEVICE_HID_EVENT_RESPONSE APP_USBDeviceHIDEventHandler
Summary: Function to track HID events.
Description: Function to track HID events. Events such as when reports are sent and received, and when the system is in idle.
Precondition: None.
Parameters: None.
Returns None.
Remarks None.
Example: USB_DEVICE_HID_EVENT_RESPONSE APP_USBDeviceHIDEventHandler
Definition at line 97 of file hid.c.
Referenced by APP_USBDeviceEventHandler().
HID_Initialize()
void HID_Initialize (void)
Definition at line 279 of file hid.c.
Referenced by APP_Initialize().
HID_Tasks()
void HID_Tasks (void)
Function: void HID_Tasks (void)
Summary: HID tasks function
Description: This routine is the HID tasks function. It defines the HID's state machine and core logic. This machine initializes opens a USB handle, waits for configuration from the host and sends data to the host when a timer flag is set. No data is read from the host.
Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this.
Parameters: None.
Returns: None.
Example: HID_Tasks()
Remarks: This routine must be called from the APP_Tasks() routine.
Definition at line 308 of file hid.c.
Referenced by APP_Tasks().
Variable Documentation
APP_MAKE_BUFFER_DMA_READY
uint8_t transmitDataBuffer [64] APP_MAKE_BUFFER_DMA_READY
Receive data buffer.
Transmit data buffer.
Definition at line 45 of file hid.c.
appData
APP_DATA appData
Definition at line 62 of file hid.c.