Logging Panel  Interface Board: high_side.c File Reference
high_side.c File Reference
#include "high_side.h"
#include "adc.h"
#include "switches.h"
#include "gpt.h"
#include "fifo.h"
#include "commmodule.h"
#include "commands.h"
#include "report.h"
#include "statusst.h"
#include <stdbool.h>
#include <xc.h>
#include <math.h>
Functions
void HIGH_SIDE_Tasks (void)
static void ReadHSUART (void)
static void WriteHSUART (void)
Variables
HIGH_SIDE_DATA HIGH_SIDE
Detailed Description
Company: Hunting Titan
File Name: side.c
Summary: This file contains the state machine code for the HIGH_SIDE operation.
Description: This file contains the state machine code for the HIGH_SIDE operation. It implements the logic of the HIGH_SIDE's state machine. These functions monitor the
HST communication when the front panel knob is in the HIGH SIDE position. A UART is configured to receive the data. This machine reads data from the UART at 20 KBaud and puts it to the RxFifo for later use. The first 30 transmissions from the HSI tool are the 'Sign On' data that includes The Tool ID and firmware version. All transmissions afterwards are the tool data values. The states are configured so that other system tasks can be maintained while these tasks are waiting for an event to occur. It may call API routines of other MPLAB Harmony modules in the system, such as drivers, system services, and middleware.
Definition in file high_side.c.
Function Documentation
HIGH_SIDE_Tasks()
void HIGH_SIDE_Tasks (void)
Function:
void HIGH_SIDE_Tasks(void)
Summary: HIGH_SIDE_Tasks function
Description: This routine is the HIGH_SIDE_Tasks function. It defines the HIGH_SIDE_Tasks state machine and core logic. This machine is used to monitor the wire-line when the High Side tool is selected. It will receive communications from the tool and send them to the host.
Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this.
Parameters: None.
Returns: None.
Remarks: This routine must be called from the APP_Tasks() routine.
Example: HIGH_SIDE_Tasks()
Definition at line 90 of file high_side.c.
Referenced by APP_Tasks().
ReadHSUART()
static void ReadHSUART (void) static
Function: static void ReadHSUART(void)
Summary: This function reads a byte of data from the UART and transfers it to the RxFifo.
Remarks: Refer to the UART.h interface header for function usage details.
< Temporary placeholder for byte data from the host.
Definition at line 261 of file high_side.c.
Referenced by HIGH_SIDE_Tasks().
WriteHSUART()
static void WriteHSUART (void) static
Definition at line 306 of file high_side.c.
Referenced by HIGH_SIDE_Tasks().
Variable Documentation
HIGH_SIDE
HIGH_SIDE_DATA HIGH_SIDE
Definition at line 69 of file high_side.c.
Referenced by APP_Initialize(), HIGH_SIDE_Tasks(), ReadHSUART(), and TIMER_Tasks().