Panel Interface Board: inszt_crc.c File Reference
inszt_crc.c File Reference
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port_common.h"
#include "crc_54zbelem.def"
#include <stdint.h>
Data Structures
struct bitmapstruct_t
Macros
#define QQQdialect MPLABX
#define QQQswitch3
#define qqqMaxBranchDepth 20
#define QQQstructbitmap
#define QQQnumfil 23
#define QQQNOATEXIT
#define QQQUPLOADATEND
#define QQQNOSTDIO
#define QQQBITMAP
#define qqqbitmapint unsigned int
#define QQQSINGLEFILE
#define QQQFILEID
#define QQQseparate
#define crc_54zzopen zzopen
#define crc_54zqqzqz1 zqqzqz1
#define QQQLDRA_PORT
#define FILEPOINT
#define LDRA_VOID_FUNC
#define qqnull_params void
#define QQQ_PROTOTYPE_DEF
#define ELEMENT(N) qqqbitmapint element##N;
#define LASTELEMENT
#define ELEMENT(N) 0,
#define CRC_H
#define qqqbranches 32
#define QQQMAXMCDCSIZE 2
#define ldra_sscanf
#define qqnull_params void
#define qqzzidfield 1
#define QQQFIXEDSIZE
#define QQQTEMP1
#define ELEMENT(N) qqbmsoutput("%8d", bitmapstruct.element##N);
#define LASTELEMENT
Typedefs
typedef void(* ldra_void_function) ()
typedef unsigned char uchar8_t
Functions
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
static void qqoutput (FILEPOINT char *s, int i)
static void qqoutput2 (FILEPOINT char *s, int i, int j)
static void qqoutput3 (FILEPOINT char *s, int i, int j, int k)
static void qqoutput4 (FILEPOINT char *s, int i, int j, int k, int l)
static void qqoutput0 (FILEPOINT char *s)
static int crc_54zqqzqz (qqnull_params)
static int crc_54zqqzqz1 (qqnull_params)
static int crc_54zqendz (int qqqi)
static int crc_54zqzqzq (int qqqi)
static void qqqupload (qqnull_params)
static void qqqbitmapreset (qqnull_params)
void Calc_CRC (uint16_t nbits, uint8_t thebits)
uint8_t Calc_CRC_Array (uint16_t Count, const uint8_t Bytes [])
uint8_t Calc_CRC_Uplink (uint16_t Count, const uint8_t Bytes [])
void Reset_CRC_Value (void)
uint8_t Get_CRC_Value (void)
static int crc_54zscanf (char *qqscan_str)
static void qqqqinitialise (int ii)
static void qqqbitmapreset ()
static void qqbmsoutput (FILEPOINT char *s, unsigned int i)
Variables
static int qqqqbmselwidth = 32
static int zzfileid = 54
int QQQindicator
static int QQQfirstmcdc =1
int crc_54zzopen
static int tbrun_mode =0
int QQQfcn_ptr_num
ldra_void_function qqqaccumupload [QQQnumfil]
static int qqqstructzzopen = 0
static unsigned char qqqzzglobflag = 0
static struct bitmapstruct_t bitmapstruct
static uint8_t CRCVal
static char qqqqone [] = "%6d\n"
static int qqqlast = 0
int qqupload_registered
Macro Definition Documentation
crc_54zqqzqz1
#define crc_54zqqzqz1 zqqzqz1
Definition at line 77 of file inszt_crc.c.
Referenced by crc_54zqendz(), crc_54zqzqzq(), and qqqupload().
crc_54zzopen
#define crc_54zzopen zzopen
Definition at line 75 of file inszt_crc.c.
Referenced by crc_54zqendz(), crc_54zqqzqz(), crc_54zqqzqz1(), and crc_54zqzqzq().
CRC_H
#define CRC_H
Definition at line 208 of file inszt_crc.c.
ELEMENT [1/3]
#define ELEMENT (N) qqqbitmapint element##N;
Definition at line 168 of file inszt_crc.c.
ELEMENT [2/3]
#define ELEMENT (N) 0,
Definition at line 168 of file inszt_crc.c.
ELEMENT [3/3]
#define ELEMENT (N) qqbmsoutput("%8d", bitmapstruct.element##N);
Definition at line 168 of file inszt_crc.c.
FILEPOINT
#define FILEPOINT
Definition at line 90 of file inszt_crc.c.
LASTELEMENT [1/2]
#define LASTELEMENT
Definition at line 169 of file inszt_crc.c.
LASTELEMENT [2/2]
#define LASTELEMENT
Definition at line 169 of file inszt_crc.c.
ldra_sscanf
#define ldra_sscanf
Definition at line 594 of file inszt_crc.c.
LDRA_VOID_FUNC
#define LDRA_VOID_FUNC
Definition at line 112 of file inszt_crc.c.
qqnull_params [1/2]
#define qqnull_params void
Definition at line 611 of file inszt_crc.c.
qqnull_params [2/2]
#define qqnull_params void
Definition at line 611 of file inszt_crc.c.
QQQ_PROTOTYPE_DEF
#define QQQ_PROTOTYPE_DEF
Definition at line 155 of file inszt_crc.c.
QQQBITMAP
#define QQQBITMAP
Definition at line 63 of file inszt_crc.c.
qqqbitmapint
#define qqqbitmapint unsigned int
Definition at line 64 of file inszt_crc.c.
qqqbranches
#define qqqbranches 32
Definition at line 589 of file inszt_crc.c.
Referenced by qqbmsoutput().
QQQdialect
#define QQQdialect MPLABX
Definition at line 28 of file inszt_crc.c.
QQQFILEID
#define QQQFILEID
Definition at line 71 of file inszt_crc.c.
QQQFIXEDSIZE
#define QQQFIXEDSIZE
Definition at line 619 of file inszt_crc.c.
QQQLDRA_PORT
#define QQQLDRA_PORT
Definition at line 78 of file inszt_crc.c.
qqqMaxBranchDepth
#define qqqMaxBranchDepth 20
Definition at line 45 of file inszt_crc.c.
QQQMAXMCDCSIZE
#define QQQMAXMCDCSIZE 2
Definition at line 590 of file inszt_crc.c.
QQQNOATEXIT
#define QQQNOATEXIT
Definition at line 59 of file inszt_crc.c.
QQQNOSTDIO
#define QQQNOSTDIO
Definition at line 61 of file inszt_crc.c.
QQQnumfil
#define QQQnumfil 23
Definition at line 49 of file inszt_crc.c.
QQQseparate
#define QQQseparate
Definition at line 72 of file inszt_crc.c.
QQQSINGLEFILE
#define QQQSINGLEFILE
Definition at line 70 of file inszt_crc.c.
QQQstructbitmap
#define QQQstructbitmap
Definition at line 46 of file inszt_crc.c.
QQQswitch3
#define QQQswitch3
Definition at line 38 of file inszt_crc.c.
QQQTEMP1
#define QQQTEMP1
Definition at line 756 of file inszt_crc.c.
QQQUPLOADATEND
#define QQQUPLOADATEND
Definition at line 60 of file inszt_crc.c.
qqzzidfield
#define qqzzidfield 1
Definition at line 613 of file inszt_crc.c.
Typedef Documentation
ldra_void_function
typedef void(* ldra_void_function) ()
Definition at line 113 of file inszt_crc.c.
uchar8_t
typedef unsigned char uchar8_t
Definition at line 218 of file inszt_crc.c.
Function Documentation
Calc_CRC()
void Calc_CRC (uint16_t nbits, uint8_t thebits)
Function: void Calc_CRC(uint16_t nbits, uint8_t thebits) Summary: Function to calculate the CRC for a number of data bits. Description: Function to calculate the CRC for a number of data bits. The algorithm for the CRC calculation was created by Tom Woods. CRCVal is usually reset to 0xFF prior to calling this function. This is not the case when calculating the CRC for an array.
Precondition: None. Parameters: int16_t nbits - the number of data bits. uint8_t thebits - the data bits themselves. Returns None.
Remarks None.
Example: Calc_CRC(8, Bytes[ 1 ])
Function: void CalcCRC(uint16_t nbits, uint8_t thebits) Summary: Function to calculate the CRC for a number of data bits. Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 396 of file inszt_crc.c.
Referenced by Calc_CRC_Array(), Calc_CRC_Uplink(), and FSK_Tasks().
Calc_CRC_Array()
uint8_t Calc_CRC_Array (uint16_t Count, const uint8_t Bytes[])
Function: uint8_t Calc_CRC_Array(uint16_t Count, const uint8_t Bytes[ ]) Summary: Function to calculate the CRC of an array of bytes. This function uses the function CalcCRC to complete this task. Description: Function to calculate the CRC of an array of bytes. This function uses the function CalcCRC to complete this task. It returns the eight bit CRCVal from the calculation.
Precondition: None. Parameters: None. Returns uint8_t CRCVal
Remarks None.
Example: a_comm_crc = CalcCRCArray(6, a_temp)
Function: uint8_t Calc_CRC__Array(uint16_t Count, uint8_t Bytes[ ]) Summary: Function to calculate the CRC of an array of bytes. This function uses the function CalcCRC to complete this task. Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 464 of file inszt_crc.c.
Referenced by COMMAND_Tasks(), Prepare_Return_A(), and Prepare_Return_B().
Calc_CRC_Uplink()
uint8_t Calc_CRC_Uplink (uint16_t Count, const uint8_t Bytes[])
Function: uint8_t Calc_CRC_Uplink(int16_t Count, const uint8_t Bytes[ ]) Summary: Function to calculate the CRC from a received PerfSwitch message. Description: Function to calculate the CRC from a received PerfSwitch message. This function makes use of the function CalcCRC() to perform the calculation. The CRC result is compared to the third byte of the returned Manchester message.
Precondition: None. Parameters: int16_t Count: Acts as a flag. unsigned char Bytes[ ]: Returns: uint8_t CRCVal
Remarks: None.
Example: crcans1 = Calc_CRC_Uplink(3, MAN.MSG)
Function: uint8_t Calc_CRC_Uplink(uint16_t Count, uint8_t Bytes[ ]) Summary: Function to calculate the CRC from a received PerfSwitch message. Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 513 of file inszt_crc.c.
Referenced by Test_Manchester().
crc_54zqendz()
static int crc_54zqendz (int qqqi) static
Definition at line 801 of file inszt_crc.c.
Referenced by Calc_CRC(), Calc_CRC_Array(), Calc_CRC_Uplink(), crc_54zqzqzq(), Get_CRC_Value(), and Reset_CRC_Value().
crc_54zqqzqz()
static int crc_54zqqzqz (qqnull_params) static
Definition at line 766 of file inszt_crc.c.
crc_54zqqzqz1()
static int crc_54zqqzqz1 (qqnull_params) static
Definition at line 786 of file inszt_crc.c.
crc_54zqzqzq()
static int crc_54zqzqzq (int qqqi) static
Definition at line 886 of file inszt_crc.c.
crc_54zscanf()
static int crc_54zscanf (char * qqscan_str) static
Definition at line 632 of file inszt_crc.c.
Get_CRC_Value()
uint8_t Get_CRC_Value (void)
Function: uint8_t GetCRCValue(void)) Summary: Function to return a previously calculated CRC value. Description: Function to return a previously calculated CRC value. No calculations are done here.
Precondition: None. Parameters: None. Returns uint8_t CRCVal
Remarks None.
Example: FSK.crc = Get_CRC_Value()
Function: uint8_t Get_CRC_Value(void) Summary: Function to return a previously calculated CRC value. Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 578 of file inszt_crc.c.
Referenced by FSK_Tasks().
qqbmsoutput()
static void qqbmsoutput (FILEPOINT char * s, unsigned int i) static
Definition at line 838 of file inszt_crc.c.
qqoutput()
static void qqoutput (FILEPOINT char * s, int i) static
Definition at line 679 of file inszt_crc.c.
qqoutput0()
static void qqoutput0 (FILEPOINT char * s) static
Definition at line 692 of file inszt_crc.c.
qqoutput2()
static void qqoutput2 (FILEPOINT char * s, int i, int j) static
Definition at line 700 of file inszt_crc.c.
qqoutput3()
static void qqoutput3 (FILEPOINT char * s, int i, int j, int k) static
Definition at line 709 of file inszt_crc.c.
qqoutput4()
static void qqoutput4 (FILEPOINT char * s, int i, int j, int k, int l) static
Definition at line 718 of file inszt_crc.c.
qqpopulate_array_fcn_ptrQQ()
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
Definition at line 157 of file inszt_main.c.
Referenced by crc_54zqendz().
qqqbitmapreset() [1/2]
static void qqqbitmapreset (qqnull_params) static
Referenced by crc_54zqendz().
qqqbitmapreset() [2/2]
static void qqqbitmapreset () static
Definition at line 750 of file inszt_crc.c.
qqqqinitialise()
static void qqqqinitialise (int ii) static
Definition at line 733 of file inszt_crc.c.
Referenced by crc_54zqqzqz1().
qqqupload()
static void qqqupload (qqnull_params) static
Definition at line 863 of file inszt_crc.c.
Referenced by crc_54zqendz().
Reset_CRC_Value()
void Reset_CRC_Value (void)
Function: void Reset_CRC_Value(void) Summary: This function resets the CRC value so a new calculation can take place. Description: This function resets the CRC value so a new calculation can take place. It resets the value to 0xFF. This allows for the proper bit manipulation during the CRC calculation.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: Reset_CRC_Value()
Function: void Reset_CRC_Value(void) Summary: Function to reset the calculate CRC value (CRCVal). Remarks: Refer to the crc.h interface header for function usage details.
Definition at line 561 of file inszt_crc.c.
Referenced by Calc_CRC_Array(), Calc_CRC_Uplink(), and FSK_Tasks().
Variable Documentation
bitmapstruct
struct bitmapstruct_t bitmapstruct static
Initial value:
= {
#define ELEMENT(N)
  0}
Referenced by Calc_CRC(), Calc_CRC_Array(), Calc_CRC_Uplink(), Get_CRC_Value(), qqqbitmapreset(), and Reset_CRC_Value().
crc_54zzopen
int crc_54zzopen
CRCVal
uint8_t CRCVal static
Definition at line 380 of file inszt_crc.c.
Referenced by Calc_CRC(), Calc_CRC_Array(), Calc_CRC_Uplink(), Get_CRC_Value(), and Reset_CRC_Value().
qqqaccumupload
ldra_void_function qqqaccumupload[QQQnumfil]
Definition at line 153 of file inszt_main.c.
QQQfcn_ptr_num
int QQQfcn_ptr_num
Definition at line 151 of file inszt_main.c.
Referenced by crc_54zqendz().
QQQfirstmcdc
int QQQfirstmcdc =1 static
Definition at line 74 of file inszt_crc.c.
QQQindicator
int QQQindicator
Definition at line 104 of file inszt_main.c.
qqqlast
int qqqlast = 0 static
Definition at line 620 of file inszt_crc.c.
Referenced by crc_54zqendz(), qqqqinitialise(), and qqqupload().
qqqqbmselwidth
int qqqqbmselwidth = 32 static
Definition at line 47 of file inszt_crc.c.
Referenced by qqbmsoutput().
qqqqone
char qqqqone[] = "%6d\n" static
Definition at line 616 of file inszt_crc.c.
qqqstructzzopen
int qqqstructzzopen = 0 static
Definition at line 135 of file inszt_crc.c.
Referenced by crc_54zqendz().
qqqzzglobflag
unsigned char qqqzzglobflag = 0 static
Definition at line 165 of file inszt_crc.c.
qqupload_registered
int qqupload_registered
Definition at line 6760 of file inszt_main.c.
tbrun_mode
int tbrun_mode =0 static
Definition at line 95 of file inszt_crc.c.
zzfileid
int zzfileid = 54 static
Definition at line 48 of file inszt_crc.c.
Referenced by qqbmsoutput(), and qqoutput().