Panel Interface Board: inszt_UART.c File Reference
inszt_UART.c File Reference
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port_common.h"
#include "UART_71zbelem.def"
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "system/common/sys_common.h"
#include "system/common/sys_module.h"
#include "system/devcon/sys_devcon.h"
#include "system/clk/sys_clk.h"
#include "system/int/sys_int.h"
#include "system/tmr/sys_tmr.h"
#include "C:\microchip\harmony\v2_06\apps\Panel_Interface_Board\firmware\src\system_config\default\system_config.h"
#include "peripheral/adchs/plib_adchs.h"
#include "peripheral/int/plib_int.h"
#include "C:\microchip\harmony\v2_06\framework\driver\driver_common.h"
#include "peripheral/tmr/plib_tmr.h"
#include "peripheral/pmp/plib_pmp.h"
#include "C:\microchip\harmony\v2_06\framework\system\system.h"
#include "C:\microchip\harmony\v2_06\framework\system\ports\sys_ports.h"
#include "driver/usb/usbhs/drv_usbhs.h"
#include "usb/usb_device.h"
#include "../system_definitions.h"
Data Structures
struct bitmapstruct_t
struct DRV_TMR_DIVIDER_RANGE
struct DRV_TMR_INIT
struct SYS_DMA_CHANNEL_OPERATION_MODE_CRC
struct SYS_DMA_INIT
union SYS_DMA_DESCRIPTOR_CONTROL
union DRV_USART_OPERATION_MODE_DATA
struct DRV_USART_INIT
struct SYS_DEBUG_INIT
struct DRV_USART_OBJ
struct _DRV_SPI_INIT
struct _DRV_SPI_CLIENT_DATA
struct APP_DATA
struct SYSTEM_OBJECTS
struct UART_DATA
struct TFifo
struct COMM_DATA
struct COMMAND_DATA
Macros
#define QQQdialect MPLABX
#define QQQswitch3
#define QQQswitch
#define qqqMaxBranchDepth 20
#define QQQstructbitmap
#define QQQnumfil 23
#define QQQNOATEXIT
#define QQQUPLOADATEND
#define QQQNOSTDIO
#define QQQBITMAP
#define qqqbitmapint unsigned int
#define QQQSINGLEFILE
#define QQQFILEID
#define QQQseparate
#define UART_71zzopen zzopen
#define UART_71zqqzqz1 zqqzqz1
#define QQQLDRA_PORT
#define FILEPOINT
#define LDRA_VOID_FUNC
#define qqnull_params void
#define QQQ_PROTOTYPE_DEF
#define ELEMENT(N) qqqbitmapint element##N;
#define LASTELEMENT
#define ELEMENT(N) 0,
#define UART_H
#define _SYS_DEFINITIONS_H
#define _DRV_IC_H
#define _SYSTEM_CONFIG_H
#define SYS_VERSION_STR "2.06"
#define SYS_VERSION 20600
#define SYS_CLK_FREQ 200000000ul
#define SYS_CLK_BUS_PERIPHERAL_1 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_2 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_3 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_4 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_5 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_7 200000000ul
#define SYS_CLK_BUS_PERIPHERAL_8 100000000ul
#define SYS_CLK_CONFIG_PRIMARY_XTAL 0ul
#define SYS_CLK_CONFIG_SECONDARY_XTAL 32768ul
#define SYS_PORT_A_ANSEL 0x3F00
#define SYS_PORT_A_TRIS 0xFFED
#define SYS_PORT_A_LAT 0x0010
#define SYS_PORT_A_ODC 0x0000
#define SYS_PORT_A_CNPU 0x0020
#define SYS_PORT_A_CNPD 0x0000
#define SYS_PORT_A_CNEN 0x0021
#define SYS_PORT_B_ANSEL 0x10C8
#define SYS_PORT_B_TRIS 0x91FF
#define SYS_PORT_B_LAT 0x0000
#define SYS_PORT_B_ODC 0x0000
#define SYS_PORT_B_CNPU 0x0000
#define SYS_PORT_B_CNPD 0x0000
#define SYS_PORT_B_CNEN 0x0000
#define SYS_PORT_C_ANSEL 0xCFE1
#define SYS_PORT_C_TRIS 0xFFFF
#define SYS_PORT_C_LAT 0x0000
#define SYS_PORT_C_ODC 0x0000
#define SYS_PORT_C_CNPU 0x0000
#define SYS_PORT_C_CNPD 0x0000
#define SYS_PORT_C_CNEN 0x0000
#define SYS_PORT_D_ANSEL 0xC100
#define SYS_PORT_D_TRIS 0xFFFF
#define SYS_PORT_D_LAT 0x0000
#define SYS_PORT_D_ODC 0x0000
#define SYS_PORT_D_CNPU 0x0000
#define SYS_PORT_D_CNPD 0x0000
#define SYS_PORT_D_CNEN 0x0000
#define SYS_PORT_E_ANSEL 0xFC00
#define SYS_PORT_E_TRIS 0xFDFF
#define SYS_PORT_E_LAT 0x0000
#define SYS_PORT_E_ODC 0x0000
#define SYS_PORT_E_CNPU 0x0000
#define SYS_PORT_E_CNPD 0x0000
#define SYS_PORT_E_CNEN 0x0000
#define SYS_PORT_F_ANSEL 0xCEC0
#define SYS_PORT_F_TRIS 0xEFFF
#define SYS_PORT_F_LAT 0x0000
#define SYS_PORT_F_ODC 0x0000
#define SYS_PORT_F_CNPU 0x0000
#define SYS_PORT_F_CNPD 0x0000
#define SYS_PORT_F_CNEN 0x0000
#define SYS_PORT_G_ANSEL 0x8CBC
#define SYS_PORT_G_TRIS 0xDFFF
#define SYS_PORT_G_LAT 0x0000
#define SYS_PORT_G_ODC 0x0000
#define SYS_PORT_G_CNPU 0x0000
#define SYS_PORT_G_CNPD 0x0000
#define SYS_PORT_G_CNEN 0x0000
#define SYS_PORT_H_ANSEL 0x0070
#define SYS_PORT_H_TRIS 0xB3FB
#define SYS_PORT_H_LAT 0x0000
#define SYS_PORT_H_ODC 0x0000
#define SYS_PORT_H_CNPU 0x0000
#define SYS_PORT_H_CNPD 0x0000
#define SYS_PORT_H_CNEN 0x0000
#define SYS_PORT_J_ANSEL 0x0000
#define SYS_PORT_J_TRIS 0x8B7F
#define SYS_PORT_J_LAT 0x0080
#define SYS_PORT_J_ODC 0x0000
#define SYS_PORT_J_CNPU 0x0000
#define SYS_PORT_J_CNPD 0x0000
#define SYS_PORT_J_CNEN 0x0800
#define SYS_PORT_K_ANSEL 0xFF00
#define SYS_PORT_K_TRIS 0xFFFF
#define SYS_PORT_K_LAT 0x0000
#define SYS_PORT_K_ODC 0x0000
#define SYS_PORT_K_CNPU 0x0000
#define SYS_PORT_K_CNPD 0x0000
#define SYS_PORT_K_CNEN 0x0000
#define SYS_INT true
#define SYS_TMR_POWER_STATE SYS_MODULE_POWER_RUN_FULL
#define SYS_TMR_DRIVER_INDEX DRV_TMR_INDEX_0
#define SYS_TMR_MAX_CLIENT_OBJECTS 5
#define SYS_TMR_FREQUENCY 1000
#define SYS_TMR_FREQUENCY_TOLERANCE 10
#define SYS_TMR_UNIT_RESOLUTION 10000
#define SYS_TMR_CLIENT_TOLERANCE 10
#define SYS_TMR_INTERRUPT_NOTIFICATION false
#define DRV_IC_DRIVER_MODE_STATIC
#define USE_8BIT_PMP
#define DRV_SPI_NUMBER_OF_MODULES 6
#define DRV_SPI_POLLED 1
#define DRV_SPI_ISR 0
#define DRV_SPI_MASTER 1
#define DRV_SPI_SLAVE 0
#define DRV_SPI_RM 0
#define DRV_SPI_EBM 1
#define DRV_SPI_8BIT 1
#define DRV_SPI_16BIT 1
#define DRV_SPI_32BIT 0
#define DRV_SPI_DMA 0
#define DRV_SPI_INSTANCES_NUMBER 3
#define DRV_SPI_CLIENTS_NUMBER 3
#define DRV_SPI_ELEMENTS_PER_QUEUE 10
#define DRV_SPI_SPI_ID_IDX0 SPI_ID_1
#define DRV_SPI_TASK_MODE_IDX0 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX0 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX0 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX0 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX0 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX0 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX0 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX0 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX0 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX0 SPI_COMMUNICATION_WIDTH_16BITS
#define DRV_SPI_CLOCK_SOURCE_IDX0 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX0 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX0 1000000
#define DRV_SPI_BUFFER_TYPE_IDX0 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX0 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX0 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0 0xFFFF
#define DRV_SPI_QUEUE_SIZE_IDX0 10
#define DRV_SPI_RESERVED_JOB_IDX0 1
#define DRV_SPI_SPI_ID_IDX1 SPI_ID_2
#define DRV_SPI_TASK_MODE_IDX1 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX1 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX1 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX1 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX1 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX1 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX1 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX1 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX1 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX1 SPI_COMMUNICATION_WIDTH_8BITS
#define DRV_SPI_CLOCK_SOURCE_IDX1 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX1 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX1 1000000
#define DRV_SPI_BUFFER_TYPE_IDX1 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX1 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX1 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1 0xFF
#define DRV_SPI_QUEUE_SIZE_IDX1 10
#define DRV_SPI_RESERVED_JOB_IDX1 1
#define DRV_SPI_SPI_ID_IDX2 SPI_ID_4
#define DRV_SPI_TASK_MODE_IDX2 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX2 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX2 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX2 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX2 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX2 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX2 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX2 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX2 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX2 SPI_COMMUNICATION_WIDTH_16BITS
#define DRV_SPI_CLOCK_SOURCE_IDX2 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX2 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX2 500000
#define DRV_SPI_BUFFER_TYPE_IDX2 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX2 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX2 SPI_INPUT_SAMPLING_PHASE_AT_END
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2 0x0000
#define DRV_SPI_QUEUE_SIZE_IDX2 10
#define DRV_SPI_RESERVED_JOB_IDX2 1
#define DRV_TMR_INTERRUPT_MODE true
#define DRV_TMR_PERIPHERAL_ID_IDX0 TMR_ID_2
#define DRV_TMR_INTERRUPT_SOURCE_IDX0 INT_SOURCE_TIMER_2
#define DRV_TMR_INTERRUPT_VECTOR_IDX0 INT_VECTOR_T2
#define DRV_TMR_ISR_VECTOR_IDX0 _TIMER_2_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX0 INT_PRIORITY_LEVEL4
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX0 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX0 TMR_PRESCALE_VALUE_8
#define DRV_TMR_OPERATION_MODE_IDX0 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX0 false
#define DRV_TMR_POWER_STATE_IDX0
#define DRV_TMR_PERIPHERAL_ID_IDX1 TMR_ID_7
#define DRV_TMR_INTERRUPT_SOURCE_IDX1 INT_SOURCE_TIMER_7
#define DRV_TMR_INTERRUPT_VECTOR_IDX1 INT_VECTOR_T7
#define DRV_TMR_ISR_VECTOR_IDX1 _TIMER_7_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX1 INT_PRIORITY_LEVEL3
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX1 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX1 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX1 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX1 false
#define DRV_TMR_POWER_STATE_IDX1
#define DRV_TMR_PERIPHERAL_ID_IDX2 TMR_ID_6
#define DRV_TMR_INTERRUPT_SOURCE_IDX2 INT_SOURCE_TIMER_6
#define DRV_TMR_INTERRUPT_VECTOR_IDX2 INT_VECTOR_T6
#define DRV_TMR_ISR_VECTOR_IDX2 _TIMER_6_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX2 INT_PRIORITY_LEVEL1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX2 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX2 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX2 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX2 false
#define DRV_TMR_POWER_STATE_IDX2
#define DRV_TMR_PERIPHERAL_ID_IDX3 TMR_ID_1
#define DRV_TMR_INTERRUPT_SOURCE_IDX3 INT_SOURCE_TIMER_1
#define DRV_TMR_INTERRUPT_VECTOR_IDX3 INT_VECTOR_T1
#define DRV_TMR_ISR_VECTOR_IDX3 _TIMER_1_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX3 INT_PRIORITY_LEVEL2
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX3 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX3 TMR_PRESCALE_VALUE_256
#define DRV_TMR_OPERATION_MODE_IDX3 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX3 false
#define DRV_TMR_POWER_STATE_IDX3
#define DRV_TMR_PERIPHERAL_ID_IDX4 TMR_ID_3
#define DRV_TMR_INTERRUPT_SOURCE_IDX4 INT_SOURCE_TIMER_3
#define DRV_TMR_INTERRUPT_VECTOR_IDX4 INT_VECTOR_T3
#define DRV_TMR_ISR_VECTOR_IDX4 _TIMER_3_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX4 INT_PRIORITY_LEVEL1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX4 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX4 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX4 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX4 false
#define DRV_TMR_POWER_STATE_IDX4
#define DRV_USART_INSTANCES_NUMBER 1
#define DRV_USART_CLIENTS_NUMBER 1
#define DRV_USART_INTERRUPT_MODE false
#define DRV_USART_BYTE_MODEL_SUPPORT true
#define DRV_USART_READ_WRITE_MODEL_SUPPORT false
#define DRV_USART_BUFFER_QUEUE_SUPPORT false
#define DRV_USBHS_DEVICE_SUPPORT true
#define DRV_USBHS_HOST_SUPPORT false
#define DRV_USBHS_INSTANCES_NUMBER 1
#define DRV_USBHS_INTERRUPT_MODE true
#define DRV_USBHS_ENDPOINTS_NUMBER 2
#define USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
#define USB_DEVICE_INSTANCES_NUMBER 1
#define USB_DEVICE_EP0_BUFFER_SIZE 64
#define USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED 2
#define LED1Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12 , Value)
#define LED2Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10 , Value)
#define DMP_FIRE_LEDToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9 , Value)
#define HVPS_ENBToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13 , Value)
#define RLY_HVPS_OUTToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14 , Value)
#define RLY_WL_SPS_POLToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2 , Value)
#define RLY_LOGToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9 , Value)
#define RLY_DMP_FIREToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10 , Value)
#define RLY_AUXToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11 , Value)
#define RLY_CCLToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1 , Value)
#define RLY_WL_MONToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12 , Value)
#define RLY_ARMCFToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13 , Value)
#define RLY_ARMToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14 , Value)
#define TPAN1Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10 , Value)
#define TPAN2Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11 , Value)
#define FSK_DAC_CSToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4 , Value)
#define RLY_COMMToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14 , Value)
#define FSK_DAC_CLRToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLROn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLROff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLRStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLRStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7 , Value)
#define WL_CPS_SWToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13 , Value)
#define HVPS_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_5)
#define MAN_SIGStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_0)
#define DMP_FIRE_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_8)
#define NEG_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_4)
#define POS_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_15)
#define DRUM1_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_2)
#define SAFE_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_1)
#define DRUM2_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_0)
#define LOG_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_3)
#define AUX_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_8)
#define ARMCF_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_1)
#define ARM_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_2)
#define ARMCF_AUTO_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_13)
#define FIRE_SW_OFFStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_8)
#define FIRE_SW_ONStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_8)
#define WL_SPS_POS_DETStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_12)
#define WL_SPS_NEG_DETStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_13)
#define MAN_CN_PORT_CHANNEL PORT_CHANNEL_A
#define MAN_CN_PORT_BIT PORTS_BIT_POS_0
#define MAN_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_A
#define HVPS_CN_PORT_CHANNEL PORT_CHANNEL_J
#define HVPS_CN_PORT_BIT PORTS_BIT_POS_11
#define HVPS_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_J
#define _DRV_COMMON_H
#define DRV_IO_ISBLOCKING(intent) (intent & DRV_IO_INTENT_BLOCKING)
#define DRV_IO_ISNONBLOCKING(intent) (intent & DRV_IO_INTENT_NONBLOCKING)
#define DRV_IO_ISEXCLUSIVE(intent) (intent & DRV_IO_INTENT_EXCLUSIVE)
#define DRV_HANDLE_INVALID (((DRV_HANDLE) - 1))
#define DRV_CONFIG_NOT_SUPPORTED (((unsigned short) - 1))
#define _PLIB_UNSUPPORTED
#define DRV_IC_INDEX_0 0
#define DRV_IC_INDEX_1 1
#define DRV_IC_INDEX_2 2
#define DRV_IC_INDEX_3 3
#define DRV_IC_INDEX_4 4
#define DRV_IC_INDEX_5 5
#define DRV_IC_INDEX_6 6
#define DRV_IC_INDEX_7 7
#define DRV_IC_INDEX_8 8
#define DRV_IC_INDEX_9 9
#define DRV_IC_INDEX_10 10
#define DRV_IC_INDEX_11 11
#define DRV_IC_INDEX_12 12
#define DRV_IC_INDEX_13 13
#define DRV_IC_INDEX_14 14
#define DRV_IC_INDEX_15 15
#define _DRV_IC_STATIC_H
#define DRV_IC_Open(drvIndex, intent) (drvIndex)
#define DRV_IC_Close(handle)
#define _DRV_ADC_STATIC_H
#define _DRV_TMR_STATIC_H
#define _DRV_TMR_H
#define _TMR_DEFINITIONS_PIC32M_H
#define DRV_TMR_INDEX_0 0
#define DRV_TMR_INDEX_1 1
#define DRV_TMR_INDEX_2 2
#define DRV_TMR_INDEX_3 3
#define DRV_TMR_INDEX_4 4
#define DRV_TMR_INDEX_5 5
#define DRV_TMR_INDEX_6 6
#define DRV_TMR_INDEX_7 7
#define DRV_TMR_INDEX_8 8
#define DRV_TMR_INDEX_9 9
#define DRV_TMR_INDEX_10 10
#define DRV_TMR_INDEX_11 11
#define DRV_TMR_INDEX_COUNT TMR_NUMBER_OF_MODULES
#define _DRV_TMR_DEPRECATED_H
#define DRV_TMR_Tasks_ISR(object) DRV_TMR_Tasks (object)
#define DRV_TMR_CounterValue16BitSet(handle, counterPeriod) DRV_TMR_CounterValueSet (handle , counterPeriod)
#define DRV_TMR_CounterValue32BitSet(handle, counterPeriod) DRV_TMR_CounterValueSet (handle , counterPeriod)
#define DRV_TMR_CounterValue16BitGet(handle) DRV_TMR_CounterValueGet (handle)
#define DRV_TMR_CounterValue32BitGet(handle) DRV_TMR_CounterValueGet (handle)
#define DRV_TMR_Alarm16BitRegister(handle, period, isPeriodic, context, callBack) DRV_TMR_AlarmRegister (handle , period , isPeriodic , context , callBack)
#define DRV_TMR_Alarm32BitRegister(handle, period, isPeriodic, context, callBack) DRV_TMR_AlarmRegister (handle , period , isPeriodic , context , callBack)
#define DRV_TMR_AlarmPeriod16BitSet(handle, value) DRV_TMR_AlarmPeriodSet (handle , value)
#define DRV_TMR_AlarmPeriod32BitSet(handle, period) DRV_TMR_AlarmPeriodSet (handle , period)
#define DRV_TMR_AlarmPeriod16BitGet(handle) DRV_TMR_AlarmPeriodGet (handle)
#define DRV_TMR_AlarmPeriod32BitGet(handle) DRV_TMR_AlarmPeriodGet (handle)
#define DRV_TMR_Alarm16BitDeregister(handle) DRV_TMR_AlarmDeregister (handle)
#define DRV_TMR_Alarm32BitDeregister(handle) DRV_TMR_AlarmDeregister (handle)
#define DRV_TIMER_DIVIDER_MAX_32BIT 0xffffffff
#define DRV_TIMER_DIVIDER_MIN_32BIT 0x2
#define DRV_TIMER_DIVIDER_MAX_16BIT 0x10000
#define DRV_TIMER_DIVIDER_MIN_16BIT 0x2
#define _DRV_PMP_STATIC_H
#define _DRV_USART_STATIC_H
#define _DRV_USART_STATIC_LOCAL_H
#define _DRV_USART_H
#define _DRV_USART_DEFINITIONS_H
#define _PLIB_USART_H
#define _USART_PROCESSOR_H
#define _SYSTEM_H
#define _SYS_DMA_H
#define _SYS_DMA_DEFINITIONS_H
#define _PLIB_DMA_H
#define _PLIB_DMA_PROCESSOR_H
#define DMA_CHANNEL_NONE ((DMA_CHANNEL) - 1)
#define DMA_CHANNEL_ANY ((DMA_CHANNEL) - 2)
#define SYS_DMA_CHANNEL_COUNT DMA_NUMBER_OF_CHANNELS
#define SYS_DMA_CHANNEL_HANDLE_INVALID ((SYS_DMA_CHANNEL_HANDLE) (- 1))
#define SYS_DMA_TasksISR(object, activeChannel) SYS_DMA_Tasks (object , activeChannel)
#define DRV_USART_INDEX_0 0
#define DRV_USART_INDEX_1 1
#define DRV_USART_INDEX_2 2
#define DRV_USART_INDEX_3 3
#define DRV_USART_INDEX_4 4
#define DRV_USART_INDEX_5 5
#define DRV_USART_COUNT USART_NUMBER_OF_MODULES
#define DRV_USART_WRITE_ERROR ((uint32_t) (- 1))
#define DRV_USART_READ_ERROR ((uint32_t) (- 1))
#define DRV_USART_BUFFER_HANDLE_INVALID ((DRV_USART_BUFFER_HANDLE) (- 1))
#define _DRV_USART_FEATURE_MAPPING_H
#define _DRV_USART_InterruptSourceIsEnabled(source) false
#define _DRV_USART_InterruptSourceEnable(source)
#define _DRV_USART_InterruptSourceDisable(source) false
#define _DRV_USART_InterruptSourceStatusClear(source) SYS_INT_SourceStatusClear (source)
#define _DRV_USART_SEM_POST(x) OSAL_SEM_Post (x)
#define _DRV_USART_TAKE_MUTEX(x, y) OSAL_MUTEX_Lock (x , y)
#define _DRV_USART_RELEASE_MUTEX(x) OSAL_MUTEX_Unlock (x)
#define _SYS_DMA_ChannelForceStart(channelHandle) SYS_DMA_ChannelForceStart (channelHandle)
#define _DRV_USART_ALWAYS_NON_BLOCKING (DRV_IO_INTENT_NONBLOCKING)
#define _DRV_USART_TRANSMIT_BUFFER_QUEUE_TASKS(x) _DRV_USART_ByteTransmitTasks (x)
#define _DRV_USART_RECEIVE_BUFFER_QUEUE_TASKS(x) _DRV_USART_ByteReceiveTasks (x)
#define _DRV_USART_ERROR_TASKS(x) _DRV_USART_ByteErrorTasks (x)
#define _DRV_USART_CLIENT_BUFFER_QUEUE_OBJECTS_REMOVE(x) true
#define _DRV_USART_ByteModelInterruptSourceEnable(source)
#define _SYS_DEBUG_H
#define SYS_DEBUG_BUFFER_DMA_READY
#define SYS_DEBUG_INDEX_0 0
#define _SYS_DEBUG_MESSAGE(level, message) do { if ((level) <= SYS_DEBUG_ErrorLevelGet ()) SYS_DEBUG_Message (message) ; } while (0)
#define _SYS_DEBUG_PRINT(level, format, ...) do { if ((level) <= SYS_DEBUG_ErrorLevelGet ()) SYS_DEBUG_Print (format , ## __VA_ARGS__) ; } while (0)
#define SYS_MESSAGE(message)
#define SYS_DEBUG_MESSAGE(level, message)
#define SYS_PRINT(fmt, ...)
#define SYS_DEBUG_PRINT(level, fmt, ...)
#define SYS_DEBUG_BreakPoint()
#define SYS_DEBUG(level, message) SYS_DEBUG_MESSAGE (level , message)
#define SYS_ERROR(level, fmt, ...) SYS_DEBUG_PRINT (level , fmt , ## __VA_ARGS__)
#define SYS_ERROR_PRINT(level, fmt, ...) SYS_DEBUG_PRINT (level , fmt , ## __VA_ARGS__)
#define _DRV_USART_RX_DEPTH 9
#define _SYS_PORTS_H
#define _SYS_PORTS_DEFINITIONS_H
#define _PLIB_PORTS_H
#define _PLIB_PORTS_PROCESSOR_H
#define _PLIB_PORTS_COMPATIBILITY_H
#define PLIB_PORTS_ChangeNoticePerPortHasOccured PLIB_PORTS_ChangeNoticePerPortHasOccurred
#define _DRV_SPI_H
#define _DRV_SPI_DEFINITIONS_H
#define _PLIB_SPI_H
#define _PLIB_SPI_PROCESSOR_H
#define DRV_SPI_BUFFER_HANDLE_INVALID ((DRV_SPI_BUFFER_HANDLE) (- 1))
#define DRV_SPI_INDEX_0 0
#define DRV_SPI_INDEX_1 1
#define DRV_SPI_INDEX_2 2
#define DRV_SPI_INDEX_3 3
#define DRV_SPI_INDEX_4 4
#define DRV_SPI_INDEX_5 5
#define DRV_SPI_INDEX_COUNT SPI_NUMBER_OF_MODULES
#define APP_H
#define FIFO_H
#define FIFO_RX_SIZE 7
#define FIFO_TX_SIZE 7
#define FIFO_ADD_OK 0
#define FIFO_FULL 1
#define FIFO_EMPTY 2U
#define COMMMODULE_H
#define COMMANDS_H
#define qqqbranches 99
#define QQQMAXMCDCSIZE 2
#define ldra_sscanf
#define qqnull_params void
#define qqzzidfield 1
#define QQQFIXEDSIZE
#define QQQTEMP1
#define ELEMENT(N) qqbmsoutput("%8d", bitmapstruct.element##N);
#define LASTELEMENT
Typedefs
typedef void(* ldra_void_function) ()
typedef uintptr_t DRV_HANDLE
typedef void(* DRV_TMR_CALLBACK) (uintptr_t context, uint32_t alarmCount)
typedef uintptr_t SYS_DMA_CHANNEL_HANDLE
typedef void(* SYS_DMA_CHANNEL_TRANSFER_EVENT_HANDLER) (SYS_DMA_TRANSFER_EVENT event, SYS_DMA_CHANNEL_HANDLE handle, uintptr_t contextHandle)
typedef uintptr_t DRV_USART_BUFFER_HANDLE
typedef void(* DRV_USART_BUFFER_EVENT_HANDLER) (DRV_USART_BUFFER_EVENT event, DRV_USART_BUFFER_HANDLE bufferHandle, uintptr_t context)
typedef void(* DRV_USART_BYTE_EVENT_HANDLER) (const SYS_MODULE_INDEX index)
typedef uint16_t PORTS_DATA_MASK
typedef uint32_t PORTS_DATA_TYPE
typedef uintptr_t DRV_SPI_BUFFER_HANDLE
typedef void(* DRV_SPI_BUFFER_EVENT_HANDLER) (DRV_SPI_BUFFER_EVENT event, DRV_SPI_BUFFER_HANDLE bufferHandle, void *context)
typedef struct _DRV_SPI_INIT DRV_SPI_INIT
typedef struct _DRV_SPI_CLIENT_DATA DRV_SPI_CLIENT_DATA
typedef unsigned char uchar8_t
Enumerations
enum DRV_IO_INTENT {
DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2,
DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0,
DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2,
DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1,
DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3,
DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE,
DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3,
DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2,
DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0,
DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2,
DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1,
DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3,
DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE,
DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3,
DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2,
DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0,
DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2,
DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1,
DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3,
DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE,
DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3,
DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2,
DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0,
DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2,
DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1,
DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3,
DRV_IO_INTENT_SHARED = 0 << 3, DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE,
DRV_IO_INTENT_BLOCKING = 0 << 2, DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3,
DRV_IO_INTENT_READ = 1 << 0, DRV_IO_INTENT_WRITE = 1 << 1, DRV_IO_INTENT_READWRITE = DRV_IO_INTENT_READ | DRV_IO_INTENT_WRITE, DRV_IO_INTENT_BLOCKING = 0 << 2,
DRV_IO_INTENT_NONBLOCKING = 1 << 2, DRV_IO_INTENT_EXCLUSIVE = 1 << 3, DRV_IO_INTENT_SHARED = 0 << 3
}
enum DRV_CLIENT_STATUS {
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10, DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1,
DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1, DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10,
DRV_CLIENT_STATUS_ERROR_EXTENDED = - 10, DRV_CLIENT_STATUS_ERROR = - 1, DRV_CLIENT_STATUS_CLOSED = 0, DRV_CLIENT_STATUS_BUSY = 1,
DRV_CLIENT_STATUS_READY = 2, DRV_CLIENT_STATUS_READY_EXTENDED = 10
}
enum DRV_IO_BUFFER_TYPES {
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE,
DRV_IO_BUFFER_TYPE_NONE = 0x00, DRV_IO_BUFFER_TYPE_READ = 0x01, DRV_IO_BUFFER_TYPE_WRITE = 0x02, DRV_IO_BUFFER_TYPE_RW = DRV_IO_BUFFER_TYPE_READ | DRV_IO_BUFFER_TYPE_WRITE
}
enum DRV_ADC_MODULE_ID {
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES
}
enum DRV_TMR_CLK_SOURCES {
DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00,
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01,
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13,
DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00,
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01,
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13,
DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00,
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01,
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13,
DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00,
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01,
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03,
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13, DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13,
DRV_TMR_CLKSOURCE_INTERNAL = 0x00, DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS = 0x01, DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS = 0x11, DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS = 0x02,
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS = 0x12, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS = 0x03, DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS = 0x13
}
enum DRV_TMR_CLIENT_STATUS {
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1,
DRV_TMR_CLIENT_STATUS_INVALID = DRV_CLIENT_STATUS_ERROR, DRV_TMR_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_TMR_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY + 0, DRV_TMR_CLIENT_STATUS_RUNNING = DRV_CLIENT_STATUS_READY + 1
}
enum DRV_TMR_OPERATION_MODE {
DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE,
DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT,
DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT,
DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE,
DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT,
DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT,
DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE,
DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT,
DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT,
DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE,
DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT,
DRV_TMR_OPERATION_MODE_32_BIT, DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT,
DRV_TMR_OPERATION_MODE_NONE, DRV_TMR_OPERATION_MODE_16_BIT, DRV_TMR_OPERATION_MODE_32_BIT
}
enum SYS_DMA_SIDL {
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE, SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE,
SYS_DMA_SIDL_DISABLE, SYS_DMA_SIDL_ENABLE
}
enum SYS_DMA_CHANNEL_CHAIN_PRIO {
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW, SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW,
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH, SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
}
enum SYS_DMA_CHANNEL_IGNORE_MATCH {
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE,
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE, SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
}
enum SYS_DMA_CHANNEL_CRC_MODE {
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND, SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND,
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND, SYS_DMA_CHANNEL_CRC_MODE_APPEND
}
enum SYS_DMA_CRC_WRITE_ORDER {
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE, SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE,
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN, SYS_DMA_CRC_WRITE_ORDER_CHANGE
}
enum SYS_DMA_CHANNEL_OP_MODE {
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5), SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1),
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3), SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5),
SYS_DMA_CHANNEL_OP_MODE_BASIC = (1 << 0), SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT = (1 << 1), SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH = (1 << 2), SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW = (1 << 3),
SYS_DMA_CHANNEL_OP_MODE_AUTO = (1 << 4), SYS_DMA_CHANNEL_OP_MODE_CRC = (1 << 5)
}
enum SYS_DMA_TRANSFER_EVENT {
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE,
SYS_DMA_TRANSFER_EVENT_COMPLETE, SYS_DMA_TRANSFER_EVENT_ERROR, SYS_DMA_TRANSFER_EVENT_ABORT, SYS_DMA_TRANSFER_EVENT_NONE
}
enum SYS_DMA_ERROR {
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1, SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1,
SYS_DMA_ERROR_NONE = 1 << 0, SYS_DMA_ERROR_ADDRESS_ERROR = 1 << 1
}
enum SYS_DMA_DATA_WIDTH {
SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE,
SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE,
SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE,
SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE, SYS_DMA_DATA_WIDTH_NONE,
SYS_DMA_DATA_WIDTH_NONE
}
enum DRV_USART_OPERATION_MODE {
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK,
DRV_USART_OPERATION_MODE_IRDA, DRV_USART_OPERATION_MODE_NORMAL, DRV_USART_OPERATION_MODE_ADDRESSED, DRV_USART_OPERATION_MODE_LOOPBACK
}
enum DRV_USART_BUFFER_EVENT {
DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE,
DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR,
DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT,
DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE,
DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR,
DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT,
DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE,
DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR,
DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT,
DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE,
DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR,
DRV_USART_BUFFER_EVENT_ABORT, DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT,
DRV_USART_BUFFER_EVENT_COMPLETE, DRV_USART_BUFFER_EVENT_ERROR, DRV_USART_BUFFER_EVENT_ABORT
}
enum DRV_USART_BUFFER_RESULT {
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED,
DRV_USART_BUFFER_RESULT_HANDLE_INVALID, DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED, DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY, DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
}
enum DRV_USART_HANDSHAKE {
DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL,
DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX,
DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE,
DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL,
DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX,
DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE,
DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL,
DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX,
DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE,
DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL,
DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX,
DRV_USART_HANDSHAKE_NONE, DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE,
DRV_USART_HANDSHAKE_FLOWCONTROL, DRV_USART_HANDSHAKE_SIMPLEX, DRV_USART_HANDSHAKE_NONE
}
enum DRV_USART_BAUD_SET_RESULT {
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS, DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS,
DRV_USART_BAUD_SET_ERROR, DRV_USART_BAUD_SET_SUCCESS
}
enum DRV_USART_LINE_CONTROL_SET_RESULT {
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS, DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS,
DRV_USART_LINE_CONTROL_SET_ERROR, DRV_USART_LINE_CONTROL_SET_SUCCESS
}
enum DRV_USART_LINE_CONTROL {
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2,
DRV_USART_LINE_CONTROL_8NONE1, DRV_USART_LINE_CONTROL_9NONE1, DRV_USART_LINE_CONTROL_8EVEN1, DRV_USART_LINE_CONTROL_8EVEN2,
DRV_USART_LINE_CONTROL_8ODD1, DRV_USART_LINE_CONTROL_8ODD2, DRV_USART_LINE_CONTROL_8NONE2, DRV_USART_LINE_CONTROL_9NONE2
}
enum DRV_USART_INIT_FLAGS {
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2),
DRV_USART_INIT_FLAG_NONE, DRV_USART_INIT_FLAG_WAKE_ON_START = (1 << 0), DRV_USART_INIT_FLAG_AUTO_BAUD = (1 << 1), DRV_USART_INIT_FLAG_STOP_IN_IDLE = (1 << 2)
}
enum DRV_USART_ERROR {
DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN,
DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING,
DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY,
DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE,
DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4),
DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN,
DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING,
DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY,
DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE,
DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4),
DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN,
DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING,
DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY,
DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE,
DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4),
DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN,
DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING,
DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY,
DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4), DRV_USART_ERROR_NONE = USART_ERROR_NONE,
DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN, DRV_USART_ERROR_ADDRESS = (1 << 4),
DRV_USART_ERROR_NONE = USART_ERROR_NONE, DRV_USART_ERROR_PARITY = USART_ERROR_PARITY, DRV_USART_ERROR_FRAMING = USART_ERROR_FRAMING, DRV_USART_ERROR_RECEIVE_OVERRUN = USART_ERROR_RECEIVER_OVERRUN,
DRV_USART_ERROR_ADDRESS = (1 << 4)
}
enum DRV_USART_CLIENT_STATUS {
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY,
DRV_USART_CLIENT_STATUS_ERROR = DRV_CLIENT_STATUS_ERROR, DRV_USART_CLIENT_STATUS_CLOSED = DRV_CLIENT_STATUS_CLOSED, DRV_USART_CLIENT_STATUS_BUSY = DRV_CLIENT_STATUS_BUSY, DRV_USART_CLIENT_STATUS_READY = DRV_CLIENT_STATUS_READY
}
enum DRV_USART_TRANSFER_STATUS {
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3),
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT = (1 << 0), DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY = (1 << 1), DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL = (1 << 2), DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY = (1 << 3)
}
enum SYS_ERROR_LEVEL {
SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3,
SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2,
SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1,
SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0,
SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4,
SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3,
SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2,
SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1,
SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0,
SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4,
SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3,
SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2,
SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1,
SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0,
SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4,
SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3,
SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2,
SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1,
SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4, SYS_ERROR_FATAL = 0,
SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3, SYS_ERROR_DEBUG = 4,
SYS_ERROR_FATAL = 0, SYS_ERROR_ERROR = 1, SYS_ERROR_WARNING = 2, SYS_ERROR_INFO = 3,
SYS_ERROR_DEBUG = 4
}
enum SYS_PORTS_PULLUP_PULLDOWN_STATUS {
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1
}
enum SYS_PORTS_PIN_DIRECTION {
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1
}
enum PORTS_PIN_INTERRUPT_TYPE {
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE
}
enum DRV_SPI_CLOCK_MODE {
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3,
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE = 0, DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL = 1, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL = 2, DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE = 3
}
enum DRV_SPI_BUFFER_TYPE {
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1, DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1,
DRV_SPI_BUFFER_TYPE_STANDARD = 0, DRV_SPI_BUFFER_TYPE_ENHANCED = 1
}
enum DRV_SPI_PROTOCOL_TYPE {
DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0,
DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1,
DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2,
DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0,
DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1,
DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2,
DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0,
DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1,
DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2,
DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0,
DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1,
DRV_SPI_PROTOCOL_TYPE_AUDIO = 2, DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2,
DRV_SPI_PROTOCOL_TYPE_STANDARD = 0, DRV_SPI_PROTOCOL_TYPE_FRAMED = 1, DRV_SPI_PROTOCOL_TYPE_AUDIO = 2
}
enum DRV_SPI_BUFFER_EVENT {
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR,
DRV_SPI_BUFFER_EVENT_PENDING, DRV_SPI_BUFFER_EVENT_PROCESSING, DRV_SPI_BUFFER_EVENT_COMPLETE, DRV_SPI_BUFFER_EVENT_ERROR
}
enum DRV_SPI_MODE {
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1, DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1,
DRV_SPI_MODE_MASTER = 0, DRV_SPI_MODE_SLAVE = 1
}
enum DRV_SPI_TASK_MODE {
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1, DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1,
DRV_SPI_TASK_MODE_POLLED = 0, DRV_SPI_TASK_MODE_ISR = 1
}
enum UART_STATES {
UART_STATE_INIT = 0, UART_STATE_OPEN, UART_STATE_READ, UART_STATE_WAIT,
UART_STATE_WRITE, UART_STATE_INIT = 0, UART_STATE_OPEN, UART_STATE_READ,
UART_STATE_WAIT, UART_STATE_WRITE, UART_STATE_INIT = 0, UART_STATE_OPEN,
UART_STATE_READ, UART_STATE_WAIT, UART_STATE_WRITE, UART_STATE_INIT =0,
UART_STATE_OPEN, UART_STATE_READ, UART_STATE_WAIT, UART_STATE_WRITE
}
enum COMM_STATES {
COMM_STATE_INIT =0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE,
COMM_STATE_INIT = 0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE,
COMM_STATE_INIT = 0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE,
COMM_STATE_INIT = 0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE,
COMM_STATE_INIT = 0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE,
COMM_STATE_INIT = 0, COMM_STATE_VALIDATE, COMM_STATE_WAIT, COMM_STATE_IDLE
}
enum COMMAND_STATES {
COMMAND_STATE_INIT =0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD,
COMMAND_STATE_INIT = 0, COMMAND_STATE_WAIT, COMMAND_STATE_CRC_CHECK, COMMAND_STATE_EXECUTE_CMD
}
Functions
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
static void qqoutput (FILEPOINT char *s, int i)
static void qqoutput2 (FILEPOINT char *s, int i, int j)
static void qqoutput3 (FILEPOINT char *s, int i, int j, int k)
static void qqoutput4 (FILEPOINT char *s, int i, int j, int k, int l)
static void qqoutput0 (FILEPOINT char *s)
static int UART_71zqqzqz (qqnull_params)
static int UART_71zqqzqz1 (qqnull_params)
static int UART_71zqendz (int qqqi)
static int UART_71zqzqzq (int qqqi)
static void qqqupload (qqnull_params)
static void qqqbitmapreset (qqnull_params)
SYS_MODULE_OBJ DRV_IC_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
DRV_HANDLE DRV_IC_Open (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT intent)
void DRV_IC_Close (DRV_HANDLE handle)
DRV_HANDLE DRV_IC_Start (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT intent)
void DRV_IC_Stop (DRV_HANDLE handle)
uint32_t DRV_IC_Capture32BitDataRead (DRV_HANDLE handle)
uint16_t DRV_IC_Capture16BitDataRead (DRV_HANDLE handle)
bool DRV_IC_BufferIsEmpty (DRV_HANDLE handle)
void DRV_IC0_Initialize (void)
void DRV_IC0_Start (void)
void DRV_IC0_Stop (void)
uint32_t DRV_IC0_Capture32BitDataRead (void)
uint16_t DRV_IC0_Capture16BitDataRead (void)
bool DRV_IC0_BufferIsEmpty (void)
void DRV_ADC_Initialize (void)
void DRV_ADC_DeInitialize (void)
void DRV_ADC0_Open (void)
void DRV_ADC0_Close (void)
void DRV_ADC1_Open (void)
void DRV_ADC1_Close (void)
void DRV_ADC_Start (void)
void DRV_ADC_Stop (void)
uint32_t DRV_ADC_SamplesRead (uint8_t bufIndex)
bool DRV_ADC_SamplesAvailable (uint8_t bufIndex)
SYS_MODULE_OBJ DRV_TMR_Initialize (const SYS_MODULE_INDEX drvIndex, const SYS_MODULE_INIT *const init)
void DRV_TMR_Deinitialize (SYS_MODULE_OBJ object)
SYS_STATUS DRV_TMR_Status (SYS_MODULE_OBJ object)
void DRV_TMR_Tasks (SYS_MODULE_OBJ object)
DRV_HANDLE DRV_TMR_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT intent)
void DRV_TMR_Close (DRV_HANDLE handle)
DRV_TMR_CLIENT_STATUS DRV_TMR_ClientStatus (DRV_HANDLE handle)
void DRV_TMR_CounterValueSet (DRV_HANDLE handle, uint32_t counterPeriod)
uint32_t DRV_TMR_CounterValueGet (DRV_HANDLE handle)
void DRV_TMR_CounterClear (DRV_HANDLE handle)
bool DRV_TMR_AlarmRegister (DRV_HANDLE handle, uint32_t divider, bool isPeriodic, uintptr_t context, DRV_TMR_CALLBACK callBack)
bool DRV_TMR_AlarmDisable (DRV_HANDLE handle)
void DRV_TMR_AlarmEnable (DRV_HANDLE handle, bool enable)
void DRV_TMR_AlarmPeriodSet (DRV_HANDLE handle, uint32_t value)
uint32_t DRV_TMR_AlarmPeriodGet (DRV_HANDLE handle)
void DRV_TMR_AlarmDeregister (DRV_HANDLE handle)
bool DRV_TMR_Start (DRV_HANDLE handle)
void DRV_TMR_Stop (DRV_HANDLE handle)
uint32_t DRV_TMR_AlarmHasElapsed (DRV_HANDLE handle)
bool DRV_TMR_ClockSet (DRV_HANDLE handle, DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE preScale)
TMR_PRESCALE DRV_TMR_PrescalerGet (DRV_HANDLE handle)
DRV_TMR_OPERATION_MODE DRV_TMR_OperationModeGet (DRV_HANDLE handle)
bool DRV_TMR_GateModeSet (DRV_HANDLE handle)
bool DRV_TMR_GateModeClear (DRV_HANDLE handle)
uint32_t DRV_TMR_CounterFrequencyGet (DRV_HANDLE handle)
DRV_TMR_OPERATION_MODE DRV_TMR_DividerRangeGet (DRV_HANDLE handle, DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR0_Initialize (void)
bool DRV_TMR0_Start (void)
void DRV_TMR0_Stop (void)
static void DRV_TMR0_DeInitialize (void)
static SYS_STATUS DRV_TMR0_Status (void)
static void DRV_TMR0_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR0_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR0_OperationModeGet (void)
static void DRV_TMR0_Close (void)
bool DRV_TMR0_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR0_CounterValueSet (uint32_t value)
uint32_t DRV_TMR0_CounterValueGet (void)
void DRV_TMR0_CounterClear (void)
TMR_PRESCALE DRV_TMR0_PrescalerGet (void)
void DRV_TMR0_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR0_PeriodValueGet (void)
void DRV_TMR0_StopInIdleDisable (void)
void DRV_TMR0_StopInIdleEnable (void)
static void DRV_TMR0_Tasks (void)
uint32_t DRV_TMR0_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR0_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR1_Initialize (void)
bool DRV_TMR1_Start (void)
void DRV_TMR1_Stop (void)
static void DRV_TMR1_DeInitialize (void)
static SYS_STATUS DRV_TMR1_Status (void)
static void DRV_TMR1_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR1_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR1_OperationModeGet (void)
static void DRV_TMR1_Close (void)
bool DRV_TMR1_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR1_CounterValueSet (uint32_t value)
uint32_t DRV_TMR1_CounterValueGet (void)
void DRV_TMR1_CounterClear (void)
TMR_PRESCALE DRV_TMR1_PrescalerGet (void)
void DRV_TMR1_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR1_PeriodValueGet (void)
void DRV_TMR1_StopInIdleDisable (void)
void DRV_TMR1_StopInIdleEnable (void)
static void DRV_TMR1_Tasks (void)
uint32_t DRV_TMR1_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR1_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR2_Initialize (void)
bool DRV_TMR2_Start (void)
void DRV_TMR2_Stop (void)
static void DRV_TMR2_DeInitialize (void)
static SYS_STATUS DRV_TMR2_Status (void)
static void DRV_TMR2_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR2_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR2_OperationModeGet (void)
static void DRV_TMR2_Close (void)
bool DRV_TMR2_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR2_CounterValueSet (uint32_t value)
uint32_t DRV_TMR2_CounterValueGet (void)
void DRV_TMR2_CounterClear (void)
TMR_PRESCALE DRV_TMR2_PrescalerGet (void)
void DRV_TMR2_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR2_PeriodValueGet (void)
void DRV_TMR2_StopInIdleDisable (void)
void DRV_TMR2_StopInIdleEnable (void)
static void DRV_TMR2_Tasks (void)
uint32_t DRV_TMR2_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR2_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR3_Initialize (void)
bool DRV_TMR3_Start (void)
void DRV_TMR3_Stop (void)
static void DRV_TMR3_DeInitialize (void)
static SYS_STATUS DRV_TMR3_Status (void)
static void DRV_TMR3_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR3_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR3_OperationModeGet (void)
static void DRV_TMR3_Close (void)
bool DRV_TMR3_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR3_CounterValueSet (uint32_t value)
uint32_t DRV_TMR3_CounterValueGet (void)
void DRV_TMR3_CounterClear (void)
TMR_PRESCALE DRV_TMR3_PrescalerGet (void)
void DRV_TMR3_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR3_PeriodValueGet (void)
void DRV_TMR3_StopInIdleDisable (void)
void DRV_TMR3_StopInIdleEnable (void)
static void DRV_TMR3_Tasks (void)
uint32_t DRV_TMR3_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR3_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR4_Initialize (void)
bool DRV_TMR4_Start (void)
void DRV_TMR4_Stop (void)
static void DRV_TMR4_DeInitialize (void)
static SYS_STATUS DRV_TMR4_Status (void)
static void DRV_TMR4_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR4_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR4_OperationModeGet (void)
static void DRV_TMR4_Close (void)
bool DRV_TMR4_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR4_CounterValueSet (uint32_t value)
uint32_t DRV_TMR4_CounterValueGet (void)
void DRV_TMR4_CounterClear (void)
TMR_PRESCALE DRV_TMR4_PrescalerGet (void)
void DRV_TMR4_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR4_PeriodValueGet (void)
void DRV_TMR4_StopInIdleDisable (void)
void DRV_TMR4_StopInIdleEnable (void)
static void DRV_TMR4_Tasks (void)
uint32_t DRV_TMR4_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR4_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_PMP0_Initialize (void)
void DRV_PMP0_ModeConfig (void)
void DRV_PMP0_TimingSet (PMP_DATA_WAIT_STATES dataWait, PMP_STROBE_WAIT_STATES strobeWait, PMP_DATA_HOLD_STATES dataHold)
uint8_t DRV_PMP0_Read (void)
void DRV_PMP0_Write (uint8_t data)
void PLIB_USART_RunInOverflowEnable (USART_MODULE_ID index)
void PLIB_USART_RunInOverflowDisable (USART_MODULE_ID index)
bool PLIB_USART_RunInOverflowIsEnabled (USART_MODULE_ID index)
void PLIB_USART_BRGClockSourceSelect (USART_MODULE_ID index, USART_BRG_CLOCK_SOURCE brgClockSource)
USART_BRG_CLOCK_SOURCE PLIB_USART_BRGClockSourceGet (USART_MODULE_ID index)
bool PLIB_USART_ModuleIsBusy (USART_MODULE_ID index)
void PLIB_USART_RunInSleepModeEnable (USART_MODULE_ID index)
void PLIB_USART_RunInSleepModeDisable (USART_MODULE_ID index)
bool PLIB_USART_RunInSleepModeIsEnabled (USART_MODULE_ID index)
void PLIB_USART_Enable (USART_MODULE_ID index)
void PLIB_USART_Disable (USART_MODULE_ID index)
void PLIB_USART_TransmitterEnable (USART_MODULE_ID index)
void PLIB_USART_TransmitterDisable (USART_MODULE_ID index)
void PLIB_USART_BaudRateSet (USART_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
void PLIB_USART_BaudRateHighSet (USART_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
uint32_t PLIB_USART_BaudRateGet (USART_MODULE_ID index, int32_t clockFrequency)
void PLIB_USART_AddressSet (USART_MODULE_ID index, uint8_t address)
uint8_t PLIB_USART_AddressGet (USART_MODULE_ID index)
void PLIB_USART_AddressMaskSet (USART_MODULE_ID index, uint8_t mask)
uint8_t PLIB_USART_AddressMaskGet (USART_MODULE_ID index)
void PLIB_USART_ReceiverAddressDetectEnable (USART_MODULE_ID index)
void PLIB_USART_ReceiverAddressDetectDisable (USART_MODULE_ID index)
bool PLIB_USART_BaudRateAutoDetectIsComplete (USART_MODULE_ID index)
void PLIB_USART_BaudRateAutoDetectEnable (USART_MODULE_ID index)
void PLIB_USART_TransmitterByteSend (USART_MODULE_ID index, int8_t data)
int8_t PLIB_USART_ReceiverByteReceive (USART_MODULE_ID index)
int16_t PLIB_USART_Receiver9BitsReceive (USART_MODULE_ID index)
bool PLIB_USART_ReceiverAddressIsReceived (USART_MODULE_ID index)
void PLIB_USART_Transmitter9BitsSend (USART_MODULE_ID index, int8_t data, bool Bit9th)
void PLIB_USART_TransmitterBreakSend (USART_MODULE_ID index)
bool PLIB_USART_TransmitterBreakSendIsComplete (USART_MODULE_ID index)
bool PLIB_USART_ReceiverDataIsAvailable (USART_MODULE_ID index)
void PLIB_USART_ReceiverOverrunErrorClear (USART_MODULE_ID index)
bool PLIB_USART_TransmitterBufferIsFull (USART_MODULE_ID index)
bool PLIB_USART_TransmitterIsEmpty (USART_MODULE_ID index)
bool PLIB_USART_ReceiverFramingErrorHasOccurred (USART_MODULE_ID index)
bool PLIB_USART_ReceiverParityErrorHasOccurred (USART_MODULE_ID index)
bool PLIB_USART_ReceiverOverrunHasOccurred (USART_MODULE_ID index)
bool PLIB_USART_ReceiverIsIdle (USART_MODULE_ID index)
void PLIB_USART_ReceiverEnable (USART_MODULE_ID index)
void PLIB_USART_ReceiverDisable (USART_MODULE_ID index)
void PLIB_USART_TransmitterIdleIsLowEnable (USART_MODULE_ID index)
void PLIB_USART_TransmitterIdleIsLowDisable (USART_MODULE_ID index)
void PLIB_USART_ReceiverIdleStateLowEnable (USART_MODULE_ID index)
void PLIB_USART_ReceiverIdleStateLowDisable (USART_MODULE_ID index)
void PLIB_USART_BaudRateHighEnable (USART_MODULE_ID index)
void PLIB_USART_BaudRateHighDisable (USART_MODULE_ID index)
void PLIB_USART_TransmitterInterruptModeSelect (USART_MODULE_ID index, USART_TRANSMIT_INTR_MODE fifolevel)
void PLIB_USART_ReceiverInterruptModeSelect (USART_MODULE_ID index, USART_RECEIVE_INTR_MODE interruptMode)
void PLIB_USART_LineControlModeSelect (USART_MODULE_ID index, USART_LINECONTROL_MODE dataFlowConfig)
void PLIB_USART_HandshakeModeSelect (USART_MODULE_ID index, USART_HANDSHAKE_MODE handshakeConfig)
void PLIB_USART_ReceiverAddressAutoDetectEnable (USART_MODULE_ID index, int8_t Mask)
void PLIB_USART_ReceiverAddressAutoDetectDisable (USART_MODULE_ID index)
void PLIB_USART_IrDAEnable (USART_MODULE_ID index)
void PLIB_USART_IrDADisable (USART_MODULE_ID index)
void PLIB_USART_LoopbackEnable (USART_MODULE_ID index)
void PLIB_USART_LoopbackDisable (USART_MODULE_ID index)
void PLIB_USART_OperationModeSelect (USART_MODULE_ID index, USART_OPERATION_MODE operationmode)
void PLIB_USART_StopInIdleEnable (USART_MODULE_ID index)
void PLIB_USART_StopInIdleDisable (USART_MODULE_ID index)
void PLIB_USART_WakeOnStartEnable (USART_MODULE_ID index)
void PLIB_USART_WakeOnStartDisable (USART_MODULE_ID index)
bool PLIB_USART_WakeOnStartIsEnabled (USART_MODULE_ID index)
void PLIB_USART_InitializeModeGeneral (USART_MODULE_ID index, bool autobaud, bool loopBackMode, bool wakeFromSleep, bool irdaMode, bool stopInIdle)
void PLIB_USART_InitializeOperation (USART_MODULE_ID index, USART_RECEIVE_INTR_MODE receiveInterruptMode, USART_TRANSMIT_INTR_MODE transmitInterruptMode, USART_OPERATION_MODE operationMode)
void PLIB_USART_BaudSetAndEnable (USART_MODULE_ID index, uint32_t systemClock, uint32_t baud)
USART_ERROR PLIB_USART_ErrorsGet (USART_MODULE_ID index)
void * PLIB_USART_TransmitterAddressGet (USART_MODULE_ID index)
void * PLIB_USART_ReceiverAddressGet (USART_MODULE_ID index)
bool PLIB_USART_ExistsRunInOverflow (USART_MODULE_ID index)
bool PLIB_USART_ExistsBRGClockSourceSelect (USART_MODULE_ID index)
bool PLIB_USART_ExistsModuleBusyStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsRunInSleepMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsEnable (USART_MODULE_ID index)
bool PLIB_USART_ExistsHandshakeMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsIrDA (USART_MODULE_ID index)
bool PLIB_USART_ExistsLineControlMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsLoopback (USART_MODULE_ID index)
bool PLIB_USART_ExistsOperationMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsStopInIdle (USART_MODULE_ID index)
bool PLIB_USART_ExistsWakeOnStart (USART_MODULE_ID index)
bool PLIB_USART_ExistsBaudRate (USART_MODULE_ID index)
bool PLIB_USART_ExistsBaudRateAutoDetect (USART_MODULE_ID index)
bool PLIB_USART_ExistsBaudRateHigh (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverAddress (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverAddressMask (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiver (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiver9Bits (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverAddressAutoDetect (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverAddressDetect (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverDataAvailableStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverEnable (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverIdleStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverFramingErrorStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverInterruptMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverIdleStateLowEnable (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverParityErrorStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsReceiverOverrunStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitter (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitter9BitsSend (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterBreak (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterBufferFullStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterEmptyStatus (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterEnable (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterInterruptMode (USART_MODULE_ID index)
bool PLIB_USART_ExistsTransmitterIdleIsLow (USART_MODULE_ID index)
bool PLIB_DMA_ChannelXBufferedDataIsWritten (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXCollisionStatus (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_COLLISION collisonType)
DMA_PING_PONG_MODE PLIB_DMA_ChannelXPingPongModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXEventIsDetected (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXPrioritySelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_PRIORITY channelPriority)
DMA_CHANNEL_PRIORITY PLIB_DMA_ChannelXPriorityGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelPrioritySelect (DMA_MODULE_ID index, DMA_CHANNEL_PRIORITY channelPriority)
DMA_CHANNEL_PRIORITY PLIB_DMA_ChannelPriorityGet (DMA_MODULE_ID index)
void PLIB_DMA_ChannelXAutoEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXAutoIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXAutoDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXChainEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXChainIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXChainDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXDisabledEnablesEvents (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXDisabledDisablesEvents (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXChainToLower (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXChainToHigher (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXBusyActiveSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXBusyInActiveSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXBusyIsBusy (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXTransferDirectionSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRANSFER_DIRECTION chTransferDirection)
DMA_CHANNEL_TRANSFER_DIRECTION PLIB_DMA_ChannelXTransferDirectionGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXStartAddressOffsetSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t address, DMA_ADDRESS_OFFSET_TYPE offset)
uint16_t PLIB_DMA_ChannelXStartAddressOffsetGet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_ADDRESS_OFFSET_TYPE offset)
void PLIB_DMA_ChannelXPeripheralAddressSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t peripheraladdress)
uint16_t PLIB_DMA_ChannelXPeripheralAddressGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXTransferCountSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t transferCount)
uint16_t PLIB_DMA_ChannelXTransferCountGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXSourceAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_SOURCE_ADDRESSING_MODE sourceAddressMode)
DMA_SOURCE_ADDRESSING_MODE PLIB_DMA_ChannelXSourceAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXDestinationAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_DESTINATION_ADDRESSING_MODE destinationAddressMode)
DMA_DESTINATION_ADDRESSING_MODE PLIB_DMA_ChannelXDestinationAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_ADDRESSING_MODE channelAddressMode)
DMA_CHANNEL_ADDRESSING_MODE PLIB_DMA_ChannelXAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXTriggerEnable (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
bool PLIB_DMA_ChannelXTriggerIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
void PLIB_DMA_ChannelXTriggerDisable (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
DMA_CHANNEL_INT_SOURCE PLIB_DMA_ChannelXTriggerSourceNumberGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXStartIRQSet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRIGGER_SOURCE IRQnum)
void PLIB_DMA_ChannelXAbortIRQSet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRIGGER_SOURCE IRQ)
void PLIB_DMA_ChannelXDataSizeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_DATA_SIZE channelDataSize)
DMA_CHANNEL_DATA_SIZE PLIB_DMA_ChannelXDataSizeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXOperatingTransferModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRANSFER_MODE channeltransferMode)
DMA_TRANSFER_MODE PLIB_DMA_ChannelXOperatingTransferModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXReloadEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXReloadIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXReloadDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXNullWriteModeEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXNullWriteModeIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXNullWriteModeDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_StartTransferSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_AbortTransferSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_BusyActiveSet (DMA_MODULE_ID index)
void PLIB_DMA_BusyActiveReset (DMA_MODULE_ID index)
bool PLIB_DMA_IsBusy (DMA_MODULE_ID index)
void PLIB_DMA_SuspendEnable (DMA_MODULE_ID index)
void PLIB_DMA_SuspendDisable (DMA_MODULE_ID index)
bool PLIB_DMA_SuspendIsEnabled (DMA_MODULE_ID index)
void PLIB_DMA_StopInIdleEnable (DMA_MODULE_ID index)
void PLIB_DMA_StopInIdleDisable (DMA_MODULE_ID index)
void PLIB_DMA_Enable (DMA_MODULE_ID index)
bool PLIB_DMA_IsEnabled (DMA_MODULE_ID index)
void PLIB_DMA_Disable (DMA_MODULE_ID index)
uint8_t PLIB_DMA_ChannelBitsGet (DMA_MODULE_ID index)
bool PLIB_DMA_LastBusAccessIsRead (DMA_MODULE_ID index)
bool PLIB_DMA_LastBusAccessIsWrite (DMA_MODULE_ID index)
uint32_t PLIB_DMA_RecentAddressAccessed (DMA_MODULE_ID index)
void PLIB_DMA_CRCChannelSelect (DMA_MODULE_ID index, DMA_CHANNEL channel)
DMA_CHANNEL PLIB_DMA_CRCChannelGet (DMA_MODULE_ID index)
void PLIB_DMA_CRCTypeSet (DMA_MODULE_ID index, DMA_CRC_TYPE CRCType)
DMA_CRC_TYPE PLIB_DMA_CRCTypeGet (DMA_MODULE_ID index)
void PLIB_DMA_CRCAppendModeEnable (DMA_MODULE_ID index)
bool PLIB_DMA_CRCAppendModeIsEnabled (DMA_MODULE_ID index)
void PLIB_DMA_CRCAppendModeDisable (DMA_MODULE_ID index)
void PLIB_DMA_CRCEnable (DMA_MODULE_ID index)
bool PLIB_DMA_CRCIsEnabled (DMA_MODULE_ID index)
void PLIB_DMA_CRCDisable (DMA_MODULE_ID index)
void PLIB_DMA_CRCPolynomialLengthSet (DMA_MODULE_ID index, uint8_t polyLength)
uint8_t PLIB_DMA_CRCPolynomialLengthGet (DMA_MODULE_ID index)
void PLIB_DMA_CRCBitOrderSelect (DMA_MODULE_ID index, DMA_CRC_BIT_ORDER bitOrder)
void PLIB_DMA_CRCWriteByteOrderAlter (DMA_MODULE_ID index)
void PLIB_DMA_CRCWriteByteOrderMaintain (DMA_MODULE_ID index)
void PLIB_DMA_CRCByteOrderSelect (DMA_MODULE_ID index, DMA_CRC_BYTE_ORDER byteOrder)
DMA_CRC_BYTE_ORDER PLIB_DMA_CRCByteOrderGet (DMA_MODULE_ID index)
uint32_t PLIB_DMA_CRCDataRead (DMA_MODULE_ID index)
void PLIB_DMA_CRCDataWrite (DMA_MODULE_ID index, uint32_t DMACRCdata)
uint32_t PLIB_DMA_CRCXOREnableGet (DMA_MODULE_ID index)
void PLIB_DMA_CRCXOREnableSet (DMA_MODULE_ID index, uint32_t DMACRCXOREnableMask)
uint32_t PLIB_DMA_ChannelXSourceStartAddressGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXSourceStartAddressSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint32_t sourceStartAddress)
uint32_t PLIB_DMA_ChannelXDestinationStartAddressGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXDestinationStartAddressSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint32_t destinationStartAddress)
uint16_t PLIB_DMA_ChannelXSourceSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXSourceSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t sourceSize)
uint16_t PLIB_DMA_ChannelXDestinationSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXDestinationSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t destinationSize)
uint16_t PLIB_DMA_ChannelXSourcePointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
uint16_t PLIB_DMA_ChannelXDestinationPointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
uint16_t PLIB_DMA_ChannelXCellSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXCellSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t CellSize)
uint16_t PLIB_DMA_ChannelXCellProgressPointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
uint16_t PLIB_DMA_ChannelXPatternDataGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXPatternDataSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t patternData)
bool PLIB_DMA_ChannelXINTSourceFlagGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
void PLIB_DMA_ChannelXINTSourceFlagSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
void PLIB_DMA_ChannelXINTSourceFlagClear (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
void PLIB_DMA_ChannelXINTSourceEnable (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
void PLIB_DMA_ChannelXINTSourceDisable (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
bool PLIB_DMA_ChannelXINTSourceIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
void PLIB_DMA_ChannelXPatternLengthSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_PATTERN_LENGTH patternLen)
DMA_PATTERN_LENGTH PLIB_DMA_ChannelXPatternLengthGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
void PLIB_DMA_ChannelXPatternIgnoreByteEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ChannelXPatternIgnoreByteIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXPatternIgnoreByteDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
void PLIB_DMA_ChannelXPatternIgnoreSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint8_t pattern)
uint8_t PLIB_DMA_ChannelXPatternIgnoreGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
bool PLIB_DMA_ExistsBusy (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsSuspend (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsStopInIdle (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsEnableControl (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelBits (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsLastBusAccess (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsRecentAddress (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCChannel (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCType (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCAppendMode (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRC (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCPolynomialLength (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCBitOrder (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCWriteByteOrder (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCByteOrder (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCData (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsCRCXOREnable (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXPriority (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXEvent (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXAuto (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXChainEnbl (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXDisabled (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelX (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXChain (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXPatternLength (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXPatternIgnoreByte (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXBusy (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXPatternIgnore (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXTrigger (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsAbortTransfer (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsStartTransfer (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXStartIRQ (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXAbortIRQ (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXINTSourceFlag (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXINTSource (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXSourceStartAddress (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXDestinationStartAddress (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXSourceSize (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXDestinationSize (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXSourcePointer (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXDestinationPointer (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXCellSize (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXCellProgressPointer (DMA_MODULE_ID index)
bool PLIB_DMA_ExistsChannelXPatternData (DMA_MODULE_ID index)
void SYS_DMA_Tasks (SYS_MODULE_OBJ object, DMA_CHANNEL activeChannel)
SYS_MODULE_OBJ SYS_DMA_Initialize (const SYS_MODULE_INIT *const init)
SYS_DMA_CHANNEL_HANDLE SYS_DMA_ChannelAllocate (DMA_CHANNEL channel)
void SYS_DMA_ChannelRelease (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelSetup (SYS_DMA_CHANNEL_HANDLE handle, SYS_DMA_CHANNEL_OP_MODE modeEnable, DMA_TRIGGER_SOURCE eventSrc)
void SYS_DMA_ChannelSetupMatchAbortMode (SYS_DMA_CHANNEL_HANDLE handle, uint16_t pattern, DMA_PATTERN_LENGTH length, SYS_DMA_CHANNEL_IGNORE_MATCH ignore, uint8_t ignorePattern)
void SYS_DMA_ChannelCRCSet (SYS_DMA_CHANNEL_HANDLE handle, SYS_DMA_CHANNEL_OPERATION_MODE_CRC crc)
uint32_t SYS_DMA_ChannelCRCGet (void)
void SYS_DMA_ChannelEnable (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelDisable (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelTransferAdd (SYS_DMA_CHANNEL_HANDLE handle, const void *srcAddr, size_t srcSize, const void *destAddr, size_t destSize, size_t cellSize)
void SYS_DMA_ChannelTransferSet (SYS_DMA_CHANNEL_HANDLE handle, const void *srcAddr, size_t srcSize, const void *destAddr, size_t destSize, size_t cellSize)
size_t SYS_DMA_ChannelSourceTransferredSizeGet (SYS_DMA_CHANNEL_HANDLE handle)
size_t SYS_DMA_ChannelDestinationTransferredSizeGet (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelTransferEventHandlerSet (SYS_DMA_CHANNEL_HANDLE handle, const SYS_DMA_CHANNEL_TRANSFER_EVENT_HANDLER eventHandler, const uintptr_t contextHandle)
SYS_DMA_ERROR SYS_DMA_ChannelErrorGet (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelForceStart (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelForceAbort (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelAbortEventSet (SYS_DMA_CHANNEL_HANDLE handle, DMA_TRIGGER_SOURCE eventSrc)
bool SYS_DMA_ChannelIsBusy (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelSuspend (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_ChannelResume (SYS_DMA_CHANNEL_HANDLE handle)
void SYS_DMA_Suspend (void)
void SYS_DMA_Resume (void)
bool SYS_DMA_IsBusy (void)
void SYS_DMA_TasksError (SYS_MODULE_OBJ object)
void SYS_DMA_TasksErrorISR (SYS_MODULE_OBJ object, DMA_CHANNEL activeChannel)
SYS_MODULE_OBJ DRV_USART_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
void DRV_USART_Deinitialize (SYS_MODULE_OBJ object)
SYS_STATUS DRV_USART_Status (SYS_MODULE_OBJ object)
void DRV_USART_TasksTransmit (SYS_MODULE_OBJ object)
void DRV_USART_TasksReceive (SYS_MODULE_OBJ object)
void DRV_USART_TasksError (SYS_MODULE_OBJ object)
DRV_HANDLE DRV_USART_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT ioIntent)
void DRV_USART_Close (const DRV_HANDLE handle)
DRV_USART_CLIENT_STATUS DRV_USART_ClientStatus (DRV_HANDLE handle)
void DRV_USART_BufferAddWrite (const DRV_HANDLE handle, DRV_USART_BUFFER_HANDLE *bufferHandle, void *buffer, const size_t size)
void DRV_USART_AddressedBufferAddWrite (const DRV_HANDLE hClient, DRV_USART_BUFFER_HANDLE *bufferHandle, uint8_t address, void *source, size_t nWords)
void DRV_USART_BufferAddRead (const DRV_HANDLE handle, DRV_USART_BUFFER_HANDLE *const bufferHandle, void *buffer, const size_t size)
void DRV_USART_BufferEventHandlerSet (const DRV_HANDLE handle, const DRV_USART_BUFFER_EVENT_HANDLER eventHandler, const uintptr_t context)
DRV_USART_BUFFER_RESULT DRV_USART_BufferRemove (DRV_USART_BUFFER_HANDLE bufferHandle)
size_t DRV_USART_BufferCompletedBytesGet (DRV_USART_BUFFER_HANDLE bufferHandle)
size_t DRV_USART_BufferProcessedSizeGet (DRV_USART_BUFFER_HANDLE bufferHandle)
size_t DRV_USART_Read (const DRV_HANDLE handle, void *buffer, const size_t numbytes)
size_t DRV_USART_Write (const DRV_HANDLE handle, void *buffer, const size_t numbytes)
DRV_USART_TRANSFER_STATUS DRV_USART_TransferStatus (const DRV_HANDLE handle)
uint8_t DRV_USART_ReadByte (const DRV_HANDLE handle)
void DRV_USART_WriteByte (const DRV_HANDLE handle, const uint8_t byte)
unsigned int DRV_USART_ReceiverBufferSizeGet (const DRV_HANDLE handle)
unsigned int DRV_USART_TransmitBufferSizeGet (const DRV_HANDLE handle)
bool DRV_USART_ReceiverBufferIsEmpty (const DRV_HANDLE handle)
bool DRV_USART_TransmitBufferIsFull (const DRV_HANDLE handle)
void DRV_USART_ByteTransmitCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
void DRV_USART_ByteReceiveCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
void DRV_USART_ByteErrorCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
DRV_USART_ERROR DRV_USART_ErrorGet (const DRV_HANDLE client)
DRV_USART_BAUD_SET_RESULT DRV_USART_BaudSet (const DRV_HANDLE client, uint32_t baud)
DRV_USART_LINE_CONTROL_SET_RESULT DRV_USART_LineControlSet (const DRV_HANDLE client, const DRV_USART_LINE_CONTROL lineControl)
SYS_MODULE_OBJ SYS_DEBUG_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
void SYS_DEBUG_Reinitialize (SYS_MODULE_OBJ object, const SYS_MODULE_INIT *const init)
void SYS_DEBUG_Deinitialize (SYS_MODULE_OBJ object)
void SYS_DEBUG_Tasks (SYS_MODULE_OBJ object)
SYS_STATUS SYS_DEBUG_Status (SYS_MODULE_OBJ object)
void SYS_DEBUG_Message (const char *message)
void SYS_DEBUG_Print (const char *format,...)
void SYS_DEBUG_ErrorLevelSet (SYS_ERROR_LEVEL level)
SYS_ERROR_LEVEL SYS_DEBUG_ErrorLevelGet (void)
SYS_MODULE_OBJ DRV_USART0_Initialize (void)
void DRV_USART0_Deinitialize (void)
SYS_STATUS DRV_USART0_Status (void)
void DRV_USART0_TasksTransmit (void)
void DRV_USART0_TasksReceive (void)
void DRV_USART0_TasksError (void)
DRV_HANDLE DRV_USART0_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT ioIntent)
void DRV_USART0_Close (void)
DRV_USART_CLIENT_STATUS DRV_USART0_ClientStatus (void)
DRV_USART_TRANSFER_STATUS DRV_USART0_TransferStatus (void)
DRV_USART_ERROR DRV_USART0_ErrorGet (void)
uint8_t DRV_USART0_ReadByte (void)
void DRV_USART0_WriteByte (const uint8_t byte)
unsigned int DRV_USART0_ReceiverBufferSizeGet (void)
unsigned int DRV_USART0_TransmitBufferSizeGet (void)
bool DRV_USART0_ReceiverBufferIsEmpty (void)
bool DRV_USART0_TransmitBufferIsFull (void)
DRV_USART_BAUD_SET_RESULT DRV_USART0_BaudSet (uint32_t baud)
DRV_USART_LINE_CONTROL_SET_RESULT DRV_USART0_LineControlSet (DRV_USART_LINE_CONTROL lineControlMode)
void PLIB_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION inputFunction, PORTS_REMAP_INPUT_PIN remapInputPin)
void PLIB_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION outputFunction, PORTS_REMAP_OUTPUT_PIN remapOutputPin)
void PLIB_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
void PLIB_PORTS_PinModePerPortSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_MODE mode)
void PLIB_PORTS_ChangeNoticePullDownPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullDownPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullUpPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullUpPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinChangeNoticePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinChangeNoticePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePerPortTurnOn (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticePerPortTurnOff (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticeInIdlePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticeInIdlePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
bool PLIB_PORTS_ChangeNoticePerPortHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_PinGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_PinGetLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
void PLIB_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinDirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinDirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PORTS_DATA_TYPE PLIB_PORTS_ReadLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PORTS_DATA_TYPE PLIB_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
void PLIB_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
void PLIB_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
void PLIB_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
void PLIB_PORTS_DirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_DirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_MASK PLIB_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelModeSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK modeMask, PORTS_PIN_MODE mode)
void PLIB_PORTS_ChannelChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_AnPinsModeSelect (PORTS_MODULE_ID index, PORTS_AN_PIN anPins, PORTS_PIN_MODE mode)
void PLIB_PORTS_CnPinsPullUpEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsPullUpDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_ChangeNoticeEnable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticeDisable (PORTS_MODULE_ID index)
void PLIB_PORTS_PinChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_PinChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChangeNoticeInIdleEnable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticeInIdleDisable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChannelSlewRateSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK channelMask, PORTS_PIN_SLEW_RATE slewRate)
PORTS_PIN_SLEW_RATE PLIB_PORTS_PinSlewRateGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChannelChangeNoticeMethodSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_CHANGE_NOTICE_METHOD changeNoticeMethod)
PORTS_CHANGE_NOTICE_METHOD PLIB_PORTS_ChannelChangeNoticeMethodGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChannelChangeNoticeEdgeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
void PLIB_PORTS_ChannelChangeNoticeEdgeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
bool PLIB_PORTS_PinChangeNoticeEdgeIsEnabled (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_CHANGE_NOTICE_EDGE cnEdgeType)
bool PLIB_PORTS_PinChangeNoticeEdgeHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_ExistsRemapInput (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsRemapOutput (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinMode (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsAnPinsMode (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsRead (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsLatchRead (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsWrite (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsDirection (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsOpenDrain (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNotice (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinChangeNotice (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeInIdle (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullUp (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinModePerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullDownPerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullUpPerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinChangeNoticePerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortTurnOn (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortInIdle (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortStatus (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsSlewRateControl (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChannelChangeNoticeMethod (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeEdgeControl (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeEdgeStatus (PORTS_MODULE_ID index)
void SYS_PORTS_Initialize ()
PORTS_DATA_TYPE SYS_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
PORTS_DATA_TYPE SYS_PORTS_LatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
void SYS_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
void SYS_PORTS_DirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_MASK SYS_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
void SYS_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void SYS_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_TYPE SYS_PORTS_InterruptStatusGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION function, PORTS_REMAP_INPUT_PIN remapPin)
void SYS_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION function, PORTS_REMAP_OUTPUT_PIN remapPin)
void SYS_PORTS_ChangeNotificationGlobalEnable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationGlobalDisable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum, SYS_PORTS_PULLUP_PULLDOWN_STATUS value)
void SYS_PORTS_ChangeNotificationDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_ChangeNotificationInIdleModeEnable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationInIdleModeDisable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_ChangeNotificationPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
void SYS_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
bool SYS_PORTS_PinLatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool SYS_PORTS_PinRead (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinDirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_InterruptEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_INTERRUPT_TYPE pinInterruptType)
void PLIB_SPI_Enable (SPI_MODULE_ID index)
void PLIB_SPI_Disable (SPI_MODULE_ID index)
void PLIB_SPI_StopInIdleEnable (SPI_MODULE_ID index)
void PLIB_SPI_StopInIdleDisable (SPI_MODULE_ID index)
bool PLIB_SPI_ReceiverHasOverflowed (SPI_MODULE_ID index)
void PLIB_SPI_ReceiverOverflowClear (SPI_MODULE_ID index)
bool PLIB_SPI_TransmitBufferIsFull (SPI_MODULE_ID index)
bool PLIB_SPI_ReceiverBufferIsFull (SPI_MODULE_ID index)
void PLIB_SPI_PinEnable (SPI_MODULE_ID index, SPI_PIN pin)
void PLIB_SPI_PinDisable (SPI_MODULE_ID index, SPI_PIN pin)
void PLIB_SPI_CommunicationWidthSelect (SPI_MODULE_ID index, SPI_COMMUNICATION_WIDTH width)
void PLIB_SPI_AudioCommunicationWidthSelect (SPI_MODULE_ID index, SPI_AUDIO_COMMUNICATION_WIDTH mode)
void PLIB_SPI_InputSamplePhaseSelect (SPI_MODULE_ID index, SPI_INPUT_SAMPLING_PHASE phase)
void PLIB_SPI_OutputDataPhaseSelect (SPI_MODULE_ID index, SPI_OUTPUT_DATA_PHASE phase)
void PLIB_SPI_ClockPolaritySelect (SPI_MODULE_ID index, SPI_CLOCK_POLARITY polarity)
void PLIB_SPI_MasterEnable (SPI_MODULE_ID index)
void PLIB_SPI_SlaveEnable (SPI_MODULE_ID index)
void PLIB_SPI_BaudRateSet (SPI_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
bool PLIB_SPI_IsBusy (SPI_MODULE_ID index)
bool PLIB_SPI_ReadDataIsSignExtended (SPI_MODULE_ID index)
void PLIB_SPI_SlaveSelectEnable (SPI_MODULE_ID index)
void PLIB_SPI_SlaveSelectDisable (SPI_MODULE_ID index)
bool PLIB_SPI_TransmitUnderRunStatusGet (SPI_MODULE_ID index)
void PLIB_SPI_TransmitUnderRunStatusClear (SPI_MODULE_ID index)
bool PLIB_SPI_TransmitBufferIsEmpty (SPI_MODULE_ID index)
void PLIB_SPI_FIFOEnable (SPI_MODULE_ID index)
void PLIB_SPI_FIFODisable (SPI_MODULE_ID index)
uint8_t PLIB_SPI_FIFOCountGet (SPI_MODULE_ID index, SPI_FIFO_TYPE type)
bool PLIB_SPI_FIFOShiftRegisterIsEmpty (SPI_MODULE_ID index)
bool PLIB_SPI_ReceiverFIFOIsEmpty (SPI_MODULE_ID index)
void PLIB_SPI_FIFOInterruptModeSelect (SPI_MODULE_ID index, SPI_FIFO_INTERRUPT mode)
void PLIB_SPI_FramedCommunicationEnable (SPI_MODULE_ID index)
void PLIB_SPI_FramedCommunicationDisable (SPI_MODULE_ID index)
void PLIB_SPI_FrameSyncPulseDirectionSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_DIRECTION direction)
void PLIB_SPI_FrameSyncPulsePolaritySelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_POLARITY polarity)
void PLIB_SPI_FrameSyncPulseEdgeSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_EDGE edge)
void PLIB_SPI_FrameSyncPulseWidthSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_WIDTH width)
void PLIB_SPI_FrameSyncPulseCounterSelect (SPI_MODULE_ID index, SPI_FRAME_SYNC_PULSE pulse)
bool PLIB_SPI_FrameErrorStatusGet (SPI_MODULE_ID index)
void PLIB_SPI_FrameErrorStatusClear (SPI_MODULE_ID index)
void PLIB_SPI_BufferClear (SPI_MODULE_ID index)
uint8_t PLIB_SPI_BufferRead (SPI_MODULE_ID index)
uint16_t PLIB_SPI_BufferRead16bit (SPI_MODULE_ID index)
uint32_t PLIB_SPI_BufferRead32bit (SPI_MODULE_ID index)
void PLIB_SPI_BufferWrite (SPI_MODULE_ID index, uint8_t data)
void PLIB_SPI_BufferWrite16bit (SPI_MODULE_ID index, uint16_t data)
void PLIB_SPI_BufferWrite32bit (SPI_MODULE_ID index, uint32_t data)
void * PLIB_SPI_BufferAddressGet (SPI_MODULE_ID index)
void PLIB_SPI_BaudRateClockSelect (SPI_MODULE_ID index, SPI_BAUD_RATE_CLOCK type)
void PLIB_SPI_ErrorInterruptEnable (SPI_MODULE_ID index, SPI_ERROR_INTERRUPT error)
void PLIB_SPI_ErrorInterruptDisable (SPI_MODULE_ID index, SPI_ERROR_INTERRUPT error)
void PLIB_SPI_AudioErrorEnable (SPI_MODULE_ID index, SPI_AUDIO_ERROR error)
void PLIB_SPI_AudioErrorDisable (SPI_MODULE_ID index, SPI_AUDIO_ERROR error)
void PLIB_SPI_AudioProtocolEnable (SPI_MODULE_ID index)
void PLIB_SPI_AudioProtocolDisable (SPI_MODULE_ID index)
void PLIB_SPI_AudioTransmitModeSelect (SPI_MODULE_ID index, SPI_AUDIO_TRANSMIT_MODE mode)
void PLIB_SPI_AudioProtocolModeSelect (SPI_MODULE_ID index, SPI_AUDIO_PROTOCOL mode)
bool PLIB_SPI_ExistsEnableControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsStopInIdleControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsReceiverOverflow (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsTransmitBufferFullStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsTransmitBufferEmptyStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsReceiveBufferStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsPinControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsCommunicationWidth (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsAudioCommunicationWidth (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsInputSamplePhase (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsOutputDataPhase (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsClockPolarity (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsMasterControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsBaudRate (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsBusStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsReadDataSignStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsSlaveSelectControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsTransmitUnderRunStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFIFOControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFIFOCount (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsReceiveFIFOStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFIFOShiftRegisterEmptyStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFIFOInterruptMode (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFramedCommunication (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameSyncPulseDirection (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameSyncPulsePolarity (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameSyncPulseEdge (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameSyncPulseWidth (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameSyncPulseCounter (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsFrameErrorStatus (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsBuffer (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsBaudRateClock (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsErrorInterruptControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsAudioErrorControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsAudioProtocolControl (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsAudioTransmitMode (SPI_MODULE_ID index)
bool PLIB_SPI_ExistsAudioProtocolMode (SPI_MODULE_ID index)
bool PLIB_SPI_Exists32bitBuffer (SPI_MODULE_ID index)
bool PLIB_SPI_Exists16bitBuffer (SPI_MODULE_ID index)
SYS_MODULE_OBJ DRV_SPI_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
void DRV_SPI_Deinitialize (SYS_MODULE_OBJ object)
SYS_STATUS DRV_SPI_Status (SYS_MODULE_OBJ object)
void DRV_SPI_Tasks (SYS_MODULE_OBJ object)
DRV_HANDLE DRV_SPI_Open (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT ioIntent)
int32_t DRV_SPI_ClientConfigure (DRV_HANDLE handle, const DRV_SPI_CLIENT_DATA *cfgData)
void DRV_SPI_Close (DRV_HANDLE handle)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddRead (DRV_HANDLE handle, void *rxBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWrite (DRV_HANDLE handle, void *txBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWriteRead (DRV_HANDLE handle, void *txBuffer, size_t txSize, void *rxBuffer, size_t rxSize, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddRead2 (DRV_HANDLE handle, void *rxBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context, DRV_SPI_BUFFER_HANDLE *jobHandle)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWrite2 (DRV_HANDLE handle, void *txBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context, DRV_SPI_BUFFER_HANDLE *jobHandle)
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWriteRead2 (DRV_HANDLE handle, void *txBuffer, size_t txSize, void *rxBuffer, size_t rxSize, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void *context, DRV_SPI_BUFFER_HANDLE *jobHandle)
DRV_SPI_BUFFER_EVENT DRV_SPI_BufferStatus (DRV_SPI_BUFFER_HANDLE bufferHandle)
bool DRV_SPIn_ReceiverBufferIsFull (void)
bool DRV_SPIn_TransmitterBufferIsFull (void)
void APP_Initialize (void)
void APP_Tasks (void)
static void ReadUART (void)
static void WriteUART (void)
void UART_Tasks (void)
static void Fifo_Init (TFifo *ptrFifo, uint8_t *ptrBuffer, uint16_t Length)
void Init_Fifo (void)
uint8_t Fifo_Put (TFifo *ptrFifo, uint8_t Data)
uint8_t Fifo_Get (TFifo *ptrFifo)
uint8_t Fifo_Length (TFifo *ptrFifo)
static void ValidateComm (void)
void COMM_Tasks (void)
void COMMAND_Tasks (void)
bool Valid_Command (uchar8_t msg)
bool GetDepthStatus (void)
static void Execute_Auto_Protocol_A (void)
static void Execute_Protocol_A (void)
static void Execute_Protocol_B (void)
static void Execute_System (void)
static int UART_71zscanf (char *qqscan_str)
static void qqqqinitialise (int ii)
static void qqqbitmapreset ()
static void qqbmsoutput (FILEPOINT char *s, unsigned int i)
Variables
static int qqqqbmselwidth = 32
static int zzfileid = 71
int QQQindicator
static int QQQfirstmcdc =1
int UART_71zzopen
static int tbrun_mode =0
int QQQfcn_ptr_num
ldra_void_function qqqaccumupload [QQQnumfil]
static int qqqstructzzopen = 0
static unsigned char qqqzzglobflag = 0
static struct bitmapstruct_t bitmapstruct
SYS_ERROR_LEVEL gblErrLvl
APP_DATA APP
SYSTEM_OBJECTS sysObj
UART_DATA UART
TFifo RX_FIFO
TFifo TX_FIFO
COMM_DATA COMM
bool DepthStatus
COMMAND_DATA CMD
static UART_STATES U_STATES
static char qqqqone [] = "%6d\n"
static int qqqlast = 0
int qqupload_registered
Macro Definition Documentation
_DRV_ADC_STATIC_H
#define _DRV_ADC_STATIC_H
Definition at line 1412 of file inszt_UART.c.
_DRV_COMMON_H
#define _DRV_COMMON_H
Definition at line 852 of file inszt_UART.c.
_DRV_IC_H
#define _DRV_IC_H
Definition at line 303 of file inszt_UART.c.
_DRV_IC_STATIC_H
#define _DRV_IC_STATIC_H
Definition at line 1325 of file inszt_UART.c.
_DRV_PMP_STATIC_H
#define _DRV_PMP_STATIC_H
Definition at line 4198 of file inszt_UART.c.
_DRV_SPI_DEFINITIONS_H
#define _DRV_SPI_DEFINITIONS_H
Definition at line 23189 of file inszt_UART.c.
_DRV_SPI_H
#define _DRV_SPI_H
Definition at line 23152 of file inszt_UART.c.
_DRV_TMR_DEPRECATED_H
#define _DRV_TMR_DEPRECATED_H
Definition at line 2908 of file inszt_UART.c.
_DRV_TMR_H
#define _DRV_TMR_H
Definition at line 1554 of file inszt_UART.c.
_DRV_TMR_STATIC_H
#define _DRV_TMR_STATIC_H
Definition at line 1511 of file inszt_UART.c.
_DRV_USART_ALWAYS_NON_BLOCKING
#define _DRV_USART_ALWAYS_NON_BLOCKING (DRV_IO_INTENT_NONBLOCKING)
Definition at line 17369 of file inszt_UART.c.
_DRV_USART_ByteModelInterruptSourceEnable
#define _DRV_USART_ByteModelInterruptSourceEnable (source)
Definition at line 17382 of file inszt_UART.c.
_DRV_USART_CLIENT_BUFFER_QUEUE_OBJECTS_REMOVE
#define _DRV_USART_CLIENT_BUFFER_QUEUE_OBJECTS_REMOVE (x) true
Definition at line 17381 of file inszt_UART.c.
_DRV_USART_DEFINITIONS_H
#define _DRV_USART_DEFINITIONS_H
Definition at line 4398 of file inszt_UART.c.
_DRV_USART_ERROR_TASKS
#define _DRV_USART_ERROR_TASKS (x) _DRV_USART_ByteErrorTasks (x)
Definition at line 17380 of file inszt_UART.c.
_DRV_USART_FEATURE_MAPPING_H
#define _DRV_USART_FEATURE_MAPPING_H
Definition at line 17350 of file inszt_UART.c.
_DRV_USART_H
#define _DRV_USART_H
Definition at line 4357 of file inszt_UART.c.
_DRV_USART_InterruptSourceDisable
#define _DRV_USART_InterruptSourceDisable (source) false
Definition at line 17361 of file inszt_UART.c.
_DRV_USART_InterruptSourceEnable
#define _DRV_USART_InterruptSourceEnable (source)
Definition at line 17360 of file inszt_UART.c.
_DRV_USART_InterruptSourceIsEnabled
#define _DRV_USART_InterruptSourceIsEnabled (source) false
Definition at line 17359 of file inszt_UART.c.
_DRV_USART_InterruptSourceStatusClear
#define _DRV_USART_InterruptSourceStatusClear (source) SYS_INT_SourceStatusClear (source)
Definition at line 17362 of file inszt_UART.c.
_DRV_USART_RECEIVE_BUFFER_QUEUE_TASKS
#define _DRV_USART_RECEIVE_BUFFER_QUEUE_TASKS (x) _DRV_USART_ByteReceiveTasks (x)
Definition at line 17379 of file inszt_UART.c.
_DRV_USART_RELEASE_MUTEX
#define _DRV_USART_RELEASE_MUTEX (x) OSAL_MUTEX_Unlock (x)
Definition at line 17365 of file inszt_UART.c.
_DRV_USART_RX_DEPTH
#define _DRV_USART_RX_DEPTH 9
Definition at line 18157 of file inszt_UART.c.
_DRV_USART_SEM_POST
#define _DRV_USART_SEM_POST (x) OSAL_SEM_Post (x)
Definition at line 17363 of file inszt_UART.c.
_DRV_USART_STATIC_H
#define _DRV_USART_STATIC_H
Definition at line 4272 of file inszt_UART.c.
_DRV_USART_STATIC_LOCAL_H
#define _DRV_USART_STATIC_LOCAL_H
Definition at line 4312 of file inszt_UART.c.
_DRV_USART_TAKE_MUTEX
#define _DRV_USART_TAKE_MUTEX (x, y) OSAL_MUTEX_Lock (x , y)
Definition at line 17364 of file inszt_UART.c.
_DRV_USART_TRANSMIT_BUFFER_QUEUE_TASKS
#define _DRV_USART_TRANSMIT_BUFFER_QUEUE_TASKS (x) _DRV_USART_ByteTransmitTasks (x)
Definition at line 17378 of file inszt_UART.c.
_PLIB_DMA_H
#define _PLIB_DMA_H
Definition at line 8027 of file inszt_UART.c.
_PLIB_DMA_PROCESSOR_H
#define _PLIB_DMA_PROCESSOR_H
Definition at line 8060 of file inszt_UART.c.
_PLIB_PORTS_COMPATIBILITY_H
#define _PLIB_PORTS_COMPATIBILITY_H
Definition at line 21703 of file inszt_UART.c.
_PLIB_PORTS_H
#define _PLIB_PORTS_H
Definition at line 18406 of file inszt_UART.c.
_PLIB_PORTS_PROCESSOR_H
#define _PLIB_PORTS_PROCESSOR_H
Definition at line 18474 of file inszt_UART.c.
_PLIB_SPI_H
#define _PLIB_SPI_H
Definition at line 23235 of file inszt_UART.c.
_PLIB_SPI_PROCESSOR_H
#define _PLIB_SPI_PROCESSOR_H
Definition at line 23270 of file inszt_UART.c.
_PLIB_UNSUPPORTED
#define _PLIB_UNSUPPORTED
Definition at line 1056 of file inszt_UART.c.
_PLIB_USART_H
#define _PLIB_USART_H
Definition at line 4443 of file inszt_UART.c.
_SYS_DEBUG_H
#define _SYS_DEBUG_H
Definition at line 17435 of file inszt_UART.c.
_SYS_DEBUG_MESSAGE
#define _SYS_DEBUG_MESSAGE (level, message) do { if ((level) <= SYS_DEBUG_ErrorLevelGet ()) SYS_DEBUG_Message (message) ; } while (0)
Definition at line 17889 of file inszt_UART.c.
_SYS_DEBUG_PRINT
#define _SYS_DEBUG_PRINT (level, format, ...) do { if ((level) <= SYS_DEBUG_ErrorLevelGet ()) SYS_DEBUG_Print (format , ## __VA_ARGS__) ; } while (0)
Definition at line 17933 of file inszt_UART.c.
_SYS_DEFINITIONS_H
#define _SYS_DEFINITIONS_H
Definition at line 249 of file inszt_UART.c.
_SYS_DMA_ChannelForceStart
#define _SYS_DMA_ChannelForceStart (channelHandle) SYS_DMA_ChannelForceStart (channelHandle)
Definition at line 17366 of file inszt_UART.c.
_SYS_DMA_DEFINITIONS_H
#define _SYS_DMA_DEFINITIONS_H
Definition at line 7981 of file inszt_UART.c.
_SYS_DMA_H
#define _SYS_DMA_H
Definition at line 7946 of file inszt_UART.c.
_SYS_PORTS_DEFINITIONS_H
#define _SYS_PORTS_DEFINITIONS_H
Definition at line 18360 of file inszt_UART.c.
_SYS_PORTS_H
#define _SYS_PORTS_H
Definition at line 18320 of file inszt_UART.c.
_SYSTEM_CONFIG_H
#define _SYSTEM_CONFIG_H
Definition at line 344 of file inszt_UART.c.
_SYSTEM_H
#define _SYSTEM_H
Definition at line 7889 of file inszt_UART.c.
_TMR_DEFINITIONS_PIC32M_H
#define _TMR_DEFINITIONS_PIC32M_H
Definition at line 1599 of file inszt_UART.c.
_USART_PROCESSOR_H
#define _USART_PROCESSOR_H
Definition at line 4487 of file inszt_UART.c.
APP_H
#define APP_H
Definition at line 27455 of file inszt_UART.c.
ARM_SWStateGet
#define ARM_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_2)
Definition at line 786 of file inszt_UART.c.
ARMCF_AUTO_SWStateGet
#define ARMCF_AUTO_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_13)
Definition at line 788 of file inszt_UART.c.
ARMCF_SWStateGet
#define ARMCF_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_1)
Definition at line 784 of file inszt_UART.c.
AUX_SWStateGet
#define AUX_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_8)
Definition at line 782 of file inszt_UART.c.
COMMANDS_H
#define COMMANDS_H
Definition at line 28124 of file inszt_UART.c.
COMMMODULE_H
#define COMMMODULE_H
Definition at line 27983 of file inszt_UART.c.
DMA_CHANNEL_ANY
#define DMA_CHANNEL_ANY ((DMA_CHANNEL) - 2)
Definition at line 13127 of file inszt_UART.c.
DMA_CHANNEL_NONE
#define DMA_CHANNEL_NONE ((DMA_CHANNEL) - 1)
Definition at line 13114 of file inszt_UART.c.
DMP_FIRE_LEDOff
#define DMP_FIRE_LEDOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 664 of file inszt_UART.c.
DMP_FIRE_LEDOn
#define DMP_FIRE_LEDOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 663 of file inszt_UART.c.
DMP_FIRE_LEDStateGet
#define DMP_FIRE_LEDStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 665 of file inszt_UART.c.
DMP_FIRE_LEDStateSet
#define DMP_FIRE_LEDStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9 , Value)
Definition at line 666 of file inszt_UART.c.
DMP_FIRE_LEDToggle
#define DMP_FIRE_LEDToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 662 of file inszt_UART.c.
DMP_FIRE_SWStateGet
#define DMP_FIRE_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_8)
Definition at line 768 of file inszt_UART.c.
DRUM1_SWStateGet
#define DRUM1_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_2)
Definition at line 774 of file inszt_UART.c.
DRUM2_SWStateGet
#define DRUM2_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_0)
Definition at line 778 of file inszt_UART.c.
DRV_CONFIG_NOT_SUPPORTED
#define DRV_CONFIG_NOT_SUPPORTED (((unsigned short) - 1))
Definition at line 1041 of file inszt_UART.c.
DRV_HANDLE_INVALID
#define DRV_HANDLE_INVALID (((DRV_HANDLE) - 1))
Definition at line 1030 of file inszt_UART.c.
DRV_IC_Close
#define DRV_IC_Close (handle)
Definition at line 1327 of file inszt_UART.c.
DRV_IC_DRIVER_MODE_STATIC
#define DRV_IC_DRIVER_MODE_STATIC
Definition at line 465 of file inszt_UART.c.
DRV_IC_INDEX_0
#define DRV_IC_INDEX_0 0
Definition at line 1076 of file inszt_UART.c.
DRV_IC_INDEX_1
#define DRV_IC_INDEX_1 1
Definition at line 1077 of file inszt_UART.c.
DRV_IC_INDEX_10
#define DRV_IC_INDEX_10 10
Definition at line 1086 of file inszt_UART.c.
DRV_IC_INDEX_11
#define DRV_IC_INDEX_11 11
Definition at line 1087 of file inszt_UART.c.
DRV_IC_INDEX_12
#define DRV_IC_INDEX_12 12
Definition at line 1088 of file inszt_UART.c.
DRV_IC_INDEX_13
#define DRV_IC_INDEX_13 13
Definition at line 1089 of file inszt_UART.c.
DRV_IC_INDEX_14
#define DRV_IC_INDEX_14 14
Definition at line 1090 of file inszt_UART.c.
DRV_IC_INDEX_15
#define DRV_IC_INDEX_15 15
Definition at line 1091 of file inszt_UART.c.
DRV_IC_INDEX_2
#define DRV_IC_INDEX_2 2
Definition at line 1078 of file inszt_UART.c.
DRV_IC_INDEX_3
#define DRV_IC_INDEX_3 3
Definition at line 1079 of file inszt_UART.c.
DRV_IC_INDEX_4
#define DRV_IC_INDEX_4 4
Definition at line 1080 of file inszt_UART.c.
DRV_IC_INDEX_5
#define DRV_IC_INDEX_5 5
Definition at line 1081 of file inszt_UART.c.
DRV_IC_INDEX_6
#define DRV_IC_INDEX_6 6
Definition at line 1082 of file inszt_UART.c.
DRV_IC_INDEX_7
#define DRV_IC_INDEX_7 7
Definition at line 1083 of file inszt_UART.c.
DRV_IC_INDEX_8
#define DRV_IC_INDEX_8 8
Definition at line 1084 of file inszt_UART.c.
DRV_IC_INDEX_9
#define DRV_IC_INDEX_9 9
Definition at line 1085 of file inszt_UART.c.
DRV_IC_Open
#define DRV_IC_Open (drvIndex, intent) (drvIndex)
Definition at line 1326 of file inszt_UART.c.
DRV_IO_ISBLOCKING
#define DRV_IO_ISBLOCKING (intent) (intent & DRV_IO_INTENT_BLOCKING)
Definition at line 954 of file inszt_UART.c.
DRV_IO_ISEXCLUSIVE
#define DRV_IO_ISEXCLUSIVE (intent) (intent & DRV_IO_INTENT_EXCLUSIVE)
Definition at line 974 of file inszt_UART.c.
DRV_IO_ISNONBLOCKING
#define DRV_IO_ISNONBLOCKING (intent) (intent & DRV_IO_INTENT_NONBLOCKING)
Definition at line 964 of file inszt_UART.c.
DRV_SPI_16BIT
#define DRV_SPI_16BIT 1
Definition at line 478 of file inszt_UART.c.
DRV_SPI_32BIT
#define DRV_SPI_32BIT 0
Definition at line 479 of file inszt_UART.c.
DRV_SPI_8BIT
#define DRV_SPI_8BIT 1
Definition at line 477 of file inszt_UART.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX0
#define DRV_SPI_ALLOW_IDLE_RUN_IDX0 false
Definition at line 489 of file inszt_UART.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX1
#define DRV_SPI_ALLOW_IDLE_RUN_IDX1 false
Definition at line 510 of file inszt_UART.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX2
#define DRV_SPI_ALLOW_IDLE_RUN_IDX2 false
Definition at line 531 of file inszt_UART.c.
DRV_SPI_BAUD_RATE_IDX0
#define DRV_SPI_BAUD_RATE_IDX0 1000000
Definition at line 499 of file inszt_UART.c.
DRV_SPI_BAUD_RATE_IDX1
#define DRV_SPI_BAUD_RATE_IDX1 1000000
Definition at line 520 of file inszt_UART.c.
DRV_SPI_BAUD_RATE_IDX2
#define DRV_SPI_BAUD_RATE_IDX2 500000
Definition at line 541 of file inszt_UART.c.
DRV_SPI_BUFFER_HANDLE_INVALID
#define DRV_SPI_BUFFER_HANDLE_INVALID ((DRV_SPI_BUFFER_HANDLE) (- 1))
Definition at line 26168 of file inszt_UART.c.
DRV_SPI_BUFFER_TYPE_IDX0
#define DRV_SPI_BUFFER_TYPE_IDX0 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 500 of file inszt_UART.c.
DRV_SPI_BUFFER_TYPE_IDX1
#define DRV_SPI_BUFFER_TYPE_IDX1 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 521 of file inszt_UART.c.
DRV_SPI_BUFFER_TYPE_IDX2
#define DRV_SPI_BUFFER_TYPE_IDX2 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 542 of file inszt_UART.c.
DRV_SPI_CLIENTS_NUMBER
#define DRV_SPI_CLIENTS_NUMBER 3
Definition at line 483 of file inszt_UART.c.
DRV_SPI_CLOCK_MODE_IDX0
#define DRV_SPI_CLOCK_MODE_IDX0 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 501 of file inszt_UART.c.
DRV_SPI_CLOCK_MODE_IDX1
#define DRV_SPI_CLOCK_MODE_IDX1 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 522 of file inszt_UART.c.
DRV_SPI_CLOCK_MODE_IDX2
#define DRV_SPI_CLOCK_MODE_IDX2 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 543 of file inszt_UART.c.
DRV_SPI_CLOCK_SOURCE_IDX0
#define DRV_SPI_CLOCK_SOURCE_IDX0 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 497 of file inszt_UART.c.
DRV_SPI_CLOCK_SOURCE_IDX1
#define DRV_SPI_CLOCK_SOURCE_IDX1 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 518 of file inszt_UART.c.
DRV_SPI_CLOCK_SOURCE_IDX2
#define DRV_SPI_CLOCK_SOURCE_IDX2 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 539 of file inszt_UART.c.
DRV_SPI_COMM_WIDTH_IDX0
#define DRV_SPI_COMM_WIDTH_IDX0 SPI_COMMUNICATION_WIDTH_16BITS
Definition at line 496 of file inszt_UART.c.
DRV_SPI_COMM_WIDTH_IDX1
#define DRV_SPI_COMM_WIDTH_IDX1 SPI_COMMUNICATION_WIDTH_8BITS
Definition at line 517 of file inszt_UART.c.
DRV_SPI_COMM_WIDTH_IDX2
#define DRV_SPI_COMM_WIDTH_IDX2 SPI_COMMUNICATION_WIDTH_16BITS
Definition at line 538 of file inszt_UART.c.
DRV_SPI_DMA
#define DRV_SPI_DMA 0
Definition at line 480 of file inszt_UART.c.
DRV_SPI_EBM
#define DRV_SPI_EBM 1
Definition at line 476 of file inszt_UART.c.
DRV_SPI_ELEMENTS_PER_QUEUE
#define DRV_SPI_ELEMENTS_PER_QUEUE 10
Definition at line 484 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX0
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX0 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 493 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX1
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX1 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 514 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX2
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX2 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 535 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX0
#define DRV_SPI_FRAME_PULSE_EDGE_IDX0 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 494 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX1
#define DRV_SPI_FRAME_PULSE_EDGE_IDX1 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 515 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX2
#define DRV_SPI_FRAME_PULSE_EDGE_IDX2 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 536 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX0
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX0 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 492 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX1
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX1 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 513 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX2
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX2 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 534 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX0
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX0 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 495 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX1
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX1 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 516 of file inszt_UART.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX2
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX2 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 537 of file inszt_UART.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX0
#define DRV_SPI_FRAME_SYNC_PULSE_IDX0 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 491 of file inszt_UART.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX1
#define DRV_SPI_FRAME_SYNC_PULSE_IDX1 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 512 of file inszt_UART.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX2
#define DRV_SPI_FRAME_SYNC_PULSE_IDX2 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 533 of file inszt_UART.c.
DRV_SPI_INDEX_0
#define DRV_SPI_INDEX_0 0
Definition at line 26180 of file inszt_UART.c.
DRV_SPI_INDEX_1
#define DRV_SPI_INDEX_1 1
Definition at line 26181 of file inszt_UART.c.
DRV_SPI_INDEX_2
#define DRV_SPI_INDEX_2 2
Definition at line 26182 of file inszt_UART.c.
DRV_SPI_INDEX_3
#define DRV_SPI_INDEX_3 3
Definition at line 26183 of file inszt_UART.c.
DRV_SPI_INDEX_4
#define DRV_SPI_INDEX_4 4
Definition at line 26184 of file inszt_UART.c.
DRV_SPI_INDEX_5
#define DRV_SPI_INDEX_5 5
Definition at line 26185 of file inszt_UART.c.
DRV_SPI_INDEX_COUNT
#define DRV_SPI_INDEX_COUNT SPI_NUMBER_OF_MODULES
Definition at line 26197 of file inszt_UART.c.
DRV_SPI_INPUT_PHASE_IDX0
#define DRV_SPI_INPUT_PHASE_IDX0 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
Definition at line 502 of file inszt_UART.c.
DRV_SPI_INPUT_PHASE_IDX1
#define DRV_SPI_INPUT_PHASE_IDX1 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
Definition at line 523 of file inszt_UART.c.
DRV_SPI_INPUT_PHASE_IDX2
#define DRV_SPI_INPUT_PHASE_IDX2 SPI_INPUT_SAMPLING_PHASE_AT_END
Definition at line 544 of file inszt_UART.c.
DRV_SPI_INSTANCES_NUMBER
#define DRV_SPI_INSTANCES_NUMBER 3
Definition at line 482 of file inszt_UART.c.
DRV_SPI_ISR
#define DRV_SPI_ISR 0
Definition at line 472 of file inszt_UART.c.
DRV_SPI_MASTER
#define DRV_SPI_MASTER 1
Definition at line 473 of file inszt_UART.c.
DRV_SPI_NUMBER_OF_MODULES
#define DRV_SPI_NUMBER_OF_MODULES 6
Definition at line 468 of file inszt_UART.c.
DRV_SPI_POLLED
#define DRV_SPI_POLLED 1
Definition at line 471 of file inszt_UART.c.
DRV_SPI_QUEUE_SIZE_IDX0
#define DRV_SPI_QUEUE_SIZE_IDX0 10
Definition at line 504 of file inszt_UART.c.
DRV_SPI_QUEUE_SIZE_IDX1
#define DRV_SPI_QUEUE_SIZE_IDX1 10
Definition at line 525 of file inszt_UART.c.
DRV_SPI_QUEUE_SIZE_IDX2
#define DRV_SPI_QUEUE_SIZE_IDX2 10
Definition at line 546 of file inszt_UART.c.
DRV_SPI_RESERVED_JOB_IDX0
#define DRV_SPI_RESERVED_JOB_IDX0 1
Definition at line 505 of file inszt_UART.c.
DRV_SPI_RESERVED_JOB_IDX1
#define DRV_SPI_RESERVED_JOB_IDX1 1
Definition at line 526 of file inszt_UART.c.
DRV_SPI_RESERVED_JOB_IDX2
#define DRV_SPI_RESERVED_JOB_IDX2 1
Definition at line 547 of file inszt_UART.c.
DRV_SPI_RM
#define DRV_SPI_RM 0
Definition at line 475 of file inszt_UART.c.
DRV_SPI_SLAVE
#define DRV_SPI_SLAVE 0
Definition at line 474 of file inszt_UART.c.
DRV_SPI_SPI_CLOCK_IDX0
#define DRV_SPI_SPI_CLOCK_IDX0 CLK_BUS_PERIPHERAL_2
Definition at line 498 of file inszt_UART.c.
DRV_SPI_SPI_CLOCK_IDX1
#define DRV_SPI_SPI_CLOCK_IDX1 CLK_BUS_PERIPHERAL_2
Definition at line 519 of file inszt_UART.c.
DRV_SPI_SPI_CLOCK_IDX2
#define DRV_SPI_SPI_CLOCK_IDX2 CLK_BUS_PERIPHERAL_2
Definition at line 540 of file inszt_UART.c.
DRV_SPI_SPI_ID_IDX0
#define DRV_SPI_SPI_ID_IDX0 SPI_ID_1
Definition at line 486 of file inszt_UART.c.
DRV_SPI_SPI_ID_IDX1
#define DRV_SPI_SPI_ID_IDX1 SPI_ID_2
Definition at line 507 of file inszt_UART.c.
DRV_SPI_SPI_ID_IDX2
#define DRV_SPI_SPI_ID_IDX2 SPI_ID_4
Definition at line 528 of file inszt_UART.c.
DRV_SPI_SPI_MODE_IDX0
#define DRV_SPI_SPI_MODE_IDX0 DRV_SPI_MODE_MASTER
Definition at line 488 of file inszt_UART.c.
DRV_SPI_SPI_MODE_IDX1
#define DRV_SPI_SPI_MODE_IDX1 DRV_SPI_MODE_MASTER
Definition at line 509 of file inszt_UART.c.
DRV_SPI_SPI_MODE_IDX2
#define DRV_SPI_SPI_MODE_IDX2 DRV_SPI_MODE_MASTER
Definition at line 530 of file inszt_UART.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX0
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX0 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 490 of file inszt_UART.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX1
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX1 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 511 of file inszt_UART.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX2
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX2 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 532 of file inszt_UART.c.
DRV_SPI_TASK_MODE_IDX0
#define DRV_SPI_TASK_MODE_IDX0 DRV_SPI_TASK_MODE_POLLED
Definition at line 487 of file inszt_UART.c.
DRV_SPI_TASK_MODE_IDX1
#define DRV_SPI_TASK_MODE_IDX1 DRV_SPI_TASK_MODE_POLLED
Definition at line 508 of file inszt_UART.c.
DRV_SPI_TASK_MODE_IDX2
#define DRV_SPI_TASK_MODE_IDX2 DRV_SPI_TASK_MODE_POLLED
Definition at line 529 of file inszt_UART.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0 0xFFFF
Definition at line 503 of file inszt_UART.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1 0xFF
Definition at line 524 of file inszt_UART.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2 0x0000
Definition at line 545 of file inszt_UART.c.
DRV_TIMER_DIVIDER_MAX_16BIT
#define DRV_TIMER_DIVIDER_MAX_16BIT 0x10000
Definition at line 3594 of file inszt_UART.c.
DRV_TIMER_DIVIDER_MAX_32BIT
#define DRV_TIMER_DIVIDER_MAX_32BIT 0xffffffff
Definition at line 3590 of file inszt_UART.c.
DRV_TIMER_DIVIDER_MIN_16BIT
#define DRV_TIMER_DIVIDER_MIN_16BIT 0x2
Definition at line 3596 of file inszt_UART.c.
DRV_TIMER_DIVIDER_MIN_32BIT
#define DRV_TIMER_DIVIDER_MIN_32BIT 0x2
Definition at line 3592 of file inszt_UART.c.
DRV_TMR_Alarm16BitDeregister
#define DRV_TMR_Alarm16BitDeregister (handle) DRV_TMR_AlarmDeregister (handle)
Definition at line 3505 of file inszt_UART.c.
DRV_TMR_Alarm16BitRegister
#define DRV_TMR_Alarm16BitRegister (handle, period, isPeriodic, context, callBack) DRV_TMR_AlarmRegister (handle , period , isPeriodic , context , callBack)
Definition at line 3257 of file inszt_UART.c.
DRV_TMR_Alarm32BitDeregister
#define DRV_TMR_Alarm32BitDeregister (handle) DRV_TMR_AlarmDeregister (handle)
Definition at line 3570 of file inszt_UART.c.
DRV_TMR_Alarm32BitRegister
#define DRV_TMR_Alarm32BitRegister (handle, period, isPeriodic, context, callBack) DRV_TMR_AlarmRegister (handle , period , isPeriodic , context , callBack)
Definition at line 3318 of file inszt_UART.c.
DRV_TMR_AlarmPeriod16BitGet
#define DRV_TMR_AlarmPeriod16BitGet (handle) DRV_TMR_AlarmPeriodGet (handle)
Definition at line 3411 of file inszt_UART.c.
DRV_TMR_AlarmPeriod16BitSet
#define DRV_TMR_AlarmPeriod16BitSet (handle, value) DRV_TMR_AlarmPeriodSet (handle , value)
Definition at line 3348 of file inszt_UART.c.
DRV_TMR_AlarmPeriod32BitGet
#define DRV_TMR_AlarmPeriod32BitGet (handle) DRV_TMR_AlarmPeriodGet (handle)
Definition at line 3443 of file inszt_UART.c.
DRV_TMR_AlarmPeriod32BitSet
#define DRV_TMR_AlarmPeriod32BitSet (handle, period) DRV_TMR_AlarmPeriodSet (handle , period)
Definition at line 3380 of file inszt_UART.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX0
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX0 false
Definition at line 560 of file inszt_UART.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX1
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX1 false
Definition at line 571 of file inszt_UART.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX2
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX2 false
Definition at line 583 of file inszt_UART.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX3
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX3 false
Definition at line 595 of file inszt_UART.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX4
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX4 false
Definition at line 607 of file inszt_UART.c.
DRV_TMR_CLOCK_SOURCE_IDX0
#define DRV_TMR_CLOCK_SOURCE_IDX0 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 557 of file inszt_UART.c.
DRV_TMR_CLOCK_SOURCE_IDX1
#define DRV_TMR_CLOCK_SOURCE_IDX1 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 568 of file inszt_UART.c.
DRV_TMR_CLOCK_SOURCE_IDX2
#define DRV_TMR_CLOCK_SOURCE_IDX2 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 580 of file inszt_UART.c.
DRV_TMR_CLOCK_SOURCE_IDX3
#define DRV_TMR_CLOCK_SOURCE_IDX3 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 592 of file inszt_UART.c.
DRV_TMR_CLOCK_SOURCE_IDX4
#define DRV_TMR_CLOCK_SOURCE_IDX4 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 604 of file inszt_UART.c.
DRV_TMR_CounterValue16BitGet
#define DRV_TMR_CounterValue16BitGet (handle) DRV_TMR_CounterValueGet (handle)
Definition at line 3137 of file inszt_UART.c.
DRV_TMR_CounterValue16BitSet
#define DRV_TMR_CounterValue16BitSet (handle, counterPeriod) DRV_TMR_CounterValueSet (handle , counterPeriod)
Definition at line 3013 of file inszt_UART.c.
DRV_TMR_CounterValue32BitGet
#define DRV_TMR_CounterValue32BitGet (handle) DRV_TMR_CounterValueGet (handle)
Definition at line 3198 of file inszt_UART.c.
DRV_TMR_CounterValue32BitSet
#define DRV_TMR_CounterValue32BitSet (handle, counterPeriod) DRV_TMR_CounterValueSet (handle , counterPeriod)
Definition at line 3078 of file inszt_UART.c.
DRV_TMR_INDEX_0
#define DRV_TMR_INDEX_0 0
Definition at line 1677 of file inszt_UART.c.
DRV_TMR_INDEX_1
#define DRV_TMR_INDEX_1 1
Definition at line 1678 of file inszt_UART.c.
DRV_TMR_INDEX_10
#define DRV_TMR_INDEX_10 10
Definition at line 1687 of file inszt_UART.c.
DRV_TMR_INDEX_11
#define DRV_TMR_INDEX_11 11
Definition at line 1688 of file inszt_UART.c.
DRV_TMR_INDEX_2
#define DRV_TMR_INDEX_2 2
Definition at line 1679 of file inszt_UART.c.
DRV_TMR_INDEX_3
#define DRV_TMR_INDEX_3 3
Definition at line 1680 of file inszt_UART.c.
DRV_TMR_INDEX_4
#define DRV_TMR_INDEX_4 4
Definition at line 1681 of file inszt_UART.c.
DRV_TMR_INDEX_5
#define DRV_TMR_INDEX_5 5
Definition at line 1682 of file inszt_UART.c.
DRV_TMR_INDEX_6
#define DRV_TMR_INDEX_6 6
Definition at line 1683 of file inszt_UART.c.
DRV_TMR_INDEX_7
#define DRV_TMR_INDEX_7 7
Definition at line 1684 of file inszt_UART.c.
DRV_TMR_INDEX_8
#define DRV_TMR_INDEX_8 8
Definition at line 1685 of file inszt_UART.c.
DRV_TMR_INDEX_9
#define DRV_TMR_INDEX_9 9
Definition at line 1686 of file inszt_UART.c.
DRV_TMR_INDEX_COUNT
#define DRV_TMR_INDEX_COUNT TMR_NUMBER_OF_MODULES
Definition at line 1699 of file inszt_UART.c.
DRV_TMR_INTERRUPT_MODE
#define DRV_TMR_INTERRUPT_MODE true
Definition at line 549 of file inszt_UART.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX0
#define DRV_TMR_INTERRUPT_PRIORITY_IDX0 INT_PRIORITY_LEVEL4
Definition at line 555 of file inszt_UART.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX1
#define DRV_TMR_INTERRUPT_PRIORITY_IDX1 INT_PRIORITY_LEVEL3
Definition at line 566 of file inszt_UART.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX2
#define DRV_TMR_INTERRUPT_PRIORITY_IDX2 INT_PRIORITY_LEVEL1
Definition at line 578 of file inszt_UART.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX3
#define DRV_TMR_INTERRUPT_PRIORITY_IDX3 INT_PRIORITY_LEVEL2
Definition at line 590 of file inszt_UART.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX4
#define DRV_TMR_INTERRUPT_PRIORITY_IDX4 INT_PRIORITY_LEVEL1
Definition at line 602 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SOURCE_IDX0
#define DRV_TMR_INTERRUPT_SOURCE_IDX0 INT_SOURCE_TIMER_2
Definition at line 552 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SOURCE_IDX1
#define DRV_TMR_INTERRUPT_SOURCE_IDX1 INT_SOURCE_TIMER_7
Definition at line 563 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SOURCE_IDX2
#define DRV_TMR_INTERRUPT_SOURCE_IDX2 INT_SOURCE_TIMER_6
Definition at line 575 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SOURCE_IDX3
#define DRV_TMR_INTERRUPT_SOURCE_IDX3 INT_SOURCE_TIMER_1
Definition at line 587 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SOURCE_IDX4
#define DRV_TMR_INTERRUPT_SOURCE_IDX4 INT_SOURCE_TIMER_3
Definition at line 599 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0 INT_SUBPRIORITY_LEVEL0
Definition at line 556 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1 INT_SUBPRIORITY_LEVEL0
Definition at line 567 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2 INT_SUBPRIORITY_LEVEL0
Definition at line 579 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3 INT_SUBPRIORITY_LEVEL0
Definition at line 591 of file inszt_UART.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4 INT_SUBPRIORITY_LEVEL0
Definition at line 603 of file inszt_UART.c.
DRV_TMR_INTERRUPT_VECTOR_IDX0
#define DRV_TMR_INTERRUPT_VECTOR_IDX0 INT_VECTOR_T2
Definition at line 553 of file inszt_UART.c.
DRV_TMR_INTERRUPT_VECTOR_IDX1
#define DRV_TMR_INTERRUPT_VECTOR_IDX1 INT_VECTOR_T7
Definition at line 564 of file inszt_UART.c.
DRV_TMR_INTERRUPT_VECTOR_IDX2
#define DRV_TMR_INTERRUPT_VECTOR_IDX2 INT_VECTOR_T6
Definition at line 576 of file inszt_UART.c.
DRV_TMR_INTERRUPT_VECTOR_IDX3
#define DRV_TMR_INTERRUPT_VECTOR_IDX3 INT_VECTOR_T1
Definition at line 588 of file inszt_UART.c.
DRV_TMR_INTERRUPT_VECTOR_IDX4
#define DRV_TMR_INTERRUPT_VECTOR_IDX4 INT_VECTOR_T3
Definition at line 600 of file inszt_UART.c.
DRV_TMR_ISR_VECTOR_IDX0
#define DRV_TMR_ISR_VECTOR_IDX0 _TIMER_2_VECTOR
Definition at line 554 of file inszt_UART.c.
DRV_TMR_ISR_VECTOR_IDX1
#define DRV_TMR_ISR_VECTOR_IDX1 _TIMER_7_VECTOR
Definition at line 565 of file inszt_UART.c.
DRV_TMR_ISR_VECTOR_IDX2
#define DRV_TMR_ISR_VECTOR_IDX2 _TIMER_6_VECTOR
Definition at line 577 of file inszt_UART.c.
DRV_TMR_ISR_VECTOR_IDX3
#define DRV_TMR_ISR_VECTOR_IDX3 _TIMER_1_VECTOR
Definition at line 589 of file inszt_UART.c.
DRV_TMR_ISR_VECTOR_IDX4
#define DRV_TMR_ISR_VECTOR_IDX4 _TIMER_3_VECTOR
Definition at line 601 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE_IDX0
#define DRV_TMR_OPERATION_MODE_IDX0 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 559 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE_IDX1
#define DRV_TMR_OPERATION_MODE_IDX1 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 570 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE_IDX2
#define DRV_TMR_OPERATION_MODE_IDX2 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 582 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE_IDX3
#define DRV_TMR_OPERATION_MODE_IDX3 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 594 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE_IDX4
#define DRV_TMR_OPERATION_MODE_IDX4 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 606 of file inszt_UART.c.
DRV_TMR_PERIPHERAL_ID_IDX0
#define DRV_TMR_PERIPHERAL_ID_IDX0 TMR_ID_2
Definition at line 551 of file inszt_UART.c.
DRV_TMR_PERIPHERAL_ID_IDX1
#define DRV_TMR_PERIPHERAL_ID_IDX1 TMR_ID_7
Definition at line 562 of file inszt_UART.c.
DRV_TMR_PERIPHERAL_ID_IDX2
#define DRV_TMR_PERIPHERAL_ID_IDX2 TMR_ID_6
Definition at line 574 of file inszt_UART.c.
DRV_TMR_PERIPHERAL_ID_IDX3
#define DRV_TMR_PERIPHERAL_ID_IDX3 TMR_ID_1
Definition at line 586 of file inszt_UART.c.
DRV_TMR_PERIPHERAL_ID_IDX4
#define DRV_TMR_PERIPHERAL_ID_IDX4 TMR_ID_3
Definition at line 598 of file inszt_UART.c.
DRV_TMR_POWER_STATE_IDX0
#define DRV_TMR_POWER_STATE_IDX0
Definition at line 561 of file inszt_UART.c.
DRV_TMR_POWER_STATE_IDX1
#define DRV_TMR_POWER_STATE_IDX1
Definition at line 572 of file inszt_UART.c.
DRV_TMR_POWER_STATE_IDX2
#define DRV_TMR_POWER_STATE_IDX2
Definition at line 584 of file inszt_UART.c.
DRV_TMR_POWER_STATE_IDX3
#define DRV_TMR_POWER_STATE_IDX3
Definition at line 596 of file inszt_UART.c.
DRV_TMR_POWER_STATE_IDX4
#define DRV_TMR_POWER_STATE_IDX4
Definition at line 608 of file inszt_UART.c.
DRV_TMR_PRESCALE_IDX0
#define DRV_TMR_PRESCALE_IDX0 TMR_PRESCALE_VALUE_8
Definition at line 558 of file inszt_UART.c.
DRV_TMR_PRESCALE_IDX1
#define DRV_TMR_PRESCALE_IDX1 TMR_PRESCALE_VALUE_16
Definition at line 569 of file inszt_UART.c.
DRV_TMR_PRESCALE_IDX2
#define DRV_TMR_PRESCALE_IDX2 TMR_PRESCALE_VALUE_16
Definition at line 581 of file inszt_UART.c.
DRV_TMR_PRESCALE_IDX3
#define DRV_TMR_PRESCALE_IDX3 TMR_PRESCALE_VALUE_256
Definition at line 593 of file inszt_UART.c.
DRV_TMR_PRESCALE_IDX4
#define DRV_TMR_PRESCALE_IDX4 TMR_PRESCALE_VALUE_16
Definition at line 605 of file inszt_UART.c.
DRV_TMR_Tasks_ISR
#define DRV_TMR_Tasks_ISR (object) DRV_TMR_Tasks (object)
Definition at line 2949 of file inszt_UART.c.
DRV_USART_BUFFER_HANDLE_INVALID
#define DRV_USART_BUFFER_HANDLE_INVALID ((DRV_USART_BUFFER_HANDLE) (- 1))
Definition at line 14956 of file inszt_UART.c.
DRV_USART_BUFFER_QUEUE_SUPPORT
#define DRV_USART_BUFFER_QUEUE_SUPPORT false
Definition at line 617 of file inszt_UART.c.
DRV_USART_BYTE_MODEL_SUPPORT
#define DRV_USART_BYTE_MODEL_SUPPORT true
Definition at line 615 of file inszt_UART.c.
DRV_USART_CLIENTS_NUMBER
#define DRV_USART_CLIENTS_NUMBER 1
Definition at line 613 of file inszt_UART.c.
DRV_USART_COUNT
#define DRV_USART_COUNT USART_NUMBER_OF_MODULES
Definition at line 14900 of file inszt_UART.c.
DRV_USART_INDEX_0
#define DRV_USART_INDEX_0 0
Definition at line 14881 of file inszt_UART.c.
DRV_USART_INDEX_1
#define DRV_USART_INDEX_1 1
Definition at line 14882 of file inszt_UART.c.
DRV_USART_INDEX_2
#define DRV_USART_INDEX_2 2
Definition at line 14883 of file inszt_UART.c.
DRV_USART_INDEX_3
#define DRV_USART_INDEX_3 3
Definition at line 14884 of file inszt_UART.c.
DRV_USART_INDEX_4
#define DRV_USART_INDEX_4 4
Definition at line 14885 of file inszt_UART.c.
DRV_USART_INDEX_5
#define DRV_USART_INDEX_5 5
Definition at line 14886 of file inszt_UART.c.
DRV_USART_INSTANCES_NUMBER
#define DRV_USART_INSTANCES_NUMBER 1
Definition at line 612 of file inszt_UART.c.
DRV_USART_INTERRUPT_MODE
#define DRV_USART_INTERRUPT_MODE false
Definition at line 614 of file inszt_UART.c.
DRV_USART_READ_ERROR
#define DRV_USART_READ_ERROR ((uint32_t) (- 1))
Definition at line 14922 of file inszt_UART.c.
DRV_USART_READ_WRITE_MODEL_SUPPORT
#define DRV_USART_READ_WRITE_MODEL_SUPPORT false
Definition at line 616 of file inszt_UART.c.
DRV_USART_WRITE_ERROR
#define DRV_USART_WRITE_ERROR ((uint32_t) (- 1))
Definition at line 14911 of file inszt_UART.c.
DRV_USBHS_DEVICE_SUPPORT
#define DRV_USBHS_DEVICE_SUPPORT true
Definition at line 625 of file inszt_UART.c.
DRV_USBHS_ENDPOINTS_NUMBER
#define DRV_USBHS_ENDPOINTS_NUMBER 2
Definition at line 633 of file inszt_UART.c.
DRV_USBHS_HOST_SUPPORT
#define DRV_USBHS_HOST_SUPPORT false
Definition at line 627 of file inszt_UART.c.
DRV_USBHS_INSTANCES_NUMBER
#define DRV_USBHS_INSTANCES_NUMBER 1
Definition at line 629 of file inszt_UART.c.
DRV_USBHS_INTERRUPT_MODE
#define DRV_USBHS_INTERRUPT_MODE true
Definition at line 631 of file inszt_UART.c.
ELEMENT [1/3]
#define ELEMENT (N) qqqbitmapint element##N;
Definition at line 170 of file inszt_UART.c.
ELEMENT [2/3]
#define ELEMENT (N) 0,
Definition at line 170 of file inszt_UART.c.
ELEMENT [3/3]
#define ELEMENT (N) qqbmsoutput("%8d", bitmapstruct.element##N);
Definition at line 170 of file inszt_UART.c.
FIFO_ADD_OK
#define FIFO_ADD_OK 0
Definition at line 27780 of file inszt_UART.c.
FIFO_EMPTY
#define FIFO_EMPTY 2U
Definition at line 27783 of file inszt_UART.c.
FIFO_FULL
#define FIFO_FULL 1
Definition at line 27781 of file inszt_UART.c.
FIFO_H
#define FIFO_H
Definition at line 27764 of file inszt_UART.c.
FIFO_RX_SIZE
#define FIFO_RX_SIZE 7
Definition at line 27777 of file inszt_UART.c.
FIFO_TX_SIZE
#define FIFO_TX_SIZE 7
Definition at line 27778 of file inszt_UART.c.
FILEPOINT
#define FILEPOINT
Definition at line 92 of file inszt_UART.c.
FIRE_SW_OFFStateGet
#define FIRE_SW_OFFStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_8)
Definition at line 790 of file inszt_UART.c.
FIRE_SW_ONStateGet
#define FIRE_SW_ONStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_8)
Definition at line 792 of file inszt_UART.c.
FSK_DAC_CLROff
#define FSK_DAC_CLROff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 754 of file inszt_UART.c.
FSK_DAC_CLROn
#define FSK_DAC_CLROn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 753 of file inszt_UART.c.
FSK_DAC_CLRStateGet
#define FSK_DAC_CLRStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 755 of file inszt_UART.c.
FSK_DAC_CLRStateSet
#define FSK_DAC_CLRStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7 , Value)
Definition at line 756 of file inszt_UART.c.
FSK_DAC_CLRToggle
#define FSK_DAC_CLRToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 752 of file inszt_UART.c.
FSK_DAC_CSOff
#define FSK_DAC_CSOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 742 of file inszt_UART.c.
FSK_DAC_CSOn
#define FSK_DAC_CSOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 741 of file inszt_UART.c.
FSK_DAC_CSStateGet
#define FSK_DAC_CSStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 743 of file inszt_UART.c.
FSK_DAC_CSStateSet
#define FSK_DAC_CSStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4 , Value)
Definition at line 744 of file inszt_UART.c.
FSK_DAC_CSToggle
#define FSK_DAC_CSToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 740 of file inszt_UART.c.
HVPS_CN_PORT_BIT
#define HVPS_CN_PORT_BIT PORTS_BIT_POS_11
Definition at line 801 of file inszt_UART.c.
HVPS_CN_PORT_CHANNEL
#define HVPS_CN_PORT_CHANNEL PORT_CHANNEL_J
Definition at line 800 of file inszt_UART.c.
HVPS_CN_PORT_INTERRUPT
#define HVPS_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_J
Definition at line 802 of file inszt_UART.c.
HVPS_ENBOff
#define HVPS_ENBOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 670 of file inszt_UART.c.
HVPS_ENBOn
#define HVPS_ENBOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 669 of file inszt_UART.c.
HVPS_ENBStateGet
#define HVPS_ENBStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 671 of file inszt_UART.c.
HVPS_ENBStateSet
#define HVPS_ENBStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13 , Value)
Definition at line 672 of file inszt_UART.c.
HVPS_ENBToggle
#define HVPS_ENBToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 668 of file inszt_UART.c.
HVPS_SWStateGet
#define HVPS_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_5)
Definition at line 764 of file inszt_UART.c.
LASTELEMENT [1/2]
#define LASTELEMENT
Definition at line 171 of file inszt_UART.c.
LASTELEMENT [2/2]
#define LASTELEMENT
Definition at line 171 of file inszt_UART.c.
ldra_sscanf
#define ldra_sscanf
Definition at line 28660 of file inszt_UART.c.
LDRA_VOID_FUNC
#define LDRA_VOID_FUNC
Definition at line 114 of file inszt_UART.c.
LED1Off
#define LED1Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 652 of file inszt_UART.c.
LED1On
#define LED1On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 651 of file inszt_UART.c.
LED1StateGet
#define LED1StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 653 of file inszt_UART.c.
LED1StateSet
#define LED1StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12 , Value)
Definition at line 654 of file inszt_UART.c.
LED1Toggle
#define LED1Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 650 of file inszt_UART.c.
LED2Off
#define LED2Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 658 of file inszt_UART.c.
LED2On
#define LED2On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 657 of file inszt_UART.c.
LED2StateGet
#define LED2StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 659 of file inszt_UART.c.
LED2StateSet
#define LED2StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10 , Value)
Definition at line 660 of file inszt_UART.c.
LED2Toggle
#define LED2Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 656 of file inszt_UART.c.
LOG_SWStateGet
#define LOG_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_3)
Definition at line 780 of file inszt_UART.c.
MAN_CN_PORT_BIT
#define MAN_CN_PORT_BIT PORTS_BIT_POS_0
Definition at line 798 of file inszt_UART.c.
MAN_CN_PORT_CHANNEL
#define MAN_CN_PORT_CHANNEL PORT_CHANNEL_A
Definition at line 797 of file inszt_UART.c.
MAN_CN_PORT_INTERRUPT
#define MAN_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_A
Definition at line 799 of file inszt_UART.c.
MAN_SIGStateGet
#define MAN_SIGStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_0)
Definition at line 766 of file inszt_UART.c.
NEG_SWStateGet
#define NEG_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_4)
Definition at line 770 of file inszt_UART.c.
PLIB_PORTS_ChangeNoticePerPortHasOccured
#define PLIB_PORTS_ChangeNoticePerPortHasOccured PLIB_PORTS_ChangeNoticePerPortHasOccurred
Definition at line 21740 of file inszt_UART.c.
POS_SWStateGet
#define POS_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_15)
Definition at line 772 of file inszt_UART.c.
qqnull_params [1/2]
#define qqnull_params void
Definition at line 28677 of file inszt_UART.c.
qqnull_params [2/2]
#define qqnull_params void
Definition at line 28677 of file inszt_UART.c.
QQQ_PROTOTYPE_DEF
#define QQQ_PROTOTYPE_DEF
Definition at line 157 of file inszt_UART.c.
QQQBITMAP
#define QQQBITMAP
Definition at line 65 of file inszt_UART.c.
qqqbitmapint
#define qqqbitmapint unsigned int
Definition at line 66 of file inszt_UART.c.
qqqbranches
#define qqqbranches 99
Definition at line 28655 of file inszt_UART.c.
Referenced by qqbmsoutput().
QQQdialect
#define QQQdialect MPLABX
Definition at line 30 of file inszt_UART.c.
QQQFILEID
#define QQQFILEID
Definition at line 73 of file inszt_UART.c.
QQQFIXEDSIZE
#define QQQFIXEDSIZE
Definition at line 28685 of file inszt_UART.c.
QQQLDRA_PORT
#define QQQLDRA_PORT
Definition at line 80 of file inszt_UART.c.
qqqMaxBranchDepth
#define qqqMaxBranchDepth 20
Definition at line 47 of file inszt_UART.c.
QQQMAXMCDCSIZE
#define QQQMAXMCDCSIZE 2
Definition at line 28656 of file inszt_UART.c.
QQQNOATEXIT
#define QQQNOATEXIT
Definition at line 61 of file inszt_UART.c.
QQQNOSTDIO
#define QQQNOSTDIO
Definition at line 63 of file inszt_UART.c.
QQQnumfil
#define QQQnumfil 23
Definition at line 51 of file inszt_UART.c.
QQQseparate
#define QQQseparate
Definition at line 74 of file inszt_UART.c.
QQQSINGLEFILE
#define QQQSINGLEFILE
Definition at line 72 of file inszt_UART.c.
QQQstructbitmap
#define QQQstructbitmap
Definition at line 48 of file inszt_UART.c.
QQQswitch
#define QQQswitch
Definition at line 42 of file inszt_UART.c.
QQQswitch3
#define QQQswitch3
Definition at line 40 of file inszt_UART.c.
QQQTEMP1
#define QQQTEMP1
Definition at line 28822 of file inszt_UART.c.
QQQUPLOADATEND
#define QQQUPLOADATEND
Definition at line 62 of file inszt_UART.c.
qqzzidfield
#define qqzzidfield 1
Definition at line 28679 of file inszt_UART.c.
RLY_ARMCFOff
#define RLY_ARMCFOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 718 of file inszt_UART.c.
RLY_ARMCFOn
#define RLY_ARMCFOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 717 of file inszt_UART.c.
RLY_ARMCFStateGet
#define RLY_ARMCFStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 719 of file inszt_UART.c.
RLY_ARMCFStateSet
#define RLY_ARMCFStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13 , Value)
Definition at line 720 of file inszt_UART.c.
RLY_ARMCFToggle
#define RLY_ARMCFToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 716 of file inszt_UART.c.
RLY_ARMOff
#define RLY_ARMOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 724 of file inszt_UART.c.
RLY_ARMOn
#define RLY_ARMOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 723 of file inszt_UART.c.
RLY_ARMStateGet
#define RLY_ARMStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 725 of file inszt_UART.c.
RLY_ARMStateSet
#define RLY_ARMStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14 , Value)
Definition at line 726 of file inszt_UART.c.
RLY_ARMToggle
#define RLY_ARMToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 722 of file inszt_UART.c.
RLY_AUXOff
#define RLY_AUXOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 700 of file inszt_UART.c.
RLY_AUXOn
#define RLY_AUXOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 699 of file inszt_UART.c.
RLY_AUXStateGet
#define RLY_AUXStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 701 of file inszt_UART.c.
RLY_AUXStateSet
#define RLY_AUXStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11 , Value)
Definition at line 702 of file inszt_UART.c.
RLY_AUXToggle
#define RLY_AUXToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 698 of file inszt_UART.c.
RLY_CCLOff
#define RLY_CCLOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 706 of file inszt_UART.c.
RLY_CCLOn
#define RLY_CCLOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 705 of file inszt_UART.c.
RLY_CCLStateGet
#define RLY_CCLStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 707 of file inszt_UART.c.
RLY_CCLStateSet
#define RLY_CCLStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1 , Value)
Definition at line 708 of file inszt_UART.c.
RLY_CCLToggle
#define RLY_CCLToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 704 of file inszt_UART.c.
RLY_COMMOff
#define RLY_COMMOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 748 of file inszt_UART.c.
RLY_COMMOn
#define RLY_COMMOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 747 of file inszt_UART.c.
RLY_COMMStateGet
#define RLY_COMMStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 749 of file inszt_UART.c.
RLY_COMMStateSet
#define RLY_COMMStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14 , Value)
Definition at line 750 of file inszt_UART.c.
RLY_COMMToggle
#define RLY_COMMToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 746 of file inszt_UART.c.
RLY_DMP_FIREOff
#define RLY_DMP_FIREOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 694 of file inszt_UART.c.
RLY_DMP_FIREOn
#define RLY_DMP_FIREOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 693 of file inszt_UART.c.
RLY_DMP_FIREStateGet
#define RLY_DMP_FIREStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 695 of file inszt_UART.c.
RLY_DMP_FIREStateSet
#define RLY_DMP_FIREStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10 , Value)
Definition at line 696 of file inszt_UART.c.
RLY_DMP_FIREToggle
#define RLY_DMP_FIREToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 692 of file inszt_UART.c.
RLY_HVPS_OUTOff
#define RLY_HVPS_OUTOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 676 of file inszt_UART.c.
RLY_HVPS_OUTOn
#define RLY_HVPS_OUTOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 675 of file inszt_UART.c.
RLY_HVPS_OUTStateGet
#define RLY_HVPS_OUTStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 677 of file inszt_UART.c.
RLY_HVPS_OUTStateSet
#define RLY_HVPS_OUTStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14 , Value)
Definition at line 678 of file inszt_UART.c.
RLY_HVPS_OUTToggle
#define RLY_HVPS_OUTToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 674 of file inszt_UART.c.
RLY_LOGOff
#define RLY_LOGOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 688 of file inszt_UART.c.
RLY_LOGOn
#define RLY_LOGOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 687 of file inszt_UART.c.
RLY_LOGStateGet
#define RLY_LOGStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 689 of file inszt_UART.c.
RLY_LOGStateSet
#define RLY_LOGStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9 , Value)
Definition at line 690 of file inszt_UART.c.
RLY_LOGToggle
#define RLY_LOGToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 686 of file inszt_UART.c.
RLY_WL_MONOff
#define RLY_WL_MONOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 712 of file inszt_UART.c.
RLY_WL_MONOn
#define RLY_WL_MONOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 711 of file inszt_UART.c.
RLY_WL_MONStateGet
#define RLY_WL_MONStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 713 of file inszt_UART.c.
RLY_WL_MONStateSet
#define RLY_WL_MONStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12 , Value)
Definition at line 714 of file inszt_UART.c.
RLY_WL_MONToggle
#define RLY_WL_MONToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 710 of file inszt_UART.c.
RLY_WL_SPS_POLOff
#define RLY_WL_SPS_POLOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 682 of file inszt_UART.c.
RLY_WL_SPS_POLOn
#define RLY_WL_SPS_POLOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 681 of file inszt_UART.c.
RLY_WL_SPS_POLStateGet
#define RLY_WL_SPS_POLStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 683 of file inszt_UART.c.
RLY_WL_SPS_POLStateSet
#define RLY_WL_SPS_POLStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2 , Value)
Definition at line 684 of file inszt_UART.c.
RLY_WL_SPS_POLToggle
#define RLY_WL_SPS_POLToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 680 of file inszt_UART.c.
SAFE_SWStateGet
#define SAFE_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_1)
Definition at line 776 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_1
#define SYS_CLK_BUS_PERIPHERAL_1 100000000ul
Definition at line 369 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_2
#define SYS_CLK_BUS_PERIPHERAL_2 100000000ul
Definition at line 370 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_3
#define SYS_CLK_BUS_PERIPHERAL_3 100000000ul
Definition at line 371 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_4
#define SYS_CLK_BUS_PERIPHERAL_4 100000000ul
Definition at line 372 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_5
#define SYS_CLK_BUS_PERIPHERAL_5 100000000ul
Definition at line 373 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_7
#define SYS_CLK_BUS_PERIPHERAL_7 200000000ul
Definition at line 374 of file inszt_UART.c.
SYS_CLK_BUS_PERIPHERAL_8
#define SYS_CLK_BUS_PERIPHERAL_8 100000000ul
Definition at line 375 of file inszt_UART.c.
SYS_CLK_CONFIG_PRIMARY_XTAL
#define SYS_CLK_CONFIG_PRIMARY_XTAL 0ul
Definition at line 376 of file inszt_UART.c.
SYS_CLK_CONFIG_SECONDARY_XTAL
#define SYS_CLK_CONFIG_SECONDARY_XTAL 32768ul
Definition at line 377 of file inszt_UART.c.
SYS_CLK_FREQ
#define SYS_CLK_FREQ 200000000ul
Definition at line 368 of file inszt_UART.c.
SYS_DEBUG
#define SYS_DEBUG (level, message) SYS_DEBUG_MESSAGE (level , message)
Definition at line 18138 of file inszt_UART.c.
SYS_DEBUG_BreakPoint
#define SYS_DEBUG_BreakPoint ()
Definition at line 18129 of file inszt_UART.c.
SYS_DEBUG_BUFFER_DMA_READY
#define SYS_DEBUG_BUFFER_DMA_READY
Definition at line 17439 of file inszt_UART.c.
SYS_DEBUG_INDEX_0
#define SYS_DEBUG_INDEX_0 0
Definition at line 17489 of file inszt_UART.c.
SYS_DEBUG_MESSAGE
#define SYS_DEBUG_MESSAGE (level, message)
Definition at line 18009 of file inszt_UART.c.
SYS_DEBUG_PRINT
#define SYS_DEBUG_PRINT (level, fmt, ...)
Definition at line 18104 of file inszt_UART.c.
SYS_DMA_CHANNEL_COUNT
#define SYS_DMA_CHANNEL_COUNT DMA_NUMBER_OF_CHANNELS
Definition at line 13140 of file inszt_UART.c.
SYS_DMA_CHANNEL_HANDLE_INVALID
#define SYS_DMA_CHANNEL_HANDLE_INVALID ((SYS_DMA_CHANNEL_HANDLE) (- 1))
Definition at line 13170 of file inszt_UART.c.
SYS_DMA_TasksISR
#define SYS_DMA_TasksISR (object, activeChannel) SYS_DMA_Tasks (object , activeChannel)
Definition at line 13495 of file inszt_UART.c.
SYS_ERROR
#define SYS_ERROR (level, fmt, ...) SYS_DEBUG_PRINT (level , fmt , ## __VA_ARGS__)
Definition at line 18139 of file inszt_UART.c.
SYS_ERROR_PRINT
#define SYS_ERROR_PRINT (level, fmt, ...) SYS_DEBUG_PRINT (level , fmt , ## __VA_ARGS__)
Definition at line 18140 of file inszt_UART.c.
SYS_INT
#define SYS_INT true
Definition at line 450 of file inszt_UART.c.
SYS_MESSAGE
#define SYS_MESSAGE (message)
Definition at line 17976 of file inszt_UART.c.
SYS_PORT_A_ANSEL
#define SYS_PORT_A_ANSEL 0x3F00
Definition at line 379 of file inszt_UART.c.
SYS_PORT_A_CNEN
#define SYS_PORT_A_CNEN 0x0021
Definition at line 385 of file inszt_UART.c.
SYS_PORT_A_CNPD
#define SYS_PORT_A_CNPD 0x0000
Definition at line 384 of file inszt_UART.c.
SYS_PORT_A_CNPU
#define SYS_PORT_A_CNPU 0x0020
Definition at line 383 of file inszt_UART.c.
SYS_PORT_A_LAT
#define SYS_PORT_A_LAT 0x0010
Definition at line 381 of file inszt_UART.c.
SYS_PORT_A_ODC
#define SYS_PORT_A_ODC 0x0000
Definition at line 382 of file inszt_UART.c.
SYS_PORT_A_TRIS
#define SYS_PORT_A_TRIS 0xFFED
Definition at line 380 of file inszt_UART.c.
SYS_PORT_B_ANSEL
#define SYS_PORT_B_ANSEL 0x10C8
Definition at line 386 of file inszt_UART.c.
SYS_PORT_B_CNEN
#define SYS_PORT_B_CNEN 0x0000
Definition at line 392 of file inszt_UART.c.
SYS_PORT_B_CNPD
#define SYS_PORT_B_CNPD 0x0000
Definition at line 391 of file inszt_UART.c.
SYS_PORT_B_CNPU
#define SYS_PORT_B_CNPU 0x0000
Definition at line 390 of file inszt_UART.c.
SYS_PORT_B_LAT
#define SYS_PORT_B_LAT 0x0000
Definition at line 388 of file inszt_UART.c.
SYS_PORT_B_ODC
#define SYS_PORT_B_ODC 0x0000
Definition at line 389 of file inszt_UART.c.
SYS_PORT_B_TRIS
#define SYS_PORT_B_TRIS 0x91FF
Definition at line 387 of file inszt_UART.c.
SYS_PORT_C_ANSEL
#define SYS_PORT_C_ANSEL 0xCFE1
Definition at line 393 of file inszt_UART.c.
SYS_PORT_C_CNEN
#define SYS_PORT_C_CNEN 0x0000
Definition at line 399 of file inszt_UART.c.
SYS_PORT_C_CNPD
#define SYS_PORT_C_CNPD 0x0000
Definition at line 398 of file inszt_UART.c.
SYS_PORT_C_CNPU
#define SYS_PORT_C_CNPU 0x0000
Definition at line 397 of file inszt_UART.c.
SYS_PORT_C_LAT
#define SYS_PORT_C_LAT 0x0000
Definition at line 395 of file inszt_UART.c.
SYS_PORT_C_ODC
#define SYS_PORT_C_ODC 0x0000
Definition at line 396 of file inszt_UART.c.
SYS_PORT_C_TRIS
#define SYS_PORT_C_TRIS 0xFFFF
Definition at line 394 of file inszt_UART.c.
SYS_PORT_D_ANSEL
#define SYS_PORT_D_ANSEL 0xC100
Definition at line 400 of file inszt_UART.c.
SYS_PORT_D_CNEN
#define SYS_PORT_D_CNEN 0x0000
Definition at line 406 of file inszt_UART.c.
SYS_PORT_D_CNPD
#define SYS_PORT_D_CNPD 0x0000
Definition at line 405 of file inszt_UART.c.
SYS_PORT_D_CNPU
#define SYS_PORT_D_CNPU 0x0000
Definition at line 404 of file inszt_UART.c.
SYS_PORT_D_LAT
#define SYS_PORT_D_LAT 0x0000
Definition at line 402 of file inszt_UART.c.
SYS_PORT_D_ODC
#define SYS_PORT_D_ODC 0x0000
Definition at line 403 of file inszt_UART.c.
SYS_PORT_D_TRIS
#define SYS_PORT_D_TRIS 0xFFFF
Definition at line 401 of file inszt_UART.c.
SYS_PORT_E_ANSEL
#define SYS_PORT_E_ANSEL 0xFC00
Definition at line 407 of file inszt_UART.c.
SYS_PORT_E_CNEN
#define SYS_PORT_E_CNEN 0x0000
Definition at line 413 of file inszt_UART.c.
SYS_PORT_E_CNPD
#define SYS_PORT_E_CNPD 0x0000
Definition at line 412 of file inszt_UART.c.
SYS_PORT_E_CNPU
#define SYS_PORT_E_CNPU 0x0000
Definition at line 411 of file inszt_UART.c.
SYS_PORT_E_LAT
#define SYS_PORT_E_LAT 0x0000
Definition at line 409 of file inszt_UART.c.
SYS_PORT_E_ODC
#define SYS_PORT_E_ODC 0x0000
Definition at line 410 of file inszt_UART.c.
SYS_PORT_E_TRIS
#define SYS_PORT_E_TRIS 0xFDFF
Definition at line 408 of file inszt_UART.c.
SYS_PORT_F_ANSEL
#define SYS_PORT_F_ANSEL 0xCEC0
Definition at line 414 of file inszt_UART.c.
SYS_PORT_F_CNEN
#define SYS_PORT_F_CNEN 0x0000
Definition at line 420 of file inszt_UART.c.
SYS_PORT_F_CNPD
#define SYS_PORT_F_CNPD 0x0000
Definition at line 419 of file inszt_UART.c.
SYS_PORT_F_CNPU
#define SYS_PORT_F_CNPU 0x0000
Definition at line 418 of file inszt_UART.c.
SYS_PORT_F_LAT
#define SYS_PORT_F_LAT 0x0000
Definition at line 416 of file inszt_UART.c.
SYS_PORT_F_ODC
#define SYS_PORT_F_ODC 0x0000
Definition at line 417 of file inszt_UART.c.
SYS_PORT_F_TRIS
#define SYS_PORT_F_TRIS 0xEFFF
Definition at line 415 of file inszt_UART.c.
SYS_PORT_G_ANSEL
#define SYS_PORT_G_ANSEL 0x8CBC
Definition at line 421 of file inszt_UART.c.
SYS_PORT_G_CNEN
#define SYS_PORT_G_CNEN 0x0000
Definition at line 427 of file inszt_UART.c.
SYS_PORT_G_CNPD
#define SYS_PORT_G_CNPD 0x0000
Definition at line 426 of file inszt_UART.c.
SYS_PORT_G_CNPU
#define SYS_PORT_G_CNPU 0x0000
Definition at line 425 of file inszt_UART.c.
SYS_PORT_G_LAT
#define SYS_PORT_G_LAT 0x0000
Definition at line 423 of file inszt_UART.c.
SYS_PORT_G_ODC
#define SYS_PORT_G_ODC 0x0000
Definition at line 424 of file inszt_UART.c.
SYS_PORT_G_TRIS
#define SYS_PORT_G_TRIS 0xDFFF
Definition at line 422 of file inszt_UART.c.
SYS_PORT_H_ANSEL
#define SYS_PORT_H_ANSEL 0x0070
Definition at line 428 of file inszt_UART.c.
SYS_PORT_H_CNEN
#define SYS_PORT_H_CNEN 0x0000
Definition at line 434 of file inszt_UART.c.
SYS_PORT_H_CNPD
#define SYS_PORT_H_CNPD 0x0000
Definition at line 433 of file inszt_UART.c.
SYS_PORT_H_CNPU
#define SYS_PORT_H_CNPU 0x0000
Definition at line 432 of file inszt_UART.c.
SYS_PORT_H_LAT
#define SYS_PORT_H_LAT 0x0000
Definition at line 430 of file inszt_UART.c.
SYS_PORT_H_ODC
#define SYS_PORT_H_ODC 0x0000
Definition at line 431 of file inszt_UART.c.
SYS_PORT_H_TRIS
#define SYS_PORT_H_TRIS 0xB3FB
Definition at line 429 of file inszt_UART.c.
SYS_PORT_J_ANSEL
#define SYS_PORT_J_ANSEL 0x0000
Definition at line 435 of file inszt_UART.c.
SYS_PORT_J_CNEN
#define SYS_PORT_J_CNEN 0x0800
Definition at line 441 of file inszt_UART.c.
SYS_PORT_J_CNPD
#define SYS_PORT_J_CNPD 0x0000
Definition at line 440 of file inszt_UART.c.
SYS_PORT_J_CNPU
#define SYS_PORT_J_CNPU 0x0000
Definition at line 439 of file inszt_UART.c.
SYS_PORT_J_LAT
#define SYS_PORT_J_LAT 0x0080
Definition at line 437 of file inszt_UART.c.
SYS_PORT_J_ODC
#define SYS_PORT_J_ODC 0x0000
Definition at line 438 of file inszt_UART.c.
SYS_PORT_J_TRIS
#define SYS_PORT_J_TRIS 0x8B7F
Definition at line 436 of file inszt_UART.c.
SYS_PORT_K_ANSEL
#define SYS_PORT_K_ANSEL 0xFF00
Definition at line 442 of file inszt_UART.c.
SYS_PORT_K_CNEN
#define SYS_PORT_K_CNEN 0x0000
Definition at line 448 of file inszt_UART.c.
SYS_PORT_K_CNPD
#define SYS_PORT_K_CNPD 0x0000
Definition at line 447 of file inszt_UART.c.
SYS_PORT_K_CNPU
#define SYS_PORT_K_CNPU 0x0000
Definition at line 446 of file inszt_UART.c.
SYS_PORT_K_LAT
#define SYS_PORT_K_LAT 0x0000
Definition at line 444 of file inszt_UART.c.
SYS_PORT_K_ODC
#define SYS_PORT_K_ODC 0x0000
Definition at line 445 of file inszt_UART.c.
SYS_PORT_K_TRIS
#define SYS_PORT_K_TRIS 0xFFFF
Definition at line 443 of file inszt_UART.c.
SYS_PRINT
#define SYS_PRINT (fmt, ...)
Definition at line 18056 of file inszt_UART.c.
SYS_TMR_CLIENT_TOLERANCE
#define SYS_TMR_CLIENT_TOLERANCE 10
Definition at line 458 of file inszt_UART.c.
SYS_TMR_DRIVER_INDEX
#define SYS_TMR_DRIVER_INDEX DRV_TMR_INDEX_0
Definition at line 453 of file inszt_UART.c.
SYS_TMR_FREQUENCY
#define SYS_TMR_FREQUENCY 1000
Definition at line 455 of file inszt_UART.c.
SYS_TMR_FREQUENCY_TOLERANCE
#define SYS_TMR_FREQUENCY_TOLERANCE 10
Definition at line 456 of file inszt_UART.c.
SYS_TMR_INTERRUPT_NOTIFICATION
#define SYS_TMR_INTERRUPT_NOTIFICATION false
Definition at line 459 of file inszt_UART.c.
SYS_TMR_MAX_CLIENT_OBJECTS
#define SYS_TMR_MAX_CLIENT_OBJECTS 5
Definition at line 454 of file inszt_UART.c.
SYS_TMR_POWER_STATE
#define SYS_TMR_POWER_STATE SYS_MODULE_POWER_RUN_FULL
Definition at line 452 of file inszt_UART.c.
SYS_TMR_UNIT_RESOLUTION
#define SYS_TMR_UNIT_RESOLUTION 10000
Definition at line 457 of file inszt_UART.c.
SYS_VERSION
#define SYS_VERSION 20600
Definition at line 364 of file inszt_UART.c.
SYS_VERSION_STR
#define SYS_VERSION_STR "2.06"
Definition at line 363 of file inszt_UART.c.
TPAN1Off
#define TPAN1Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 730 of file inszt_UART.c.
TPAN1On
#define TPAN1On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 729 of file inszt_UART.c.
TPAN1StateGet
#define TPAN1StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 731 of file inszt_UART.c.
TPAN1StateSet
#define TPAN1StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10 , Value)
Definition at line 732 of file inszt_UART.c.
TPAN1Toggle
#define TPAN1Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 728 of file inszt_UART.c.
TPAN2Off
#define TPAN2Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 736 of file inszt_UART.c.
TPAN2On
#define TPAN2On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 735 of file inszt_UART.c.
TPAN2StateGet
#define TPAN2StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 737 of file inszt_UART.c.
TPAN2StateSet
#define TPAN2StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11 , Value)
Definition at line 738 of file inszt_UART.c.
TPAN2Toggle
#define TPAN2Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 734 of file inszt_UART.c.
UART_71zqqzqz1
#define UART_71zqqzqz1 zqqzqz1
Definition at line 79 of file inszt_UART.c.
Referenced by qqqupload(), UART_71zqendz(), and UART_71zqzqzq().
UART_71zzopen
#define UART_71zzopen zzopen
Definition at line 77 of file inszt_UART.c.
Referenced by UART_71zqendz(), UART_71zqqzqz(), UART_71zqqzqz1(), and UART_71zqzqzq().
UART_H
#define UART_H
Definition at line 210 of file inszt_UART.c.
USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
#define USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
Definition at line 636 of file inszt_UART.c.
USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED
#define USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED 2
Definition at line 642 of file inszt_UART.c.
USB_DEVICE_EP0_BUFFER_SIZE
#define USB_DEVICE_EP0_BUFFER_SIZE 64
Definition at line 640 of file inszt_UART.c.
USB_DEVICE_INSTANCES_NUMBER
#define USB_DEVICE_INSTANCES_NUMBER 1
Definition at line 638 of file inszt_UART.c.
USE_8BIT_PMP
#define USE_8BIT_PMP
Definition at line 466 of file inszt_UART.c.
WL_CPS_SWOff
#define WL_CPS_SWOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 760 of file inszt_UART.c.
WL_CPS_SWOn
#define WL_CPS_SWOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 759 of file inszt_UART.c.
WL_CPS_SWStateGet
#define WL_CPS_SWStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 761 of file inszt_UART.c.
WL_CPS_SWStateSet
#define WL_CPS_SWStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13 , Value)
Definition at line 762 of file inszt_UART.c.
WL_CPS_SWToggle
#define WL_CPS_SWToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 758 of file inszt_UART.c.
WL_SPS_NEG_DETStateGet
#define WL_SPS_NEG_DETStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_13)
Definition at line 796 of file inszt_UART.c.
WL_SPS_POS_DETStateGet
#define WL_SPS_POS_DETStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_12)
Definition at line 794 of file inszt_UART.c.
Typedef Documentation
DRV_HANDLE
typedef uintptr_t DRV_HANDLE
Definition at line 1017 of file inszt_UART.c.
DRV_SPI_BUFFER_EVENT_HANDLER
typedef void(* DRV_SPI_BUFFER_EVENT_HANDLER) (DRV_SPI_BUFFER_EVENT event, DRV_SPI_BUFFER_HANDLE bufferHandle, void *context)
Definition at line 26424 of file inszt_UART.c.
DRV_SPI_BUFFER_HANDLE
typedef uintptr_t DRV_SPI_BUFFER_HANDLE
Definition at line 26156 of file inszt_UART.c.
DRV_SPI_CLIENT_DATA
typedef struct _DRV_SPI_CLIENT_DATA DRV_SPI_CLIENT_DATA
DRV_SPI_INIT
typedef struct _DRV_SPI_INIT DRV_SPI_INIT
DRV_TMR_CALLBACK
typedef void(* DRV_TMR_CALLBACK) (uintptr_t context, uint32_t alarmCount)
Definition at line 1837 of file inszt_UART.c.
DRV_USART_BUFFER_EVENT_HANDLER
typedef void(* DRV_USART_BUFFER_EVENT_HANDLER) (DRV_USART_BUFFER_EVENT event, DRV_USART_BUFFER_HANDLE bufferHandle, uintptr_t context)
Definition at line 15105 of file inszt_UART.c.
DRV_USART_BUFFER_HANDLE
typedef uintptr_t DRV_USART_BUFFER_HANDLE
Definition at line 14944 of file inszt_UART.c.
DRV_USART_BYTE_EVENT_HANDLER
typedef void(* DRV_USART_BYTE_EVENT_HANDLER) (const SYS_MODULE_INDEX index)
Definition at line 15137 of file inszt_UART.c.
ldra_void_function
typedef void(* ldra_void_function) ()
Definition at line 115 of file inszt_UART.c.
PORTS_DATA_MASK
typedef uint16_t PORTS_DATA_MASK
Definition at line 18428 of file inszt_UART.c.
PORTS_DATA_TYPE
typedef uint32_t PORTS_DATA_TYPE
Definition at line 18441 of file inszt_UART.c.
SYS_DMA_CHANNEL_HANDLE
typedef uintptr_t SYS_DMA_CHANNEL_HANDLE
Definition at line 13158 of file inszt_UART.c.
SYS_DMA_CHANNEL_TRANSFER_EVENT_HANDLER
typedef void(* SYS_DMA_CHANNEL_TRANSFER_EVENT_HANDLER) (SYS_DMA_TRANSFER_EVENT event, SYS_DMA_CHANNEL_HANDLE handle, uintptr_t contextHandle)
Definition at line 13538 of file inszt_UART.c.
uchar8_t
typedef unsigned char uchar8_t
Definition at line 28148 of file inszt_UART.c.
Enumeration Type Documentation
COMM_STATES
enum COMM_STATES
Enumerator
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
COMM_STATE_INIT
Application's state machine's initial state.
COMM_STATE_VALIDATE
Ensure the command received is valid.
COMM_STATE_WAIT
Process the data from the communication.
COMM_STATE_IDLE
Only comes here after the communication has been completed.
Definition at line 28004 of file inszt_UART.c.
COMMAND_STATES
enum COMMAND_STATES
Enumerator
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
COMMAND_STATE_INIT
COMMAND_TASKS state machine's initial state.
COMMAND_STATE_WAIT
Machine waits here for next command to process.
COMMAND_STATE_CRC_CHECK
Check that the CRC calculation matches transmitted value.
COMMAND_STATE_EXECUTE_CMD
Execute the transmitted comaand and prepare the return message.
Definition at line 28156 of file inszt_UART.c.
DRV_ADC_MODULE_ID
enum DRV_ADC_MODULE_ID
Enumerator
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
Definition at line 1418 of file inszt_UART.c.
DRV_CLIENT_STATUS
enum DRV_CLIENT_STATUS
Enumerator
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
DRV_CLIENT_STATUS_ERROR_EXTENDED
DRV_CLIENT_STATUS_ERROR
DRV_CLIENT_STATUS_CLOSED
DRV_CLIENT_STATUS_BUSY
DRV_CLIENT_STATUS_READY
DRV_CLIENT_STATUS_READY_EXTENDED
Definition at line 928 of file inszt_UART.c.
DRV_IO_BUFFER_TYPES
enum DRV_IO_BUFFER_TYPES
Enumerator
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
DRV_IO_BUFFER_TYPE_NONE
DRV_IO_BUFFER_TYPE_READ
DRV_IO_BUFFER_TYPE_WRITE
DRV_IO_BUFFER_TYPE_RW
Definition at line 985 of file inszt_UART.c.
DRV_IO_INTENT
enum DRV_IO_INTENT
Enumerator
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
DRV_IO_INTENT_READ
DRV_IO_INTENT_WRITE
DRV_IO_INTENT_READWRITE
DRV_IO_INTENT_BLOCKING
DRV_IO_INTENT_NONBLOCKING
DRV_IO_INTENT_EXCLUSIVE
DRV_IO_INTENT_SHARED
Definition at line 884 of file inszt_UART.c.
DRV_SPI_BUFFER_EVENT
enum DRV_SPI_BUFFER_EVENT
Enumerator
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
DRV_SPI_BUFFER_EVENT_PENDING
DRV_SPI_BUFFER_EVENT_PROCESSING
DRV_SPI_BUFFER_EVENT_COMPLETE
DRV_SPI_BUFFER_EVENT_ERROR
Definition at line 26308 of file inszt_UART.c.
DRV_SPI_BUFFER_TYPE
enum DRV_SPI_BUFFER_TYPE
Enumerator
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
DRV_SPI_BUFFER_TYPE_STANDARD
DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 26253 of file inszt_UART.c.
DRV_SPI_CLOCK_MODE
enum DRV_SPI_CLOCK_MODE
Enumerator
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_RISE
DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_FALL
DRV_SPI_CLOCK_MODE_IDLE_HIGH_EDGE_RISE
Definition at line 26208 of file inszt_UART.c.
DRV_SPI_MODE
enum DRV_SPI_MODE
Enumerator
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
DRV_SPI_MODE_MASTER
DRV_SPI_MODE_SLAVE
Definition at line 26330 of file inszt_UART.c.
DRV_SPI_PROTOCOL_TYPE
enum DRV_SPI_PROTOCOL_TYPE
Enumerator
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
DRV_SPI_PROTOCOL_TYPE_STANDARD
DRV_SPI_PROTOCOL_TYPE_FRAMED
DRV_SPI_PROTOCOL_TYPE_AUDIO
Definition at line 26276 of file inszt_UART.c.
DRV_SPI_TASK_MODE
enum DRV_SPI_TASK_MODE
Enumerator
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
DRV_SPI_TASK_MODE_POLLED
DRV_SPI_TASK_MODE_ISR
Definition at line 26353 of file inszt_UART.c.
DRV_TMR_CLIENT_STATUS
enum DRV_TMR_CLIENT_STATUS
Enumerator
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
DRV_TMR_CLIENT_STATUS_INVALID
DRV_TMR_CLIENT_STATUS_BUSY
DRV_TMR_CLIENT_STATUS_READY
DRV_TMR_CLIENT_STATUS_RUNNING
Definition at line 1710 of file inszt_UART.c.
DRV_TMR_CLK_SOURCES
enum DRV_TMR_CLK_SOURCES
Enumerator
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_INTERNAL
DRV_TMR_CLKSOURCE_EXTERNAL_SYNCHRONOUS
DRV_TMR_CLKSOURCE_EXTERNAL_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_SECONDARY_OSCILLATOR_ASYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_SYNCHRONOUS
DRV_TMR_CLKSOURCE_LPRC_OSCILLATOR_ASYNCHRONOUS
Definition at line 1603 of file inszt_UART.c.
DRV_TMR_OPERATION_MODE
enum DRV_TMR_OPERATION_MODE
Enumerator
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
DRV_TMR_OPERATION_MODE_NONE
DRV_TMR_OPERATION_MODE_16_BIT
DRV_TMR_OPERATION_MODE_32_BIT
Definition at line 1757 of file inszt_UART.c.
DRV_USART_BAUD_SET_RESULT
enum DRV_USART_BAUD_SET_RESULT
Enumerator
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
DRV_USART_BAUD_SET_ERROR
DRV_USART_BAUD_SET_SUCCESS
Definition at line 15175 of file inszt_UART.c.
DRV_USART_BUFFER_EVENT
enum DRV_USART_BUFFER_EVENT
Enumerator
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
DRV_USART_BUFFER_EVENT_COMPLETE
DRV_USART_BUFFER_EVENT_ERROR
DRV_USART_BUFFER_EVENT_ABORT
Definition at line 15005 of file inszt_UART.c.
DRV_USART_BUFFER_RESULT
enum DRV_USART_BUFFER_RESULT
Enumerator
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
DRV_USART_BUFFER_RESULT_HANDLE_INVALID
DRV_USART_BUFFER_RESULT_HANDLE_EXPIRED
DRV_USART_BUFFER_RESULT_REMOVED_SUCCESFULLY
DRV_USART_BUFFER_RESULT_REMOVAL_FAILED
Definition at line 15027 of file inszt_UART.c.
DRV_USART_CLIENT_STATUS
enum DRV_USART_CLIENT_STATUS
Enumerator
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
DRV_USART_CLIENT_STATUS_ERROR
DRV_USART_CLIENT_STATUS_CLOSED
DRV_USART_CLIENT_STATUS_BUSY
DRV_USART_CLIENT_STATUS_READY
Definition at line 15373 of file inszt_UART.c.
DRV_USART_ERROR
enum DRV_USART_ERROR
Enumerator
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
DRV_USART_ERROR_NONE
DRV_USART_ERROR_PARITY
DRV_USART_ERROR_FRAMING
DRV_USART_ERROR_RECEIVE_OVERRUN
DRV_USART_ERROR_ADDRESS
Definition at line 15335 of file inszt_UART.c.
DRV_USART_HANDSHAKE
enum DRV_USART_HANDSHAKE
Enumerator
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
DRV_USART_HANDSHAKE_FLOWCONTROL
DRV_USART_HANDSHAKE_SIMPLEX
DRV_USART_HANDSHAKE_NONE
Definition at line 15150 of file inszt_UART.c.
DRV_USART_INIT_FLAGS
enum DRV_USART_INIT_FLAGS
Enumerator
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
DRV_USART_INIT_FLAG_NONE
DRV_USART_INIT_FLAG_WAKE_ON_START
DRV_USART_INIT_FLAG_AUTO_BAUD
DRV_USART_INIT_FLAG_STOP_IN_IDLE
Definition at line 15273 of file inszt_UART.c.
DRV_USART_LINE_CONTROL
enum DRV_USART_LINE_CONTROL
Enumerator
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
DRV_USART_LINE_CONTROL_8NONE1
DRV_USART_LINE_CONTROL_9NONE1
DRV_USART_LINE_CONTROL_8EVEN1
DRV_USART_LINE_CONTROL_8EVEN2
DRV_USART_LINE_CONTROL_8ODD1
DRV_USART_LINE_CONTROL_8ODD2
DRV_USART_LINE_CONTROL_8NONE2
DRV_USART_LINE_CONTROL_9NONE2
Definition at line 15224 of file inszt_UART.c.
DRV_USART_LINE_CONTROL_SET_RESULT
enum DRV_USART_LINE_CONTROL_SET_RESULT
Enumerator
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
DRV_USART_LINE_CONTROL_SET_ERROR
DRV_USART_LINE_CONTROL_SET_SUCCESS
Definition at line 15196 of file inszt_UART.c.
DRV_USART_OPERATION_MODE
enum DRV_USART_OPERATION_MODE
Enumerator
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
DRV_USART_OPERATION_MODE_IRDA
DRV_USART_OPERATION_MODE_NORMAL
DRV_USART_OPERATION_MODE_ADDRESSED
DRV_USART_OPERATION_MODE_LOOPBACK
Definition at line 14968 of file inszt_UART.c.
DRV_USART_TRANSFER_STATUS
enum DRV_USART_TRANSFER_STATUS
Enumerator
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
DRV_USART_TRANSFER_STATUS_RECEIVER_DATA_PRESENT
DRV_USART_TRANSFER_STATUS_RECEIVER_EMPTY
DRV_USART_TRANSFER_STATUS_TRANSMIT_FULL
DRV_USART_TRANSFER_STATUS_TRANSMIT_EMPTY
Definition at line 15398 of file inszt_UART.c.
PORTS_PIN_INTERRUPT_TYPE
enum PORTS_PIN_INTERRUPT_TYPE
Enumerator
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
Definition at line 21812 of file inszt_UART.c.
SYS_DMA_CHANNEL_CHAIN_PRIO
enum SYS_DMA_CHANNEL_CHAIN_PRIO
Enumerator
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
SYS_DMA_CHANNEL_CHAIN_PRIO_HIGH
SYS_DMA_CHANNEL_CHAIN_PRIO_LOW
Definition at line 13204 of file inszt_UART.c.
SYS_DMA_CHANNEL_CRC_MODE
enum SYS_DMA_CHANNEL_CRC_MODE
Enumerator
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
SYS_DMA_CHANNEL_CRC_MODE_BACKGROUND
SYS_DMA_CHANNEL_CRC_MODE_APPEND
Definition at line 13244 of file inszt_UART.c.
SYS_DMA_CHANNEL_IGNORE_MATCH
enum SYS_DMA_CHANNEL_IGNORE_MATCH
Enumerator
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_DISABLE
SYS_DMA_CHANNEL_IGNORE_MATCH_ENABLE
Definition at line 13225 of file inszt_UART.c.
SYS_DMA_CHANNEL_OP_MODE
enum SYS_DMA_CHANNEL_OP_MODE
Enumerator
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
SYS_DMA_CHANNEL_OP_MODE_BASIC
SYS_DMA_CHANNEL_OP_MODE_MATCH_ABORT
SYS_DMA_CHANNEL_OP_MODE_CHAIN_HIGH
SYS_DMA_CHANNEL_OP_MODE_CHAIN_LOW
SYS_DMA_CHANNEL_OP_MODE_AUTO
SYS_DMA_CHANNEL_OP_MODE_CRC
Definition at line 13290 of file inszt_UART.c.
SYS_DMA_CRC_WRITE_ORDER
enum SYS_DMA_CRC_WRITE_ORDER
Enumerator
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
SYS_DMA_CRC_WRITE_ORDER_MAINTAIN
SYS_DMA_CRC_WRITE_ORDER_CHANGE
Definition at line 13267 of file inszt_UART.c.
SYS_DMA_DATA_WIDTH
enum SYS_DMA_DATA_WIDTH
Enumerator
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
SYS_DMA_DATA_WIDTH_NONE
Definition at line 13431 of file inszt_UART.c.
SYS_DMA_ERROR
enum SYS_DMA_ERROR
Enumerator
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
SYS_DMA_ERROR_NONE
SYS_DMA_ERROR_ADDRESS_ERROR
Definition at line 13400 of file inszt_UART.c.
SYS_DMA_SIDL
enum SYS_DMA_SIDL
Enumerator
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
SYS_DMA_SIDL_DISABLE
SYS_DMA_SIDL_ENABLE
Definition at line 13184 of file inszt_UART.c.
SYS_DMA_TRANSFER_EVENT
enum SYS_DMA_TRANSFER_EVENT
Enumerator
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
SYS_DMA_TRANSFER_EVENT_COMPLETE
SYS_DMA_TRANSFER_EVENT_ERROR
SYS_DMA_TRANSFER_EVENT_ABORT
SYS_DMA_TRANSFER_EVENT_NONE
Definition at line 13378 of file inszt_UART.c.
SYS_ERROR_LEVEL
enum SYS_ERROR_LEVEL
Enumerator
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
SYS_ERROR_FATAL
SYS_ERROR_ERROR
SYS_ERROR_WARNING
SYS_ERROR_INFO
SYS_ERROR_DEBUG
Definition at line 17457 of file inszt_UART.c.
SYS_PORTS_PIN_DIRECTION
enum SYS_PORTS_PIN_DIRECTION
Enumerator
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
Definition at line 21797 of file inszt_UART.c.
SYS_PORTS_PULLUP_PULLDOWN_STATUS
enum SYS_PORTS_PULLUP_PULLDOWN_STATUS
Enumerator
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
Definition at line 21773 of file inszt_UART.c.
UART_STATES
enum UART_STATES
Enumerator
UART_STATE_INIT
UART's state machine's initial state.
UART_STATE_OPEN
Open the UART channel.
UART_STATE_READ
Read the UART data and transfer to a RxFifo.
UART_STATE_WAIT
Wait for the command to be processed.
UART_STATE_WRITE
Transfer the response data from the TxFifo to the UART.
UART_STATE_INIT
UART's state machine's initial state.
UART_STATE_OPEN
Open the UART channel.
UART_STATE_READ
Read the UART data and transfer to a RxFifo.
UART_STATE_WAIT
Wait for the command to be processed.
UART_STATE_WRITE
Transfer the response data from the TxFifo to the UART.
UART_STATE_INIT
UART's state machine's initial state.
UART_STATE_OPEN
Open the UART channel.
UART_STATE_READ
Read the UART data and transfer to a RxFifo.
UART_STATE_WAIT
Wait for the command to be processed.
UART_STATE_WRITE
Transfer the response data from the TxFifo to the UART.
UART_STATE_INIT
UART's state machine's initial state.
UART_STATE_OPEN
Open the UART channel.
UART_STATE_READ
Read the UART data and transfer to a RxFifo.
UART_STATE_WAIT
Wait for the command to be processed.
UART_STATE_WRITE
Transfer the response data from the TxFifo to the UART.
Definition at line 27617 of file inszt_UART.c.
Function Documentation
APP_Initialize()
void APP_Initialize (void)
Function: void APP_Initialize(void) Summary: Autonomous tool application initialization routine. Description: This function initializes the application. It places the application in its initial state and prepares it to run so that its APP_Tasks function can be called. Precondition: All other system initialization routines should be called before calling this routine (in "SYS_Initialize"). Parameters: None. Returns: None. Example: APP_Initialize() Remarks: This routine must be called from the main function.
Definition at line 93 of file app.c.
APP_Tasks()
void APP_Tasks (void)
Function: void APP_Tasks(void) Summary: Application tasks function Description: This function is the main application's tasks function. It contains the various tasks that are maintained during the operation of the shooting panel. Precondition: The system ("SYS_Initialize") and application ("APP_Initialize") initialization should be called before calling this. Parameters: None. Returns: None. Example: APP_Tasks() Remarks: This routine must be called from the main() routine.
Definition at line 130 of file app.c.
COMM_Tasks()
void COMM_Tasks (void)
Function: void COMM_Tasks(void) Summary: COMM tasks function Description: This routine is the COMM tasks function. It defines the COMM's state machine and core logic. This task controls the communications between a host UART or host USB. Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this. Parameters: None. Returns: None. Example: COMM_Tasks()
Remarks: This routine must be called from COMM_Tasks() routine.
Definition at line 88 of file commmodule.c.
COMMAND_Tasks()
void COMMAND_Tasks (void)
Function: void COMMAND_Tasks(void) Summary: This function executes the commands from the host. Description: This function executes the commands from the host. It does this by first ensuring the CRC of the received command is correct. If the CRC check matches, it goes on to execute the command. The commands are divided up into three types; Protocol A, Protocol B and System. Protocol A commands control the function of the Panel Interface Board. Protocol B commands are for a PerfSwitch or other down hole tool. System commands control the panel operation while it is being used for shooting. An example would be showing the depth status.
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: void COMMAND_Tasks()
Function: void COMMAND_Tasks(void)
Summary: This function executes the commands from the host.
Description: This function executes the commands from the host. It does this by first ensuring the CRC of the received command is correct. If the CRC check matches, it goes on to execute the command. The commands are divided up into three types; Protocol A, Protocol B and System. Protocol A commands control the function of the Panel Interface Board. Protocol B commands are for a PerfSwitch or other down hole tool. System commands control the panel operation while it is being used for shooting. An example would be showing the depth status.
Precondition: None.
Parameters: None.
Returns None.
Remarks: None.
Example: void COMMAND_Tasks()
Definition at line 225 of file commands.c.
DRV_ADC0_Close()
void DRV_ADC0_Close (void) inline
DRV_ADC0_Open()
void DRV_ADC0_Open (void) inline
DRV_ADC1_Close()
void DRV_ADC1_Close (void) inline
DRV_ADC1_Open()
void DRV_ADC1_Open (void) inline
DRV_ADC_DeInitialize()
void DRV_ADC_DeInitialize (void) inline
DRV_ADC_Initialize()
void DRV_ADC_Initialize (void)
DRV_ADC_SamplesAvailable()
bool DRV_ADC_SamplesAvailable (uint8_t bufIndex)
DRV_ADC_SamplesRead()
uint32_t DRV_ADC_SamplesRead (uint8_t bufIndex)
DRV_ADC_Start()
void DRV_ADC_Start (void) inline
DRV_ADC_Stop()
void DRV_ADC_Stop (void) inline
DRV_IC0_BufferIsEmpty()
bool DRV_IC0_BufferIsEmpty (void)
DRV_IC0_Capture16BitDataRead()
uint16_t DRV_IC0_Capture16BitDataRead (void)
DRV_IC0_Capture32BitDataRead()
uint32_t DRV_IC0_Capture32BitDataRead (void)
DRV_IC0_Initialize()
void DRV_IC0_Initialize (void)
DRV_IC0_Start()
void DRV_IC0_Start (void)
DRV_IC0_Stop()
void DRV_IC0_Stop (void)
DRV_IC_BufferIsEmpty()
bool DRV_IC_BufferIsEmpty (DRV_HANDLE handle)
DRV_IC_Capture16BitDataRead()
uint16_t DRV_IC_Capture16BitDataRead (DRV_HANDLE handle)
DRV_IC_Capture32BitDataRead()
uint32_t DRV_IC_Capture32BitDataRead (DRV_HANDLE handle)
DRV_IC_Close()
void DRV_IC_Close (DRV_HANDLE handle)
DRV_IC_Initialize()
SYS_MODULE_OBJ DRV_IC_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
DRV_IC_Open()
DRV_HANDLE DRV_IC_Open (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT intent)
DRV_IC_Start()
DRV_HANDLE DRV_IC_Start (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT intent)
DRV_IC_Stop()
void DRV_IC_Stop (DRV_HANDLE handle)
DRV_PMP0_Initialize()
void DRV_PMP0_Initialize (void)
DRV_PMP0_ModeConfig()
void DRV_PMP0_ModeConfig (void)
DRV_PMP0_Read()
uint8_t DRV_PMP0_Read (void)
DRV_PMP0_TimingSet()
void DRV_PMP0_TimingSet (PMP_DATA_WAIT_STATES dataWait, PMP_STROBE_WAIT_STATES strobeWait, PMP_DATA_HOLD_STATES dataHold)
DRV_PMP0_Write()
void DRV_PMP0_Write (uint8_t data)
DRV_SPI_BufferAddRead()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddRead (DRV_HANDLE handle, void * rxBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context)
DRV_SPI_BufferAddRead2()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddRead2 (DRV_HANDLE handle, void * rxBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context, DRV_SPI_BUFFER_HANDLE * jobHandle)
DRV_SPI_BufferAddWrite()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWrite (DRV_HANDLE handle, void * txBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context)
DRV_SPI_BufferAddWrite2()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWrite2 (DRV_HANDLE handle, void * txBuffer, size_t size, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context, DRV_SPI_BUFFER_HANDLE * jobHandle)
DRV_SPI_BufferAddWriteRead()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWriteRead (DRV_HANDLE handle, void * txBuffer, size_t txSize, void * rxBuffer, size_t rxSize, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context)
DRV_SPI_BufferAddWriteRead2()
DRV_SPI_BUFFER_HANDLE DRV_SPI_BufferAddWriteRead2 (DRV_HANDLE handle, void * txBuffer, size_t txSize, void * rxBuffer, size_t rxSize, DRV_SPI_BUFFER_EVENT_HANDLER completeCB, void * context, DRV_SPI_BUFFER_HANDLE * jobHandle)
DRV_SPI_BufferStatus()
DRV_SPI_BUFFER_EVENT DRV_SPI_BufferStatus (DRV_SPI_BUFFER_HANDLE bufferHandle)
DRV_SPI_ClientConfigure()
int32_t DRV_SPI_ClientConfigure (DRV_HANDLE handle, const DRV_SPI_CLIENT_DATA * cfgData)
DRV_SPI_Close()
void DRV_SPI_Close (DRV_HANDLE handle)
DRV_SPI_Deinitialize()
void DRV_SPI_Deinitialize (SYS_MODULE_OBJ object)
DRV_SPI_Initialize()
SYS_MODULE_OBJ DRV_SPI_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
DRV_SPI_Open()
DRV_HANDLE DRV_SPI_Open (const SYS_MODULE_INDEX drvIndex, const DRV_IO_INTENT ioIntent)
DRV_SPI_Status()
SYS_STATUS DRV_SPI_Status (SYS_MODULE_OBJ object)
DRV_SPI_Tasks()
void DRV_SPI_Tasks (SYS_MODULE_OBJ object)
DRV_SPIn_ReceiverBufferIsFull()
bool DRV_SPIn_ReceiverBufferIsFull (void)
DRV_SPIn_TransmitterBufferIsFull()
bool DRV_SPIn_TransmitterBufferIsFull (void)
DRV_TMR0_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR0_ClientStatus (void)
DRV_TMR0_ClockSet()
bool DRV_TMR0_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR0_Close()
static void DRV_TMR0_Close (void) inline static
Definition at line 3654 of file inszt_UART.c.
DRV_TMR0_CounterClear()
void DRV_TMR0_CounterClear (void)
DRV_TMR0_CounterFrequencyGet()
uint32_t DRV_TMR0_CounterFrequencyGet (void)
DRV_TMR0_CounterValueGet()
uint32_t DRV_TMR0_CounterValueGet (void)
DRV_TMR0_CounterValueSet()
void DRV_TMR0_CounterValueSet (uint32_t value)
DRV_TMR0_DeInitialize()
static void DRV_TMR0_DeInitialize (void) inline static
Definition at line 3613 of file inszt_UART.c.
DRV_TMR0_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR0_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR0_Initialize()
void DRV_TMR0_Initialize (void)
DRV_TMR0_Open()
static void DRV_TMR0_Open (void) inline static
Definition at line 3633 of file inszt_UART.c.
DRV_TMR0_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR0_OperationModeGet (void) inline static
Definition at line 3644 of file inszt_UART.c.
DRV_TMR0_PeriodValueGet()
uint32_t DRV_TMR0_PeriodValueGet (void)
DRV_TMR0_PeriodValueSet()
void DRV_TMR0_PeriodValueSet (uint32_t value)
DRV_TMR0_PrescalerGet()
TMR_PRESCALE DRV_TMR0_PrescalerGet (void)
DRV_TMR0_Start()
bool DRV_TMR0_Start (void)
DRV_TMR0_Status()
static SYS_STATUS DRV_TMR0_Status (void) inline static
Definition at line 3622 of file inszt_UART.c.
DRV_TMR0_Stop()
void DRV_TMR0_Stop (void)
Referenced by DRV_TMR0_Close(), and DRV_TMR0_DeInitialize().
DRV_TMR0_StopInIdleDisable()
void DRV_TMR0_StopInIdleDisable (void)
DRV_TMR0_StopInIdleEnable()
void DRV_TMR0_StopInIdleEnable (void)
DRV_TMR0_Tasks()
static void DRV_TMR0_Tasks (void) inline static
Definition at line 3694 of file inszt_UART.c.
DRV_TMR1_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR1_ClientStatus (void)
DRV_TMR1_ClockSet()
bool DRV_TMR1_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR1_Close()
static void DRV_TMR1_Close (void) inline static
Definition at line 3764 of file inszt_UART.c.
DRV_TMR1_CounterClear()
void DRV_TMR1_CounterClear (void)
DRV_TMR1_CounterFrequencyGet()
uint32_t DRV_TMR1_CounterFrequencyGet (void)
DRV_TMR1_CounterValueGet()
uint32_t DRV_TMR1_CounterValueGet (void)
DRV_TMR1_CounterValueSet()
void DRV_TMR1_CounterValueSet (uint32_t value)
DRV_TMR1_DeInitialize()
static void DRV_TMR1_DeInitialize (void) inline static
Definition at line 3723 of file inszt_UART.c.
DRV_TMR1_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR1_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR1_Initialize()
void DRV_TMR1_Initialize (void)
DRV_TMR1_Open()
static void DRV_TMR1_Open (void) inline static
Definition at line 3743 of file inszt_UART.c.
DRV_TMR1_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR1_OperationModeGet (void) inline static
Definition at line 3754 of file inszt_UART.c.
DRV_TMR1_PeriodValueGet()
uint32_t DRV_TMR1_PeriodValueGet (void)
DRV_TMR1_PeriodValueSet()
void DRV_TMR1_PeriodValueSet (uint32_t value)
DRV_TMR1_PrescalerGet()
TMR_PRESCALE DRV_TMR1_PrescalerGet (void)
DRV_TMR1_Start()
bool DRV_TMR1_Start (void)
DRV_TMR1_Status()
static SYS_STATUS DRV_TMR1_Status (void) inline static
Definition at line 3732 of file inszt_UART.c.
DRV_TMR1_Stop()
void DRV_TMR1_Stop (void)
Referenced by DRV_TMR1_Close(), and DRV_TMR1_DeInitialize().
DRV_TMR1_StopInIdleDisable()
void DRV_TMR1_StopInIdleDisable (void)
DRV_TMR1_StopInIdleEnable()
void DRV_TMR1_StopInIdleEnable (void)
DRV_TMR1_Tasks()
static void DRV_TMR1_Tasks (void) inline static
Definition at line 3804 of file inszt_UART.c.
DRV_TMR2_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR2_ClientStatus (void)
DRV_TMR2_ClockSet()
bool DRV_TMR2_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR2_Close()
static void DRV_TMR2_Close (void) inline static
Definition at line 3874 of file inszt_UART.c.
DRV_TMR2_CounterClear()
void DRV_TMR2_CounterClear (void)
DRV_TMR2_CounterFrequencyGet()
uint32_t DRV_TMR2_CounterFrequencyGet (void)
DRV_TMR2_CounterValueGet()
uint32_t DRV_TMR2_CounterValueGet (void)
DRV_TMR2_CounterValueSet()
void DRV_TMR2_CounterValueSet (uint32_t value)
DRV_TMR2_DeInitialize()
static void DRV_TMR2_DeInitialize (void) inline static
Definition at line 3833 of file inszt_UART.c.
DRV_TMR2_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR2_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR2_Initialize()
void DRV_TMR2_Initialize (void)
DRV_TMR2_Open()
static void DRV_TMR2_Open (void) inline static
Definition at line 3853 of file inszt_UART.c.
DRV_TMR2_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR2_OperationModeGet (void) inline static
Definition at line 3864 of file inszt_UART.c.
DRV_TMR2_PeriodValueGet()
uint32_t DRV_TMR2_PeriodValueGet (void)
DRV_TMR2_PeriodValueSet()
void DRV_TMR2_PeriodValueSet (uint32_t value)
DRV_TMR2_PrescalerGet()
TMR_PRESCALE DRV_TMR2_PrescalerGet (void)
DRV_TMR2_Start()
bool DRV_TMR2_Start (void)
DRV_TMR2_Status()
static SYS_STATUS DRV_TMR2_Status (void) inline static
Definition at line 3842 of file inszt_UART.c.
DRV_TMR2_Stop()
void DRV_TMR2_Stop (void)
Referenced by DRV_TMR2_Close(), and DRV_TMR2_DeInitialize().
DRV_TMR2_StopInIdleDisable()
void DRV_TMR2_StopInIdleDisable (void)
DRV_TMR2_StopInIdleEnable()
void DRV_TMR2_StopInIdleEnable (void)
DRV_TMR2_Tasks()
static void DRV_TMR2_Tasks (void) inline static
Definition at line 3914 of file inszt_UART.c.
DRV_TMR3_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR3_ClientStatus (void)
DRV_TMR3_ClockSet()
bool DRV_TMR3_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR3_Close()
static void DRV_TMR3_Close (void) inline static
Definition at line 3984 of file inszt_UART.c.
DRV_TMR3_CounterClear()
void DRV_TMR3_CounterClear (void)
DRV_TMR3_CounterFrequencyGet()
uint32_t DRV_TMR3_CounterFrequencyGet (void)
DRV_TMR3_CounterValueGet()
uint32_t DRV_TMR3_CounterValueGet (void)
DRV_TMR3_CounterValueSet()
void DRV_TMR3_CounterValueSet (uint32_t value)
DRV_TMR3_DeInitialize()
static void DRV_TMR3_DeInitialize (void) inline static
Definition at line 3943 of file inszt_UART.c.
DRV_TMR3_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR3_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR3_Initialize()
void DRV_TMR3_Initialize (void)
DRV_TMR3_Open()
static void DRV_TMR3_Open (void) inline static
Definition at line 3963 of file inszt_UART.c.
DRV_TMR3_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR3_OperationModeGet (void) inline static
Definition at line 3974 of file inszt_UART.c.
DRV_TMR3_PeriodValueGet()
uint32_t DRV_TMR3_PeriodValueGet (void)
DRV_TMR3_PeriodValueSet()
void DRV_TMR3_PeriodValueSet (uint32_t value)
DRV_TMR3_PrescalerGet()
TMR_PRESCALE DRV_TMR3_PrescalerGet (void)
DRV_TMR3_Start()
bool DRV_TMR3_Start (void)
DRV_TMR3_Status()
static SYS_STATUS DRV_TMR3_Status (void) inline static
Definition at line 3952 of file inszt_UART.c.
DRV_TMR3_Stop()
void DRV_TMR3_Stop (void)
Referenced by DRV_TMR3_Close(), and DRV_TMR3_DeInitialize().
DRV_TMR3_StopInIdleDisable()
void DRV_TMR3_StopInIdleDisable (void)
DRV_TMR3_StopInIdleEnable()
void DRV_TMR3_StopInIdleEnable (void)
DRV_TMR3_Tasks()
static void DRV_TMR3_Tasks (void) inline static
Definition at line 4024 of file inszt_UART.c.
DRV_TMR4_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR4_ClientStatus (void)
DRV_TMR4_ClockSet()
bool DRV_TMR4_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR4_Close()
static void DRV_TMR4_Close (void) inline static
Definition at line 4094 of file inszt_UART.c.
DRV_TMR4_CounterClear()
void DRV_TMR4_CounterClear (void)
DRV_TMR4_CounterFrequencyGet()
uint32_t DRV_TMR4_CounterFrequencyGet (void)
DRV_TMR4_CounterValueGet()
uint32_t DRV_TMR4_CounterValueGet (void)
DRV_TMR4_CounterValueSet()
void DRV_TMR4_CounterValueSet (uint32_t value)
DRV_TMR4_DeInitialize()
static void DRV_TMR4_DeInitialize (void) inline static
Definition at line 4053 of file inszt_UART.c.
DRV_TMR4_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR4_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR4_Initialize()
void DRV_TMR4_Initialize (void)
DRV_TMR4_Open()
static void DRV_TMR4_Open (void) inline static
Definition at line 4073 of file inszt_UART.c.
DRV_TMR4_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR4_OperationModeGet (void) inline static
Definition at line 4084 of file inszt_UART.c.
DRV_TMR4_PeriodValueGet()
uint32_t DRV_TMR4_PeriodValueGet (void)
DRV_TMR4_PeriodValueSet()
void DRV_TMR4_PeriodValueSet (uint32_t value)
DRV_TMR4_PrescalerGet()
TMR_PRESCALE DRV_TMR4_PrescalerGet (void)
DRV_TMR4_Start()
bool DRV_TMR4_Start (void)
DRV_TMR4_Status()
static SYS_STATUS DRV_TMR4_Status (void) inline static
Definition at line 4062 of file inszt_UART.c.
DRV_TMR4_Stop()
void DRV_TMR4_Stop (void)
Referenced by DRV_TMR4_Close(), and DRV_TMR4_DeInitialize().
DRV_TMR4_StopInIdleDisable()
void DRV_TMR4_StopInIdleDisable (void)
DRV_TMR4_StopInIdleEnable()
void DRV_TMR4_StopInIdleEnable (void)
DRV_TMR4_Tasks()
static void DRV_TMR4_Tasks (void) inline static
Definition at line 4134 of file inszt_UART.c.
DRV_TMR_AlarmDeregister()
void DRV_TMR_AlarmDeregister (DRV_HANDLE handle)
DRV_TMR_AlarmDisable()
bool DRV_TMR_AlarmDisable (DRV_HANDLE handle)
DRV_TMR_AlarmEnable()
void DRV_TMR_AlarmEnable (DRV_HANDLE handle, bool enable)
DRV_TMR_AlarmHasElapsed()
uint32_t DRV_TMR_AlarmHasElapsed (DRV_HANDLE handle)
DRV_TMR_AlarmPeriodGet()
uint32_t DRV_TMR_AlarmPeriodGet (DRV_HANDLE handle)
DRV_TMR_AlarmPeriodSet()
void DRV_TMR_AlarmPeriodSet (DRV_HANDLE handle, uint32_t value)
DRV_TMR_AlarmRegister()
bool DRV_TMR_AlarmRegister (DRV_HANDLE handle, uint32_t divider, bool isPeriodic, uintptr_t context, DRV_TMR_CALLBACK callBack)
DRV_TMR_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR_ClientStatus (DRV_HANDLE handle)
DRV_TMR_ClockSet()
bool DRV_TMR_ClockSet (DRV_HANDLE handle, DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE preScale)
DRV_TMR_Close()
void DRV_TMR_Close (DRV_HANDLE handle)
DRV_TMR_CounterClear()
void DRV_TMR_CounterClear (DRV_HANDLE handle)
DRV_TMR_CounterFrequencyGet()
uint32_t DRV_TMR_CounterFrequencyGet (DRV_HANDLE handle)
DRV_TMR_CounterValueGet()
uint32_t DRV_TMR_CounterValueGet (DRV_HANDLE handle)
DRV_TMR_CounterValueSet()
void DRV_TMR_CounterValueSet (DRV_HANDLE handle, uint32_t counterPeriod)
DRV_TMR_Deinitialize()
void DRV_TMR_Deinitialize (SYS_MODULE_OBJ object)
DRV_TMR_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR_DividerRangeGet (DRV_HANDLE handle, DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR_GateModeClear()
bool DRV_TMR_GateModeClear (DRV_HANDLE handle)
DRV_TMR_GateModeSet()
bool DRV_TMR_GateModeSet (DRV_HANDLE handle)
DRV_TMR_Initialize()
SYS_MODULE_OBJ DRV_TMR_Initialize (const SYS_MODULE_INDEX drvIndex, const SYS_MODULE_INIT *const init)
DRV_TMR_Open()
DRV_HANDLE DRV_TMR_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT intent)
DRV_TMR_OperationModeGet()
DRV_TMR_OPERATION_MODE DRV_TMR_OperationModeGet (DRV_HANDLE handle)
DRV_TMR_PrescalerGet()
TMR_PRESCALE DRV_TMR_PrescalerGet (DRV_HANDLE handle)
DRV_TMR_Start()
bool DRV_TMR_Start (DRV_HANDLE handle)
DRV_TMR_Status()
SYS_STATUS DRV_TMR_Status (SYS_MODULE_OBJ object)
DRV_TMR_Stop()
void DRV_TMR_Stop (DRV_HANDLE handle)
DRV_TMR_Tasks()
void DRV_TMR_Tasks (SYS_MODULE_OBJ object)
DRV_USART0_BaudSet()
DRV_USART_BAUD_SET_RESULT DRV_USART0_BaudSet (uint32_t baud)
DRV_USART0_ClientStatus()
DRV_USART_CLIENT_STATUS DRV_USART0_ClientStatus (void)
DRV_USART0_Close()
void DRV_USART0_Close (void)
DRV_USART0_Deinitialize()
void DRV_USART0_Deinitialize (void)
DRV_USART0_ErrorGet()
DRV_USART_ERROR DRV_USART0_ErrorGet (void)
DRV_USART0_Initialize()
SYS_MODULE_OBJ DRV_USART0_Initialize (void)
DRV_USART0_LineControlSet()
DRV_USART_LINE_CONTROL_SET_RESULT DRV_USART0_LineControlSet (DRV_USART_LINE_CONTROL lineControlMode)
DRV_USART0_Open()
DRV_HANDLE DRV_USART0_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT ioIntent)
DRV_USART0_ReadByte()
uint8_t DRV_USART0_ReadByte (void)
DRV_USART0_ReceiverBufferIsEmpty()
bool DRV_USART0_ReceiverBufferIsEmpty (void)
DRV_USART0_ReceiverBufferSizeGet()
unsigned int DRV_USART0_ReceiverBufferSizeGet (void)
DRV_USART0_Status()
SYS_STATUS DRV_USART0_Status (void)
DRV_USART0_TasksError()
void DRV_USART0_TasksError (void)
DRV_USART0_TasksReceive()
void DRV_USART0_TasksReceive (void)
DRV_USART0_TasksTransmit()
void DRV_USART0_TasksTransmit (void)
DRV_USART0_TransferStatus()
DRV_USART_TRANSFER_STATUS DRV_USART0_TransferStatus (void)
DRV_USART0_TransmitBufferIsFull()
bool DRV_USART0_TransmitBufferIsFull (void)
DRV_USART0_TransmitBufferSizeGet()
unsigned int DRV_USART0_TransmitBufferSizeGet (void)
DRV_USART0_WriteByte()
void DRV_USART0_WriteByte (const uint8_t byte)
DRV_USART_AddressedBufferAddWrite()
void DRV_USART_AddressedBufferAddWrite (const DRV_HANDLE hClient, DRV_USART_BUFFER_HANDLE * bufferHandle, uint8_t address, void * source, size_t nWords)
DRV_USART_BaudSet()
DRV_USART_BAUD_SET_RESULT DRV_USART_BaudSet (const DRV_HANDLE client, uint32_t baud)
DRV_USART_BufferAddRead()
void DRV_USART_BufferAddRead (const DRV_HANDLE handle, DRV_USART_BUFFER_HANDLE *const bufferHandle, void * buffer, const size_t size)
DRV_USART_BufferAddWrite()
void DRV_USART_BufferAddWrite (const DRV_HANDLE handle, DRV_USART_BUFFER_HANDLE * bufferHandle, void * buffer, const size_t size)
DRV_USART_BufferCompletedBytesGet()
size_t DRV_USART_BufferCompletedBytesGet (DRV_USART_BUFFER_HANDLE bufferHandle)
DRV_USART_BufferEventHandlerSet()
void DRV_USART_BufferEventHandlerSet (const DRV_HANDLE handle, const DRV_USART_BUFFER_EVENT_HANDLER eventHandler, const uintptr_t context)
DRV_USART_BufferProcessedSizeGet()
size_t DRV_USART_BufferProcessedSizeGet (DRV_USART_BUFFER_HANDLE bufferHandle)
DRV_USART_BufferRemove()
DRV_USART_BUFFER_RESULT DRV_USART_BufferRemove (DRV_USART_BUFFER_HANDLE bufferHandle)
DRV_USART_ByteErrorCallbackSet()
void DRV_USART_ByteErrorCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
DRV_USART_ByteReceiveCallbackSet()
void DRV_USART_ByteReceiveCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
DRV_USART_ByteTransmitCallbackSet()
void DRV_USART_ByteTransmitCallbackSet (const SYS_MODULE_INDEX index, const DRV_USART_BYTE_EVENT_HANDLER eventHandler)
DRV_USART_ClientStatus()
DRV_USART_CLIENT_STATUS DRV_USART_ClientStatus (DRV_HANDLE handle)
DRV_USART_Close()
void DRV_USART_Close (const DRV_HANDLE handle)
DRV_USART_Deinitialize()
void DRV_USART_Deinitialize (SYS_MODULE_OBJ object)
DRV_USART_ErrorGet()
DRV_USART_ERROR DRV_USART_ErrorGet (const DRV_HANDLE client)
DRV_USART_Initialize()
SYS_MODULE_OBJ DRV_USART_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
DRV_USART_LineControlSet()
DRV_USART_LINE_CONTROL_SET_RESULT DRV_USART_LineControlSet (const DRV_HANDLE client, const DRV_USART_LINE_CONTROL lineControl)
DRV_USART_Open()
DRV_HANDLE DRV_USART_Open (const SYS_MODULE_INDEX index, const DRV_IO_INTENT ioIntent)
Referenced by UART_Tasks().
DRV_USART_Read()
size_t DRV_USART_Read (const DRV_HANDLE handle, void * buffer, const size_t numbytes)
DRV_USART_ReadByte()
uint8_t DRV_USART_ReadByte (const DRV_HANDLE handle)
Referenced by ReadUART().
DRV_USART_ReceiverBufferIsEmpty()
bool DRV_USART_ReceiverBufferIsEmpty (const DRV_HANDLE handle)
Referenced by ReadUART().
DRV_USART_ReceiverBufferSizeGet()
unsigned int DRV_USART_ReceiverBufferSizeGet (const DRV_HANDLE handle)
DRV_USART_Status()
SYS_STATUS DRV_USART_Status (SYS_MODULE_OBJ object)
DRV_USART_TasksError()
void DRV_USART_TasksError (SYS_MODULE_OBJ object)
DRV_USART_TasksReceive()
void DRV_USART_TasksReceive (SYS_MODULE_OBJ object)
DRV_USART_TasksTransmit()
void DRV_USART_TasksTransmit (SYS_MODULE_OBJ object)
DRV_USART_TransferStatus()
DRV_USART_TRANSFER_STATUS DRV_USART_TransferStatus (const DRV_HANDLE handle)
DRV_USART_TransmitBufferIsFull()
bool DRV_USART_TransmitBufferIsFull (const DRV_HANDLE handle)
DRV_USART_TransmitBufferSizeGet()
unsigned int DRV_USART_TransmitBufferSizeGet (const DRV_HANDLE handle)
DRV_USART_Write()
size_t DRV_USART_Write (const DRV_HANDLE handle, void * buffer, const size_t numbytes)
DRV_USART_WriteByte()
void DRV_USART_WriteByte (const DRV_HANDLE handle, const uint8_t byte)
Execute_Auto_Protocol_A()
static void Execute_Auto_Protocol_A (void) static
Function: static void Execute_Auto_Protocol_A (void) Summary: This function executes the Auto Protocol A commands. Description: This function executes the Auto Protocol A commands. These are commands that control the panel. The commands are listed as case statements. Once the action is completed, a response is generated and sent back to the host.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: Execute_Auto_Protocol_A ()
Execute_Protocol_A()
static void Execute_Protocol_A (void) static
Function: static void Execute_Protocol_A (void) Summary: This function executes the Protocol A commands. Description: This function executes the Protocol A commands. These are commands that control the panel. The commands are listed as case statements. Once the action is completed, a response is generated and sent back to the host.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: ExecuteProtocolA ()
Execute_Protocol_B()
static void Execute_Protocol_B (void) static
Function: static void Execute_Protocol_B (void) Summary: This function executes the Protocol B commands. Description: This function executes the Protocol B commands. These are commands that are for a PerfSwitch or other tool. The commands are listed as case statements. Once the action is completed, a response is generated and sent back to the host.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: ExecuteProtocolB ()
Execute_System()
static void Execute_System (void) static
Function: static void Execute_System(void) Summary: This function executes the system commands. Description: This function executes the system commands. Once the action is completed, a response is generated and sent back to the host.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: ExecuteSystem()
Fifo_Get()
uint8_t Fifo_Get (TFifo * ptrFifo)
Function: uint8_t Fifo_Get(TFifo *ptrFifo) Summary: Function to retrieve an entry from Fifo. Description: Function to retrieve an entry from Fifo. If Fifo is empty then function returns FIFO_EMPTY. Otherwise, the function returns the oldest entry in FifoBuffer and increments FifoTail.
Precondition: None. Parameters: TFifo *ptrFifo Returns uint8_t Contents of Fifo buffer.
Remarks: None.
Example: temp = Fifo_Get(&RX_FIFO)
Function: uint8_t Fifo_Get(TFifo *ptrFifo)
Summary: Function to retrieve the oldest entry from a Fifo. It also provides a check for an empty Fifo.
Remarks: Refer to the fifo.h interface header for function usage details.
Function: uint8_t Fifo_Get(TFifo *ptrFifo) Summary: Function to retrieve an entry from Fifo. Description: Function to retrieve an entry from Fifo. If Fifo is empty then function returns FIFO_EMPTY. Otherwise, the function returns the oldest entry in FifoBuffer and increments FifoTail.
Precondition: None. Parameters: TFifo *ptrFifo Returns uint8_t Contents of Fifo buffer.
Remarks: None.
Example: temp = Fifo_Get(&RX_FIFO)
Function: uint8_t Fifo_Get(TFifo *ptrFifo) Summary: Function to retrieve the oldest entry from a Fifo. It also provides a check for an empty Fifo. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 160 of file fifo.c.
Referenced by WriteUART().
Fifo_Init()
static void Fifo_Init (TFifo * ptrFifo, uint8_t * ptrBuffer, uint16_t Length) static
Function: static void Fifo_Init(TFifo *ptrFifo, unsigned char *ptrBuffer, int Length) Summary: This function initializes a given Fifo. Description: This function initializes the communication Fifo. It is used to initialize both the transmit and receive Fifo's.
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: Fifo_Init(&RX_FIFO, FifoRxBuffer, FIFO_RX_SIZE)
Fifo_Length()
uint8_t Fifo_Length (TFifo * ptrFifo)
Function: uint8_t Fifo_Length(TFifo *ptrFifo) Summary: Function to find the length of the buffer. Description: Function to find the length of the buffer.
Precondition: None. Parameters: TFifo *ptrFifo: The pointer to the Fifo. Returns uint8_t. Length of the fifo buffer.
Remarks: None.
Example: if(Fifo_Length(&RX_FIFO) == CMD.cmd_size)
Function: uint8_t Fifo_Length(TFifo *ptrFifo)
Summary: Function to find the length of the buffer.
Description: Function to find the length of the buffer.
Precondition: None.
Parameters: TFifo *ptrFifo: The pointer to the Fifo.
Returns uint8_t. Length of the fifo buffer.
Remarks: None.
Example: if(Fifo_Length(&RX_FIFO) == CMD.cmd_size)
Definition at line 202 of file fifo.c.
Fifo_Put()
uint8_t Fifo_Put (TFifo * ptrFifo, uint8_t Data)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data) Summary: Function to add an entry (byte)to a Fifo. Description: Function to add an entry (byte)to a Fifo. If the Fifo is full then the function returns FIFO_FULL, otherwise the function adds the entry to the FifoBuffer, increments FifoHead and returns FIFO_ADD_OK.
Precondition: None. Parameters: uint8_t Data: The byte of data to be added. TFifo *ptrFifo: The pointer to the Fifo that is being manipulated. Returns integer value. Fifo_Full or FIFO_ADD_OK
Remarks: None.
Example: Fifo_Put(&TX_FIFO, b_comm_crc)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data)
Summary: Function to put a byte of data into a Fifo. It also provides a check for a full Fifo.
Remarks: Refer to the fifo.h interface header for function usage details.
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data) Summary: Function to add an entry (byte)to a Fifo. Description: Function to add an entry (byte)to a Fifo. If the Fifo is full then the function returns FIFO_FULL, otherwise the function adds the entry to the FifoBuffer, increments FifoHead and returns FIFO_ADD_OK.
Precondition: None. Parameters: uint8_t Data: The byte of data to be added. TFifo *ptrFifo: The pointer to the Fifo that is being manipulated. Returns integer value. Fifo_Full or FIFO_ADD_OK
Remarks: None.
Example: Fifo_Put(&TX_FIFO, b_comm_crc)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data) Summary: Function to put a byte of data into a Fifo. It also provides a check for a full Fifo. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 117 of file fifo.c.
Referenced by ReadUART().
GetDepthStatus()
bool GetDepthStatus (void)
Function: bool GetDepthStatus (void) Summary: This function compares the received command(first byte)and compares it to a list of correct commands. Description: This function compares the received command(first byte)and compares it to a list of correct commands. If there is a match, the rest of the transmission is received for processing. Used in the ValidateComm function in commmodule.c
Precondition: None. Parameters: unsigned char msg - The one byte command to compare. Returns unsigned short ans.
Remarks None.
Example: GetDepthStatus ()
Function: bool GetDepthStatus (void) Summary: This function compares the received command(first byte)and compares it to a list of correct commands. Description: This function compares the received command(first byte)and compares it to a list of correct commands. If there is a match, the rest of the transmission is received for processing. Used in the ValidateComm function in commmodule.c
Precondition: None. Parameters: unsigned char msg - The one byte command to compare. Returns unsigned short ans.
Remarks None.
Example: GetDepthStatus ()
Function: bool GetDepthStatus(void) Summary: Function to enable/disable the FIRE Switch. SDS Warrior controls this setting. TRUE by default at power up. Remarks: Refer to the commands.h interface header for function usage details.
Definition at line 31861 of file inszt_commands.c.
Init_Fifo()
void Init_Fifo (void)
Function: void Init_Fifo(void) Summary: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. Description: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. This function is called in APP_Initialize in app.c
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: Init_Fifo()
Function: void Init_Fifo(void)
Summary: Function to initialize the Tx and Rx FIFOs.
Remarks: Refer to the fifo.h interface header for function usage details.
Function: void Init_Fifo(void) Summary: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. Description: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. This function is called in APP_Initialize in app.c
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: Init_Fifo()
Function: void Init_Fifo(void) Summary: Function to initialize the Tx and Rx FIFOs. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 100 of file fifo.c.
PLIB_DMA_AbortTransferSet()
void PLIB_DMA_AbortTransferSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_BusyActiveReset()
void PLIB_DMA_BusyActiveReset (DMA_MODULE_ID index)
PLIB_DMA_BusyActiveSet()
void PLIB_DMA_BusyActiveSet (DMA_MODULE_ID index)
PLIB_DMA_ChannelBitsGet()
uint8_t PLIB_DMA_ChannelBitsGet (DMA_MODULE_ID index)
PLIB_DMA_ChannelPriorityGet()
DMA_CHANNEL_PRIORITY PLIB_DMA_ChannelPriorityGet (DMA_MODULE_ID index)
PLIB_DMA_ChannelPrioritySelect()
void PLIB_DMA_ChannelPrioritySelect (DMA_MODULE_ID index, DMA_CHANNEL_PRIORITY channelPriority)
PLIB_DMA_ChannelXAbortIRQSet()
void PLIB_DMA_ChannelXAbortIRQSet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRIGGER_SOURCE IRQ)
PLIB_DMA_ChannelXAddressModeGet()
DMA_CHANNEL_ADDRESSING_MODE PLIB_DMA_ChannelXAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXAddressModeSelect()
void PLIB_DMA_ChannelXAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_ADDRESSING_MODE channelAddressMode)
PLIB_DMA_ChannelXAutoDisable()
void PLIB_DMA_ChannelXAutoDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXAutoEnable()
void PLIB_DMA_ChannelXAutoEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXAutoIsEnabled()
bool PLIB_DMA_ChannelXAutoIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXBufferedDataIsWritten()
bool PLIB_DMA_ChannelXBufferedDataIsWritten (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXBusyActiveSet()
void PLIB_DMA_ChannelXBusyActiveSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXBusyInActiveSet()
void PLIB_DMA_ChannelXBusyInActiveSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXBusyIsBusy()
bool PLIB_DMA_ChannelXBusyIsBusy (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXCellProgressPointerGet()
uint16_t PLIB_DMA_ChannelXCellProgressPointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXCellSizeGet()
uint16_t PLIB_DMA_ChannelXCellSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXCellSizeSet()
void PLIB_DMA_ChannelXCellSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t CellSize)
PLIB_DMA_ChannelXChainDisable()
void PLIB_DMA_ChannelXChainDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXChainEnable()
void PLIB_DMA_ChannelXChainEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXChainIsEnabled()
bool PLIB_DMA_ChannelXChainIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXChainToHigher()
void PLIB_DMA_ChannelXChainToHigher (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXChainToLower()
void PLIB_DMA_ChannelXChainToLower (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXCollisionStatus()
bool PLIB_DMA_ChannelXCollisionStatus (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_COLLISION collisonType)
PLIB_DMA_ChannelXDataSizeGet()
DMA_CHANNEL_DATA_SIZE PLIB_DMA_ChannelXDataSizeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXDataSizeSelect()
void PLIB_DMA_ChannelXDataSizeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_DATA_SIZE channelDataSize)
PLIB_DMA_ChannelXDestinationAddressModeGet()
DMA_DESTINATION_ADDRESSING_MODE PLIB_DMA_ChannelXDestinationAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXDestinationAddressModeSelect()
void PLIB_DMA_ChannelXDestinationAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_DESTINATION_ADDRESSING_MODE destinationAddressMode)
PLIB_DMA_ChannelXDestinationPointerGet()
uint16_t PLIB_DMA_ChannelXDestinationPointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXDestinationSizeGet()
uint16_t PLIB_DMA_ChannelXDestinationSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXDestinationSizeSet()
void PLIB_DMA_ChannelXDestinationSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t destinationSize)
PLIB_DMA_ChannelXDestinationStartAddressGet()
uint32_t PLIB_DMA_ChannelXDestinationStartAddressGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXDestinationStartAddressSet()
void PLIB_DMA_ChannelXDestinationStartAddressSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint32_t destinationStartAddress)
PLIB_DMA_ChannelXDisable()
void PLIB_DMA_ChannelXDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXDisabledDisablesEvents()
void PLIB_DMA_ChannelXDisabledDisablesEvents (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXDisabledEnablesEvents()
void PLIB_DMA_ChannelXDisabledEnablesEvents (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXEnable()
void PLIB_DMA_ChannelXEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXEventIsDetected()
bool PLIB_DMA_ChannelXEventIsDetected (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXINTSourceDisable()
void PLIB_DMA_ChannelXINTSourceDisable (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXINTSourceEnable()
void PLIB_DMA_ChannelXINTSourceEnable (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXINTSourceFlagClear()
void PLIB_DMA_ChannelXINTSourceFlagClear (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXINTSourceFlagGet()
bool PLIB_DMA_ChannelXINTSourceFlagGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXINTSourceFlagSet()
void PLIB_DMA_ChannelXINTSourceFlagSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXINTSourceIsEnabled()
bool PLIB_DMA_ChannelXINTSourceIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_INT_TYPE dmaINTSource)
PLIB_DMA_ChannelXIsEnabled()
bool PLIB_DMA_ChannelXIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXNullWriteModeDisable()
void PLIB_DMA_ChannelXNullWriteModeDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXNullWriteModeEnable()
void PLIB_DMA_ChannelXNullWriteModeEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXNullWriteModeIsEnabled()
bool PLIB_DMA_ChannelXNullWriteModeIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXOperatingTransferModeGet()
DMA_TRANSFER_MODE PLIB_DMA_ChannelXOperatingTransferModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXOperatingTransferModeSelect()
void PLIB_DMA_ChannelXOperatingTransferModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRANSFER_MODE channeltransferMode)
PLIB_DMA_ChannelXPatternDataGet()
uint16_t PLIB_DMA_ChannelXPatternDataGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXPatternDataSet()
void PLIB_DMA_ChannelXPatternDataSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t patternData)
PLIB_DMA_ChannelXPatternIgnoreByteDisable()
void PLIB_DMA_ChannelXPatternIgnoreByteDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPatternIgnoreByteEnable()
void PLIB_DMA_ChannelXPatternIgnoreByteEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPatternIgnoreByteIsEnabled()
bool PLIB_DMA_ChannelXPatternIgnoreByteIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPatternIgnoreGet()
uint8_t PLIB_DMA_ChannelXPatternIgnoreGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPatternIgnoreSet()
void PLIB_DMA_ChannelXPatternIgnoreSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint8_t pattern)
PLIB_DMA_ChannelXPatternLengthGet()
DMA_PATTERN_LENGTH PLIB_DMA_ChannelXPatternLengthGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXPatternLengthSet()
void PLIB_DMA_ChannelXPatternLengthSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, DMA_PATTERN_LENGTH patternLen)
PLIB_DMA_ChannelXPeripheralAddressGet()
uint16_t PLIB_DMA_ChannelXPeripheralAddressGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPeripheralAddressSet()
void PLIB_DMA_ChannelXPeripheralAddressSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t peripheraladdress)
PLIB_DMA_ChannelXPingPongModeGet()
DMA_PING_PONG_MODE PLIB_DMA_ChannelXPingPongModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPriorityGet()
DMA_CHANNEL_PRIORITY PLIB_DMA_ChannelXPriorityGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXPrioritySelect()
void PLIB_DMA_ChannelXPrioritySelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_PRIORITY channelPriority)
PLIB_DMA_ChannelXReloadDisable()
void PLIB_DMA_ChannelXReloadDisable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXReloadEnable()
void PLIB_DMA_ChannelXReloadEnable (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXReloadIsEnabled()
bool PLIB_DMA_ChannelXReloadIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXSourceAddressModeGet()
DMA_SOURCE_ADDRESSING_MODE PLIB_DMA_ChannelXSourceAddressModeGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXSourceAddressModeSelect()
void PLIB_DMA_ChannelXSourceAddressModeSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_SOURCE_ADDRESSING_MODE sourceAddressMode)
PLIB_DMA_ChannelXSourcePointerGet()
uint16_t PLIB_DMA_ChannelXSourcePointerGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXSourceSizeGet()
uint16_t PLIB_DMA_ChannelXSourceSizeGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXSourceSizeSet()
void PLIB_DMA_ChannelXSourceSizeSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint16_t sourceSize)
PLIB_DMA_ChannelXSourceStartAddressGet()
uint32_t PLIB_DMA_ChannelXSourceStartAddressGet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel)
PLIB_DMA_ChannelXSourceStartAddressSet()
void PLIB_DMA_ChannelXSourceStartAddressSet (DMA_MODULE_ID index, DMA_CHANNEL dmaChannel, uint32_t sourceStartAddress)
PLIB_DMA_ChannelXStartAddressOffsetGet()
uint16_t PLIB_DMA_ChannelXStartAddressOffsetGet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_ADDRESS_OFFSET_TYPE offset)
PLIB_DMA_ChannelXStartAddressOffsetSet()
void PLIB_DMA_ChannelXStartAddressOffsetSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t address, DMA_ADDRESS_OFFSET_TYPE offset)
PLIB_DMA_ChannelXStartIRQSet()
void PLIB_DMA_ChannelXStartIRQSet (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_TRIGGER_SOURCE IRQnum)
PLIB_DMA_ChannelXTransferCountGet()
uint16_t PLIB_DMA_ChannelXTransferCountGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXTransferCountSet()
void PLIB_DMA_ChannelXTransferCountSet (DMA_MODULE_ID index, DMA_CHANNEL channel, uint16_t transferCount)
PLIB_DMA_ChannelXTransferDirectionGet()
DMA_CHANNEL_TRANSFER_DIRECTION PLIB_DMA_ChannelXTransferDirectionGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_ChannelXTransferDirectionSelect()
void PLIB_DMA_ChannelXTransferDirectionSelect (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRANSFER_DIRECTION chTransferDirection)
PLIB_DMA_ChannelXTriggerDisable()
void PLIB_DMA_ChannelXTriggerDisable (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
PLIB_DMA_ChannelXTriggerEnable()
void PLIB_DMA_ChannelXTriggerEnable (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
PLIB_DMA_ChannelXTriggerIsEnabled()
bool PLIB_DMA_ChannelXTriggerIsEnabled (DMA_MODULE_ID index, DMA_CHANNEL channel, DMA_CHANNEL_TRIGGER_TYPE trigger)
PLIB_DMA_ChannelXTriggerSourceNumberGet()
DMA_CHANNEL_INT_SOURCE PLIB_DMA_ChannelXTriggerSourceNumberGet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_CRCAppendModeDisable()
void PLIB_DMA_CRCAppendModeDisable (DMA_MODULE_ID index)
PLIB_DMA_CRCAppendModeEnable()
void PLIB_DMA_CRCAppendModeEnable (DMA_MODULE_ID index)
PLIB_DMA_CRCAppendModeIsEnabled()
bool PLIB_DMA_CRCAppendModeIsEnabled (DMA_MODULE_ID index)
PLIB_DMA_CRCBitOrderSelect()
void PLIB_DMA_CRCBitOrderSelect (DMA_MODULE_ID index, DMA_CRC_BIT_ORDER bitOrder)
PLIB_DMA_CRCByteOrderGet()
DMA_CRC_BYTE_ORDER PLIB_DMA_CRCByteOrderGet (DMA_MODULE_ID index)
PLIB_DMA_CRCByteOrderSelect()
void PLIB_DMA_CRCByteOrderSelect (DMA_MODULE_ID index, DMA_CRC_BYTE_ORDER byteOrder)
PLIB_DMA_CRCChannelGet()
DMA_CHANNEL PLIB_DMA_CRCChannelGet (DMA_MODULE_ID index)
PLIB_DMA_CRCChannelSelect()
void PLIB_DMA_CRCChannelSelect (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_CRCDataRead()
uint32_t PLIB_DMA_CRCDataRead (DMA_MODULE_ID index)
PLIB_DMA_CRCDataWrite()
void PLIB_DMA_CRCDataWrite (DMA_MODULE_ID index, uint32_t DMACRCdata)
PLIB_DMA_CRCDisable()
void PLIB_DMA_CRCDisable (DMA_MODULE_ID index)
PLIB_DMA_CRCEnable()
void PLIB_DMA_CRCEnable (DMA_MODULE_ID index)
PLIB_DMA_CRCIsEnabled()
bool PLIB_DMA_CRCIsEnabled (DMA_MODULE_ID index)
PLIB_DMA_CRCPolynomialLengthGet()
uint8_t PLIB_DMA_CRCPolynomialLengthGet (DMA_MODULE_ID index)
PLIB_DMA_CRCPolynomialLengthSet()
void PLIB_DMA_CRCPolynomialLengthSet (DMA_MODULE_ID index, uint8_t polyLength)
PLIB_DMA_CRCTypeGet()
DMA_CRC_TYPE PLIB_DMA_CRCTypeGet (DMA_MODULE_ID index)
PLIB_DMA_CRCTypeSet()
void PLIB_DMA_CRCTypeSet (DMA_MODULE_ID index, DMA_CRC_TYPE CRCType)
PLIB_DMA_CRCWriteByteOrderAlter()
void PLIB_DMA_CRCWriteByteOrderAlter (DMA_MODULE_ID index)
PLIB_DMA_CRCWriteByteOrderMaintain()
void PLIB_DMA_CRCWriteByteOrderMaintain (DMA_MODULE_ID index)
PLIB_DMA_CRCXOREnableGet()
uint32_t PLIB_DMA_CRCXOREnableGet (DMA_MODULE_ID index)
PLIB_DMA_CRCXOREnableSet()
void PLIB_DMA_CRCXOREnableSet (DMA_MODULE_ID index, uint32_t DMACRCXOREnableMask)
PLIB_DMA_Disable()
void PLIB_DMA_Disable (DMA_MODULE_ID index)
PLIB_DMA_Enable()
void PLIB_DMA_Enable (DMA_MODULE_ID index)
PLIB_DMA_ExistsAbortTransfer()
bool PLIB_DMA_ExistsAbortTransfer (DMA_MODULE_ID index)
PLIB_DMA_ExistsBusy()
bool PLIB_DMA_ExistsBusy (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelBits()
bool PLIB_DMA_ExistsChannelBits (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelX()
bool PLIB_DMA_ExistsChannelX (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXAbortIRQ()
bool PLIB_DMA_ExistsChannelXAbortIRQ (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXAuto()
bool PLIB_DMA_ExistsChannelXAuto (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXBusy()
bool PLIB_DMA_ExistsChannelXBusy (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXCellProgressPointer()
bool PLIB_DMA_ExistsChannelXCellProgressPointer (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXCellSize()
bool PLIB_DMA_ExistsChannelXCellSize (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXChain()
bool PLIB_DMA_ExistsChannelXChain (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXChainEnbl()
bool PLIB_DMA_ExistsChannelXChainEnbl (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXDestinationPointer()
bool PLIB_DMA_ExistsChannelXDestinationPointer (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXDestinationSize()
bool PLIB_DMA_ExistsChannelXDestinationSize (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXDestinationStartAddress()
bool PLIB_DMA_ExistsChannelXDestinationStartAddress (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXDisabled()
bool PLIB_DMA_ExistsChannelXDisabled (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXEvent()
bool PLIB_DMA_ExistsChannelXEvent (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXINTSource()
bool PLIB_DMA_ExistsChannelXINTSource (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXINTSourceFlag()
bool PLIB_DMA_ExistsChannelXINTSourceFlag (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXPatternData()
bool PLIB_DMA_ExistsChannelXPatternData (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXPatternIgnore()
bool PLIB_DMA_ExistsChannelXPatternIgnore (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXPatternIgnoreByte()
bool PLIB_DMA_ExistsChannelXPatternIgnoreByte (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXPatternLength()
bool PLIB_DMA_ExistsChannelXPatternLength (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXPriority()
bool PLIB_DMA_ExistsChannelXPriority (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXSourcePointer()
bool PLIB_DMA_ExistsChannelXSourcePointer (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXSourceSize()
bool PLIB_DMA_ExistsChannelXSourceSize (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXSourceStartAddress()
bool PLIB_DMA_ExistsChannelXSourceStartAddress (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXStartIRQ()
bool PLIB_DMA_ExistsChannelXStartIRQ (DMA_MODULE_ID index)
PLIB_DMA_ExistsChannelXTrigger()
bool PLIB_DMA_ExistsChannelXTrigger (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRC()
bool PLIB_DMA_ExistsCRC (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCAppendMode()
bool PLIB_DMA_ExistsCRCAppendMode (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCBitOrder()
bool PLIB_DMA_ExistsCRCBitOrder (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCByteOrder()
bool PLIB_DMA_ExistsCRCByteOrder (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCChannel()
bool PLIB_DMA_ExistsCRCChannel (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCData()
bool PLIB_DMA_ExistsCRCData (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCPolynomialLength()
bool PLIB_DMA_ExistsCRCPolynomialLength (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCType()
bool PLIB_DMA_ExistsCRCType (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCWriteByteOrder()
bool PLIB_DMA_ExistsCRCWriteByteOrder (DMA_MODULE_ID index)
PLIB_DMA_ExistsCRCXOREnable()
bool PLIB_DMA_ExistsCRCXOREnable (DMA_MODULE_ID index)
PLIB_DMA_ExistsEnableControl()
bool PLIB_DMA_ExistsEnableControl (DMA_MODULE_ID index)
PLIB_DMA_ExistsLastBusAccess()
bool PLIB_DMA_ExistsLastBusAccess (DMA_MODULE_ID index)
PLIB_DMA_ExistsRecentAddress()
bool PLIB_DMA_ExistsRecentAddress (DMA_MODULE_ID index)
PLIB_DMA_ExistsStartTransfer()
bool PLIB_DMA_ExistsStartTransfer (DMA_MODULE_ID index)
PLIB_DMA_ExistsStopInIdle()
bool PLIB_DMA_ExistsStopInIdle (DMA_MODULE_ID index)
PLIB_DMA_ExistsSuspend()
bool PLIB_DMA_ExistsSuspend (DMA_MODULE_ID index)
PLIB_DMA_IsBusy()
bool PLIB_DMA_IsBusy (DMA_MODULE_ID index)
PLIB_DMA_IsEnabled()
bool PLIB_DMA_IsEnabled (DMA_MODULE_ID index)
PLIB_DMA_LastBusAccessIsRead()
bool PLIB_DMA_LastBusAccessIsRead (DMA_MODULE_ID index)
PLIB_DMA_LastBusAccessIsWrite()
bool PLIB_DMA_LastBusAccessIsWrite (DMA_MODULE_ID index)
PLIB_DMA_RecentAddressAccessed()
uint32_t PLIB_DMA_RecentAddressAccessed (DMA_MODULE_ID index)
PLIB_DMA_StartTransferSet()
void PLIB_DMA_StartTransferSet (DMA_MODULE_ID index, DMA_CHANNEL channel)
PLIB_DMA_StopInIdleDisable()
void PLIB_DMA_StopInIdleDisable (DMA_MODULE_ID index)
PLIB_DMA_StopInIdleEnable()
void PLIB_DMA_StopInIdleEnable (DMA_MODULE_ID index)
PLIB_DMA_SuspendDisable()
void PLIB_DMA_SuspendDisable (DMA_MODULE_ID index)
PLIB_DMA_SuspendEnable()
void PLIB_DMA_SuspendEnable (DMA_MODULE_ID index)
PLIB_DMA_SuspendIsEnabled()
bool PLIB_DMA_SuspendIsEnabled (DMA_MODULE_ID index)
PLIB_PORTS_AnPinsModeSelect()
void PLIB_PORTS_AnPinsModeSelect (PORTS_MODULE_ID index, PORTS_AN_PIN anPins, PORTS_PIN_MODE mode)
PLIB_PORTS_ChangeNoticeDisable()
void PLIB_PORTS_ChangeNoticeDisable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeEnable()
void PLIB_PORTS_ChangeNoticeEnable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdleDisable()
void PLIB_PORTS_ChangeNoticeInIdleDisable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdleEnable()
void PLIB_PORTS_ChangeNoticeInIdleEnable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdlePerPortDisable()
void PLIB_PORTS_ChangeNoticeInIdlePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticeInIdlePerPortEnable()
void PLIB_PORTS_ChangeNoticeInIdlePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePerPortHasOccurred()
bool PLIB_PORTS_ChangeNoticePerPortHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePerPortTurnOff()
void PLIB_PORTS_ChangeNoticePerPortTurnOff (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePerPortTurnOn()
void PLIB_PORTS_ChangeNoticePerPortTurnOn (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePullDownPerPortDisable()
void PLIB_PORTS_ChangeNoticePullDownPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullDownPerPortEnable()
void PLIB_PORTS_ChangeNoticePullDownPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullUpDisable()
void PLIB_PORTS_ChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_ChangeNoticePullUpEnable()
void PLIB_PORTS_ChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_ChangeNoticePullUpPerPortDisable()
void PLIB_PORTS_ChangeNoticePullUpPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullUpPerPortEnable()
void PLIB_PORTS_ChangeNoticePullUpPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChannelChangeNoticeDisable()
void PLIB_PORTS_ChannelChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticeEdgeDisable()
void PLIB_PORTS_ChannelChangeNoticeEdgeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
PLIB_PORTS_ChannelChangeNoticeEdgeEnable()
void PLIB_PORTS_ChannelChangeNoticeEdgeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
PLIB_PORTS_ChannelChangeNoticeEnable()
void PLIB_PORTS_ChannelChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticeMethodGet()
PORTS_CHANGE_NOTICE_METHOD PLIB_PORTS_ChannelChangeNoticeMethodGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChannelChangeNoticeMethodSelect()
void PLIB_PORTS_ChannelChangeNoticeMethodSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_CHANGE_NOTICE_METHOD changeNoticeMethod)
PLIB_PORTS_ChannelChangeNoticePullDownDisable()
void PLIB_PORTS_ChannelChangeNoticePullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullDownEnable()
void PLIB_PORTS_ChannelChangeNoticePullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullUpDisable()
void PLIB_PORTS_ChannelChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullUpEnable()
void PLIB_PORTS_ChannelChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelModeSelect()
void PLIB_PORTS_ChannelModeSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK modeMask, PORTS_PIN_MODE mode)
PLIB_PORTS_ChannelSlewRateSelect()
void PLIB_PORTS_ChannelSlewRateSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK channelMask, PORTS_PIN_SLEW_RATE slewRate)
PLIB_PORTS_Clear()
void PLIB_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
PLIB_PORTS_CnPinsDisable()
void PLIB_PORTS_CnPinsDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsEnable()
void PLIB_PORTS_CnPinsEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsPullUpDisable()
void PLIB_PORTS_CnPinsPullUpDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsPullUpEnable()
void PLIB_PORTS_CnPinsPullUpEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_DirectionGet()
PORTS_DATA_MASK PLIB_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_DirectionInputSet()
void PLIB_PORTS_DirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_DirectionOutputSet()
void PLIB_PORTS_DirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ExistsAnPinsMode()
bool PLIB_PORTS_ExistsAnPinsMode (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNotice()
bool PLIB_PORTS_ExistsChangeNotice (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeEdgeControl()
bool PLIB_PORTS_ExistsChangeNoticeEdgeControl (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeEdgeStatus()
bool PLIB_PORTS_ExistsChangeNoticeEdgeStatus (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeInIdle()
bool PLIB_PORTS_ExistsChangeNoticeInIdle (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortInIdle()
bool PLIB_PORTS_ExistsChangeNoticePerPortInIdle (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortStatus()
bool PLIB_PORTS_ExistsChangeNoticePerPortStatus (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortTurnOn()
bool PLIB_PORTS_ExistsChangeNoticePerPortTurnOn (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullDownPerPort()
bool PLIB_PORTS_ExistsChangeNoticePullDownPerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullUp()
bool PLIB_PORTS_ExistsChangeNoticePullUp (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullUpPerPort()
bool PLIB_PORTS_ExistsChangeNoticePullUpPerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChannelChangeNoticeMethod()
bool PLIB_PORTS_ExistsChannelChangeNoticeMethod (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsLatchRead()
bool PLIB_PORTS_ExistsLatchRead (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinChangeNotice()
bool PLIB_PORTS_ExistsPinChangeNotice (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinChangeNoticePerPort()
bool PLIB_PORTS_ExistsPinChangeNoticePerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinMode()
bool PLIB_PORTS_ExistsPinMode (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinModePerPort()
bool PLIB_PORTS_ExistsPinModePerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsDirection()
bool PLIB_PORTS_ExistsPortsDirection (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsOpenDrain()
bool PLIB_PORTS_ExistsPortsOpenDrain (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsRead()
bool PLIB_PORTS_ExistsPortsRead (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsWrite()
bool PLIB_PORTS_ExistsPortsWrite (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsRemapInput()
bool PLIB_PORTS_ExistsRemapInput (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsRemapOutput()
bool PLIB_PORTS_ExistsRemapOutput (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsSlewRateControl()
bool PLIB_PORTS_ExistsSlewRateControl (PORTS_MODULE_ID index)
PLIB_PORTS_OpenDrainDisable()
void PLIB_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_OpenDrainEnable()
void PLIB_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_PinChangeNoticeDisable()
void PLIB_PORTS_PinChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_PinChangeNoticeEdgeHasOccurred()
bool PLIB_PORTS_PinChangeNoticeEdgeHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinChangeNoticeEdgeIsEnabled()
bool PLIB_PORTS_PinChangeNoticeEdgeIsEnabled (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_CHANGE_NOTICE_EDGE cnEdgeType)
PLIB_PORTS_PinChangeNoticeEnable()
void PLIB_PORTS_PinChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_PinChangeNoticePerPortDisable()
void PLIB_PORTS_PinChangeNoticePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinChangeNoticePerPortEnable()
void PLIB_PORTS_PinChangeNoticePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinClear()
void PLIB_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinDirectionInputSet()
void PLIB_PORTS_PinDirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinDirectionOutputSet()
void PLIB_PORTS_PinDirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinGet()
bool PLIB_PORTS_PinGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinGetLatched()
bool PLIB_PORTS_PinGetLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinModePerPortSelect()
void PLIB_PORTS_PinModePerPortSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_MODE mode)
PLIB_PORTS_PinModeSelect()
void PLIB_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
PLIB_PORTS_PinOpenDrainDisable()
void PLIB_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinOpenDrainEnable()
void PLIB_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinSet()
void PLIB_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinSlewRateGet()
PORTS_PIN_SLEW_RATE PLIB_PORTS_PinSlewRateGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinToggle()
void PLIB_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinWrite()
void PLIB_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
PLIB_PORTS_Read()
PORTS_DATA_TYPE PLIB_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ReadLatched()
PORTS_DATA_TYPE PLIB_PORTS_ReadLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_RemapInput()
void PLIB_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION inputFunction, PORTS_REMAP_INPUT_PIN remapInputPin)
PLIB_PORTS_RemapOutput()
void PLIB_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION outputFunction, PORTS_REMAP_OUTPUT_PIN remapOutputPin)
PLIB_PORTS_Set()
void PLIB_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
PLIB_PORTS_Toggle()
void PLIB_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
PLIB_PORTS_Write()
void PLIB_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
PLIB_SPI_AudioCommunicationWidthSelect()
void PLIB_SPI_AudioCommunicationWidthSelect (SPI_MODULE_ID index, SPI_AUDIO_COMMUNICATION_WIDTH mode)
PLIB_SPI_AudioErrorDisable()
void PLIB_SPI_AudioErrorDisable (SPI_MODULE_ID index, SPI_AUDIO_ERROR error)
PLIB_SPI_AudioErrorEnable()
void PLIB_SPI_AudioErrorEnable (SPI_MODULE_ID index, SPI_AUDIO_ERROR error)
PLIB_SPI_AudioProtocolDisable()
void PLIB_SPI_AudioProtocolDisable (SPI_MODULE_ID index)
PLIB_SPI_AudioProtocolEnable()
void PLIB_SPI_AudioProtocolEnable (SPI_MODULE_ID index)
PLIB_SPI_AudioProtocolModeSelect()
void PLIB_SPI_AudioProtocolModeSelect (SPI_MODULE_ID index, SPI_AUDIO_PROTOCOL mode)
PLIB_SPI_AudioTransmitModeSelect()
void PLIB_SPI_AudioTransmitModeSelect (SPI_MODULE_ID index, SPI_AUDIO_TRANSMIT_MODE mode)
PLIB_SPI_BaudRateClockSelect()
void PLIB_SPI_BaudRateClockSelect (SPI_MODULE_ID index, SPI_BAUD_RATE_CLOCK type)
PLIB_SPI_BaudRateSet()
void PLIB_SPI_BaudRateSet (SPI_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
PLIB_SPI_BufferAddressGet()
void* PLIB_SPI_BufferAddressGet (SPI_MODULE_ID index)
PLIB_SPI_BufferClear()
void PLIB_SPI_BufferClear (SPI_MODULE_ID index)
PLIB_SPI_BufferRead()
uint8_t PLIB_SPI_BufferRead (SPI_MODULE_ID index)
PLIB_SPI_BufferRead16bit()
uint16_t PLIB_SPI_BufferRead16bit (SPI_MODULE_ID index)
PLIB_SPI_BufferRead32bit()
uint32_t PLIB_SPI_BufferRead32bit (SPI_MODULE_ID index)
PLIB_SPI_BufferWrite()
void PLIB_SPI_BufferWrite (SPI_MODULE_ID index, uint8_t data)
PLIB_SPI_BufferWrite16bit()
void PLIB_SPI_BufferWrite16bit (SPI_MODULE_ID index, uint16_t data)
PLIB_SPI_BufferWrite32bit()
void PLIB_SPI_BufferWrite32bit (SPI_MODULE_ID index, uint32_t data)
PLIB_SPI_ClockPolaritySelect()
void PLIB_SPI_ClockPolaritySelect (SPI_MODULE_ID index, SPI_CLOCK_POLARITY polarity)
PLIB_SPI_CommunicationWidthSelect()
void PLIB_SPI_CommunicationWidthSelect (SPI_MODULE_ID index, SPI_COMMUNICATION_WIDTH width)
PLIB_SPI_Disable()
void PLIB_SPI_Disable (SPI_MODULE_ID index)
PLIB_SPI_Enable()
void PLIB_SPI_Enable (SPI_MODULE_ID index)
PLIB_SPI_ErrorInterruptDisable()
void PLIB_SPI_ErrorInterruptDisable (SPI_MODULE_ID index, SPI_ERROR_INTERRUPT error)
PLIB_SPI_ErrorInterruptEnable()
void PLIB_SPI_ErrorInterruptEnable (SPI_MODULE_ID index, SPI_ERROR_INTERRUPT error)
PLIB_SPI_Exists16bitBuffer()
bool PLIB_SPI_Exists16bitBuffer (SPI_MODULE_ID index)
PLIB_SPI_Exists32bitBuffer()
bool PLIB_SPI_Exists32bitBuffer (SPI_MODULE_ID index)
PLIB_SPI_ExistsAudioCommunicationWidth()
bool PLIB_SPI_ExistsAudioCommunicationWidth (SPI_MODULE_ID index)
PLIB_SPI_ExistsAudioErrorControl()
bool PLIB_SPI_ExistsAudioErrorControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsAudioProtocolControl()
bool PLIB_SPI_ExistsAudioProtocolControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsAudioProtocolMode()
bool PLIB_SPI_ExistsAudioProtocolMode (SPI_MODULE_ID index)
PLIB_SPI_ExistsAudioTransmitMode()
bool PLIB_SPI_ExistsAudioTransmitMode (SPI_MODULE_ID index)
PLIB_SPI_ExistsBaudRate()
bool PLIB_SPI_ExistsBaudRate (SPI_MODULE_ID index)
PLIB_SPI_ExistsBaudRateClock()
bool PLIB_SPI_ExistsBaudRateClock (SPI_MODULE_ID index)
PLIB_SPI_ExistsBuffer()
bool PLIB_SPI_ExistsBuffer (SPI_MODULE_ID index)
PLIB_SPI_ExistsBusStatus()
bool PLIB_SPI_ExistsBusStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsClockPolarity()
bool PLIB_SPI_ExistsClockPolarity (SPI_MODULE_ID index)
PLIB_SPI_ExistsCommunicationWidth()
bool PLIB_SPI_ExistsCommunicationWidth (SPI_MODULE_ID index)
PLIB_SPI_ExistsEnableControl()
bool PLIB_SPI_ExistsEnableControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsErrorInterruptControl()
bool PLIB_SPI_ExistsErrorInterruptControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsFIFOControl()
bool PLIB_SPI_ExistsFIFOControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsFIFOCount()
bool PLIB_SPI_ExistsFIFOCount (SPI_MODULE_ID index)
PLIB_SPI_ExistsFIFOInterruptMode()
bool PLIB_SPI_ExistsFIFOInterruptMode (SPI_MODULE_ID index)
PLIB_SPI_ExistsFIFOShiftRegisterEmptyStatus()
bool PLIB_SPI_ExistsFIFOShiftRegisterEmptyStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsFramedCommunication()
bool PLIB_SPI_ExistsFramedCommunication (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameErrorStatus()
bool PLIB_SPI_ExistsFrameErrorStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameSyncPulseCounter()
bool PLIB_SPI_ExistsFrameSyncPulseCounter (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameSyncPulseDirection()
bool PLIB_SPI_ExistsFrameSyncPulseDirection (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameSyncPulseEdge()
bool PLIB_SPI_ExistsFrameSyncPulseEdge (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameSyncPulsePolarity()
bool PLIB_SPI_ExistsFrameSyncPulsePolarity (SPI_MODULE_ID index)
PLIB_SPI_ExistsFrameSyncPulseWidth()
bool PLIB_SPI_ExistsFrameSyncPulseWidth (SPI_MODULE_ID index)
PLIB_SPI_ExistsInputSamplePhase()
bool PLIB_SPI_ExistsInputSamplePhase (SPI_MODULE_ID index)
PLIB_SPI_ExistsMasterControl()
bool PLIB_SPI_ExistsMasterControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsOutputDataPhase()
bool PLIB_SPI_ExistsOutputDataPhase (SPI_MODULE_ID index)
PLIB_SPI_ExistsPinControl()
bool PLIB_SPI_ExistsPinControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsReadDataSignStatus()
bool PLIB_SPI_ExistsReadDataSignStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsReceiveBufferStatus()
bool PLIB_SPI_ExistsReceiveBufferStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsReceiveFIFOStatus()
bool PLIB_SPI_ExistsReceiveFIFOStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsReceiverOverflow()
bool PLIB_SPI_ExistsReceiverOverflow (SPI_MODULE_ID index)
PLIB_SPI_ExistsSlaveSelectControl()
bool PLIB_SPI_ExistsSlaveSelectControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsStopInIdleControl()
bool PLIB_SPI_ExistsStopInIdleControl (SPI_MODULE_ID index)
PLIB_SPI_ExistsTransmitBufferEmptyStatus()
bool PLIB_SPI_ExistsTransmitBufferEmptyStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsTransmitBufferFullStatus()
bool PLIB_SPI_ExistsTransmitBufferFullStatus (SPI_MODULE_ID index)
PLIB_SPI_ExistsTransmitUnderRunStatus()
bool PLIB_SPI_ExistsTransmitUnderRunStatus (SPI_MODULE_ID index)
PLIB_SPI_FIFOCountGet()
uint8_t PLIB_SPI_FIFOCountGet (SPI_MODULE_ID index, SPI_FIFO_TYPE type)
PLIB_SPI_FIFODisable()
void PLIB_SPI_FIFODisable (SPI_MODULE_ID index)
PLIB_SPI_FIFOEnable()
void PLIB_SPI_FIFOEnable (SPI_MODULE_ID index)
PLIB_SPI_FIFOInterruptModeSelect()
void PLIB_SPI_FIFOInterruptModeSelect (SPI_MODULE_ID index, SPI_FIFO_INTERRUPT mode)
PLIB_SPI_FIFOShiftRegisterIsEmpty()
bool PLIB_SPI_FIFOShiftRegisterIsEmpty (SPI_MODULE_ID index)
PLIB_SPI_FramedCommunicationDisable()
void PLIB_SPI_FramedCommunicationDisable (SPI_MODULE_ID index)
PLIB_SPI_FramedCommunicationEnable()
void PLIB_SPI_FramedCommunicationEnable (SPI_MODULE_ID index)
PLIB_SPI_FrameErrorStatusClear()
void PLIB_SPI_FrameErrorStatusClear (SPI_MODULE_ID index)
PLIB_SPI_FrameErrorStatusGet()
bool PLIB_SPI_FrameErrorStatusGet (SPI_MODULE_ID index)
PLIB_SPI_FrameSyncPulseCounterSelect()
void PLIB_SPI_FrameSyncPulseCounterSelect (SPI_MODULE_ID index, SPI_FRAME_SYNC_PULSE pulse)
PLIB_SPI_FrameSyncPulseDirectionSelect()
void PLIB_SPI_FrameSyncPulseDirectionSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_DIRECTION direction)
PLIB_SPI_FrameSyncPulseEdgeSelect()
void PLIB_SPI_FrameSyncPulseEdgeSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_EDGE edge)
PLIB_SPI_FrameSyncPulsePolaritySelect()
void PLIB_SPI_FrameSyncPulsePolaritySelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_POLARITY polarity)
PLIB_SPI_FrameSyncPulseWidthSelect()
void PLIB_SPI_FrameSyncPulseWidthSelect (SPI_MODULE_ID index, SPI_FRAME_PULSE_WIDTH width)
PLIB_SPI_InputSamplePhaseSelect()
void PLIB_SPI_InputSamplePhaseSelect (SPI_MODULE_ID index, SPI_INPUT_SAMPLING_PHASE phase)
PLIB_SPI_IsBusy()
bool PLIB_SPI_IsBusy (SPI_MODULE_ID index)
PLIB_SPI_MasterEnable()
void PLIB_SPI_MasterEnable (SPI_MODULE_ID index)
PLIB_SPI_OutputDataPhaseSelect()
void PLIB_SPI_OutputDataPhaseSelect (SPI_MODULE_ID index, SPI_OUTPUT_DATA_PHASE phase)
PLIB_SPI_PinDisable()
void PLIB_SPI_PinDisable (SPI_MODULE_ID index, SPI_PIN pin)
PLIB_SPI_PinEnable()
void PLIB_SPI_PinEnable (SPI_MODULE_ID index, SPI_PIN pin)
PLIB_SPI_ReadDataIsSignExtended()
bool PLIB_SPI_ReadDataIsSignExtended (SPI_MODULE_ID index)
PLIB_SPI_ReceiverBufferIsFull()
bool PLIB_SPI_ReceiverBufferIsFull (SPI_MODULE_ID index)
PLIB_SPI_ReceiverFIFOIsEmpty()
bool PLIB_SPI_ReceiverFIFOIsEmpty (SPI_MODULE_ID index)
PLIB_SPI_ReceiverHasOverflowed()
bool PLIB_SPI_ReceiverHasOverflowed (SPI_MODULE_ID index)
PLIB_SPI_ReceiverOverflowClear()
void PLIB_SPI_ReceiverOverflowClear (SPI_MODULE_ID index)
PLIB_SPI_SlaveEnable()
void PLIB_SPI_SlaveEnable (SPI_MODULE_ID index)
PLIB_SPI_SlaveSelectDisable()
void PLIB_SPI_SlaveSelectDisable (SPI_MODULE_ID index)
PLIB_SPI_SlaveSelectEnable()
void PLIB_SPI_SlaveSelectEnable (SPI_MODULE_ID index)
PLIB_SPI_StopInIdleDisable()
void PLIB_SPI_StopInIdleDisable (SPI_MODULE_ID index)
PLIB_SPI_StopInIdleEnable()
void PLIB_SPI_StopInIdleEnable (SPI_MODULE_ID index)
PLIB_SPI_TransmitBufferIsEmpty()
bool PLIB_SPI_TransmitBufferIsEmpty (SPI_MODULE_ID index)
PLIB_SPI_TransmitBufferIsFull()
bool PLIB_SPI_TransmitBufferIsFull (SPI_MODULE_ID index)
PLIB_SPI_TransmitUnderRunStatusClear()
void PLIB_SPI_TransmitUnderRunStatusClear (SPI_MODULE_ID index)
PLIB_SPI_TransmitUnderRunStatusGet()
bool PLIB_SPI_TransmitUnderRunStatusGet (SPI_MODULE_ID index)
PLIB_USART_AddressGet()
uint8_t PLIB_USART_AddressGet (USART_MODULE_ID index)
PLIB_USART_AddressMaskGet()
uint8_t PLIB_USART_AddressMaskGet (USART_MODULE_ID index)
PLIB_USART_AddressMaskSet()
void PLIB_USART_AddressMaskSet (USART_MODULE_ID index, uint8_t mask)
PLIB_USART_AddressSet()
void PLIB_USART_AddressSet (USART_MODULE_ID index, uint8_t address)
PLIB_USART_BaudRateAutoDetectEnable()
void PLIB_USART_BaudRateAutoDetectEnable (USART_MODULE_ID index)
PLIB_USART_BaudRateAutoDetectIsComplete()
bool PLIB_USART_BaudRateAutoDetectIsComplete (USART_MODULE_ID index)
PLIB_USART_BaudRateGet()
uint32_t PLIB_USART_BaudRateGet (USART_MODULE_ID index, int32_t clockFrequency)
PLIB_USART_BaudRateHighDisable()
void PLIB_USART_BaudRateHighDisable (USART_MODULE_ID index)
PLIB_USART_BaudRateHighEnable()
void PLIB_USART_BaudRateHighEnable (USART_MODULE_ID index)
PLIB_USART_BaudRateHighSet()
void PLIB_USART_BaudRateHighSet (USART_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
PLIB_USART_BaudRateSet()
void PLIB_USART_BaudRateSet (USART_MODULE_ID index, uint32_t clockFrequency, uint32_t baudRate)
PLIB_USART_BaudSetAndEnable()
void PLIB_USART_BaudSetAndEnable (USART_MODULE_ID index, uint32_t systemClock, uint32_t baud)
PLIB_USART_BRGClockSourceGet()
USART_BRG_CLOCK_SOURCE PLIB_USART_BRGClockSourceGet (USART_MODULE_ID index)
PLIB_USART_BRGClockSourceSelect()
void PLIB_USART_BRGClockSourceSelect (USART_MODULE_ID index, USART_BRG_CLOCK_SOURCE brgClockSource)
PLIB_USART_Disable()
void PLIB_USART_Disable (USART_MODULE_ID index)
PLIB_USART_Enable()
void PLIB_USART_Enable (USART_MODULE_ID index)
PLIB_USART_ErrorsGet()
USART_ERROR PLIB_USART_ErrorsGet (USART_MODULE_ID index)
PLIB_USART_ExistsBaudRate()
bool PLIB_USART_ExistsBaudRate (USART_MODULE_ID index)
PLIB_USART_ExistsBaudRateAutoDetect()
bool PLIB_USART_ExistsBaudRateAutoDetect (USART_MODULE_ID index)
PLIB_USART_ExistsBaudRateHigh()
bool PLIB_USART_ExistsBaudRateHigh (USART_MODULE_ID index)
PLIB_USART_ExistsBRGClockSourceSelect()
bool PLIB_USART_ExistsBRGClockSourceSelect (USART_MODULE_ID index)
PLIB_USART_ExistsEnable()
bool PLIB_USART_ExistsEnable (USART_MODULE_ID index)
PLIB_USART_ExistsHandshakeMode()
bool PLIB_USART_ExistsHandshakeMode (USART_MODULE_ID index)
PLIB_USART_ExistsIrDA()
bool PLIB_USART_ExistsIrDA (USART_MODULE_ID index)
PLIB_USART_ExistsLineControlMode()
bool PLIB_USART_ExistsLineControlMode (USART_MODULE_ID index)
PLIB_USART_ExistsLoopback()
bool PLIB_USART_ExistsLoopback (USART_MODULE_ID index)
PLIB_USART_ExistsModuleBusyStatus()
bool PLIB_USART_ExistsModuleBusyStatus (USART_MODULE_ID index)
PLIB_USART_ExistsOperationMode()
bool PLIB_USART_ExistsOperationMode (USART_MODULE_ID index)
PLIB_USART_ExistsReceiver()
bool PLIB_USART_ExistsReceiver (USART_MODULE_ID index)
PLIB_USART_ExistsReceiver9Bits()
bool PLIB_USART_ExistsReceiver9Bits (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverAddress()
bool PLIB_USART_ExistsReceiverAddress (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverAddressAutoDetect()
bool PLIB_USART_ExistsReceiverAddressAutoDetect (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverAddressDetect()
bool PLIB_USART_ExistsReceiverAddressDetect (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverAddressMask()
bool PLIB_USART_ExistsReceiverAddressMask (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverDataAvailableStatus()
bool PLIB_USART_ExistsReceiverDataAvailableStatus (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverEnable()
bool PLIB_USART_ExistsReceiverEnable (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverFramingErrorStatus()
bool PLIB_USART_ExistsReceiverFramingErrorStatus (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverIdleStateLowEnable()
bool PLIB_USART_ExistsReceiverIdleStateLowEnable (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverIdleStatus()
bool PLIB_USART_ExistsReceiverIdleStatus (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverInterruptMode()
bool PLIB_USART_ExistsReceiverInterruptMode (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverOverrunStatus()
bool PLIB_USART_ExistsReceiverOverrunStatus (USART_MODULE_ID index)
PLIB_USART_ExistsReceiverParityErrorStatus()
bool PLIB_USART_ExistsReceiverParityErrorStatus (USART_MODULE_ID index)
PLIB_USART_ExistsRunInOverflow()
bool PLIB_USART_ExistsRunInOverflow (USART_MODULE_ID index)
PLIB_USART_ExistsRunInSleepMode()
bool PLIB_USART_ExistsRunInSleepMode (USART_MODULE_ID index)
PLIB_USART_ExistsStopInIdle()
bool PLIB_USART_ExistsStopInIdle (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitter()
bool PLIB_USART_ExistsTransmitter (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitter9BitsSend()
bool PLIB_USART_ExistsTransmitter9BitsSend (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterBreak()
bool PLIB_USART_ExistsTransmitterBreak (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterBufferFullStatus()
bool PLIB_USART_ExistsTransmitterBufferFullStatus (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterEmptyStatus()
bool PLIB_USART_ExistsTransmitterEmptyStatus (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterEnable()
bool PLIB_USART_ExistsTransmitterEnable (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterIdleIsLow()
bool PLIB_USART_ExistsTransmitterIdleIsLow (USART_MODULE_ID index)
PLIB_USART_ExistsTransmitterInterruptMode()
bool PLIB_USART_ExistsTransmitterInterruptMode (USART_MODULE_ID index)
PLIB_USART_ExistsWakeOnStart()
bool PLIB_USART_ExistsWakeOnStart (USART_MODULE_ID index)
PLIB_USART_HandshakeModeSelect()
void PLIB_USART_HandshakeModeSelect (USART_MODULE_ID index, USART_HANDSHAKE_MODE handshakeConfig)
PLIB_USART_InitializeModeGeneral()
void PLIB_USART_InitializeModeGeneral (USART_MODULE_ID index, bool autobaud, bool loopBackMode, bool wakeFromSleep, bool irdaMode, bool stopInIdle)
PLIB_USART_InitializeOperation()
void PLIB_USART_InitializeOperation (USART_MODULE_ID index, USART_RECEIVE_INTR_MODE receiveInterruptMode, USART_TRANSMIT_INTR_MODE transmitInterruptMode, USART_OPERATION_MODE operationMode)
PLIB_USART_IrDADisable()
void PLIB_USART_IrDADisable (USART_MODULE_ID index)
PLIB_USART_IrDAEnable()
void PLIB_USART_IrDAEnable (USART_MODULE_ID index)
PLIB_USART_LineControlModeSelect()
void PLIB_USART_LineControlModeSelect (USART_MODULE_ID index, USART_LINECONTROL_MODE dataFlowConfig)
PLIB_USART_LoopbackDisable()
void PLIB_USART_LoopbackDisable (USART_MODULE_ID index)
PLIB_USART_LoopbackEnable()
void PLIB_USART_LoopbackEnable (USART_MODULE_ID index)
PLIB_USART_ModuleIsBusy()
bool PLIB_USART_ModuleIsBusy (USART_MODULE_ID index)
PLIB_USART_OperationModeSelect()
void PLIB_USART_OperationModeSelect (USART_MODULE_ID index, USART_OPERATION_MODE operationmode)
PLIB_USART_Receiver9BitsReceive()
int16_t PLIB_USART_Receiver9BitsReceive (USART_MODULE_ID index)
PLIB_USART_ReceiverAddressAutoDetectDisable()
void PLIB_USART_ReceiverAddressAutoDetectDisable (USART_MODULE_ID index)
PLIB_USART_ReceiverAddressAutoDetectEnable()
void PLIB_USART_ReceiverAddressAutoDetectEnable (USART_MODULE_ID index, int8_t Mask)
PLIB_USART_ReceiverAddressDetectDisable()
void PLIB_USART_ReceiverAddressDetectDisable (USART_MODULE_ID index)
PLIB_USART_ReceiverAddressDetectEnable()
void PLIB_USART_ReceiverAddressDetectEnable (USART_MODULE_ID index)
PLIB_USART_ReceiverAddressGet()
void* PLIB_USART_ReceiverAddressGet (USART_MODULE_ID index)
PLIB_USART_ReceiverAddressIsReceived()
bool PLIB_USART_ReceiverAddressIsReceived (USART_MODULE_ID index)
PLIB_USART_ReceiverByteReceive()
int8_t PLIB_USART_ReceiverByteReceive (USART_MODULE_ID index)
PLIB_USART_ReceiverDataIsAvailable()
bool PLIB_USART_ReceiverDataIsAvailable (USART_MODULE_ID index)
PLIB_USART_ReceiverDisable()
void PLIB_USART_ReceiverDisable (USART_MODULE_ID index)
PLIB_USART_ReceiverEnable()
void PLIB_USART_ReceiverEnable (USART_MODULE_ID index)
PLIB_USART_ReceiverFramingErrorHasOccurred()
bool PLIB_USART_ReceiverFramingErrorHasOccurred (USART_MODULE_ID index)
PLIB_USART_ReceiverIdleStateLowDisable()
void PLIB_USART_ReceiverIdleStateLowDisable (USART_MODULE_ID index)
PLIB_USART_ReceiverIdleStateLowEnable()
void PLIB_USART_ReceiverIdleStateLowEnable (USART_MODULE_ID index)
PLIB_USART_ReceiverInterruptModeSelect()
void PLIB_USART_ReceiverInterruptModeSelect (USART_MODULE_ID index, USART_RECEIVE_INTR_MODE interruptMode)
PLIB_USART_ReceiverIsIdle()
bool PLIB_USART_ReceiverIsIdle (USART_MODULE_ID index)
PLIB_USART_ReceiverOverrunErrorClear()
void PLIB_USART_ReceiverOverrunErrorClear (USART_MODULE_ID index)
PLIB_USART_ReceiverOverrunHasOccurred()
bool PLIB_USART_ReceiverOverrunHasOccurred (USART_MODULE_ID index)
PLIB_USART_ReceiverParityErrorHasOccurred()
bool PLIB_USART_ReceiverParityErrorHasOccurred (USART_MODULE_ID index)
PLIB_USART_RunInOverflowDisable()
void PLIB_USART_RunInOverflowDisable (USART_MODULE_ID index)
PLIB_USART_RunInOverflowEnable()
void PLIB_USART_RunInOverflowEnable (USART_MODULE_ID index)
PLIB_USART_RunInOverflowIsEnabled()
bool PLIB_USART_RunInOverflowIsEnabled (USART_MODULE_ID index)
PLIB_USART_RunInSleepModeDisable()
void PLIB_USART_RunInSleepModeDisable (USART_MODULE_ID index)
PLIB_USART_RunInSleepModeEnable()
void PLIB_USART_RunInSleepModeEnable (USART_MODULE_ID index)
PLIB_USART_RunInSleepModeIsEnabled()
bool PLIB_USART_RunInSleepModeIsEnabled (USART_MODULE_ID index)
PLIB_USART_StopInIdleDisable()
void PLIB_USART_StopInIdleDisable (USART_MODULE_ID index)
PLIB_USART_StopInIdleEnable()
void PLIB_USART_StopInIdleEnable (USART_MODULE_ID index)
PLIB_USART_Transmitter9BitsSend()
void PLIB_USART_Transmitter9BitsSend (USART_MODULE_ID index, int8_t data, bool Bit9th)
PLIB_USART_TransmitterAddressGet()
void* PLIB_USART_TransmitterAddressGet (USART_MODULE_ID index)
PLIB_USART_TransmitterBreakSend()
void PLIB_USART_TransmitterBreakSend (USART_MODULE_ID index)
PLIB_USART_TransmitterBreakSendIsComplete()
bool PLIB_USART_TransmitterBreakSendIsComplete (USART_MODULE_ID index)
PLIB_USART_TransmitterBufferIsFull()
bool PLIB_USART_TransmitterBufferIsFull (USART_MODULE_ID index)
PLIB_USART_TransmitterByteSend()
void PLIB_USART_TransmitterByteSend (USART_MODULE_ID index, int8_t data)
Referenced by WriteUART().
PLIB_USART_TransmitterDisable()
void PLIB_USART_TransmitterDisable (USART_MODULE_ID index)
PLIB_USART_TransmitterEnable()
void PLIB_USART_TransmitterEnable (USART_MODULE_ID index)
PLIB_USART_TransmitterIdleIsLowDisable()
void PLIB_USART_TransmitterIdleIsLowDisable (USART_MODULE_ID index)
PLIB_USART_TransmitterIdleIsLowEnable()
void PLIB_USART_TransmitterIdleIsLowEnable (USART_MODULE_ID index)
PLIB_USART_TransmitterInterruptModeSelect()
void PLIB_USART_TransmitterInterruptModeSelect (USART_MODULE_ID index, USART_TRANSMIT_INTR_MODE fifolevel)
PLIB_USART_TransmitterIsEmpty()
bool PLIB_USART_TransmitterIsEmpty (USART_MODULE_ID index)
Referenced by WriteUART().
PLIB_USART_WakeOnStartDisable()
void PLIB_USART_WakeOnStartDisable (USART_MODULE_ID index)
PLIB_USART_WakeOnStartEnable()
void PLIB_USART_WakeOnStartEnable (USART_MODULE_ID index)
PLIB_USART_WakeOnStartIsEnabled()
bool PLIB_USART_WakeOnStartIsEnabled (USART_MODULE_ID index)
qqbmsoutput()
static void qqbmsoutput (FILEPOINT char * s, unsigned int i) static
Definition at line 28904 of file inszt_UART.c.
qqoutput()
static void qqoutput (FILEPOINT char * s, int i) static
Definition at line 28745 of file inszt_UART.c.
qqoutput0()
static void qqoutput0 (FILEPOINT char * s) static
Definition at line 28758 of file inszt_UART.c.
qqoutput2()
static void qqoutput2 (FILEPOINT char * s, int i, int j) static
Definition at line 28766 of file inszt_UART.c.
qqoutput3()
static void qqoutput3 (FILEPOINT char * s, int i, int j, int k) static
Definition at line 28775 of file inszt_UART.c.
qqoutput4()
static void qqoutput4 (FILEPOINT char * s, int i, int j, int k, int l) static
Definition at line 28784 of file inszt_UART.c.
qqpopulate_array_fcn_ptrQQ()
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
Definition at line 157 of file inszt_main.c.
Referenced by UART_71zqendz().
qqqbitmapreset() [1/2]
static void qqqbitmapreset (qqnull_params) static
Referenced by UART_71zqendz().
qqqbitmapreset() [2/2]
static void qqqbitmapreset () static
Definition at line 28816 of file inszt_UART.c.
qqqqinitialise()
static void qqqqinitialise (int ii) static
Definition at line 28799 of file inszt_UART.c.
Referenced by UART_71zqqzqz1().
qqqupload()
static void qqqupload (qqnull_params) static
Definition at line 28929 of file inszt_UART.c.
Referenced by UART_71zqendz().
ReadUART()
static void ReadUART (void) static
Function: static void ReadUART(void) Summary: This function reads a byte from the UART when data is received from the host. Description: This function reads a byte from the UART when data is received from the host. It puts the received byte into the RxFifo for later use.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: ReadUART()
Function: static void ReadUART(void) Summary: This function reads a byte of data from the UART and transfers it to the RxFifo. Remarks: Refer to the UART.h interface header for function usage details.
< Temporary placeholder for byte data from the host.
Definition at line 28553 of file inszt_UART.c.
SYS_DEBUG_Deinitialize()
void SYS_DEBUG_Deinitialize (SYS_MODULE_OBJ object)
SYS_DEBUG_ErrorLevelGet()
SYS_ERROR_LEVEL SYS_DEBUG_ErrorLevelGet (void)
SYS_DEBUG_ErrorLevelSet()
void SYS_DEBUG_ErrorLevelSet (SYS_ERROR_LEVEL level)
SYS_DEBUG_Initialize()
SYS_MODULE_OBJ SYS_DEBUG_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT *const init)
SYS_DEBUG_Message()
void SYS_DEBUG_Message (const char * message)
SYS_DEBUG_Print()
void SYS_DEBUG_Print (const char * format, ...)
SYS_DEBUG_Reinitialize()
void SYS_DEBUG_Reinitialize (SYS_MODULE_OBJ object, const SYS_MODULE_INIT *const init)
SYS_DEBUG_Status()
SYS_STATUS SYS_DEBUG_Status (SYS_MODULE_OBJ object)
SYS_DEBUG_Tasks()
void SYS_DEBUG_Tasks (SYS_MODULE_OBJ object)
SYS_DMA_ChannelAbortEventSet()
void SYS_DMA_ChannelAbortEventSet (SYS_DMA_CHANNEL_HANDLE handle, DMA_TRIGGER_SOURCE eventSrc)
SYS_DMA_ChannelAllocate()
SYS_DMA_CHANNEL_HANDLE SYS_DMA_ChannelAllocate (DMA_CHANNEL channel)
SYS_DMA_ChannelCRCGet()
uint32_t SYS_DMA_ChannelCRCGet (void)
SYS_DMA_ChannelCRCSet()
void SYS_DMA_ChannelCRCSet (SYS_DMA_CHANNEL_HANDLE handle, SYS_DMA_CHANNEL_OPERATION_MODE_CRC crc)
SYS_DMA_ChannelDestinationTransferredSizeGet()
size_t SYS_DMA_ChannelDestinationTransferredSizeGet (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelDisable()
void SYS_DMA_ChannelDisable (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelEnable()
void SYS_DMA_ChannelEnable (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelErrorGet()
SYS_DMA_ERROR SYS_DMA_ChannelErrorGet (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelForceAbort()
void SYS_DMA_ChannelForceAbort (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelForceStart()
void SYS_DMA_ChannelForceStart (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelIsBusy()
bool SYS_DMA_ChannelIsBusy (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelRelease()
void SYS_DMA_ChannelRelease (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelResume()
void SYS_DMA_ChannelResume (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelSetup()
void SYS_DMA_ChannelSetup (SYS_DMA_CHANNEL_HANDLE handle, SYS_DMA_CHANNEL_OP_MODE modeEnable, DMA_TRIGGER_SOURCE eventSrc)
SYS_DMA_ChannelSetupMatchAbortMode()
void SYS_DMA_ChannelSetupMatchAbortMode (SYS_DMA_CHANNEL_HANDLE handle, uint16_t pattern, DMA_PATTERN_LENGTH length, SYS_DMA_CHANNEL_IGNORE_MATCH ignore, uint8_t ignorePattern)
SYS_DMA_ChannelSourceTransferredSizeGet()
size_t SYS_DMA_ChannelSourceTransferredSizeGet (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelSuspend()
void SYS_DMA_ChannelSuspend (SYS_DMA_CHANNEL_HANDLE handle)
SYS_DMA_ChannelTransferAdd()
void SYS_DMA_ChannelTransferAdd (SYS_DMA_CHANNEL_HANDLE handle, const void * srcAddr, size_t srcSize, const void * destAddr, size_t destSize, size_t cellSize)
SYS_DMA_ChannelTransferEventHandlerSet()
void SYS_DMA_ChannelTransferEventHandlerSet (SYS_DMA_CHANNEL_HANDLE handle, const SYS_DMA_CHANNEL_TRANSFER_EVENT_HANDLER eventHandler, const uintptr_t contextHandle)
SYS_DMA_ChannelTransferSet()
void SYS_DMA_ChannelTransferSet (SYS_DMA_CHANNEL_HANDLE handle, const void * srcAddr, size_t srcSize, const void * destAddr, size_t destSize, size_t cellSize)
SYS_DMA_Initialize()
SYS_MODULE_OBJ SYS_DMA_Initialize (const SYS_MODULE_INIT *const init)
SYS_DMA_IsBusy()
bool SYS_DMA_IsBusy (void)
SYS_DMA_Resume()
void SYS_DMA_Resume (void)
SYS_DMA_Suspend()
void SYS_DMA_Suspend (void)
SYS_DMA_Tasks()
void SYS_DMA_Tasks (SYS_MODULE_OBJ object, DMA_CHANNEL activeChannel)
SYS_DMA_TasksError()
void SYS_DMA_TasksError (SYS_MODULE_OBJ object)
SYS_DMA_TasksErrorISR()
void SYS_DMA_TasksErrorISR (SYS_MODULE_OBJ object, DMA_CHANNEL activeChannel)
SYS_PORTS_ChangeNotificationDisable()
void SYS_PORTS_ChangeNotificationDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_ChangeNotificationEnable()
void SYS_PORTS_ChangeNotificationEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum, SYS_PORTS_PULLUP_PULLDOWN_STATUS value)
SYS_PORTS_ChangeNotificationGlobalDisable()
void SYS_PORTS_ChangeNotificationGlobalDisable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationGlobalEnable()
void SYS_PORTS_ChangeNotificationGlobalEnable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationInIdleModeDisable()
void SYS_PORTS_ChangeNotificationInIdleModeDisable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationInIdleModeEnable()
void SYS_PORTS_ChangeNotificationInIdleModeEnable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationPullUpDisable()
void SYS_PORTS_ChangeNotificationPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_ChangeNotificationPullUpEnable()
void SYS_PORTS_ChangeNotificationPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_Clear()
void SYS_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
SYS_PORTS_DirectionGet()
PORTS_DATA_MASK SYS_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_DirectionSelect()
void SYS_PORTS_DirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_Initialize()
void SYS_PORTS_Initialize ()
SYS_PORTS_InterruptEnable()
void SYS_PORTS_InterruptEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_INTERRUPT_TYPE pinInterruptType)
SYS_PORTS_InterruptStatusGet()
PORTS_DATA_TYPE SYS_PORTS_InterruptStatusGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_LatchedGet()
PORTS_DATA_TYPE SYS_PORTS_LatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_OpenDrainDisable()
void SYS_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_OpenDrainEnable()
void SYS_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_PinClear()
void SYS_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinDirectionSelect()
void SYS_PORTS_PinDirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinLatchedGet()
bool SYS_PORTS_PinLatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinModeSelect()
void SYS_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
SYS_PORTS_PinOpenDrainDisable()
void SYS_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinOpenDrainEnable()
void SYS_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullDownDisable()
void SYS_PORTS_PinPullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullDownEnable()
void SYS_PORTS_PinPullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullUpDisable()
void SYS_PORTS_PinPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullUpEnable()
void SYS_PORTS_PinPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinRead()
bool SYS_PORTS_PinRead (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinSet()
void SYS_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinToggle()
void SYS_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinWrite()
void SYS_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
SYS_PORTS_Read()
PORTS_DATA_TYPE SYS_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_RemapInput()
void SYS_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION function, PORTS_REMAP_INPUT_PIN remapPin)
SYS_PORTS_RemapOutput()
void SYS_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION function, PORTS_REMAP_OUTPUT_PIN remapPin)
SYS_PORTS_Set()
void SYS_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
SYS_PORTS_Toggle()
void SYS_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
SYS_PORTS_Write()
void SYS_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
UART_71zqendz()
static int UART_71zqendz (int qqqi) static
Definition at line 28867 of file inszt_UART.c.
Referenced by DRV_TMR0_Close(), DRV_TMR0_DeInitialize(), DRV_TMR0_Open(), DRV_TMR0_OperationModeGet(), DRV_TMR0_Status(), DRV_TMR0_Tasks(), DRV_TMR1_Close(), DRV_TMR1_DeInitialize(), DRV_TMR1_Open(), DRV_TMR1_OperationModeGet(), DRV_TMR1_Status(), DRV_TMR1_Tasks(), DRV_TMR2_Close(), DRV_TMR2_DeInitialize(), DRV_TMR2_Open(), DRV_TMR2_OperationModeGet(), DRV_TMR2_Status(), DRV_TMR2_Tasks(), DRV_TMR3_Close(), DRV_TMR3_DeInitialize(), DRV_TMR3_Open(), DRV_TMR3_OperationModeGet(), DRV_TMR3_Status(), DRV_TMR3_Tasks(), DRV_TMR4_Close(), DRV_TMR4_DeInitialize(), DRV_TMR4_Open(), DRV_TMR4_OperationModeGet(), DRV_TMR4_Status(), DRV_TMR4_Tasks(), ReadUART(), UART_71zqzqzq(), UART_Tasks(), and WriteUART().
UART_71zqqzqz()
static int UART_71zqqzqz (qqnull_params) static
Definition at line 28832 of file inszt_UART.c.
UART_71zqqzqz1()
static int UART_71zqqzqz1 (qqnull_params) static
Definition at line 28852 of file inszt_UART.c.
UART_71zqzqzq()
static int UART_71zqzqzq (int qqqi) static
Definition at line 28952 of file inszt_UART.c.
UART_71zscanf()
static int UART_71zscanf (char * qqscan_str) static
Definition at line 28698 of file inszt_UART.c.
UART_Tasks()
void UART_Tasks (void)
Function:
void UART_Tasks(void) Summary: UART_Tasks function Description: This routine is the UART_Tasks function. It defines the UART_Tasks state machine and core logic. This machine is used to send and receive data from the host. Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this. Parameters: None. Returns: None. Remarks: This routine must be called from the APP_Tasks() routine. Example: UART_Tasks()
Definition at line 28419 of file inszt_UART.c.
Valid_Command()
bool Valid_Command (uchar8_t msg)
Function: bool Valid_Command(uchar8_t msg) Summary: This function compares the received command(first byte)and compares it to a list of correct commands. Description: This function compares the received command(first byte)and compares it to a list of correct commands. If there is a match, the rest of the transmission is received for processing. Used in the ValidateComm function in commmodule.c
Precondition: None. Parameters: uchar8_t msg - The one byte command to compare. Returns bool ans - true if command is valid.
Remarks None.
Example: Valid_Command(command)
Function: bool GetDepthStatus(void)
Summary: Function to enable/disable the FIRE Switch. SDS Warrior controls this setting. TRUE by default at power up.
Remarks: Refer to the commands.h interface header for function usage details.
Function: bool Valid_Command(uchar8_t msg)
Summary: Function receives a command for validation and returns a true if it is a valid command.
Remarks: Refer to the commands.h interface header for function usage details.
Function: bool Valid_Command(uchar8_t msg) Summary: Function receives a command for validation and returns a true if it is a valid command. Remarks: Refer to the commands.h interface header for function usage details.
Function: bool Valid_Command(uchar8_t msg) Summary: This function compares the received command(first byte)and compares it to a list of correct commands. Description: This function compares the received command(first byte)and compares it to a list of correct commands. If there is a match, the rest of the transmission is received for processing. Used in the ValidateComm function in commmodule.c
Precondition: None. Parameters: uchar8_t msg - The one byte command to compare. Returns bool ans - true if command is valid.
Remarks None.
Example: Valid_Command(command)
Function: bool Valid_Command(uchar8_t msg) Summary: Function receives a command for validation and returns a true if it is a valid command. Remarks: Refer to the commands.h interface header for function usage details.
Definition at line 1111 of file commands.c.
ValidateComm()
static void ValidateComm (void) static
Function: static void ValidateComm(void) Summary: This function reads the battery voltage, temperature and remaining capacity based on the command given to the function Description: Description: This task handles reading messages from Receive Queue (RxQ Fifo) and processes them. It looks for a valid command & upon finding it puts the remainder into the Command buffer for processing.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: void ValidateComm()
WriteUART()
static void WriteUART (void) static
Function: static void WriteUART(void) Summary: This function transfers a byte to the host. Description: This function transfers a byte to the host. A byte is transferred from the TxFifo to the UART for transmission to the host. The baud rate is 115200,N-8-1. Once the required number of bytes are transferred, a flag is set to notify the UART_Tasks machine to look for a another transmission from the host.
Precondition: None. Parameters: None. Returns None.
Remarks None.
Example: WriteUART()
Definition at line 28597 of file inszt_UART.c.
Referenced by UART_Tasks().
Variable Documentation
APP
APP_DATA APP
Definition at line 73 of file app.c.
bitmapstruct
struct bitmapstruct_t bitmapstruct static
Initial value:
= {
#define ELEMENT(N)
  0}
Referenced by DRV_TMR0_Close(), DRV_TMR0_DeInitialize(), DRV_TMR0_Open(), DRV_TMR0_OperationModeGet(), DRV_TMR0_Status(), DRV_TMR0_Tasks(), DRV_TMR1_Close(), DRV_TMR1_DeInitialize(), DRV_TMR1_Open(), DRV_TMR1_OperationModeGet(), DRV_TMR1_Status(), DRV_TMR1_Tasks(), DRV_TMR2_Close(), DRV_TMR2_DeInitialize(), DRV_TMR2_Open(), DRV_TMR2_OperationModeGet(), DRV_TMR2_Status(), DRV_TMR2_Tasks(), DRV_TMR3_Close(), DRV_TMR3_DeInitialize(), DRV_TMR3_Open(), DRV_TMR3_OperationModeGet(), DRV_TMR3_Status(), DRV_TMR3_Tasks(), DRV_TMR4_Close(), DRV_TMR4_DeInitialize(), DRV_TMR4_Open(), DRV_TMR4_OperationModeGet(), DRV_TMR4_Status(), DRV_TMR4_Tasks(), qqqbitmapreset(), ReadUART(), UART_Tasks(), and WriteUART().
CMD
COMMAND_DATA CMD
Definition at line 196 of file commands.c.
Referenced by UART_Tasks(), and WriteUART().
COMM
COMM_DATA COMM
Definition at line 58 of file commmodule.c.
Referenced by ReadUART(), UART_Tasks(), and WriteUART().
DepthStatus
bool DepthStatus
Definition at line 204 of file commands.c.
gblErrLvl
SYS_ERROR_LEVEL gblErrLvl
qqqaccumupload
ldra_void_function qqqaccumupload[QQQnumfil]
Definition at line 153 of file inszt_main.c.
QQQfcn_ptr_num
int QQQfcn_ptr_num
Definition at line 151 of file inszt_main.c.
Referenced by UART_71zqendz().
QQQfirstmcdc
int QQQfirstmcdc =1 static
Definition at line 76 of file inszt_UART.c.
QQQindicator
int QQQindicator
Definition at line 104 of file inszt_main.c.
qqqlast
int qqqlast = 0 static
Definition at line 28686 of file inszt_UART.c.
Referenced by qqqqinitialise(), qqqupload(), and UART_71zqendz().
qqqqbmselwidth
int qqqqbmselwidth = 32 static
Definition at line 49 of file inszt_UART.c.
Referenced by qqbmsoutput().
qqqqone
char qqqqone[] = "%6d\n" static
Definition at line 28682 of file inszt_UART.c.
qqqstructzzopen
int qqqstructzzopen = 0 static
Definition at line 137 of file inszt_UART.c.
Referenced by UART_71zqendz().
qqqzzglobflag
unsigned char qqqzzglobflag = 0 static
Definition at line 167 of file inszt_UART.c.
Referenced by UART_Tasks().
qqupload_registered
int qqupload_registered
Definition at line 6760 of file inszt_main.c.
RX_FIFO
TFifo RX_FIFO
Definition at line 47 of file fifo.c.
Referenced by ReadUART().
sysObj
SYSTEM_OBJECTS sysObj
tbrun_mode
int tbrun_mode =0 static
Definition at line 97 of file inszt_UART.c.
TX_FIFO
TFifo TX_FIFO
Definition at line 48 of file fifo.c.
Referenced by WriteUART().
U_STATES
UART_STATES U_STATES static
Definition at line 28402 of file inszt_UART.c.
UART
UART_DATA UART
Definition at line 28399 of file inszt_UART.c.
Referenced by ReadUART(), UART_Tasks(), and WriteUART().
UART_71zzopen
int UART_71zzopen
zzfileid
int zzfileid = 71 static
Definition at line 50 of file inszt_UART.c.
Referenced by qqbmsoutput(), and qqoutput().