Panel Interface Board: inszt_main.c File Reference
inszt_main.c File Reference
#include <stddef.h>
#include <stdbool.h>
#include <stdlib.h>
#include "system/common/sys_module.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port_common.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port.c"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port_common.c"
#include "main_68zbelem.def"
#include <stdint.h>
#include "system/common/sys_common.h"
#include "driver/ic/drv_ic.h"
#include "system/devcon/sys_devcon.h"
#include "system/clk/sys_clk.h"
#include "system/int/sys_int.h"
#include "system/tmr/sys_tmr.h"
#include "C:\microchip\harmony\v2_06\apps\Panel_Interface_Board\firmware\src\system_config\default\system_config.h"
#include "peripheral/adchs/plib_adchs.h"
#include "peripheral/int/plib_int.h"
#include "driver/tmr/drv_tmr.h"
#include "peripheral/tmr/plib_tmr.h"
#include "peripheral/pmp/plib_pmp.h"
#include "driver/usart/drv_usart_static.h"
#include "driver/spi/drv_spi.h"
#include "driver/usb/usbhs/drv_usbhs.h"
#include "usb/usb_device.h"
#include "C:\microchip\harmony\v2_06\apps\Panel_Interface_Board\firmware\src\app.h"
#include "classb/classb.h"
Data Structures
struct bitmapstruct_t
struct APP_DATA
struct SYSTEM_OBJECTS
struct ClassB_Test_Flags
Macros
#define QQQdialect MPLABX
#define QQQswitch3
#define qqqMaxBranchDepth 20
#define QQQstructbitmap
#define QQQnumfil 23
#define QQQNOATEXIT
#define QQQUPLOADATEND
#define QQQNOSTDIO
#define QQQBITMAP
#define qqqbitmapint unsigned int
#define QQQMAINFL
#define QQQSINGLEFILE
#define QQQFILEID
#define QQQseparate
#define main_68zzopen zzopen
#define main_68zqqzqz1 zqqzqz1
#define QQQLDRA_PORT
#define FILEPOINT
#define LDRA_VOID_FUNC
#define qqnull_params void
#define QQQ_PROTOTYPE_DEF
#define ELEMENT(N) qqqbitmapint element##N;
#define LASTELEMENT
#define ELEMENT(N) 0,
#define APP_H
#define TEST_H
#define _SYSTEM_CONFIG_H
#define SYS_VERSION_STR "2.06"
#define SYS_VERSION 20600
#define SYS_CLK_FREQ 200000000ul
#define SYS_CLK_BUS_PERIPHERAL_1 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_2 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_3 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_4 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_5 100000000ul
#define SYS_CLK_BUS_PERIPHERAL_7 200000000ul
#define SYS_CLK_BUS_PERIPHERAL_8 100000000ul
#define SYS_CLK_CONFIG_PRIMARY_XTAL 0ul
#define SYS_CLK_CONFIG_SECONDARY_XTAL 32768ul
#define SYS_PORT_A_ANSEL 0x3F00
#define SYS_PORT_A_TRIS 0xFFED
#define SYS_PORT_A_LAT 0x0010
#define SYS_PORT_A_ODC 0x0000
#define SYS_PORT_A_CNPU 0x0020
#define SYS_PORT_A_CNPD 0x0000
#define SYS_PORT_A_CNEN 0x0021
#define SYS_PORT_B_ANSEL 0x10C8
#define SYS_PORT_B_TRIS 0x91FF
#define SYS_PORT_B_LAT 0x0000
#define SYS_PORT_B_ODC 0x0000
#define SYS_PORT_B_CNPU 0x0000
#define SYS_PORT_B_CNPD 0x0000
#define SYS_PORT_B_CNEN 0x0000
#define SYS_PORT_C_ANSEL 0xCFE1
#define SYS_PORT_C_TRIS 0xFFFF
#define SYS_PORT_C_LAT 0x0000
#define SYS_PORT_C_ODC 0x0000
#define SYS_PORT_C_CNPU 0x0000
#define SYS_PORT_C_CNPD 0x0000
#define SYS_PORT_C_CNEN 0x0000
#define SYS_PORT_D_ANSEL 0xC100
#define SYS_PORT_D_TRIS 0xFFFF
#define SYS_PORT_D_LAT 0x0000
#define SYS_PORT_D_ODC 0x0000
#define SYS_PORT_D_CNPU 0x0000
#define SYS_PORT_D_CNPD 0x0000
#define SYS_PORT_D_CNEN 0x0000
#define SYS_PORT_E_ANSEL 0xFC00
#define SYS_PORT_E_TRIS 0xFDFF
#define SYS_PORT_E_LAT 0x0000
#define SYS_PORT_E_ODC 0x0000
#define SYS_PORT_E_CNPU 0x0000
#define SYS_PORT_E_CNPD 0x0000
#define SYS_PORT_E_CNEN 0x0000
#define SYS_PORT_F_ANSEL 0xCEC0
#define SYS_PORT_F_TRIS 0xEFFF
#define SYS_PORT_F_LAT 0x0000
#define SYS_PORT_F_ODC 0x0000
#define SYS_PORT_F_CNPU 0x0000
#define SYS_PORT_F_CNPD 0x0000
#define SYS_PORT_F_CNEN 0x0000
#define SYS_PORT_G_ANSEL 0x8CBC
#define SYS_PORT_G_TRIS 0xDFFF
#define SYS_PORT_G_LAT 0x0000
#define SYS_PORT_G_ODC 0x0000
#define SYS_PORT_G_CNPU 0x0000
#define SYS_PORT_G_CNPD 0x0000
#define SYS_PORT_G_CNEN 0x0000
#define SYS_PORT_H_ANSEL 0x0070
#define SYS_PORT_H_TRIS 0xB3FB
#define SYS_PORT_H_LAT 0x0000
#define SYS_PORT_H_ODC 0x0000
#define SYS_PORT_H_CNPU 0x0000
#define SYS_PORT_H_CNPD 0x0000
#define SYS_PORT_H_CNEN 0x0000
#define SYS_PORT_J_ANSEL 0x0000
#define SYS_PORT_J_TRIS 0x8B7F
#define SYS_PORT_J_LAT 0x0080
#define SYS_PORT_J_ODC 0x0000
#define SYS_PORT_J_CNPU 0x0000
#define SYS_PORT_J_CNPD 0x0000
#define SYS_PORT_J_CNEN 0x0800
#define SYS_PORT_K_ANSEL 0xFF00
#define SYS_PORT_K_TRIS 0xFFFF
#define SYS_PORT_K_LAT 0x0000
#define SYS_PORT_K_ODC 0x0000
#define SYS_PORT_K_CNPU 0x0000
#define SYS_PORT_K_CNPD 0x0000
#define SYS_PORT_K_CNEN 0x0000
#define SYS_INT true
#define SYS_TMR_POWER_STATE SYS_MODULE_POWER_RUN_FULL
#define SYS_TMR_DRIVER_INDEX DRV_TMR_INDEX_0
#define SYS_TMR_MAX_CLIENT_OBJECTS 5
#define SYS_TMR_FREQUENCY 1000
#define SYS_TMR_FREQUENCY_TOLERANCE 10
#define SYS_TMR_UNIT_RESOLUTION 10000
#define SYS_TMR_CLIENT_TOLERANCE 10
#define SYS_TMR_INTERRUPT_NOTIFICATION false
#define DRV_IC_DRIVER_MODE_STATIC
#define USE_8BIT_PMP
#define DRV_SPI_NUMBER_OF_MODULES 6
#define DRV_SPI_POLLED 1
#define DRV_SPI_ISR 0
#define DRV_SPI_MASTER 1
#define DRV_SPI_SLAVE 0
#define DRV_SPI_RM 0
#define DRV_SPI_EBM 1
#define DRV_SPI_8BIT 1
#define DRV_SPI_16BIT 1
#define DRV_SPI_32BIT 0
#define DRV_SPI_DMA 0
#define DRV_SPI_INSTANCES_NUMBER 3
#define DRV_SPI_CLIENTS_NUMBER 3
#define DRV_SPI_ELEMENTS_PER_QUEUE 10
#define DRV_SPI_SPI_ID_IDX0 SPI_ID_1
#define DRV_SPI_TASK_MODE_IDX0 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX0 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX0 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX0 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX0 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX0 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX0 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX0 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX0 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX0 SPI_COMMUNICATION_WIDTH_16BITS
#define DRV_SPI_CLOCK_SOURCE_IDX0 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX0 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX0 1000000
#define DRV_SPI_BUFFER_TYPE_IDX0 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX0 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX0 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0 0xFFFF
#define DRV_SPI_QUEUE_SIZE_IDX0 10
#define DRV_SPI_RESERVED_JOB_IDX0 1
#define DRV_SPI_SPI_ID_IDX1 SPI_ID_2
#define DRV_SPI_TASK_MODE_IDX1 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX1 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX1 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX1 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX1 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX1 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX1 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX1 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX1 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX1 SPI_COMMUNICATION_WIDTH_8BITS
#define DRV_SPI_CLOCK_SOURCE_IDX1 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX1 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX1 1000000
#define DRV_SPI_BUFFER_TYPE_IDX1 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX1 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX1 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1 0xFF
#define DRV_SPI_QUEUE_SIZE_IDX1 10
#define DRV_SPI_RESERVED_JOB_IDX1 1
#define DRV_SPI_SPI_ID_IDX2 SPI_ID_4
#define DRV_SPI_TASK_MODE_IDX2 DRV_SPI_TASK_MODE_POLLED
#define DRV_SPI_SPI_MODE_IDX2 DRV_SPI_MODE_MASTER
#define DRV_SPI_ALLOW_IDLE_RUN_IDX2 false
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX2 DRV_SPI_PROTOCOL_TYPE_FRAMED
#define DRV_SPI_FRAME_SYNC_PULSE_IDX2 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX2 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX2 SPI_FRAME_PULSE_DIRECTION_OUTPUT
#define DRV_SPI_FRAME_PULSE_EDGE_IDX2 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX2 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
#define DRV_SPI_COMM_WIDTH_IDX2 SPI_COMMUNICATION_WIDTH_16BITS
#define DRV_SPI_CLOCK_SOURCE_IDX2 SPI_BAUD_RATE_PBCLK_CLOCK
#define DRV_SPI_SPI_CLOCK_IDX2 CLK_BUS_PERIPHERAL_2
#define DRV_SPI_BAUD_RATE_IDX2 500000
#define DRV_SPI_BUFFER_TYPE_IDX2 DRV_SPI_BUFFER_TYPE_ENHANCED
#define DRV_SPI_CLOCK_MODE_IDX2 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
#define DRV_SPI_INPUT_PHASE_IDX2 SPI_INPUT_SAMPLING_PHASE_AT_END
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2 0x0000
#define DRV_SPI_QUEUE_SIZE_IDX2 10
#define DRV_SPI_RESERVED_JOB_IDX2 1
#define DRV_TMR_INTERRUPT_MODE true
#define DRV_TMR_PERIPHERAL_ID_IDX0 TMR_ID_2
#define DRV_TMR_INTERRUPT_SOURCE_IDX0 INT_SOURCE_TIMER_2
#define DRV_TMR_INTERRUPT_VECTOR_IDX0 INT_VECTOR_T2
#define DRV_TMR_ISR_VECTOR_IDX0 _TIMER_2_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX0 INT_PRIORITY_LEVEL4
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX0 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX0 TMR_PRESCALE_VALUE_8
#define DRV_TMR_OPERATION_MODE_IDX0 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX0 false
#define DRV_TMR_POWER_STATE_IDX0
#define DRV_TMR_PERIPHERAL_ID_IDX1 TMR_ID_7
#define DRV_TMR_INTERRUPT_SOURCE_IDX1 INT_SOURCE_TIMER_7
#define DRV_TMR_INTERRUPT_VECTOR_IDX1 INT_VECTOR_T7
#define DRV_TMR_ISR_VECTOR_IDX1 _TIMER_7_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX1 INT_PRIORITY_LEVEL3
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX1 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX1 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX1 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX1 false
#define DRV_TMR_POWER_STATE_IDX1
#define DRV_TMR_PERIPHERAL_ID_IDX2 TMR_ID_6
#define DRV_TMR_INTERRUPT_SOURCE_IDX2 INT_SOURCE_TIMER_6
#define DRV_TMR_INTERRUPT_VECTOR_IDX2 INT_VECTOR_T6
#define DRV_TMR_ISR_VECTOR_IDX2 _TIMER_6_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX2 INT_PRIORITY_LEVEL1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX2 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX2 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX2 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX2 false
#define DRV_TMR_POWER_STATE_IDX2
#define DRV_TMR_PERIPHERAL_ID_IDX3 TMR_ID_1
#define DRV_TMR_INTERRUPT_SOURCE_IDX3 INT_SOURCE_TIMER_1
#define DRV_TMR_INTERRUPT_VECTOR_IDX3 INT_VECTOR_T1
#define DRV_TMR_ISR_VECTOR_IDX3 _TIMER_1_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX3 INT_PRIORITY_LEVEL2
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX3 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX3 TMR_PRESCALE_VALUE_256
#define DRV_TMR_OPERATION_MODE_IDX3 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX3 false
#define DRV_TMR_POWER_STATE_IDX3
#define DRV_TMR_PERIPHERAL_ID_IDX4 TMR_ID_3
#define DRV_TMR_INTERRUPT_SOURCE_IDX4 INT_SOURCE_TIMER_3
#define DRV_TMR_INTERRUPT_VECTOR_IDX4 INT_VECTOR_T3
#define DRV_TMR_ISR_VECTOR_IDX4 _TIMER_3_VECTOR
#define DRV_TMR_INTERRUPT_PRIORITY_IDX4 INT_PRIORITY_LEVEL1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4 INT_SUBPRIORITY_LEVEL0
#define DRV_TMR_CLOCK_SOURCE_IDX4 DRV_TMR_CLKSOURCE_INTERNAL
#define DRV_TMR_PRESCALE_IDX4 TMR_PRESCALE_VALUE_16
#define DRV_TMR_OPERATION_MODE_IDX4 DRV_TMR_OPERATION_MODE_16_BIT
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX4 false
#define DRV_TMR_POWER_STATE_IDX4
#define DRV_USART_INSTANCES_NUMBER 1
#define DRV_USART_CLIENTS_NUMBER 1
#define DRV_USART_INTERRUPT_MODE false
#define DRV_USART_BYTE_MODEL_SUPPORT true
#define DRV_USART_READ_WRITE_MODEL_SUPPORT false
#define DRV_USART_BUFFER_QUEUE_SUPPORT false
#define DRV_USBHS_DEVICE_SUPPORT true
#define DRV_USBHS_HOST_SUPPORT false
#define DRV_USBHS_INSTANCES_NUMBER 1
#define DRV_USBHS_INTERRUPT_MODE true
#define DRV_USBHS_ENDPOINTS_NUMBER 2
#define USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
#define USB_DEVICE_INSTANCES_NUMBER 1
#define USB_DEVICE_EP0_BUFFER_SIZE 64
#define USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED 2
#define LED1Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
#define LED1StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12 , Value)
#define LED2Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
#define LED2StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10 , Value)
#define DMP_FIRE_LEDToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
#define DMP_FIRE_LEDStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9 , Value)
#define HVPS_ENBToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
#define HVPS_ENBStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13 , Value)
#define RLY_HVPS_OUTToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
#define RLY_HVPS_OUTStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14 , Value)
#define RLY_WL_SPS_POLToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
#define RLY_WL_SPS_POLStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2 , Value)
#define RLY_LOGToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
#define RLY_LOGStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9 , Value)
#define RLY_DMP_FIREToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
#define RLY_DMP_FIREStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10 , Value)
#define RLY_AUXToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
#define RLY_AUXStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11 , Value)
#define RLY_CCLToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
#define RLY_CCLStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1 , Value)
#define RLY_WL_MONToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
#define RLY_WL_MONStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12 , Value)
#define RLY_ARMCFToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
#define RLY_ARMCFStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13 , Value)
#define RLY_ARMToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
#define RLY_ARMStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14 , Value)
#define TPAN1Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
#define TPAN1StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10 , Value)
#define TPAN2Toggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2On() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2Off() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2StateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
#define TPAN2StateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11 , Value)
#define FSK_DAC_CSToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
#define FSK_DAC_CSStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4 , Value)
#define RLY_COMMToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
#define RLY_COMMStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14 , Value)
#define FSK_DAC_CLRToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLROn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLROff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLRStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
#define FSK_DAC_CLRStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7 , Value)
#define WL_CPS_SWToggle() PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWOn() PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWOff() PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWStateGet() PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
#define WL_CPS_SWStateSet(Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13 , Value)
#define HVPS_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_5)
#define MAN_SIGStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_0)
#define DMP_FIRE_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_8)
#define NEG_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_4)
#define POS_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_15)
#define DRUM1_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_2)
#define SAFE_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_1)
#define DRUM2_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_0)
#define LOG_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_3)
#define AUX_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_8)
#define ARMCF_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_1)
#define ARM_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_2)
#define ARMCF_AUTO_SWStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_13)
#define FIRE_SW_OFFStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_8)
#define FIRE_SW_ONStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_8)
#define WL_SPS_POS_DETStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_12)
#define WL_SPS_NEG_DETStateGet() PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_13)
#define MAN_CN_PORT_CHANNEL PORT_CHANNEL_A
#define MAN_CN_PORT_BIT PORTS_BIT_POS_0
#define MAN_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_A
#define HVPS_CN_PORT_CHANNEL PORT_CHANNEL_J
#define HVPS_CN_PORT_BIT PORTS_BIT_POS_11
#define HVPS_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_J
#define _SYS_DEFINITIONS_H
#define _DRV_ADC_STATIC_H
#define _DRV_TMR_STATIC_H
#define DRV_TIMER_DIVIDER_MAX_32BIT 0xffffffff
#define DRV_TIMER_DIVIDER_MIN_32BIT 0x2
#define DRV_TIMER_DIVIDER_MAX_16BIT 0x10000
#define DRV_TIMER_DIVIDER_MIN_16BIT 0x2
#define _DRV_PMP_STATIC_H
#define _SYS_PORTS_H
#define _SYS_PORTS_DEFINITIONS_H
#define _PLIB_PORTS_H
#define _PLIB_PORTS_PROCESSOR_H
#define _PLIB_PORTS_COMPATIBILITY_H
#define PLIB_PORTS_ChangeNoticePerPortHasOccured PLIB_PORTS_ChangeNoticePerPortHasOccurred
#define qqqbranches 64
#define QQQMAXMCDCSIZE 2
#define UPLOAD_EXECUTION_HISTORY
#define ldra_sscanf
#define qqnull_params void
#define qqzzidfield 1
#define QQQFIXEDSIZE
#define QQQTEMP1
#define ELEMENT(N) qqbmsoutput("%8d", bitmapstruct.element##N);
#define LASTELEMENT
Typedefs
typedef void(* ldra_void_function) ()
typedef uint16_t PORTS_DATA_MASK
typedef uint32_t PORTS_DATA_TYPE
Enumerations
enum DRV_ADC_MODULE_ID {
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES, DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES,
DRV_ADC_ID_1 = ADCHS_ID_0, DRV_ADCHS_NUMBER_OF_MODULES
}
enum SYS_PORTS_PULLUP_PULLDOWN_STATUS {
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1, SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1,
SYS_PORTS_PULLUP_DISABLE = 0, SYS_PORTS_PULLUP_ENABLE = 1
}
enum SYS_PORTS_PIN_DIRECTION {
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1, SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1,
SYS_PORTS_DIRECTION_OUTPUT = 0, SYS_PORTS_DIRECTION_INPUT = 1
}
enum PORTS_PIN_INTERRUPT_TYPE {
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE,
PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE, PORTS_PIN_INTERRUPT_NONE
}
Functions
void qqqtotalupload (void)
void qqqtotalreset (void)
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
static void qqoutput (FILEPOINT char *s, int i)
static void qqoutput2 (FILEPOINT char *s, int i, int j)
static void qqoutput3 (FILEPOINT char *s, int i, int j, int k)
static void qqoutput4 (FILEPOINT char *s, int i, int j, int k, int l)
static void qqoutput0 (FILEPOINT char *s)
static int main_68zqqzqz (qqnull_params)
static int main_68zqqzqz1 (qqnull_params)
static int main_68zqendz (int qqqi)
static int main_68zqzqzq (int qqqi)
static void qqqupload (qqnull_params)
static void qqqbitmapreset (qqnull_params)
void APP_Initialize (void)
void APP_Tasks (void)
void DRV_ADC_Initialize (void)
void DRV_ADC_DeInitialize (void)
void DRV_ADC0_Open (void)
void DRV_ADC0_Close (void)
void DRV_ADC1_Open (void)
void DRV_ADC1_Close (void)
void DRV_ADC_Start (void)
void DRV_ADC_Stop (void)
uint32_t DRV_ADC_SamplesRead (uint8_t bufIndex)
bool DRV_ADC_SamplesAvailable (uint8_t bufIndex)
void DRV_TMR0_Initialize (void)
bool DRV_TMR0_Start (void)
void DRV_TMR0_Stop (void)
static void DRV_TMR0_DeInitialize (void)
static SYS_STATUS DRV_TMR0_Status (void)
static void DRV_TMR0_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR0_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR0_OperationModeGet (void)
static void DRV_TMR0_Close (void)
bool DRV_TMR0_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR0_CounterValueSet (uint32_t value)
uint32_t DRV_TMR0_CounterValueGet (void)
void DRV_TMR0_CounterClear (void)
TMR_PRESCALE DRV_TMR0_PrescalerGet (void)
void DRV_TMR0_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR0_PeriodValueGet (void)
void DRV_TMR0_StopInIdleDisable (void)
void DRV_TMR0_StopInIdleEnable (void)
static void DRV_TMR0_Tasks (void)
uint32_t DRV_TMR0_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR0_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR1_Initialize (void)
bool DRV_TMR1_Start (void)
void DRV_TMR1_Stop (void)
static void DRV_TMR1_DeInitialize (void)
static SYS_STATUS DRV_TMR1_Status (void)
static void DRV_TMR1_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR1_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR1_OperationModeGet (void)
static void DRV_TMR1_Close (void)
bool DRV_TMR1_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR1_CounterValueSet (uint32_t value)
uint32_t DRV_TMR1_CounterValueGet (void)
void DRV_TMR1_CounterClear (void)
TMR_PRESCALE DRV_TMR1_PrescalerGet (void)
void DRV_TMR1_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR1_PeriodValueGet (void)
void DRV_TMR1_StopInIdleDisable (void)
void DRV_TMR1_StopInIdleEnable (void)
static void DRV_TMR1_Tasks (void)
uint32_t DRV_TMR1_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR1_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR2_Initialize (void)
bool DRV_TMR2_Start (void)
void DRV_TMR2_Stop (void)
static void DRV_TMR2_DeInitialize (void)
static SYS_STATUS DRV_TMR2_Status (void)
static void DRV_TMR2_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR2_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR2_OperationModeGet (void)
static void DRV_TMR2_Close (void)
bool DRV_TMR2_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR2_CounterValueSet (uint32_t value)
uint32_t DRV_TMR2_CounterValueGet (void)
void DRV_TMR2_CounterClear (void)
TMR_PRESCALE DRV_TMR2_PrescalerGet (void)
void DRV_TMR2_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR2_PeriodValueGet (void)
void DRV_TMR2_StopInIdleDisable (void)
void DRV_TMR2_StopInIdleEnable (void)
static void DRV_TMR2_Tasks (void)
uint32_t DRV_TMR2_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR2_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR3_Initialize (void)
bool DRV_TMR3_Start (void)
void DRV_TMR3_Stop (void)
static void DRV_TMR3_DeInitialize (void)
static SYS_STATUS DRV_TMR3_Status (void)
static void DRV_TMR3_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR3_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR3_OperationModeGet (void)
static void DRV_TMR3_Close (void)
bool DRV_TMR3_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR3_CounterValueSet (uint32_t value)
uint32_t DRV_TMR3_CounterValueGet (void)
void DRV_TMR3_CounterClear (void)
TMR_PRESCALE DRV_TMR3_PrescalerGet (void)
void DRV_TMR3_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR3_PeriodValueGet (void)
void DRV_TMR3_StopInIdleDisable (void)
void DRV_TMR3_StopInIdleEnable (void)
static void DRV_TMR3_Tasks (void)
uint32_t DRV_TMR3_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR3_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_TMR4_Initialize (void)
bool DRV_TMR4_Start (void)
void DRV_TMR4_Stop (void)
static void DRV_TMR4_DeInitialize (void)
static SYS_STATUS DRV_TMR4_Status (void)
static void DRV_TMR4_Open (void)
DRV_TMR_CLIENT_STATUS DRV_TMR4_ClientStatus (void)
static DRV_TMR_OPERATION_MODE DRV_TMR4_OperationModeGet (void)
static void DRV_TMR4_Close (void)
bool DRV_TMR4_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
void DRV_TMR4_CounterValueSet (uint32_t value)
uint32_t DRV_TMR4_CounterValueGet (void)
void DRV_TMR4_CounterClear (void)
TMR_PRESCALE DRV_TMR4_PrescalerGet (void)
void DRV_TMR4_PeriodValueSet (uint32_t value)
uint32_t DRV_TMR4_PeriodValueGet (void)
void DRV_TMR4_StopInIdleDisable (void)
void DRV_TMR4_StopInIdleEnable (void)
static void DRV_TMR4_Tasks (void)
uint32_t DRV_TMR4_CounterFrequencyGet (void)
DRV_TMR_OPERATION_MODE DRV_TMR4_DividerRangeGet (DRV_TMR_DIVIDER_RANGE *pDivRange)
void DRV_PMP0_Initialize (void)
void DRV_PMP0_ModeConfig (void)
void DRV_PMP0_TimingSet (PMP_DATA_WAIT_STATES dataWait, PMP_STROBE_WAIT_STATES strobeWait, PMP_DATA_HOLD_STATES dataHold)
uint8_t DRV_PMP0_Read (void)
void DRV_PMP0_Write (uint8_t data)
void PLIB_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION inputFunction, PORTS_REMAP_INPUT_PIN remapInputPin)
void PLIB_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION outputFunction, PORTS_REMAP_OUTPUT_PIN remapOutputPin)
void PLIB_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
void PLIB_PORTS_PinModePerPortSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_MODE mode)
void PLIB_PORTS_ChangeNoticePullDownPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullDownPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullUpPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePullUpPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinChangeNoticePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinChangeNoticePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChangeNoticePerPortTurnOn (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticePerPortTurnOff (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticeInIdlePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChangeNoticeInIdlePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
bool PLIB_PORTS_ChangeNoticePerPortHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_PinGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_PinGetLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
void PLIB_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinDirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinDirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PORTS_DATA_TYPE PLIB_PORTS_ReadLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PORTS_DATA_TYPE PLIB_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
void PLIB_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
void PLIB_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
void PLIB_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
void PLIB_PORTS_DirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_DirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_MASK PLIB_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelModeSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK modeMask, PORTS_PIN_MODE mode)
void PLIB_PORTS_ChannelChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticePullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_ChannelChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void PLIB_PORTS_AnPinsModeSelect (PORTS_MODULE_ID index, PORTS_AN_PIN anPins, PORTS_PIN_MODE mode)
void PLIB_PORTS_CnPinsPullUpEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsPullUpDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_CnPinsDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
void PLIB_PORTS_ChangeNoticeEnable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticeDisable (PORTS_MODULE_ID index)
void PLIB_PORTS_PinChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_PinChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChangeNoticeInIdleEnable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticeInIdleDisable (PORTS_MODULE_ID index)
void PLIB_PORTS_ChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void PLIB_PORTS_ChannelSlewRateSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK channelMask, PORTS_PIN_SLEW_RATE slewRate)
PORTS_PIN_SLEW_RATE PLIB_PORTS_PinSlewRateGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void PLIB_PORTS_ChannelChangeNoticeMethodSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_CHANGE_NOTICE_METHOD changeNoticeMethod)
PORTS_CHANGE_NOTICE_METHOD PLIB_PORTS_ChannelChangeNoticeMethodGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void PLIB_PORTS_ChannelChangeNoticeEdgeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
void PLIB_PORTS_ChannelChangeNoticeEdgeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
bool PLIB_PORTS_PinChangeNoticeEdgeIsEnabled (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_CHANGE_NOTICE_EDGE cnEdgeType)
bool PLIB_PORTS_PinChangeNoticeEdgeHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool PLIB_PORTS_ExistsRemapInput (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsRemapOutput (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinMode (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsAnPinsMode (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsRead (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsLatchRead (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsWrite (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsDirection (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPortsOpenDrain (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNotice (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinChangeNotice (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeInIdle (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullUp (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinModePerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullDownPerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePullUpPerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsPinChangeNoticePerPort (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortTurnOn (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortInIdle (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticePerPortStatus (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsSlewRateControl (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChannelChangeNoticeMethod (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeEdgeControl (PORTS_MODULE_ID index)
bool PLIB_PORTS_ExistsChangeNoticeEdgeStatus (PORTS_MODULE_ID index)
void SYS_PORTS_Initialize ()
PORTS_DATA_TYPE SYS_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
PORTS_DATA_TYPE SYS_PORTS_LatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
void SYS_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
void SYS_PORTS_DirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_MASK SYS_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
void SYS_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
void SYS_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PORTS_DATA_TYPE SYS_PORTS_InterruptStatusGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
void SYS_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION function, PORTS_REMAP_INPUT_PIN remapPin)
void SYS_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION function, PORTS_REMAP_OUTPUT_PIN remapPin)
void SYS_PORTS_ChangeNotificationGlobalEnable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationGlobalDisable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum, SYS_PORTS_PULLUP_PULLDOWN_STATUS value)
void SYS_PORTS_ChangeNotificationDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_ChangeNotificationInIdleModeEnable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationInIdleModeDisable (PORTS_MODULE_ID index)
void SYS_PORTS_ChangeNotificationPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_ChangeNotificationPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
void SYS_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
void SYS_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
bool SYS_PORTS_PinLatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
bool SYS_PORTS_PinRead (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinDirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_PinPullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
void SYS_PORTS_InterruptEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_INTERRUPT_TYPE pinInterruptType)
void TEST_Tasks (void)
int main (void)
LDRA_PRAGMA_NO_OPTIMISATION void LDRA_NO_OPTIMISATION upload_execution_history (void)
static int main_68zscanf (char *qqscan_str)
static void qqqqinitialise (int ii)
static void qqqbitmapreset ()
static void qqbmsoutput (FILEPOINT char *s, unsigned int i)
Variables
static int qqqqbmselwidth = 32
static int zzfileid = 68
int QQQindicator =0
int QQQfirstmcdc =1
int main_68zzopen = 0
static int tbrun_mode =0
int qqqshell_upload = 0
int QQQfcn_ptr_num = 0
static int qqqisinitialised = 0
ldra_void_function qqqaccumupload [QQQnumfil]
ldra_void_function qqqaccumreset [QQQnumfil]
static unsigned char qqqzzglobflag = 0
static struct bitmapstruct_t bitmapstruct
APP_DATA APP
SYSTEM_OBJECTS sysObj
ClassB_Test_Flags TEST_FLAG
static char qqqqone [] = "%6d\n"
static int qqqlast = 0
unsigned int * qqzzglobarrb [QQQnumfil]
short qqzzglobbrns [QQQnumfil] = {0}
short qqzzglobfileid [QQQnumfil] = {0}
int qqupload_registered = 0
Macro Definition Documentation
_DRV_ADC_STATIC_H
#define _DRV_ADC_STATIC_H
Definition at line 980 of file inszt_main.c.
_DRV_PMP_STATIC_H
#define _DRV_PMP_STATIC_H
Definition at line 1668 of file inszt_main.c.
_DRV_TMR_STATIC_H
#define _DRV_TMR_STATIC_H
Definition at line 1079 of file inszt_main.c.
_PLIB_PORTS_COMPATIBILITY_H
#define _PLIB_PORTS_COMPATIBILITY_H
Definition at line 5122 of file inszt_main.c.
_PLIB_PORTS_H
#define _PLIB_PORTS_H
Definition at line 1825 of file inszt_main.c.
_PLIB_PORTS_PROCESSOR_H
#define _PLIB_PORTS_PROCESSOR_H
Definition at line 1893 of file inszt_main.c.
_SYS_DEFINITIONS_H
#define _SYS_DEFINITIONS_H
Definition at line 922 of file inszt_main.c.
_SYS_PORTS_DEFINITIONS_H
#define _SYS_PORTS_DEFINITIONS_H
Definition at line 1779 of file inszt_main.c.
_SYS_PORTS_H
#define _SYS_PORTS_H
Definition at line 1739 of file inszt_main.c.
_SYSTEM_CONFIG_H
#define _SYSTEM_CONFIG_H
Definition at line 420 of file inszt_main.c.
APP_H
#define APP_H
Definition at line 243 of file inszt_main.c.
ARM_SWStateGet
#define ARM_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_2)
Definition at line 862 of file inszt_main.c.
ARMCF_AUTO_SWStateGet
#define ARMCF_AUTO_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_13)
Definition at line 864 of file inszt_main.c.
ARMCF_SWStateGet
#define ARMCF_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_K , PORTS_BIT_POS_1)
Definition at line 860 of file inszt_main.c.
AUX_SWStateGet
#define AUX_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_8)
Definition at line 858 of file inszt_main.c.
DMP_FIRE_LEDOff
#define DMP_FIRE_LEDOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 740 of file inszt_main.c.
DMP_FIRE_LEDOn
#define DMP_FIRE_LEDOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 739 of file inszt_main.c.
DMP_FIRE_LEDStateGet
#define DMP_FIRE_LEDStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 741 of file inszt_main.c.
DMP_FIRE_LEDStateSet
#define DMP_FIRE_LEDStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9 , Value)
Definition at line 742 of file inszt_main.c.
DMP_FIRE_LEDToggle
#define DMP_FIRE_LEDToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_9)
Definition at line 738 of file inszt_main.c.
DMP_FIRE_SWStateGet
#define DMP_FIRE_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_E , PORTS_BIT_POS_8)
Definition at line 844 of file inszt_main.c.
DRUM1_SWStateGet
#define DRUM1_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_2)
Definition at line 850 of file inszt_main.c.
DRUM2_SWStateGet
#define DRUM2_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_0)
Definition at line 854 of file inszt_main.c.
DRV_IC_DRIVER_MODE_STATIC
#define DRV_IC_DRIVER_MODE_STATIC
Definition at line 541 of file inszt_main.c.
DRV_SPI_16BIT
#define DRV_SPI_16BIT 1
Definition at line 554 of file inszt_main.c.
DRV_SPI_32BIT
#define DRV_SPI_32BIT 0
Definition at line 555 of file inszt_main.c.
DRV_SPI_8BIT
#define DRV_SPI_8BIT 1
Definition at line 553 of file inszt_main.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX0
#define DRV_SPI_ALLOW_IDLE_RUN_IDX0 false
Definition at line 565 of file inszt_main.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX1
#define DRV_SPI_ALLOW_IDLE_RUN_IDX1 false
Definition at line 586 of file inszt_main.c.
DRV_SPI_ALLOW_IDLE_RUN_IDX2
#define DRV_SPI_ALLOW_IDLE_RUN_IDX2 false
Definition at line 607 of file inszt_main.c.
DRV_SPI_BAUD_RATE_IDX0
#define DRV_SPI_BAUD_RATE_IDX0 1000000
Definition at line 575 of file inszt_main.c.
DRV_SPI_BAUD_RATE_IDX1
#define DRV_SPI_BAUD_RATE_IDX1 1000000
Definition at line 596 of file inszt_main.c.
DRV_SPI_BAUD_RATE_IDX2
#define DRV_SPI_BAUD_RATE_IDX2 500000
Definition at line 617 of file inszt_main.c.
DRV_SPI_BUFFER_TYPE_IDX0
#define DRV_SPI_BUFFER_TYPE_IDX0 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 576 of file inszt_main.c.
DRV_SPI_BUFFER_TYPE_IDX1
#define DRV_SPI_BUFFER_TYPE_IDX1 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 597 of file inszt_main.c.
DRV_SPI_BUFFER_TYPE_IDX2
#define DRV_SPI_BUFFER_TYPE_IDX2 DRV_SPI_BUFFER_TYPE_ENHANCED
Definition at line 618 of file inszt_main.c.
DRV_SPI_CLIENTS_NUMBER
#define DRV_SPI_CLIENTS_NUMBER 3
Definition at line 559 of file inszt_main.c.
DRV_SPI_CLOCK_MODE_IDX0
#define DRV_SPI_CLOCK_MODE_IDX0 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 577 of file inszt_main.c.
DRV_SPI_CLOCK_MODE_IDX1
#define DRV_SPI_CLOCK_MODE_IDX1 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 598 of file inszt_main.c.
DRV_SPI_CLOCK_MODE_IDX2
#define DRV_SPI_CLOCK_MODE_IDX2 DRV_SPI_CLOCK_MODE_IDLE_LOW_EDGE_FALL
Definition at line 619 of file inszt_main.c.
DRV_SPI_CLOCK_SOURCE_IDX0
#define DRV_SPI_CLOCK_SOURCE_IDX0 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 573 of file inszt_main.c.
DRV_SPI_CLOCK_SOURCE_IDX1
#define DRV_SPI_CLOCK_SOURCE_IDX1 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 594 of file inszt_main.c.
DRV_SPI_CLOCK_SOURCE_IDX2
#define DRV_SPI_CLOCK_SOURCE_IDX2 SPI_BAUD_RATE_PBCLK_CLOCK
Definition at line 615 of file inszt_main.c.
DRV_SPI_COMM_WIDTH_IDX0
#define DRV_SPI_COMM_WIDTH_IDX0 SPI_COMMUNICATION_WIDTH_16BITS
Definition at line 572 of file inszt_main.c.
DRV_SPI_COMM_WIDTH_IDX1
#define DRV_SPI_COMM_WIDTH_IDX1 SPI_COMMUNICATION_WIDTH_8BITS
Definition at line 593 of file inszt_main.c.
DRV_SPI_COMM_WIDTH_IDX2
#define DRV_SPI_COMM_WIDTH_IDX2 SPI_COMMUNICATION_WIDTH_16BITS
Definition at line 614 of file inszt_main.c.
DRV_SPI_DMA
#define DRV_SPI_DMA 0
Definition at line 556 of file inszt_main.c.
DRV_SPI_EBM
#define DRV_SPI_EBM 1
Definition at line 552 of file inszt_main.c.
DRV_SPI_ELEMENTS_PER_QUEUE
#define DRV_SPI_ELEMENTS_PER_QUEUE 10
Definition at line 560 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX0
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX0 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 569 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX1
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX1 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 590 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_DIRECTION_IDX2
#define DRV_SPI_FRAME_PULSE_DIRECTION_IDX2 SPI_FRAME_PULSE_DIRECTION_OUTPUT
Definition at line 611 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX0
#define DRV_SPI_FRAME_PULSE_EDGE_IDX0 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 570 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX1
#define DRV_SPI_FRAME_PULSE_EDGE_IDX1 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 591 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_EDGE_IDX2
#define DRV_SPI_FRAME_PULSE_EDGE_IDX2 SPI_FRAME_PULSE_EDGE_COINCIDES_FIRST_BIT_CLOCK
Definition at line 612 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX0
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX0 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 568 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX1
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX1 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 589 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_POLARITY_IDX2
#define DRV_SPI_FRAME_PULSE_POLARITY_IDX2 SPI_FRAME_PULSE_POLARITY_ACTIVE_LOW
Definition at line 610 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX0
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX0 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 571 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX1
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX1 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 592 of file inszt_main.c.
DRV_SPI_FRAME_PULSE_WIDTH_IDX2
#define DRV_SPI_FRAME_PULSE_WIDTH_IDX2 SPI_FRAME_PULSE_WIDTH_ONE_WORD_LENGTH
Definition at line 613 of file inszt_main.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX0
#define DRV_SPI_FRAME_SYNC_PULSE_IDX0 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 567 of file inszt_main.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX1
#define DRV_SPI_FRAME_SYNC_PULSE_IDX1 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 588 of file inszt_main.c.
DRV_SPI_FRAME_SYNC_PULSE_IDX2
#define DRV_SPI_FRAME_SYNC_PULSE_IDX2 SPI_FRAME_SYNC_PULSE_ON_EVERY_DATA_CHARACTER
Definition at line 609 of file inszt_main.c.
DRV_SPI_INPUT_PHASE_IDX0
#define DRV_SPI_INPUT_PHASE_IDX0 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
Definition at line 578 of file inszt_main.c.
DRV_SPI_INPUT_PHASE_IDX1
#define DRV_SPI_INPUT_PHASE_IDX1 SPI_INPUT_SAMPLING_PHASE_IN_MIDDLE
Definition at line 599 of file inszt_main.c.
DRV_SPI_INPUT_PHASE_IDX2
#define DRV_SPI_INPUT_PHASE_IDX2 SPI_INPUT_SAMPLING_PHASE_AT_END
Definition at line 620 of file inszt_main.c.
DRV_SPI_INSTANCES_NUMBER
#define DRV_SPI_INSTANCES_NUMBER 3
Definition at line 558 of file inszt_main.c.
DRV_SPI_ISR
#define DRV_SPI_ISR 0
Definition at line 548 of file inszt_main.c.
DRV_SPI_MASTER
#define DRV_SPI_MASTER 1
Definition at line 549 of file inszt_main.c.
DRV_SPI_NUMBER_OF_MODULES
#define DRV_SPI_NUMBER_OF_MODULES 6
Definition at line 544 of file inszt_main.c.
DRV_SPI_POLLED
#define DRV_SPI_POLLED 1
Definition at line 547 of file inszt_main.c.
DRV_SPI_QUEUE_SIZE_IDX0
#define DRV_SPI_QUEUE_SIZE_IDX0 10
Definition at line 580 of file inszt_main.c.
DRV_SPI_QUEUE_SIZE_IDX1
#define DRV_SPI_QUEUE_SIZE_IDX1 10
Definition at line 601 of file inszt_main.c.
DRV_SPI_QUEUE_SIZE_IDX2
#define DRV_SPI_QUEUE_SIZE_IDX2 10
Definition at line 622 of file inszt_main.c.
DRV_SPI_RESERVED_JOB_IDX0
#define DRV_SPI_RESERVED_JOB_IDX0 1
Definition at line 581 of file inszt_main.c.
DRV_SPI_RESERVED_JOB_IDX1
#define DRV_SPI_RESERVED_JOB_IDX1 1
Definition at line 602 of file inszt_main.c.
DRV_SPI_RESERVED_JOB_IDX2
#define DRV_SPI_RESERVED_JOB_IDX2 1
Definition at line 623 of file inszt_main.c.
DRV_SPI_RM
#define DRV_SPI_RM 0
Definition at line 551 of file inszt_main.c.
DRV_SPI_SLAVE
#define DRV_SPI_SLAVE 0
Definition at line 550 of file inszt_main.c.
DRV_SPI_SPI_CLOCK_IDX0
#define DRV_SPI_SPI_CLOCK_IDX0 CLK_BUS_PERIPHERAL_2
Definition at line 574 of file inszt_main.c.
DRV_SPI_SPI_CLOCK_IDX1
#define DRV_SPI_SPI_CLOCK_IDX1 CLK_BUS_PERIPHERAL_2
Definition at line 595 of file inszt_main.c.
DRV_SPI_SPI_CLOCK_IDX2
#define DRV_SPI_SPI_CLOCK_IDX2 CLK_BUS_PERIPHERAL_2
Definition at line 616 of file inszt_main.c.
DRV_SPI_SPI_ID_IDX0
#define DRV_SPI_SPI_ID_IDX0 SPI_ID_1
Definition at line 562 of file inszt_main.c.
DRV_SPI_SPI_ID_IDX1
#define DRV_SPI_SPI_ID_IDX1 SPI_ID_2
Definition at line 583 of file inszt_main.c.
DRV_SPI_SPI_ID_IDX2
#define DRV_SPI_SPI_ID_IDX2 SPI_ID_4
Definition at line 604 of file inszt_main.c.
DRV_SPI_SPI_MODE_IDX0
#define DRV_SPI_SPI_MODE_IDX0 DRV_SPI_MODE_MASTER
Definition at line 564 of file inszt_main.c.
DRV_SPI_SPI_MODE_IDX1
#define DRV_SPI_SPI_MODE_IDX1 DRV_SPI_MODE_MASTER
Definition at line 585 of file inszt_main.c.
DRV_SPI_SPI_MODE_IDX2
#define DRV_SPI_SPI_MODE_IDX2 DRV_SPI_MODE_MASTER
Definition at line 606 of file inszt_main.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX0
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX0 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 566 of file inszt_main.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX1
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX1 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 587 of file inszt_main.c.
DRV_SPI_SPI_PROTOCOL_TYPE_IDX2
#define DRV_SPI_SPI_PROTOCOL_TYPE_IDX2 DRV_SPI_PROTOCOL_TYPE_FRAMED
Definition at line 608 of file inszt_main.c.
DRV_SPI_TASK_MODE_IDX0
#define DRV_SPI_TASK_MODE_IDX0 DRV_SPI_TASK_MODE_POLLED
Definition at line 563 of file inszt_main.c.
DRV_SPI_TASK_MODE_IDX1
#define DRV_SPI_TASK_MODE_IDX1 DRV_SPI_TASK_MODE_POLLED
Definition at line 584 of file inszt_main.c.
DRV_SPI_TASK_MODE_IDX2
#define DRV_SPI_TASK_MODE_IDX2 DRV_SPI_TASK_MODE_POLLED
Definition at line 605 of file inszt_main.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX0 0xFFFF
Definition at line 579 of file inszt_main.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX1 0xFF
Definition at line 600 of file inszt_main.c.
DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2
#define DRV_SPI_TRANSMIT_DUMMY_BYTE_VALUE_IDX2 0x0000
Definition at line 621 of file inszt_main.c.
DRV_TIMER_DIVIDER_MAX_16BIT
#define DRV_TIMER_DIVIDER_MAX_16BIT 0x10000
Definition at line 1094 of file inszt_main.c.
DRV_TIMER_DIVIDER_MAX_32BIT
#define DRV_TIMER_DIVIDER_MAX_32BIT 0xffffffff
Definition at line 1090 of file inszt_main.c.
DRV_TIMER_DIVIDER_MIN_16BIT
#define DRV_TIMER_DIVIDER_MIN_16BIT 0x2
Definition at line 1096 of file inszt_main.c.
DRV_TIMER_DIVIDER_MIN_32BIT
#define DRV_TIMER_DIVIDER_MIN_32BIT 0x2
Definition at line 1092 of file inszt_main.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX0
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX0 false
Definition at line 636 of file inszt_main.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX1
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX1 false
Definition at line 647 of file inszt_main.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX2
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX2 false
Definition at line 659 of file inszt_main.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX3
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX3 false
Definition at line 671 of file inszt_main.c.
DRV_TMR_ASYNC_WRITE_ENABLE_IDX4
#define DRV_TMR_ASYNC_WRITE_ENABLE_IDX4 false
Definition at line 683 of file inszt_main.c.
DRV_TMR_CLOCK_SOURCE_IDX0
#define DRV_TMR_CLOCK_SOURCE_IDX0 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 633 of file inszt_main.c.
DRV_TMR_CLOCK_SOURCE_IDX1
#define DRV_TMR_CLOCK_SOURCE_IDX1 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 644 of file inszt_main.c.
DRV_TMR_CLOCK_SOURCE_IDX2
#define DRV_TMR_CLOCK_SOURCE_IDX2 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 656 of file inszt_main.c.
DRV_TMR_CLOCK_SOURCE_IDX3
#define DRV_TMR_CLOCK_SOURCE_IDX3 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 668 of file inszt_main.c.
DRV_TMR_CLOCK_SOURCE_IDX4
#define DRV_TMR_CLOCK_SOURCE_IDX4 DRV_TMR_CLKSOURCE_INTERNAL
Definition at line 680 of file inszt_main.c.
DRV_TMR_INTERRUPT_MODE
#define DRV_TMR_INTERRUPT_MODE true
Definition at line 625 of file inszt_main.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX0
#define DRV_TMR_INTERRUPT_PRIORITY_IDX0 INT_PRIORITY_LEVEL4
Definition at line 631 of file inszt_main.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX1
#define DRV_TMR_INTERRUPT_PRIORITY_IDX1 INT_PRIORITY_LEVEL3
Definition at line 642 of file inszt_main.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX2
#define DRV_TMR_INTERRUPT_PRIORITY_IDX2 INT_PRIORITY_LEVEL1
Definition at line 654 of file inszt_main.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX3
#define DRV_TMR_INTERRUPT_PRIORITY_IDX3 INT_PRIORITY_LEVEL2
Definition at line 666 of file inszt_main.c.
DRV_TMR_INTERRUPT_PRIORITY_IDX4
#define DRV_TMR_INTERRUPT_PRIORITY_IDX4 INT_PRIORITY_LEVEL1
Definition at line 678 of file inszt_main.c.
DRV_TMR_INTERRUPT_SOURCE_IDX0
#define DRV_TMR_INTERRUPT_SOURCE_IDX0 INT_SOURCE_TIMER_2
Definition at line 628 of file inszt_main.c.
DRV_TMR_INTERRUPT_SOURCE_IDX1
#define DRV_TMR_INTERRUPT_SOURCE_IDX1 INT_SOURCE_TIMER_7
Definition at line 639 of file inszt_main.c.
DRV_TMR_INTERRUPT_SOURCE_IDX2
#define DRV_TMR_INTERRUPT_SOURCE_IDX2 INT_SOURCE_TIMER_6
Definition at line 651 of file inszt_main.c.
DRV_TMR_INTERRUPT_SOURCE_IDX3
#define DRV_TMR_INTERRUPT_SOURCE_IDX3 INT_SOURCE_TIMER_1
Definition at line 663 of file inszt_main.c.
DRV_TMR_INTERRUPT_SOURCE_IDX4
#define DRV_TMR_INTERRUPT_SOURCE_IDX4 INT_SOURCE_TIMER_3
Definition at line 675 of file inszt_main.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX0 INT_SUBPRIORITY_LEVEL0
Definition at line 632 of file inszt_main.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX1 INT_SUBPRIORITY_LEVEL0
Definition at line 643 of file inszt_main.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX2 INT_SUBPRIORITY_LEVEL0
Definition at line 655 of file inszt_main.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX3 INT_SUBPRIORITY_LEVEL0
Definition at line 667 of file inszt_main.c.
DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4
#define DRV_TMR_INTERRUPT_SUB_PRIORITY_IDX4 INT_SUBPRIORITY_LEVEL0
Definition at line 679 of file inszt_main.c.
DRV_TMR_INTERRUPT_VECTOR_IDX0
#define DRV_TMR_INTERRUPT_VECTOR_IDX0 INT_VECTOR_T2
Definition at line 629 of file inszt_main.c.
DRV_TMR_INTERRUPT_VECTOR_IDX1
#define DRV_TMR_INTERRUPT_VECTOR_IDX1 INT_VECTOR_T7
Definition at line 640 of file inszt_main.c.
DRV_TMR_INTERRUPT_VECTOR_IDX2
#define DRV_TMR_INTERRUPT_VECTOR_IDX2 INT_VECTOR_T6
Definition at line 652 of file inszt_main.c.
DRV_TMR_INTERRUPT_VECTOR_IDX3
#define DRV_TMR_INTERRUPT_VECTOR_IDX3 INT_VECTOR_T1
Definition at line 664 of file inszt_main.c.
DRV_TMR_INTERRUPT_VECTOR_IDX4
#define DRV_TMR_INTERRUPT_VECTOR_IDX4 INT_VECTOR_T3
Definition at line 676 of file inszt_main.c.
DRV_TMR_ISR_VECTOR_IDX0
#define DRV_TMR_ISR_VECTOR_IDX0 _TIMER_2_VECTOR
Definition at line 630 of file inszt_main.c.
DRV_TMR_ISR_VECTOR_IDX1
#define DRV_TMR_ISR_VECTOR_IDX1 _TIMER_7_VECTOR
Definition at line 641 of file inszt_main.c.
DRV_TMR_ISR_VECTOR_IDX2
#define DRV_TMR_ISR_VECTOR_IDX2 _TIMER_6_VECTOR
Definition at line 653 of file inszt_main.c.
DRV_TMR_ISR_VECTOR_IDX3
#define DRV_TMR_ISR_VECTOR_IDX3 _TIMER_1_VECTOR
Definition at line 665 of file inszt_main.c.
DRV_TMR_ISR_VECTOR_IDX4
#define DRV_TMR_ISR_VECTOR_IDX4 _TIMER_3_VECTOR
Definition at line 677 of file inszt_main.c.
DRV_TMR_OPERATION_MODE_IDX0
#define DRV_TMR_OPERATION_MODE_IDX0 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 635 of file inszt_main.c.
DRV_TMR_OPERATION_MODE_IDX1
#define DRV_TMR_OPERATION_MODE_IDX1 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 646 of file inszt_main.c.
DRV_TMR_OPERATION_MODE_IDX2
#define DRV_TMR_OPERATION_MODE_IDX2 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 658 of file inszt_main.c.
DRV_TMR_OPERATION_MODE_IDX3
#define DRV_TMR_OPERATION_MODE_IDX3 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 670 of file inszt_main.c.
DRV_TMR_OPERATION_MODE_IDX4
#define DRV_TMR_OPERATION_MODE_IDX4 DRV_TMR_OPERATION_MODE_16_BIT
Definition at line 682 of file inszt_main.c.
DRV_TMR_PERIPHERAL_ID_IDX0
#define DRV_TMR_PERIPHERAL_ID_IDX0 TMR_ID_2
Definition at line 627 of file inszt_main.c.
DRV_TMR_PERIPHERAL_ID_IDX1
#define DRV_TMR_PERIPHERAL_ID_IDX1 TMR_ID_7
Definition at line 638 of file inszt_main.c.
DRV_TMR_PERIPHERAL_ID_IDX2
#define DRV_TMR_PERIPHERAL_ID_IDX2 TMR_ID_6
Definition at line 650 of file inszt_main.c.
DRV_TMR_PERIPHERAL_ID_IDX3
#define DRV_TMR_PERIPHERAL_ID_IDX3 TMR_ID_1
Definition at line 662 of file inszt_main.c.
DRV_TMR_PERIPHERAL_ID_IDX4
#define DRV_TMR_PERIPHERAL_ID_IDX4 TMR_ID_3
Definition at line 674 of file inszt_main.c.
DRV_TMR_POWER_STATE_IDX0
#define DRV_TMR_POWER_STATE_IDX0
Definition at line 637 of file inszt_main.c.
DRV_TMR_POWER_STATE_IDX1
#define DRV_TMR_POWER_STATE_IDX1
Definition at line 648 of file inszt_main.c.
DRV_TMR_POWER_STATE_IDX2
#define DRV_TMR_POWER_STATE_IDX2
Definition at line 660 of file inszt_main.c.
DRV_TMR_POWER_STATE_IDX3
#define DRV_TMR_POWER_STATE_IDX3
Definition at line 672 of file inszt_main.c.
DRV_TMR_POWER_STATE_IDX4
#define DRV_TMR_POWER_STATE_IDX4
Definition at line 684 of file inszt_main.c.
DRV_TMR_PRESCALE_IDX0
#define DRV_TMR_PRESCALE_IDX0 TMR_PRESCALE_VALUE_8
Definition at line 634 of file inszt_main.c.
DRV_TMR_PRESCALE_IDX1
#define DRV_TMR_PRESCALE_IDX1 TMR_PRESCALE_VALUE_16
Definition at line 645 of file inszt_main.c.
DRV_TMR_PRESCALE_IDX2
#define DRV_TMR_PRESCALE_IDX2 TMR_PRESCALE_VALUE_16
Definition at line 657 of file inszt_main.c.
DRV_TMR_PRESCALE_IDX3
#define DRV_TMR_PRESCALE_IDX3 TMR_PRESCALE_VALUE_256
Definition at line 669 of file inszt_main.c.
DRV_TMR_PRESCALE_IDX4
#define DRV_TMR_PRESCALE_IDX4 TMR_PRESCALE_VALUE_16
Definition at line 681 of file inszt_main.c.
DRV_USART_BUFFER_QUEUE_SUPPORT
#define DRV_USART_BUFFER_QUEUE_SUPPORT false
Definition at line 693 of file inszt_main.c.
DRV_USART_BYTE_MODEL_SUPPORT
#define DRV_USART_BYTE_MODEL_SUPPORT true
Definition at line 691 of file inszt_main.c.
DRV_USART_CLIENTS_NUMBER
#define DRV_USART_CLIENTS_NUMBER 1
Definition at line 689 of file inszt_main.c.
DRV_USART_INSTANCES_NUMBER
#define DRV_USART_INSTANCES_NUMBER 1
Definition at line 688 of file inszt_main.c.
DRV_USART_INTERRUPT_MODE
#define DRV_USART_INTERRUPT_MODE false
Definition at line 690 of file inszt_main.c.
DRV_USART_READ_WRITE_MODEL_SUPPORT
#define DRV_USART_READ_WRITE_MODEL_SUPPORT false
Definition at line 692 of file inszt_main.c.
DRV_USBHS_DEVICE_SUPPORT
#define DRV_USBHS_DEVICE_SUPPORT true
Definition at line 701 of file inszt_main.c.
DRV_USBHS_ENDPOINTS_NUMBER
#define DRV_USBHS_ENDPOINTS_NUMBER 2
Definition at line 709 of file inszt_main.c.
DRV_USBHS_HOST_SUPPORT
#define DRV_USBHS_HOST_SUPPORT false
Definition at line 703 of file inszt_main.c.
DRV_USBHS_INSTANCES_NUMBER
#define DRV_USBHS_INSTANCES_NUMBER 1
Definition at line 705 of file inszt_main.c.
DRV_USBHS_INTERRUPT_MODE
#define DRV_USBHS_INTERRUPT_MODE true
Definition at line 707 of file inszt_main.c.
ELEMENT [1/3]
#define ELEMENT (N) qqqbitmapint element##N;
Definition at line 199 of file inszt_main.c.
ELEMENT [2/3]
#define ELEMENT (N) 0,
Definition at line 199 of file inszt_main.c.
ELEMENT [3/3]
#define ELEMENT (N) qqbmsoutput("%8d", bitmapstruct.element##N);
Definition at line 199 of file inszt_main.c.
FILEPOINT
#define FILEPOINT
Definition at line 121 of file inszt_main.c.
FIRE_SW_OFFStateGet
#define FIRE_SW_OFFStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_8)
Definition at line 866 of file inszt_main.c.
FIRE_SW_ONStateGet
#define FIRE_SW_ONStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_8)
Definition at line 868 of file inszt_main.c.
FSK_DAC_CLROff
#define FSK_DAC_CLROff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 830 of file inszt_main.c.
FSK_DAC_CLROn
#define FSK_DAC_CLROn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 829 of file inszt_main.c.
FSK_DAC_CLRStateGet
#define FSK_DAC_CLRStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 831 of file inszt_main.c.
FSK_DAC_CLRStateSet
#define FSK_DAC_CLRStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7 , Value)
Definition at line 832 of file inszt_main.c.
FSK_DAC_CLRToggle
#define FSK_DAC_CLRToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_7)
Definition at line 828 of file inszt_main.c.
FSK_DAC_CSOff
#define FSK_DAC_CSOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 818 of file inszt_main.c.
FSK_DAC_CSOn
#define FSK_DAC_CSOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 817 of file inszt_main.c.
FSK_DAC_CSStateGet
#define FSK_DAC_CSStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 819 of file inszt_main.c.
FSK_DAC_CSStateSet
#define FSK_DAC_CSStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4 , Value)
Definition at line 820 of file inszt_main.c.
FSK_DAC_CSToggle
#define FSK_DAC_CSToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_4)
Definition at line 816 of file inszt_main.c.
HVPS_CN_PORT_BIT
#define HVPS_CN_PORT_BIT PORTS_BIT_POS_11
Definition at line 877 of file inszt_main.c.
HVPS_CN_PORT_CHANNEL
#define HVPS_CN_PORT_CHANNEL PORT_CHANNEL_J
Definition at line 876 of file inszt_main.c.
HVPS_CN_PORT_INTERRUPT
#define HVPS_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_J
Definition at line 878 of file inszt_main.c.
HVPS_ENBOff
#define HVPS_ENBOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 746 of file inszt_main.c.
HVPS_ENBOn
#define HVPS_ENBOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 745 of file inszt_main.c.
HVPS_ENBStateGet
#define HVPS_ENBStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 747 of file inszt_main.c.
HVPS_ENBStateSet
#define HVPS_ENBStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13 , Value)
Definition at line 748 of file inszt_main.c.
HVPS_ENBToggle
#define HVPS_ENBToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_13)
Definition at line 744 of file inszt_main.c.
HVPS_SWStateGet
#define HVPS_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_5)
Definition at line 840 of file inszt_main.c.
LASTELEMENT [1/2]
#define LASTELEMENT
Definition at line 200 of file inszt_main.c.
LASTELEMENT [2/2]
#define LASTELEMENT
Definition at line 200 of file inszt_main.c.
ldra_sscanf
#define ldra_sscanf
Definition at line 6730 of file inszt_main.c.
LDRA_VOID_FUNC
#define LDRA_VOID_FUNC
Definition at line 143 of file inszt_main.c.
LED1Off
#define LED1Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 728 of file inszt_main.c.
LED1On
#define LED1On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 727 of file inszt_main.c.
LED1StateGet
#define LED1StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 729 of file inszt_main.c.
LED1StateSet
#define LED1StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12 , Value)
Definition at line 730 of file inszt_main.c.
LED1Toggle
#define LED1Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_12)
Definition at line 726 of file inszt_main.c.
LED2Off
#define LED2Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 734 of file inszt_main.c.
LED2On
#define LED2On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 733 of file inszt_main.c.
LED2StateGet
#define LED2StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 735 of file inszt_main.c.
LED2StateSet
#define LED2StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10 , Value)
Definition at line 736 of file inszt_main.c.
LED2Toggle
#define LED2Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_10)
Definition at line 732 of file inszt_main.c.
LOG_SWStateGet
#define LOG_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_3)
Definition at line 856 of file inszt_main.c.
main_68zqqzqz1
#define main_68zqqzqz1 zqqzqz1
Definition at line 108 of file inszt_main.c.
Referenced by main(), main_68zqendz(), main_68zqzqzq(), and qqqupload().
main_68zzopen
#define main_68zzopen zzopen
Definition at line 106 of file inszt_main.c.
Referenced by main_68zqendz(), main_68zqqzqz(), main_68zqqzqz1(), and main_68zqzqzq().
MAN_CN_PORT_BIT
#define MAN_CN_PORT_BIT PORTS_BIT_POS_0
Definition at line 874 of file inszt_main.c.
MAN_CN_PORT_CHANNEL
#define MAN_CN_PORT_CHANNEL PORT_CHANNEL_A
Definition at line 873 of file inszt_main.c.
MAN_CN_PORT_INTERRUPT
#define MAN_CN_PORT_INTERRUPT INT_SOURCE_CHANGE_NOTICE_A
Definition at line 875 of file inszt_main.c.
MAN_SIGStateGet
#define MAN_SIGStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_0)
Definition at line 842 of file inszt_main.c.
NEG_SWStateGet
#define NEG_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_4)
Definition at line 846 of file inszt_main.c.
PLIB_PORTS_ChangeNoticePerPortHasOccured
#define PLIB_PORTS_ChangeNoticePerPortHasOccured PLIB_PORTS_ChangeNoticePerPortHasOccurred
Definition at line 5159 of file inszt_main.c.
POS_SWStateGet
#define POS_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_15)
Definition at line 848 of file inszt_main.c.
qqnull_params [1/2]
#define qqnull_params void
Definition at line 6747 of file inszt_main.c.
qqnull_params [2/2]
#define qqnull_params void
Definition at line 6747 of file inszt_main.c.
QQQ_PROTOTYPE_DEF
#define QQQ_PROTOTYPE_DEF
Definition at line 186 of file inszt_main.c.
QQQBITMAP
#define QQQBITMAP
Definition at line 94 of file inszt_main.c.
qqqbitmapint
#define qqqbitmapint unsigned int
Definition at line 95 of file inszt_main.c.
qqqbranches
#define qqqbranches 64
Definition at line 6709 of file inszt_main.c.
Referenced by qqbmsoutput().
QQQdialect
#define QQQdialect MPLABX
Definition at line 59 of file inszt_main.c.
QQQFILEID
#define QQQFILEID
Definition at line 102 of file inszt_main.c.
QQQFIXEDSIZE
#define QQQFIXEDSIZE
Definition at line 6755 of file inszt_main.c.
QQQLDRA_PORT
#define QQQLDRA_PORT
Definition at line 109 of file inszt_main.c.
QQQMAINFL
#define QQQMAINFL
Definition at line 100 of file inszt_main.c.
qqqMaxBranchDepth
#define qqqMaxBranchDepth 20
Definition at line 76 of file inszt_main.c.
QQQMAXMCDCSIZE
#define QQQMAXMCDCSIZE 2
Definition at line 6710 of file inszt_main.c.
QQQNOATEXIT
#define QQQNOATEXIT
Definition at line 90 of file inszt_main.c.
QQQNOSTDIO
#define QQQNOSTDIO
Definition at line 92 of file inszt_main.c.
QQQnumfil
#define QQQnumfil 23
Definition at line 80 of file inszt_main.c.
QQQseparate
#define QQQseparate
Definition at line 103 of file inszt_main.c.
QQQSINGLEFILE
#define QQQSINGLEFILE
Definition at line 101 of file inszt_main.c.
QQQstructbitmap
#define QQQstructbitmap
Definition at line 77 of file inszt_main.c.
QQQswitch3
#define QQQswitch3
Definition at line 69 of file inszt_main.c.
QQQTEMP1
#define QQQTEMP1
Definition at line 6895 of file inszt_main.c.
QQQUPLOADATEND
#define QQQUPLOADATEND
Definition at line 91 of file inszt_main.c.
qqzzidfield
#define qqzzidfield 1
Definition at line 6749 of file inszt_main.c.
RLY_ARMCFOff
#define RLY_ARMCFOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 794 of file inszt_main.c.
RLY_ARMCFOn
#define RLY_ARMCFOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 793 of file inszt_main.c.
RLY_ARMCFStateGet
#define RLY_ARMCFStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 795 of file inszt_main.c.
RLY_ARMCFStateSet
#define RLY_ARMCFStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13 , Value)
Definition at line 796 of file inszt_main.c.
RLY_ARMCFToggle
#define RLY_ARMCFToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_13)
Definition at line 792 of file inszt_main.c.
RLY_ARMOff
#define RLY_ARMOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 800 of file inszt_main.c.
RLY_ARMOn
#define RLY_ARMOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 799 of file inszt_main.c.
RLY_ARMStateGet
#define RLY_ARMStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 801 of file inszt_main.c.
RLY_ARMStateSet
#define RLY_ARMStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14 , Value)
Definition at line 802 of file inszt_main.c.
RLY_ARMToggle
#define RLY_ARMToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_14)
Definition at line 798 of file inszt_main.c.
RLY_AUXOff
#define RLY_AUXOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 776 of file inszt_main.c.
RLY_AUXOn
#define RLY_AUXOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 775 of file inszt_main.c.
RLY_AUXStateGet
#define RLY_AUXStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 777 of file inszt_main.c.
RLY_AUXStateSet
#define RLY_AUXStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11 , Value)
Definition at line 778 of file inszt_main.c.
RLY_AUXToggle
#define RLY_AUXToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_11)
Definition at line 774 of file inszt_main.c.
RLY_CCLOff
#define RLY_CCLOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 782 of file inszt_main.c.
RLY_CCLOn
#define RLY_CCLOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 781 of file inszt_main.c.
RLY_CCLStateGet
#define RLY_CCLStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 783 of file inszt_main.c.
RLY_CCLStateSet
#define RLY_CCLStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1 , Value)
Definition at line 784 of file inszt_main.c.
RLY_CCLToggle
#define RLY_CCLToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_A , PORTS_BIT_POS_1)
Definition at line 780 of file inszt_main.c.
RLY_COMMOff
#define RLY_COMMOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 824 of file inszt_main.c.
RLY_COMMOn
#define RLY_COMMOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 823 of file inszt_main.c.
RLY_COMMStateGet
#define RLY_COMMStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 825 of file inszt_main.c.
RLY_COMMStateSet
#define RLY_COMMStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14 , Value)
Definition at line 826 of file inszt_main.c.
RLY_COMMToggle
#define RLY_COMMToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_14)
Definition at line 822 of file inszt_main.c.
RLY_DMP_FIREOff
#define RLY_DMP_FIREOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 770 of file inszt_main.c.
RLY_DMP_FIREOn
#define RLY_DMP_FIREOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 769 of file inszt_main.c.
RLY_DMP_FIREStateGet
#define RLY_DMP_FIREStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 771 of file inszt_main.c.
RLY_DMP_FIREStateSet
#define RLY_DMP_FIREStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10 , Value)
Definition at line 772 of file inszt_main.c.
RLY_DMP_FIREToggle
#define RLY_DMP_FIREToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_10)
Definition at line 768 of file inszt_main.c.
RLY_HVPS_OUTOff
#define RLY_HVPS_OUTOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 752 of file inszt_main.c.
RLY_HVPS_OUTOn
#define RLY_HVPS_OUTOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 751 of file inszt_main.c.
RLY_HVPS_OUTStateGet
#define RLY_HVPS_OUTStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 753 of file inszt_main.c.
RLY_HVPS_OUTStateSet
#define RLY_HVPS_OUTStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14 , Value)
Definition at line 754 of file inszt_main.c.
RLY_HVPS_OUTToggle
#define RLY_HVPS_OUTToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_J , PORTS_BIT_POS_14)
Definition at line 750 of file inszt_main.c.
RLY_LOGOff
#define RLY_LOGOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 764 of file inszt_main.c.
RLY_LOGOn
#define RLY_LOGOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 763 of file inszt_main.c.
RLY_LOGStateGet
#define RLY_LOGStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 765 of file inszt_main.c.
RLY_LOGStateSet
#define RLY_LOGStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9 , Value)
Definition at line 766 of file inszt_main.c.
RLY_LOGToggle
#define RLY_LOGToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_9)
Definition at line 762 of file inszt_main.c.
RLY_WL_MONOff
#define RLY_WL_MONOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 788 of file inszt_main.c.
RLY_WL_MONOn
#define RLY_WL_MONOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 787 of file inszt_main.c.
RLY_WL_MONStateGet
#define RLY_WL_MONStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 789 of file inszt_main.c.
RLY_WL_MONStateSet
#define RLY_WL_MONStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12 , Value)
Definition at line 790 of file inszt_main.c.
RLY_WL_MONToggle
#define RLY_WL_MONToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_F , PORTS_BIT_POS_12)
Definition at line 786 of file inszt_main.c.
RLY_WL_SPS_POLOff
#define RLY_WL_SPS_POLOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 758 of file inszt_main.c.
RLY_WL_SPS_POLOn
#define RLY_WL_SPS_POLOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 757 of file inszt_main.c.
RLY_WL_SPS_POLStateGet
#define RLY_WL_SPS_POLStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 759 of file inszt_main.c.
RLY_WL_SPS_POLStateSet
#define RLY_WL_SPS_POLStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2 , Value)
Definition at line 760 of file inszt_main.c.
RLY_WL_SPS_POLToggle
#define RLY_WL_SPS_POLToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_2)
Definition at line 756 of file inszt_main.c.
SAFE_SWStateGet
#define SAFE_SWStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_B , PORTS_BIT_POS_1)
Definition at line 852 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_1
#define SYS_CLK_BUS_PERIPHERAL_1 100000000ul
Definition at line 445 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_2
#define SYS_CLK_BUS_PERIPHERAL_2 100000000ul
Definition at line 446 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_3
#define SYS_CLK_BUS_PERIPHERAL_3 100000000ul
Definition at line 447 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_4
#define SYS_CLK_BUS_PERIPHERAL_4 100000000ul
Definition at line 448 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_5
#define SYS_CLK_BUS_PERIPHERAL_5 100000000ul
Definition at line 449 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_7
#define SYS_CLK_BUS_PERIPHERAL_7 200000000ul
Definition at line 450 of file inszt_main.c.
SYS_CLK_BUS_PERIPHERAL_8
#define SYS_CLK_BUS_PERIPHERAL_8 100000000ul
Definition at line 451 of file inszt_main.c.
SYS_CLK_CONFIG_PRIMARY_XTAL
#define SYS_CLK_CONFIG_PRIMARY_XTAL 0ul
Definition at line 452 of file inszt_main.c.
SYS_CLK_CONFIG_SECONDARY_XTAL
#define SYS_CLK_CONFIG_SECONDARY_XTAL 32768ul
Definition at line 453 of file inszt_main.c.
SYS_CLK_FREQ
#define SYS_CLK_FREQ 200000000ul
Definition at line 444 of file inszt_main.c.
SYS_INT
#define SYS_INT true
Definition at line 526 of file inszt_main.c.
SYS_PORT_A_ANSEL
#define SYS_PORT_A_ANSEL 0x3F00
Definition at line 455 of file inszt_main.c.
SYS_PORT_A_CNEN
#define SYS_PORT_A_CNEN 0x0021
Definition at line 461 of file inszt_main.c.
SYS_PORT_A_CNPD
#define SYS_PORT_A_CNPD 0x0000
Definition at line 460 of file inszt_main.c.
SYS_PORT_A_CNPU
#define SYS_PORT_A_CNPU 0x0020
Definition at line 459 of file inszt_main.c.
SYS_PORT_A_LAT
#define SYS_PORT_A_LAT 0x0010
Definition at line 457 of file inszt_main.c.
SYS_PORT_A_ODC
#define SYS_PORT_A_ODC 0x0000
Definition at line 458 of file inszt_main.c.
SYS_PORT_A_TRIS
#define SYS_PORT_A_TRIS 0xFFED
Definition at line 456 of file inszt_main.c.
SYS_PORT_B_ANSEL
#define SYS_PORT_B_ANSEL 0x10C8
Definition at line 462 of file inszt_main.c.
SYS_PORT_B_CNEN
#define SYS_PORT_B_CNEN 0x0000
Definition at line 468 of file inszt_main.c.
SYS_PORT_B_CNPD
#define SYS_PORT_B_CNPD 0x0000
Definition at line 467 of file inszt_main.c.
SYS_PORT_B_CNPU
#define SYS_PORT_B_CNPU 0x0000
Definition at line 466 of file inszt_main.c.
SYS_PORT_B_LAT
#define SYS_PORT_B_LAT 0x0000
Definition at line 464 of file inszt_main.c.
SYS_PORT_B_ODC
#define SYS_PORT_B_ODC 0x0000
Definition at line 465 of file inszt_main.c.
SYS_PORT_B_TRIS
#define SYS_PORT_B_TRIS 0x91FF
Definition at line 463 of file inszt_main.c.
SYS_PORT_C_ANSEL
#define SYS_PORT_C_ANSEL 0xCFE1
Definition at line 469 of file inszt_main.c.
SYS_PORT_C_CNEN
#define SYS_PORT_C_CNEN 0x0000
Definition at line 475 of file inszt_main.c.
SYS_PORT_C_CNPD
#define SYS_PORT_C_CNPD 0x0000
Definition at line 474 of file inszt_main.c.
SYS_PORT_C_CNPU
#define SYS_PORT_C_CNPU 0x0000
Definition at line 473 of file inszt_main.c.
SYS_PORT_C_LAT
#define SYS_PORT_C_LAT 0x0000
Definition at line 471 of file inszt_main.c.
SYS_PORT_C_ODC
#define SYS_PORT_C_ODC 0x0000
Definition at line 472 of file inszt_main.c.
SYS_PORT_C_TRIS
#define SYS_PORT_C_TRIS 0xFFFF
Definition at line 470 of file inszt_main.c.
SYS_PORT_D_ANSEL
#define SYS_PORT_D_ANSEL 0xC100
Definition at line 476 of file inszt_main.c.
SYS_PORT_D_CNEN
#define SYS_PORT_D_CNEN 0x0000
Definition at line 482 of file inszt_main.c.
SYS_PORT_D_CNPD
#define SYS_PORT_D_CNPD 0x0000
Definition at line 481 of file inszt_main.c.
SYS_PORT_D_CNPU
#define SYS_PORT_D_CNPU 0x0000
Definition at line 480 of file inszt_main.c.
SYS_PORT_D_LAT
#define SYS_PORT_D_LAT 0x0000
Definition at line 478 of file inszt_main.c.
SYS_PORT_D_ODC
#define SYS_PORT_D_ODC 0x0000
Definition at line 479 of file inszt_main.c.
SYS_PORT_D_TRIS
#define SYS_PORT_D_TRIS 0xFFFF
Definition at line 477 of file inszt_main.c.
SYS_PORT_E_ANSEL
#define SYS_PORT_E_ANSEL 0xFC00
Definition at line 483 of file inszt_main.c.
SYS_PORT_E_CNEN
#define SYS_PORT_E_CNEN 0x0000
Definition at line 489 of file inszt_main.c.
SYS_PORT_E_CNPD
#define SYS_PORT_E_CNPD 0x0000
Definition at line 488 of file inszt_main.c.
SYS_PORT_E_CNPU
#define SYS_PORT_E_CNPU 0x0000
Definition at line 487 of file inszt_main.c.
SYS_PORT_E_LAT
#define SYS_PORT_E_LAT 0x0000
Definition at line 485 of file inszt_main.c.
SYS_PORT_E_ODC
#define SYS_PORT_E_ODC 0x0000
Definition at line 486 of file inszt_main.c.
SYS_PORT_E_TRIS
#define SYS_PORT_E_TRIS 0xFDFF
Definition at line 484 of file inszt_main.c.
SYS_PORT_F_ANSEL
#define SYS_PORT_F_ANSEL 0xCEC0
Definition at line 490 of file inszt_main.c.
SYS_PORT_F_CNEN
#define SYS_PORT_F_CNEN 0x0000
Definition at line 496 of file inszt_main.c.
SYS_PORT_F_CNPD
#define SYS_PORT_F_CNPD 0x0000
Definition at line 495 of file inszt_main.c.
SYS_PORT_F_CNPU
#define SYS_PORT_F_CNPU 0x0000
Definition at line 494 of file inszt_main.c.
SYS_PORT_F_LAT
#define SYS_PORT_F_LAT 0x0000
Definition at line 492 of file inszt_main.c.
SYS_PORT_F_ODC
#define SYS_PORT_F_ODC 0x0000
Definition at line 493 of file inszt_main.c.
SYS_PORT_F_TRIS
#define SYS_PORT_F_TRIS 0xEFFF
Definition at line 491 of file inszt_main.c.
SYS_PORT_G_ANSEL
#define SYS_PORT_G_ANSEL 0x8CBC
Definition at line 497 of file inszt_main.c.
SYS_PORT_G_CNEN
#define SYS_PORT_G_CNEN 0x0000
Definition at line 503 of file inszt_main.c.
SYS_PORT_G_CNPD
#define SYS_PORT_G_CNPD 0x0000
Definition at line 502 of file inszt_main.c.
SYS_PORT_G_CNPU
#define SYS_PORT_G_CNPU 0x0000
Definition at line 501 of file inszt_main.c.
SYS_PORT_G_LAT
#define SYS_PORT_G_LAT 0x0000
Definition at line 499 of file inszt_main.c.
SYS_PORT_G_ODC
#define SYS_PORT_G_ODC 0x0000
Definition at line 500 of file inszt_main.c.
SYS_PORT_G_TRIS
#define SYS_PORT_G_TRIS 0xDFFF
Definition at line 498 of file inszt_main.c.
SYS_PORT_H_ANSEL
#define SYS_PORT_H_ANSEL 0x0070
Definition at line 504 of file inszt_main.c.
SYS_PORT_H_CNEN
#define SYS_PORT_H_CNEN 0x0000
Definition at line 510 of file inszt_main.c.
SYS_PORT_H_CNPD
#define SYS_PORT_H_CNPD 0x0000
Definition at line 509 of file inszt_main.c.
SYS_PORT_H_CNPU
#define SYS_PORT_H_CNPU 0x0000
Definition at line 508 of file inszt_main.c.
SYS_PORT_H_LAT
#define SYS_PORT_H_LAT 0x0000
Definition at line 506 of file inszt_main.c.
SYS_PORT_H_ODC
#define SYS_PORT_H_ODC 0x0000
Definition at line 507 of file inszt_main.c.
SYS_PORT_H_TRIS
#define SYS_PORT_H_TRIS 0xB3FB
Definition at line 505 of file inszt_main.c.
SYS_PORT_J_ANSEL
#define SYS_PORT_J_ANSEL 0x0000
Definition at line 511 of file inszt_main.c.
SYS_PORT_J_CNEN
#define SYS_PORT_J_CNEN 0x0800
Definition at line 517 of file inszt_main.c.
SYS_PORT_J_CNPD
#define SYS_PORT_J_CNPD 0x0000
Definition at line 516 of file inszt_main.c.
SYS_PORT_J_CNPU
#define SYS_PORT_J_CNPU 0x0000
Definition at line 515 of file inszt_main.c.
SYS_PORT_J_LAT
#define SYS_PORT_J_LAT 0x0080
Definition at line 513 of file inszt_main.c.
SYS_PORT_J_ODC
#define SYS_PORT_J_ODC 0x0000
Definition at line 514 of file inszt_main.c.
SYS_PORT_J_TRIS
#define SYS_PORT_J_TRIS 0x8B7F
Definition at line 512 of file inszt_main.c.
SYS_PORT_K_ANSEL
#define SYS_PORT_K_ANSEL 0xFF00
Definition at line 518 of file inszt_main.c.
SYS_PORT_K_CNEN
#define SYS_PORT_K_CNEN 0x0000
Definition at line 524 of file inszt_main.c.
SYS_PORT_K_CNPD
#define SYS_PORT_K_CNPD 0x0000
Definition at line 523 of file inszt_main.c.
SYS_PORT_K_CNPU
#define SYS_PORT_K_CNPU 0x0000
Definition at line 522 of file inszt_main.c.
SYS_PORT_K_LAT
#define SYS_PORT_K_LAT 0x0000
Definition at line 520 of file inszt_main.c.
SYS_PORT_K_ODC
#define SYS_PORT_K_ODC 0x0000
Definition at line 521 of file inszt_main.c.
SYS_PORT_K_TRIS
#define SYS_PORT_K_TRIS 0xFFFF
Definition at line 519 of file inszt_main.c.
SYS_TMR_CLIENT_TOLERANCE
#define SYS_TMR_CLIENT_TOLERANCE 10
Definition at line 534 of file inszt_main.c.
SYS_TMR_DRIVER_INDEX
#define SYS_TMR_DRIVER_INDEX DRV_TMR_INDEX_0
Definition at line 529 of file inszt_main.c.
SYS_TMR_FREQUENCY
#define SYS_TMR_FREQUENCY 1000
Definition at line 531 of file inszt_main.c.
SYS_TMR_FREQUENCY_TOLERANCE
#define SYS_TMR_FREQUENCY_TOLERANCE 10
Definition at line 532 of file inszt_main.c.
SYS_TMR_INTERRUPT_NOTIFICATION
#define SYS_TMR_INTERRUPT_NOTIFICATION false
Definition at line 535 of file inszt_main.c.
SYS_TMR_MAX_CLIENT_OBJECTS
#define SYS_TMR_MAX_CLIENT_OBJECTS 5
Definition at line 530 of file inszt_main.c.
SYS_TMR_POWER_STATE
#define SYS_TMR_POWER_STATE SYS_MODULE_POWER_RUN_FULL
Definition at line 528 of file inszt_main.c.
SYS_TMR_UNIT_RESOLUTION
#define SYS_TMR_UNIT_RESOLUTION 10000
Definition at line 533 of file inszt_main.c.
SYS_VERSION
#define SYS_VERSION 20600
Definition at line 440 of file inszt_main.c.
SYS_VERSION_STR
#define SYS_VERSION_STR "2.06"
Definition at line 439 of file inszt_main.c.
TEST_H
#define TEST_H
Definition at line 370 of file inszt_main.c.
TPAN1Off
#define TPAN1Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 806 of file inszt_main.c.
TPAN1On
#define TPAN1On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 805 of file inszt_main.c.
TPAN1StateGet
#define TPAN1StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 807 of file inszt_main.c.
TPAN1StateSet
#define TPAN1StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10 , Value)
Definition at line 808 of file inszt_main.c.
TPAN1Toggle
#define TPAN1Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_10)
Definition at line 804 of file inszt_main.c.
TPAN2Off
#define TPAN2Off () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 812 of file inszt_main.c.
TPAN2On
#define TPAN2On () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 811 of file inszt_main.c.
TPAN2StateGet
#define TPAN2StateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 813 of file inszt_main.c.
TPAN2StateSet
#define TPAN2StateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11 , Value)
Definition at line 814 of file inszt_main.c.
TPAN2Toggle
#define TPAN2Toggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_11)
Definition at line 810 of file inszt_main.c.
UPLOAD_EXECUTION_HISTORY
#define UPLOAD_EXECUTION_HISTORY
Definition at line 6716 of file inszt_main.c.
USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
#define USB_DEVICE_DRIVER_INITIALIZE_EXPLICIT
Definition at line 712 of file inszt_main.c.
USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED
#define USB_DEVICE_ENDPOINT_QUEUE_DEPTH_COMBINED 2
Definition at line 718 of file inszt_main.c.
USB_DEVICE_EP0_BUFFER_SIZE
#define USB_DEVICE_EP0_BUFFER_SIZE 64
Definition at line 716 of file inszt_main.c.
USB_DEVICE_INSTANCES_NUMBER
#define USB_DEVICE_INSTANCES_NUMBER 1
Definition at line 714 of file inszt_main.c.
USE_8BIT_PMP
#define USE_8BIT_PMP
Definition at line 542 of file inszt_main.c.
WL_CPS_SWOff
#define WL_CPS_SWOff () PLIB_PORTS_PinClear (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 836 of file inszt_main.c.
WL_CPS_SWOn
#define WL_CPS_SWOn () PLIB_PORTS_PinSet (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 835 of file inszt_main.c.
WL_CPS_SWStateGet
#define WL_CPS_SWStateGet () PLIB_PORTS_PinGetLatched (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 837 of file inszt_main.c.
WL_CPS_SWStateSet
#define WL_CPS_SWStateSet (Value) PLIB_PORTS_PinWrite (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13 , Value)
Definition at line 838 of file inszt_main.c.
WL_CPS_SWToggle
#define WL_CPS_SWToggle () PLIB_PORTS_PinToggle (PORTS_ID_0 , PORT_CHANNEL_G , PORTS_BIT_POS_13)
Definition at line 834 of file inszt_main.c.
WL_SPS_NEG_DETStateGet
#define WL_SPS_NEG_DETStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_13)
Definition at line 872 of file inszt_main.c.
WL_SPS_POS_DETStateGet
#define WL_SPS_POS_DETStateGet () PLIB_PORTS_PinGet (PORTS_ID_0 , PORT_CHANNEL_H , PORTS_BIT_POS_12)
Definition at line 870 of file inszt_main.c.
Typedef Documentation
ldra_void_function
typedef void(* ldra_void_function) ()
Definition at line 144 of file inszt_main.c.
PORTS_DATA_MASK
typedef uint16_t PORTS_DATA_MASK
Definition at line 1847 of file inszt_main.c.
PORTS_DATA_TYPE
typedef uint32_t PORTS_DATA_TYPE
Definition at line 1860 of file inszt_main.c.
Enumeration Type Documentation
DRV_ADC_MODULE_ID
enum DRV_ADC_MODULE_ID
Enumerator
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
DRV_ADC_ID_1
DRV_ADCHS_NUMBER_OF_MODULES
Definition at line 986 of file inszt_main.c.
PORTS_PIN_INTERRUPT_TYPE
enum PORTS_PIN_INTERRUPT_TYPE
Enumerator
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
PORTS_PIN_INTERRUPT_NONE
Definition at line 5231 of file inszt_main.c.
SYS_PORTS_PIN_DIRECTION
enum SYS_PORTS_PIN_DIRECTION
Enumerator
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
SYS_PORTS_DIRECTION_OUTPUT
SYS_PORTS_DIRECTION_INPUT
Definition at line 5216 of file inszt_main.c.
SYS_PORTS_PULLUP_PULLDOWN_STATUS
enum SYS_PORTS_PULLUP_PULLDOWN_STATUS
Enumerator
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
SYS_PORTS_PULLUP_DISABLE
SYS_PORTS_PULLUP_ENABLE
Definition at line 5192 of file inszt_main.c.
Function Documentation
APP_Initialize()
void APP_Initialize (void)
Function: void APP_Initialize(void) Summary: Autonomous tool application initialization routine. Description: This function initializes the application. It places the application in its initial state and prepares it to run so that its APP_Tasks function can be called. Precondition: All other system initialization routines should be called before calling this routine (in "SYS_Initialize"). Parameters: None. Returns: None. Example: APP_Initialize() Remarks: This routine must be called from the main function.
Definition at line 93 of file app.c.
Referenced by main().
APP_Tasks()
void APP_Tasks (void)
Function: void APP_Tasks(void) Summary: Application tasks function Description: This function is the main application's tasks function. It contains the various tasks that are maintained during the operation of the shooting panel. Precondition: The system ("SYS_Initialize") and application ("APP_Initialize") initialization should be called before calling this. Parameters: None. Returns: None. Example: APP_Tasks() Remarks: This routine must be called from the main() routine.
Definition at line 130 of file app.c.
Referenced by main().
DRV_ADC0_Close()
void DRV_ADC0_Close (void) inline
DRV_ADC0_Open()
void DRV_ADC0_Open (void) inline
DRV_ADC1_Close()
void DRV_ADC1_Close (void) inline
DRV_ADC1_Open()
void DRV_ADC1_Open (void) inline
DRV_ADC_DeInitialize()
void DRV_ADC_DeInitialize (void) inline
DRV_ADC_Initialize()
void DRV_ADC_Initialize (void)
DRV_ADC_SamplesAvailable()
bool DRV_ADC_SamplesAvailable (uint8_t bufIndex)
DRV_ADC_SamplesRead()
uint32_t DRV_ADC_SamplesRead (uint8_t bufIndex)
DRV_ADC_Start()
void DRV_ADC_Start (void) inline
DRV_ADC_Stop()
void DRV_ADC_Stop (void) inline
DRV_PMP0_Initialize()
void DRV_PMP0_Initialize (void)
DRV_PMP0_ModeConfig()
void DRV_PMP0_ModeConfig (void)
DRV_PMP0_Read()
uint8_t DRV_PMP0_Read (void)
DRV_PMP0_TimingSet()
void DRV_PMP0_TimingSet (PMP_DATA_WAIT_STATES dataWait, PMP_STROBE_WAIT_STATES strobeWait, PMP_DATA_HOLD_STATES dataHold)
DRV_PMP0_Write()
void DRV_PMP0_Write (uint8_t data)
DRV_TMR0_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR0_ClientStatus (void)
DRV_TMR0_ClockSet()
bool DRV_TMR0_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR0_Close()
static void DRV_TMR0_Close (void) inline static
Definition at line 1150 of file inszt_main.c.
DRV_TMR0_CounterClear()
void DRV_TMR0_CounterClear (void)
DRV_TMR0_CounterFrequencyGet()
uint32_t DRV_TMR0_CounterFrequencyGet (void)
DRV_TMR0_CounterValueGet()
uint32_t DRV_TMR0_CounterValueGet (void)
DRV_TMR0_CounterValueSet()
void DRV_TMR0_CounterValueSet (uint32_t value)
DRV_TMR0_DeInitialize()
static void DRV_TMR0_DeInitialize (void) inline static
Definition at line 1113 of file inszt_main.c.
DRV_TMR0_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR0_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR0_Initialize()
void DRV_TMR0_Initialize (void)
DRV_TMR0_Open()
static void DRV_TMR0_Open (void) inline static
Definition at line 1131 of file inszt_main.c.
DRV_TMR0_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR0_OperationModeGet (void) inline static
Definition at line 1141 of file inszt_main.c.
DRV_TMR0_PeriodValueGet()
uint32_t DRV_TMR0_PeriodValueGet (void)
DRV_TMR0_PeriodValueSet()
void DRV_TMR0_PeriodValueSet (uint32_t value)
DRV_TMR0_PrescalerGet()
TMR_PRESCALE DRV_TMR0_PrescalerGet (void)
DRV_TMR0_Start()
bool DRV_TMR0_Start (void)
DRV_TMR0_Status()
static SYS_STATUS DRV_TMR0_Status (void) inline static
Definition at line 1121 of file inszt_main.c.
DRV_TMR0_Stop()
void DRV_TMR0_Stop (void)
Referenced by DRV_TMR0_Close(), and DRV_TMR0_DeInitialize().
DRV_TMR0_StopInIdleDisable()
void DRV_TMR0_StopInIdleDisable (void)
DRV_TMR0_StopInIdleEnable()
void DRV_TMR0_StopInIdleEnable (void)
DRV_TMR0_Tasks()
static void DRV_TMR0_Tasks (void) inline static
Definition at line 1189 of file inszt_main.c.
DRV_TMR1_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR1_ClientStatus (void)
DRV_TMR1_ClockSet()
bool DRV_TMR1_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR1_Close()
static void DRV_TMR1_Close (void) inline static
Definition at line 1254 of file inszt_main.c.
DRV_TMR1_CounterClear()
void DRV_TMR1_CounterClear (void)
DRV_TMR1_CounterFrequencyGet()
uint32_t DRV_TMR1_CounterFrequencyGet (void)
DRV_TMR1_CounterValueGet()
uint32_t DRV_TMR1_CounterValueGet (void)
DRV_TMR1_CounterValueSet()
void DRV_TMR1_CounterValueSet (uint32_t value)
DRV_TMR1_DeInitialize()
static void DRV_TMR1_DeInitialize (void) inline static
Definition at line 1217 of file inszt_main.c.
DRV_TMR1_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR1_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR1_Initialize()
void DRV_TMR1_Initialize (void)
DRV_TMR1_Open()
static void DRV_TMR1_Open (void) inline static
Definition at line 1235 of file inszt_main.c.
DRV_TMR1_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR1_OperationModeGet (void) inline static
Definition at line 1245 of file inszt_main.c.
DRV_TMR1_PeriodValueGet()
uint32_t DRV_TMR1_PeriodValueGet (void)
DRV_TMR1_PeriodValueSet()
void DRV_TMR1_PeriodValueSet (uint32_t value)
DRV_TMR1_PrescalerGet()
TMR_PRESCALE DRV_TMR1_PrescalerGet (void)
DRV_TMR1_Start()
bool DRV_TMR1_Start (void)
DRV_TMR1_Status()
static SYS_STATUS DRV_TMR1_Status (void) inline static
Definition at line 1225 of file inszt_main.c.
DRV_TMR1_Stop()
void DRV_TMR1_Stop (void)
Referenced by DRV_TMR1_Close(), and DRV_TMR1_DeInitialize().
DRV_TMR1_StopInIdleDisable()
void DRV_TMR1_StopInIdleDisable (void)
DRV_TMR1_StopInIdleEnable()
void DRV_TMR1_StopInIdleEnable (void)
DRV_TMR1_Tasks()
static void DRV_TMR1_Tasks (void) inline static
Definition at line 1293 of file inszt_main.c.
DRV_TMR2_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR2_ClientStatus (void)
DRV_TMR2_ClockSet()
bool DRV_TMR2_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR2_Close()
static void DRV_TMR2_Close (void) inline static
Definition at line 1358 of file inszt_main.c.
DRV_TMR2_CounterClear()
void DRV_TMR2_CounterClear (void)
DRV_TMR2_CounterFrequencyGet()
uint32_t DRV_TMR2_CounterFrequencyGet (void)
DRV_TMR2_CounterValueGet()
uint32_t DRV_TMR2_CounterValueGet (void)
DRV_TMR2_CounterValueSet()
void DRV_TMR2_CounterValueSet (uint32_t value)
DRV_TMR2_DeInitialize()
static void DRV_TMR2_DeInitialize (void) inline static
Definition at line 1321 of file inszt_main.c.
DRV_TMR2_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR2_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR2_Initialize()
void DRV_TMR2_Initialize (void)
DRV_TMR2_Open()
static void DRV_TMR2_Open (void) inline static
Definition at line 1339 of file inszt_main.c.
DRV_TMR2_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR2_OperationModeGet (void) inline static
Definition at line 1349 of file inszt_main.c.
DRV_TMR2_PeriodValueGet()
uint32_t DRV_TMR2_PeriodValueGet (void)
DRV_TMR2_PeriodValueSet()
void DRV_TMR2_PeriodValueSet (uint32_t value)
DRV_TMR2_PrescalerGet()
TMR_PRESCALE DRV_TMR2_PrescalerGet (void)
DRV_TMR2_Start()
bool DRV_TMR2_Start (void)
DRV_TMR2_Status()
static SYS_STATUS DRV_TMR2_Status (void) inline static
Definition at line 1329 of file inszt_main.c.
DRV_TMR2_Stop()
void DRV_TMR2_Stop (void)
Referenced by DRV_TMR2_Close(), and DRV_TMR2_DeInitialize().
DRV_TMR2_StopInIdleDisable()
void DRV_TMR2_StopInIdleDisable (void)
DRV_TMR2_StopInIdleEnable()
void DRV_TMR2_StopInIdleEnable (void)
DRV_TMR2_Tasks()
static void DRV_TMR2_Tasks (void) inline static
Definition at line 1397 of file inszt_main.c.
DRV_TMR3_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR3_ClientStatus (void)
DRV_TMR3_ClockSet()
bool DRV_TMR3_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR3_Close()
static void DRV_TMR3_Close (void) inline static
Definition at line 1462 of file inszt_main.c.
DRV_TMR3_CounterClear()
void DRV_TMR3_CounterClear (void)
DRV_TMR3_CounterFrequencyGet()
uint32_t DRV_TMR3_CounterFrequencyGet (void)
DRV_TMR3_CounterValueGet()
uint32_t DRV_TMR3_CounterValueGet (void)
DRV_TMR3_CounterValueSet()
void DRV_TMR3_CounterValueSet (uint32_t value)
DRV_TMR3_DeInitialize()
static void DRV_TMR3_DeInitialize (void) inline static
Definition at line 1425 of file inszt_main.c.
DRV_TMR3_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR3_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR3_Initialize()
void DRV_TMR3_Initialize (void)
DRV_TMR3_Open()
static void DRV_TMR3_Open (void) inline static
Definition at line 1443 of file inszt_main.c.
DRV_TMR3_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR3_OperationModeGet (void) inline static
Definition at line 1453 of file inszt_main.c.
DRV_TMR3_PeriodValueGet()
uint32_t DRV_TMR3_PeriodValueGet (void)
DRV_TMR3_PeriodValueSet()
void DRV_TMR3_PeriodValueSet (uint32_t value)
DRV_TMR3_PrescalerGet()
TMR_PRESCALE DRV_TMR3_PrescalerGet (void)
DRV_TMR3_Start()
bool DRV_TMR3_Start (void)
DRV_TMR3_Status()
static SYS_STATUS DRV_TMR3_Status (void) inline static
Definition at line 1433 of file inszt_main.c.
DRV_TMR3_Stop()
void DRV_TMR3_Stop (void)
Referenced by DRV_TMR3_Close(), and DRV_TMR3_DeInitialize().
DRV_TMR3_StopInIdleDisable()
void DRV_TMR3_StopInIdleDisable (void)
DRV_TMR3_StopInIdleEnable()
void DRV_TMR3_StopInIdleEnable (void)
DRV_TMR3_Tasks()
static void DRV_TMR3_Tasks (void) inline static
Definition at line 1501 of file inszt_main.c.
DRV_TMR4_ClientStatus()
DRV_TMR_CLIENT_STATUS DRV_TMR4_ClientStatus (void)
DRV_TMR4_ClockSet()
bool DRV_TMR4_ClockSet (DRV_TMR_CLK_SOURCES clockSource, TMR_PRESCALE prescale)
DRV_TMR4_Close()
static void DRV_TMR4_Close (void) inline static
Definition at line 1566 of file inszt_main.c.
DRV_TMR4_CounterClear()
void DRV_TMR4_CounterClear (void)
DRV_TMR4_CounterFrequencyGet()
uint32_t DRV_TMR4_CounterFrequencyGet (void)
DRV_TMR4_CounterValueGet()
uint32_t DRV_TMR4_CounterValueGet (void)
DRV_TMR4_CounterValueSet()
void DRV_TMR4_CounterValueSet (uint32_t value)
DRV_TMR4_DeInitialize()
static void DRV_TMR4_DeInitialize (void) inline static
Definition at line 1529 of file inszt_main.c.
DRV_TMR4_DividerRangeGet()
DRV_TMR_OPERATION_MODE DRV_TMR4_DividerRangeGet (DRV_TMR_DIVIDER_RANGE * pDivRange)
DRV_TMR4_Initialize()
void DRV_TMR4_Initialize (void)
DRV_TMR4_Open()
static void DRV_TMR4_Open (void) inline static
Definition at line 1547 of file inszt_main.c.
DRV_TMR4_OperationModeGet()
static DRV_TMR_OPERATION_MODE DRV_TMR4_OperationModeGet (void) inline static
Definition at line 1557 of file inszt_main.c.
DRV_TMR4_PeriodValueGet()
uint32_t DRV_TMR4_PeriodValueGet (void)
DRV_TMR4_PeriodValueSet()
void DRV_TMR4_PeriodValueSet (uint32_t value)
DRV_TMR4_PrescalerGet()
TMR_PRESCALE DRV_TMR4_PrescalerGet (void)
DRV_TMR4_Start()
bool DRV_TMR4_Start (void)
DRV_TMR4_Status()
static SYS_STATUS DRV_TMR4_Status (void) inline static
Definition at line 1537 of file inszt_main.c.
DRV_TMR4_Stop()
void DRV_TMR4_Stop (void)
Referenced by DRV_TMR4_Close(), and DRV_TMR4_DeInitialize().
DRV_TMR4_StopInIdleDisable()
void DRV_TMR4_StopInIdleDisable (void)
DRV_TMR4_StopInIdleEnable()
void DRV_TMR4_StopInIdleEnable (void)
DRV_TMR4_Tasks()
static void DRV_TMR4_Tasks (void) inline static
Definition at line 1605 of file inszt_main.c.
main()
int main (void)
Definition at line 6678 of file inszt_main.c.
main_68zqendz()
static int main_68zqendz (int qqqi) static
Definition at line 6940 of file inszt_main.c.
Referenced by main_68zqzqzq().
main_68zqqzqz()
static int main_68zqqzqz (qqnull_params) static
Definition at line 6905 of file inszt_main.c.
main_68zqqzqz1()
static int main_68zqqzqz1 (qqnull_params) static
Definition at line 6925 of file inszt_main.c.
main_68zqzqzq()
static int main_68zqzqzq (int qqqi) static
Definition at line 7033 of file inszt_main.c.
Referenced by main().
main_68zscanf()
static int main_68zscanf (char * qqscan_str) static
Definition at line 6771 of file inszt_main.c.
PLIB_PORTS_AnPinsModeSelect()
void PLIB_PORTS_AnPinsModeSelect (PORTS_MODULE_ID index, PORTS_AN_PIN anPins, PORTS_PIN_MODE mode)
PLIB_PORTS_ChangeNoticeDisable()
void PLIB_PORTS_ChangeNoticeDisable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeEnable()
void PLIB_PORTS_ChangeNoticeEnable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdleDisable()
void PLIB_PORTS_ChangeNoticeInIdleDisable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdleEnable()
void PLIB_PORTS_ChangeNoticeInIdleEnable (PORTS_MODULE_ID index)
PLIB_PORTS_ChangeNoticeInIdlePerPortDisable()
void PLIB_PORTS_ChangeNoticeInIdlePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticeInIdlePerPortEnable()
void PLIB_PORTS_ChangeNoticeInIdlePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePerPortHasOccurred()
bool PLIB_PORTS_ChangeNoticePerPortHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePerPortTurnOff()
void PLIB_PORTS_ChangeNoticePerPortTurnOff (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePerPortTurnOn()
void PLIB_PORTS_ChangeNoticePerPortTurnOn (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChangeNoticePullDownPerPortDisable()
void PLIB_PORTS_ChangeNoticePullDownPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullDownPerPortEnable()
void PLIB_PORTS_ChangeNoticePullDownPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullUpDisable()
void PLIB_PORTS_ChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_ChangeNoticePullUpEnable()
void PLIB_PORTS_ChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_ChangeNoticePullUpPerPortDisable()
void PLIB_PORTS_ChangeNoticePullUpPerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChangeNoticePullUpPerPortEnable()
void PLIB_PORTS_ChangeNoticePullUpPerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_ChannelChangeNoticeDisable()
void PLIB_PORTS_ChannelChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticeEdgeDisable()
void PLIB_PORTS_ChannelChangeNoticeEdgeDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
PLIB_PORTS_ChannelChangeNoticeEdgeEnable()
void PLIB_PORTS_ChannelChangeNoticeEdgeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK edgeRisingMask, PORTS_DATA_MASK edgeFallingMask)
PLIB_PORTS_ChannelChangeNoticeEnable()
void PLIB_PORTS_ChannelChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticeMethodGet()
PORTS_CHANGE_NOTICE_METHOD PLIB_PORTS_ChannelChangeNoticeMethodGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ChannelChangeNoticeMethodSelect()
void PLIB_PORTS_ChannelChangeNoticeMethodSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_CHANGE_NOTICE_METHOD changeNoticeMethod)
PLIB_PORTS_ChannelChangeNoticePullDownDisable()
void PLIB_PORTS_ChannelChangeNoticePullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullDownEnable()
void PLIB_PORTS_ChannelChangeNoticePullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullUpDisable()
void PLIB_PORTS_ChannelChangeNoticePullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelChangeNoticePullUpEnable()
void PLIB_PORTS_ChannelChangeNoticePullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ChannelModeSelect()
void PLIB_PORTS_ChannelModeSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK modeMask, PORTS_PIN_MODE mode)
PLIB_PORTS_ChannelSlewRateSelect()
void PLIB_PORTS_ChannelSlewRateSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK channelMask, PORTS_PIN_SLEW_RATE slewRate)
PLIB_PORTS_Clear()
void PLIB_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
PLIB_PORTS_CnPinsDisable()
void PLIB_PORTS_CnPinsDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsEnable()
void PLIB_PORTS_CnPinsEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsPullUpDisable()
void PLIB_PORTS_CnPinsPullUpDisable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_CnPinsPullUpEnable()
void PLIB_PORTS_CnPinsPullUpEnable (PORTS_MODULE_ID index, PORTS_CN_PIN cnPins)
PLIB_PORTS_DirectionGet()
PORTS_DATA_MASK PLIB_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_DirectionInputSet()
void PLIB_PORTS_DirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_DirectionOutputSet()
void PLIB_PORTS_DirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_ExistsAnPinsMode()
bool PLIB_PORTS_ExistsAnPinsMode (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNotice()
bool PLIB_PORTS_ExistsChangeNotice (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeEdgeControl()
bool PLIB_PORTS_ExistsChangeNoticeEdgeControl (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeEdgeStatus()
bool PLIB_PORTS_ExistsChangeNoticeEdgeStatus (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticeInIdle()
bool PLIB_PORTS_ExistsChangeNoticeInIdle (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortInIdle()
bool PLIB_PORTS_ExistsChangeNoticePerPortInIdle (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortStatus()
bool PLIB_PORTS_ExistsChangeNoticePerPortStatus (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePerPortTurnOn()
bool PLIB_PORTS_ExistsChangeNoticePerPortTurnOn (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullDownPerPort()
bool PLIB_PORTS_ExistsChangeNoticePullDownPerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullUp()
bool PLIB_PORTS_ExistsChangeNoticePullUp (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChangeNoticePullUpPerPort()
bool PLIB_PORTS_ExistsChangeNoticePullUpPerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsChannelChangeNoticeMethod()
bool PLIB_PORTS_ExistsChannelChangeNoticeMethod (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsLatchRead()
bool PLIB_PORTS_ExistsLatchRead (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinChangeNotice()
bool PLIB_PORTS_ExistsPinChangeNotice (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinChangeNoticePerPort()
bool PLIB_PORTS_ExistsPinChangeNoticePerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinMode()
bool PLIB_PORTS_ExistsPinMode (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPinModePerPort()
bool PLIB_PORTS_ExistsPinModePerPort (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsDirection()
bool PLIB_PORTS_ExistsPortsDirection (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsOpenDrain()
bool PLIB_PORTS_ExistsPortsOpenDrain (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsRead()
bool PLIB_PORTS_ExistsPortsRead (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsPortsWrite()
bool PLIB_PORTS_ExistsPortsWrite (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsRemapInput()
bool PLIB_PORTS_ExistsRemapInput (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsRemapOutput()
bool PLIB_PORTS_ExistsRemapOutput (PORTS_MODULE_ID index)
PLIB_PORTS_ExistsSlewRateControl()
bool PLIB_PORTS_ExistsSlewRateControl (PORTS_MODULE_ID index)
PLIB_PORTS_OpenDrainDisable()
void PLIB_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_OpenDrainEnable()
void PLIB_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
PLIB_PORTS_PinChangeNoticeDisable()
void PLIB_PORTS_PinChangeNoticeDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_PinChangeNoticeEdgeHasOccurred()
bool PLIB_PORTS_PinChangeNoticeEdgeHasOccurred (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinChangeNoticeEdgeIsEnabled()
bool PLIB_PORTS_PinChangeNoticeEdgeIsEnabled (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_CHANGE_NOTICE_EDGE cnEdgeType)
PLIB_PORTS_PinChangeNoticeEnable()
void PLIB_PORTS_PinChangeNoticeEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
PLIB_PORTS_PinChangeNoticePerPortDisable()
void PLIB_PORTS_PinChangeNoticePerPortDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinChangeNoticePerPortEnable()
void PLIB_PORTS_PinChangeNoticePerPortEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinClear()
void PLIB_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinDirectionInputSet()
void PLIB_PORTS_PinDirectionInputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinDirectionOutputSet()
void PLIB_PORTS_PinDirectionOutputSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinGet()
bool PLIB_PORTS_PinGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinGetLatched()
bool PLIB_PORTS_PinGetLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinModePerPortSelect()
void PLIB_PORTS_PinModePerPortSelect (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_MODE mode)
PLIB_PORTS_PinModeSelect()
void PLIB_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
PLIB_PORTS_PinOpenDrainDisable()
void PLIB_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinOpenDrainEnable()
void PLIB_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinSet()
void PLIB_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinSlewRateGet()
PORTS_PIN_SLEW_RATE PLIB_PORTS_PinSlewRateGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinToggle()
void PLIB_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
PLIB_PORTS_PinWrite()
void PLIB_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
PLIB_PORTS_Read()
PORTS_DATA_TYPE PLIB_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_ReadLatched()
PORTS_DATA_TYPE PLIB_PORTS_ReadLatched (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
PLIB_PORTS_RemapInput()
void PLIB_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION inputFunction, PORTS_REMAP_INPUT_PIN remapInputPin)
PLIB_PORTS_RemapOutput()
void PLIB_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION outputFunction, PORTS_REMAP_OUTPUT_PIN remapOutputPin)
PLIB_PORTS_Set()
void PLIB_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
PLIB_PORTS_Toggle()
void PLIB_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
PLIB_PORTS_Write()
void PLIB_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
qqbmsoutput()
static void qqbmsoutput (FILEPOINT char * s, unsigned int i) static
Definition at line 6985 of file inszt_main.c.
qqoutput()
static void qqoutput (FILEPOINT char * s, int i) static
Definition at line 6818 of file inszt_main.c.
qqoutput0()
static void qqoutput0 (FILEPOINT char * s) static
Definition at line 6831 of file inszt_main.c.
qqoutput2()
static void qqoutput2 (FILEPOINT char * s, int i, int j) static
Definition at line 6839 of file inszt_main.c.
qqoutput3()
static void qqoutput3 (FILEPOINT char * s, int i, int j, int k) static
Definition at line 6848 of file inszt_main.c.
qqoutput4()
static void qqoutput4 (FILEPOINT char * s, int i, int j, int k, int l) static
Definition at line 6857 of file inszt_main.c.
qqpopulate_array_fcn_ptrQQ()
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
Definition at line 157 of file inszt_main.c.
Referenced by adc_63zqendz(), app_64zqendz(), cf_52zqendz(), commands_65zqendz(), commmodule_53zqendz(), crc_54zqendz(), fifo_55zqendz(), fsk_60zqendz(), hvps_61zqendz(), hvps_test_67zqendz(), man_59zqendz(), statusst_58zqendz(), switches_57zqendz(), system_okay_69zqendz(), test_70zqendz(), timers_56zqendz(), UART_71zqendz(), USB_62zqendz(), wl_cps_51zqendz(), and wl_sps_50zqendz().
qqqbitmapreset() [1/2]
static void qqqbitmapreset (qqnull_params) static
qqqbitmapreset() [2/2]
static void qqqbitmapreset () static
Definition at line 6889 of file inszt_main.c.
qqqqinitialise()
static void qqqqinitialise (int ii) static
Definition at line 6872 of file inszt_main.c.
Referenced by main_68zqqzqz1().
qqqtotalreset()
void qqqtotalreset (void)
Definition at line 7067 of file inszt_main.c.
qqqtotalupload()
void qqqtotalupload (void)
Definition at line 7054 of file inszt_main.c.
Referenced by upload_execution_history().
qqqupload()
static void qqqupload (qqnull_params) static
Definition at line 7010 of file inszt_main.c.
Referenced by upload_execution_history().
SYS_PORTS_ChangeNotificationDisable()
void SYS_PORTS_ChangeNotificationDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_ChangeNotificationEnable()
void SYS_PORTS_ChangeNotificationEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum, SYS_PORTS_PULLUP_PULLDOWN_STATUS value)
SYS_PORTS_ChangeNotificationGlobalDisable()
void SYS_PORTS_ChangeNotificationGlobalDisable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationGlobalEnable()
void SYS_PORTS_ChangeNotificationGlobalEnable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationInIdleModeDisable()
void SYS_PORTS_ChangeNotificationInIdleModeDisable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationInIdleModeEnable()
void SYS_PORTS_ChangeNotificationInIdleModeEnable (PORTS_MODULE_ID index)
SYS_PORTS_ChangeNotificationPullUpDisable()
void SYS_PORTS_ChangeNotificationPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_ChangeNotificationPullUpEnable()
void SYS_PORTS_ChangeNotificationPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANGE_NOTICE_PIN pinNum)
SYS_PORTS_Clear()
void SYS_PORTS_Clear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK clearMask)
SYS_PORTS_DirectionGet()
PORTS_DATA_MASK SYS_PORTS_DirectionGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_DirectionSelect()
void SYS_PORTS_DirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_Initialize()
void SYS_PORTS_Initialize ()
SYS_PORTS_InterruptEnable()
void SYS_PORTS_InterruptEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, PORTS_PIN_INTERRUPT_TYPE pinInterruptType)
SYS_PORTS_InterruptStatusGet()
PORTS_DATA_TYPE SYS_PORTS_InterruptStatusGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_LatchedGet()
PORTS_DATA_TYPE SYS_PORTS_LatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_OpenDrainDisable()
void SYS_PORTS_OpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_OpenDrainEnable()
void SYS_PORTS_OpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK mask)
SYS_PORTS_PinClear()
void SYS_PORTS_PinClear (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinDirectionSelect()
void SYS_PORTS_PinDirectionSelect (PORTS_MODULE_ID index, SYS_PORTS_PIN_DIRECTION pinDir, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinLatchedGet()
bool SYS_PORTS_PinLatchedGet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinModeSelect()
void SYS_PORTS_PinModeSelect (PORTS_MODULE_ID index, PORTS_ANALOG_PIN pin, PORTS_PIN_MODE mode)
SYS_PORTS_PinOpenDrainDisable()
void SYS_PORTS_PinOpenDrainDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinOpenDrainEnable()
void SYS_PORTS_PinOpenDrainEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullDownDisable()
void SYS_PORTS_PinPullDownDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullDownEnable()
void SYS_PORTS_PinPullDownEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullUpDisable()
void SYS_PORTS_PinPullUpDisable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinPullUpEnable()
void SYS_PORTS_PinPullUpEnable (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinRead()
bool SYS_PORTS_PinRead (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinSet()
void SYS_PORTS_PinSet (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinToggle()
void SYS_PORTS_PinToggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos)
SYS_PORTS_PinWrite()
void SYS_PORTS_PinWrite (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_BIT_POS bitPos, bool value)
SYS_PORTS_Read()
PORTS_DATA_TYPE SYS_PORTS_Read (PORTS_MODULE_ID index, PORTS_CHANNEL channel)
SYS_PORTS_RemapInput()
void SYS_PORTS_RemapInput (PORTS_MODULE_ID index, PORTS_REMAP_INPUT_FUNCTION function, PORTS_REMAP_INPUT_PIN remapPin)
SYS_PORTS_RemapOutput()
void SYS_PORTS_RemapOutput (PORTS_MODULE_ID index, PORTS_REMAP_OUTPUT_FUNCTION function, PORTS_REMAP_OUTPUT_PIN remapPin)
SYS_PORTS_Set()
void SYS_PORTS_Set (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value, PORTS_DATA_MASK mask)
SYS_PORTS_Toggle()
void SYS_PORTS_Toggle (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_MASK toggleMask)
SYS_PORTS_Write()
void SYS_PORTS_Write (PORTS_MODULE_ID index, PORTS_CHANNEL channel, PORTS_DATA_TYPE value)
TEST_Tasks()
void TEST_Tasks (void)
Function: void TEST_Tasks (void) Summary: Function to perform self test on PIB controller before system initialization. Remarks: Refer to the test.h interface header for function usage details.
Definition at line 7087 of file inszt_test.c.
Referenced by main().
upload_execution_history()
LDRA_PRAGMA_NO_OPTIMISATION void LDRA_NO_OPTIMISATION upload_execution_history (void)
Definition at line 6719 of file inszt_main.c.
Referenced by main_68zqendz().
Variable Documentation
APP
APP_DATA APP
Definition at line 73 of file app.c.
bitmapstruct
struct bitmapstruct_t bitmapstruct static
Initial value:
= {
#define ELEMENT(N)
  0}
Referenced by DRV_TMR0_Close(), DRV_TMR0_DeInitialize(), DRV_TMR0_Open(), DRV_TMR0_OperationModeGet(), DRV_TMR0_Status(), DRV_TMR0_Tasks(), DRV_TMR1_Close(), DRV_TMR1_DeInitialize(), DRV_TMR1_Open(), DRV_TMR1_OperationModeGet(), DRV_TMR1_Status(), DRV_TMR1_Tasks(), DRV_TMR2_Close(), DRV_TMR2_DeInitialize(), DRV_TMR2_Open(), DRV_TMR2_OperationModeGet(), DRV_TMR2_Status(), DRV_TMR2_Tasks(), DRV_TMR3_Close(), DRV_TMR3_DeInitialize(), DRV_TMR3_Open(), DRV_TMR3_OperationModeGet(), DRV_TMR3_Status(), DRV_TMR3_Tasks(), DRV_TMR4_Close(), DRV_TMR4_DeInitialize(), DRV_TMR4_Open(), DRV_TMR4_OperationModeGet(), DRV_TMR4_Status(), DRV_TMR4_Tasks(), main(), and qqqbitmapreset().
main_68zzopen
int main_68zzopen = 0
Definition at line 107 of file inszt_main.c.
qqqaccumreset
ldra_void_function qqqaccumreset[QQQnumfil]
Definition at line 154 of file inszt_main.c.
Referenced by qqpopulate_array_fcn_ptrQQ(), and qqqtotalreset().
qqqaccumupload
ldra_void_function qqqaccumupload[QQQnumfil]
Definition at line 153 of file inszt_main.c.
Referenced by qqpopulate_array_fcn_ptrQQ(), and qqqtotalupload().
QQQfcn_ptr_num
int QQQfcn_ptr_num = 0
Definition at line 151 of file inszt_main.c.
Referenced by adc_63zqendz(), app_64zqendz(), cf_52zqendz(), commands_65zqendz(), commmodule_53zqendz(), crc_54zqendz(), fifo_55zqendz(), fsk_60zqendz(), hvps_61zqendz(), hvps_test_67zqendz(), man_59zqendz(), qqpopulate_array_fcn_ptrQQ(), qqqtotalreset(), qqqtotalupload(), statusst_58zqendz(), switches_57zqendz(), system_okay_69zqendz(), test_70zqendz(), timers_56zqendz(), UART_71zqendz(), USB_62zqendz(), wl_cps_51zqendz(), and wl_sps_50zqendz().
QQQfirstmcdc
int QQQfirstmcdc =1
Definition at line 105 of file inszt_main.c.
QQQindicator
int QQQindicator =0
Definition at line 104 of file inszt_main.c.
qqqisinitialised
int qqqisinitialised = 0 static
Definition at line 152 of file inszt_main.c.
qqqlast
int qqqlast = 0 static
Definition at line 6756 of file inszt_main.c.
Referenced by main_68zqendz(), qqqqinitialise(), and qqqupload().
qqqqbmselwidth
int qqqqbmselwidth = 32 static
Definition at line 78 of file inszt_main.c.
Referenced by qqbmsoutput().
qqqqone
char qqqqone[] = "%6d\n" static
Definition at line 6752 of file inszt_main.c.
qqqshell_upload
int qqqshell_upload = 0
Definition at line 150 of file inszt_main.c.
Referenced by upload_execution_history().
qqqzzglobflag
unsigned char qqqzzglobflag = 0 static
Definition at line 196 of file inszt_main.c.
qqupload_registered
int qqupload_registered = 0
Definition at line 6760 of file inszt_main.c.
qqzzglobarrb
unsigned int* qqzzglobarrb[QQQnumfil]
Definition at line 6757 of file inszt_main.c.
qqzzglobbrns
short qqzzglobbrns[QQQnumfil] = {0}
Definition at line 6758 of file inszt_main.c.
qqzzglobfileid
short qqzzglobfileid[QQQnumfil] = {0}
Definition at line 6759 of file inszt_main.c.
sysObj
SYSTEM_OBJECTS sysObj
tbrun_mode
int tbrun_mode =0 static
Definition at line 126 of file inszt_main.c.
Referenced by upload_execution_history().
TEST_FLAG
ClassB_Test_Flags TEST_FLAG
Definition at line 6691 of file inszt_test.c.
Referenced by SYSTEM_OKAY_Tasks().
zzfileid
int zzfileid = 68 static
Definition at line 79 of file inszt_main.c.
Referenced by qqbmsoutput(), and qqoutput().