Panel Interface Board: inszt_fifo.c File Reference
inszt_fifo.c File Reference
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port.h"
#include "C:\LDRA_Toolsuite\Compiler_spec\Microchip\Mplabx_xc32_script\ldra_port_common.h"
#include "fifo_55zbelem.def"
#include <stdbool.h>
#include <stdint.h>
Data Structures
struct bitmapstruct_t
struct TFifo
Macros
#define QQQdialect MPLABX
#define QQQswitch3
#define qqqMaxBranchDepth 20
#define QQQstructbitmap
#define QQQnumfil 23
#define QQQNOATEXIT
#define QQQUPLOADATEND
#define QQQNOSTDIO
#define QQQBITMAP
#define qqqbitmapint unsigned int
#define QQQSINGLEFILE
#define QQQFILEID
#define QQQseparate
#define fifo_55zzopen zzopen
#define fifo_55zqqzqz1 zqqzqz1
#define QQQLDRA_PORT
#define FILEPOINT
#define LDRA_VOID_FUNC
#define qqnull_params void
#define QQQ_PROTOTYPE_DEF
#define ELEMENT(N) qqqbitmapint element##N;
#define LASTELEMENT
#define ELEMENT(N) 0,
#define FIFO_H
#define FIFO_RX_SIZE 7
#define FIFO_TX_SIZE 7
#define FIFO_ADD_OK 0
#define FIFO_FULL 1
#define FIFO_EMPTY 2U
#define qqqbranches 26
#define QQQMAXMCDCSIZE 2
#define ldra_sscanf
#define qqnull_params void
#define qqzzidfield 1
#define QQQFIXEDSIZE
#define QQQTEMP1
#define ELEMENT(N) qqbmsoutput("%8d", bitmapstruct.element##N);
#define LASTELEMENT
Typedefs
typedef void(* ldra_void_function) ()
typedef unsigned char uchar8_t
Functions
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
static void qqoutput (FILEPOINT char *s, int i)
static void qqoutput2 (FILEPOINT char *s, int i, int j)
static void qqoutput3 (FILEPOINT char *s, int i, int j, int k)
static void qqoutput4 (FILEPOINT char *s, int i, int j, int k, int l)
static void qqoutput0 (FILEPOINT char *s)
static int fifo_55zqqzqz (qqnull_params)
static int fifo_55zqqzqz1 (qqnull_params)
static int fifo_55zqendz (int qqqi)
static int fifo_55zqzqzq (int qqqi)
static void qqqupload (qqnull_params)
static void qqqbitmapreset (qqnull_params)
static void Fifo_Init (TFifo *ptrFifo, uint8_t *ptrBuffer, uint16_t Length)
void Init_Fifo (void)
uint8_t Fifo_Put (TFifo *ptrFifo, uint8_t Data)
uint8_t Fifo_Get (TFifo *ptrFifo)
uint8_t Fifo_Length (TFifo *ptrFifo)
static int fifo_55zscanf (char *qqscan_str)
static void qqqqinitialise (int ii)
static void qqqbitmapreset ()
static void qqbmsoutput (FILEPOINT char *s, unsigned int i)
Variables
static int qqqqbmselwidth = 32
static int zzfileid = 55
int QQQindicator
static int QQQfirstmcdc =1
int fifo_55zzopen
static int tbrun_mode =0
int QQQfcn_ptr_num
ldra_void_function qqqaccumupload [QQQnumfil]
static int qqqstructzzopen = 0
static unsigned char qqqzzglobflag = 0
static struct bitmapstruct_t bitmapstruct
TFifo RX_FIFO
TFifo TX_FIFO
static uint8_t FifoRxBuffer [7]
static uint8_t FifoTxBuffer [7]
static char qqqqone [] = "%6d\n"
static int qqqlast = 0
int qqupload_registered
Macro Definition Documentation
ELEMENT [1/3]
#define ELEMENT (N) qqqbitmapint element##N;
Definition at line 168 of file inszt_fifo.c.
ELEMENT [2/3]
#define ELEMENT (N) 0,
Definition at line 168 of file inszt_fifo.c.
ELEMENT [3/3]
#define ELEMENT (N) qqbmsoutput("%8d", bitmapstruct.element##N);
Definition at line 168 of file inszt_fifo.c.
fifo_55zqqzqz1
#define fifo_55zqqzqz1 zqqzqz1
Definition at line 77 of file inszt_fifo.c.
Referenced by fifo_55zqendz(), fifo_55zqzqzq(), and qqqupload().
fifo_55zzopen
#define fifo_55zzopen zzopen
Definition at line 75 of file inszt_fifo.c.
Referenced by fifo_55zqendz(), fifo_55zqqzqz(), fifo_55zqqzqz1(), and fifo_55zqzqzq().
FIFO_ADD_OK
#define FIFO_ADD_OK 0
Definition at line 224 of file inszt_fifo.c.
FIFO_EMPTY
#define FIFO_EMPTY 2U
Definition at line 227 of file inszt_fifo.c.
FIFO_FULL
#define FIFO_FULL 1
Definition at line 225 of file inszt_fifo.c.
FIFO_H
#define FIFO_H
Definition at line 208 of file inszt_fifo.c.
FIFO_RX_SIZE
#define FIFO_RX_SIZE 7
Definition at line 221 of file inszt_fifo.c.
FIFO_TX_SIZE
#define FIFO_TX_SIZE 7
Definition at line 222 of file inszt_fifo.c.
FILEPOINT
#define FILEPOINT
Definition at line 90 of file inszt_fifo.c.
LASTELEMENT [1/2]
#define LASTELEMENT
Definition at line 169 of file inszt_fifo.c.
LASTELEMENT [2/2]
#define LASTELEMENT
Definition at line 169 of file inszt_fifo.c.
ldra_sscanf
#define ldra_sscanf
Definition at line 668 of file inszt_fifo.c.
LDRA_VOID_FUNC
#define LDRA_VOID_FUNC
Definition at line 112 of file inszt_fifo.c.
qqnull_params [1/2]
#define qqnull_params void
Definition at line 685 of file inszt_fifo.c.
qqnull_params [2/2]
#define qqnull_params void
Definition at line 685 of file inszt_fifo.c.
QQQ_PROTOTYPE_DEF
#define QQQ_PROTOTYPE_DEF
Definition at line 155 of file inszt_fifo.c.
QQQBITMAP
#define QQQBITMAP
Definition at line 63 of file inszt_fifo.c.
qqqbitmapint
#define qqqbitmapint unsigned int
Definition at line 64 of file inszt_fifo.c.
qqqbranches
#define qqqbranches 26
Definition at line 663 of file inszt_fifo.c.
Referenced by qqbmsoutput().
QQQdialect
#define QQQdialect MPLABX
Definition at line 28 of file inszt_fifo.c.
QQQFILEID
#define QQQFILEID
Definition at line 71 of file inszt_fifo.c.
QQQFIXEDSIZE
#define QQQFIXEDSIZE
Definition at line 693 of file inszt_fifo.c.
QQQLDRA_PORT
#define QQQLDRA_PORT
Definition at line 78 of file inszt_fifo.c.
qqqMaxBranchDepth
#define qqqMaxBranchDepth 20
Definition at line 45 of file inszt_fifo.c.
QQQMAXMCDCSIZE
#define QQQMAXMCDCSIZE 2
Definition at line 664 of file inszt_fifo.c.
QQQNOATEXIT
#define QQQNOATEXIT
Definition at line 59 of file inszt_fifo.c.
QQQNOSTDIO
#define QQQNOSTDIO
Definition at line 61 of file inszt_fifo.c.
QQQnumfil
#define QQQnumfil 23
Definition at line 49 of file inszt_fifo.c.
QQQseparate
#define QQQseparate
Definition at line 72 of file inszt_fifo.c.
QQQSINGLEFILE
#define QQQSINGLEFILE
Definition at line 70 of file inszt_fifo.c.
QQQstructbitmap
#define QQQstructbitmap
Definition at line 46 of file inszt_fifo.c.
QQQswitch3
#define QQQswitch3
Definition at line 38 of file inszt_fifo.c.
QQQTEMP1
#define QQQTEMP1
Definition at line 830 of file inszt_fifo.c.
QQQUPLOADATEND
#define QQQUPLOADATEND
Definition at line 60 of file inszt_fifo.c.
qqzzidfield
#define qqzzidfield 1
Definition at line 687 of file inszt_fifo.c.
Typedef Documentation
ldra_void_function
typedef void(* ldra_void_function) ()
Definition at line 113 of file inszt_fifo.c.
uchar8_t
typedef unsigned char uchar8_t
Definition at line 411 of file inszt_fifo.c.
Function Documentation
fifo_55zqendz()
static int fifo_55zqendz (int qqqi) static
Definition at line 875 of file inszt_fifo.c.
Referenced by fifo_55zqzqzq(), Fifo_Get(), Fifo_Init(), Fifo_Length(), Fifo_Put(), and Init_Fifo().
fifo_55zqqzqz()
static int fifo_55zqqzqz (qqnull_params) static
Definition at line 840 of file inszt_fifo.c.
fifo_55zqqzqz1()
static int fifo_55zqqzqz1 (qqnull_params) static
Definition at line 860 of file inszt_fifo.c.
fifo_55zqzqzq()
static int fifo_55zqzqzq (int qqqi) static
Definition at line 960 of file inszt_fifo.c.
fifo_55zscanf()
static int fifo_55zscanf (char * qqscan_str) static
Definition at line 706 of file inszt_fifo.c.
Fifo_Get()
uint8_t Fifo_Get (TFifo * ptrFifo)
Function: uint8_t Fifo_Get(TFifo *ptrFifo) Summary: Function to retrieve an entry from Fifo. Description: Function to retrieve an entry from Fifo. If Fifo is empty then function returns FIFO_EMPTY. Otherwise, the function returns the oldest entry in FifoBuffer and increments FifoTail.
Precondition: None. Parameters: TFifo *ptrFifo Returns uint8_t Contents of Fifo buffer.
Remarks: None.
Example: temp = Fifo_Get(&RX_FIFO)
Function: uint8_t Fifo_Get(TFifo *ptrFifo) Summary: Function to retrieve the oldest entry from a Fifo. It also provides a check for an empty Fifo. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 581 of file inszt_fifo.c.
Referenced by USB_Tasks(), ValidateComm(), and WriteUART().
Fifo_Init()
static void Fifo_Init (TFifo * ptrFifo, uint8_t * ptrBuffer, uint16_t Length) static
Function: static void Fifo_Init(TFifo *ptrFifo, unsigned char *ptrBuffer, int Length) Summary: This function initializes a given Fifo. Description: This function initializes the communication Fifo. It is used to initialize both the transmit and receive Fifo's.
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: Fifo_Init(&RX_FIFO, FifoRxBuffer, FIFO_RX_SIZE)
Function: void Fifo_Init(TFifo *ptrFifo, uint8_t *ptrBuffer, uint16_t Length) Summary: Function to initialize a Fifo. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 454 of file inszt_fifo.c.
Referenced by Init_Fifo().
Fifo_Length()
uint8_t Fifo_Length (TFifo * ptrFifo)
Function: uint8_t Fifo_Length(TFifo *ptrFifo) Summary: Function to find the length of the buffer. Description: Function to find the length of the buffer.
Precondition: None. Parameters: TFifo *ptrFifo: The pointer to the Fifo. Returns uint8_t. Length of the fifo buffer.
Remarks: None.
Example: if(Fifo_Length(&RX_FIFO) == CMD.cmd_size)
Definition at line 651 of file inszt_fifo.c.
Referenced by USB_Tasks().
Fifo_Put()
uint8_t Fifo_Put (TFifo * ptrFifo, uint8_t Data)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data) Summary: Function to add an entry (byte)to a Fifo. Description: Function to add an entry (byte)to a Fifo. If the Fifo is full then the function returns FIFO_FULL, otherwise the function adds the entry to the FifoBuffer, increments FifoHead and returns FIFO_ADD_OK.
Precondition: None. Parameters: uint8_t Data: The byte of data to be added. TFifo *ptrFifo: The pointer to the Fifo that is being manipulated. Returns integer value. Fifo_Full or FIFO_ADD_OK
Remarks: None.
Example: Fifo_Put(&TX_FIFO, b_comm_crc)
Function: uint8_t Fifo_Put(TFifo *ptrFifo, uint8_t Data) Summary: Function to put a byte of data into a Fifo. It also provides a check for a full Fifo. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 511 of file inszt_fifo.c.
Referenced by Prepare_Return_A(), Prepare_Return_B(), ReadUART(), and USB_Tasks().
Init_Fifo()
void Init_Fifo (void)
Function: void Init_Fifo(void) Summary: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. Description: This function calls the function Fifo_Init to initialize the RxFifo and TxFifo. This function is called in APP_Initialize in app.c
Precondition: None. Parameters: None. Returns None.
Remarks: None.
Example: Init_Fifo()
Function: void Init_Fifo(void) Summary: Function to initialize the Tx and Rx FIFOs. Remarks: Refer to the fifo.h interface header for function usage details.
Definition at line 487 of file inszt_fifo.c.
Referenced by APP_Initialize().
qqbmsoutput()
static void qqbmsoutput (FILEPOINT char * s, unsigned int i) static
Definition at line 912 of file inszt_fifo.c.
qqoutput()
static void qqoutput (FILEPOINT char * s, int i) static
Definition at line 753 of file inszt_fifo.c.
qqoutput0()
static void qqoutput0 (FILEPOINT char * s) static
Definition at line 766 of file inszt_fifo.c.
qqoutput2()
static void qqoutput2 (FILEPOINT char * s, int i, int j) static
Definition at line 774 of file inszt_fifo.c.
qqoutput3()
static void qqoutput3 (FILEPOINT char * s, int i, int j, int k) static
Definition at line 783 of file inszt_fifo.c.
qqoutput4()
static void qqoutput4 (FILEPOINT char * s, int i, int j, int k, int l) static
Definition at line 792 of file inszt_fifo.c.
qqpopulate_array_fcn_ptrQQ()
void qqpopulate_array_fcn_ptrQQ (int x, ldra_void_function y, ldra_void_function z)
Definition at line 157 of file inszt_main.c.
Referenced by fifo_55zqendz().
qqqbitmapreset() [1/2]
static void qqqbitmapreset (qqnull_params) static
Referenced by fifo_55zqendz().
qqqbitmapreset() [2/2]
static void qqqbitmapreset () static
Definition at line 824 of file inszt_fifo.c.
qqqqinitialise()
static void qqqqinitialise (int ii) static
Definition at line 807 of file inszt_fifo.c.
Referenced by fifo_55zqqzqz1().
qqqupload()
static void qqqupload (qqnull_params) static
Definition at line 937 of file inszt_fifo.c.
Referenced by fifo_55zqendz().
Variable Documentation
bitmapstruct
struct bitmapstruct_t bitmapstruct static
Initial value:
= {
#define ELEMENT(N)
  0}
Referenced by Fifo_Get(), Fifo_Init(), Fifo_Length(), Fifo_Put(), Init_Fifo(), and qqqbitmapreset().
fifo_55zzopen
int fifo_55zzopen
FifoRxBuffer
uint8_t FifoRxBuffer[7] static
Definition at line 435 of file inszt_fifo.c.
Referenced by Init_Fifo().
FifoTxBuffer
uint8_t FifoTxBuffer[7] static
Definition at line 438 of file inszt_fifo.c.
Referenced by Init_Fifo().
qqqaccumupload
ldra_void_function qqqaccumupload[QQQnumfil]
Definition at line 153 of file inszt_main.c.
QQQfcn_ptr_num
int QQQfcn_ptr_num
Definition at line 151 of file inszt_main.c.
Referenced by fifo_55zqendz().
QQQfirstmcdc
int QQQfirstmcdc =1 static
Definition at line 74 of file inszt_fifo.c.
QQQindicator
int QQQindicator
Definition at line 104 of file inszt_main.c.
qqqlast
int qqqlast = 0 static
Definition at line 694 of file inszt_fifo.c.
Referenced by fifo_55zqendz(), qqqqinitialise(), and qqqupload().
qqqqbmselwidth
int qqqqbmselwidth = 32 static
Definition at line 47 of file inszt_fifo.c.
Referenced by qqbmsoutput().
qqqqone
char qqqqone[] = "%6d\n" static
Definition at line 690 of file inszt_fifo.c.
qqqstructzzopen
int qqqstructzzopen = 0 static
Definition at line 135 of file inszt_fifo.c.
Referenced by fifo_55zqendz().
qqqzzglobflag
unsigned char qqqzzglobflag = 0 static
Definition at line 165 of file inszt_fifo.c.
qqupload_registered
int qqupload_registered
Definition at line 6760 of file inszt_main.c.
RX_FIFO
TFifo RX_FIFO
Definition at line 429 of file inszt_fifo.c.
Referenced by Init_Fifo().
tbrun_mode
int tbrun_mode =0 static
Definition at line 95 of file inszt_fifo.c.
TX_FIFO
TFifo TX_FIFO
Definition at line 432 of file inszt_fifo.c.
Referenced by Init_Fifo().
zzfileid
int zzfileid = 55 static
Definition at line 48 of file inszt_fifo.c.
Referenced by qqbmsoutput(), and qqoutput().