Logging Panel  Interface Board: statusst.c File Reference
statusst.c File Reference
#include "statusst.h"
#include "crc.h"
#include "fifo.h"
#include "fsk.h"
#include "report.h"
#include <stdint.h>
Macros
#define bitset(var, bitno)
#define bitclr(var, bitno)
Functions
void Set_Status (uint8_t bitposn)
void Clear_Status (uint8_t bitposn)
void Prepare_Return_A (uint8_t byte, uint16_t data2, uint16_t data1)
Variables
static uint16_t PIB_Status
Detailed Description
Company: Hunting Titan
File Name: statusst.c
Summary: This file contains functions to manipulate the status register bits used in the Protocol A and B commands.
Description: This file contains functions to manipulate the status register bits used in the Protocol A and B commands. The bits are set or cleared based on switch actions and command responses.
Definition in file statusst.c.
Macro Definition Documentation
bitclr
#define bitclr (var, bitno)
Value:
((var) &= ~ (1UL << (bitno)))
Definition at line 42 of file statusst.c.
Referenced by Clear_Status().
bitset
#define bitset (var, bitno)
Value:
((var) |= 1UL << (bitno))
Definition at line 41 of file statusst.c.
Referenced by Set_Status().
Function Documentation
Clear_Status()
void Clear_Status (uint8_t bitposn)
Function: void Clear_Status(uint8_t bitposn)
Summary: Function to clear a desired bit position to a 0 in the SurfaceStatus register.
Remarks: Refer to the statusst.h interface header for function usage details.
Definition at line 86 of file statusst.c.
Referenced by Execute_Protocol_A(), GAMMA_Counts(), GPT_RX_Tasks(), HIGH_SIDE_Tasks(), SYSTEM_OKAY_Tasks(), and ValidateComm().
Prepare_Return_A()
void Prepare_Return_A (uint8_t byte, uint16_t data2, uint16_t data1)
Function: void Prepare_Return_A(uint8_t byte, uint16_t data2, uint16_t data1)
Summary: Function to prepare the protocol A response.
Remarks: Refer to the statusst.h interface header for function usage details.
Definition at line 102 of file statusst.c.
Referenced by Execute_Auto_Protocol_A(), Execute_Protocol_A(), and ValidateComm().
Set_Status()
void Set_Status (uint8_t bitposn)
Function: void Set_Status(uint8_t bitposn)
Summary: Function to set a desired bit position to a one in the SurfaceStatus register.
Remarks: Refer to the statusst.h interface header for function usage details.
Definition at line 70 of file statusst.c.
Referenced by GAMMA_Counts(), GPT_RX_Tasks(), HIGH_SIDE_Tasks(), SYSTEM_OKAY_Tasks(), and ValidateComm().
Variable Documentation
PIB_Status
uint16_t PIB_Status static
Definition at line 51 of file statusst.c.
Referenced by Clear_Status(), Prepare_Return_A(), and Set_Status().