Logging Panel  Interface Board: wl_cps.c File Reference
wl_cps.c File Reference
#include "wl_cps.h"
#include "app.h"
#include "adc.h"
#include "statusst.h"
#include <math.h>
Functions
void WL_CPS_Tasks (void)
static void Init_WL_CPS (void)
static void Read_WL_CPS_V_I (void)
static void Check_WL_CPS_Over_Current (void)
void Adjust_WL_CPS_Voltage (uint8_t target)
void Set_WL_CPS_CurrentLimit (uint8_t value)
Variables
WL_CPS_DATA WL_CPS
static WL_CPS_STATES CP_STATES
Detailed Description
Company: Hunting Titan
File Name: wl_cps.c
Summary: This file contains the source code for controlling and monitoring the wire-line communications power supply.
Description: This file contains the source code for controlling and monitoring the wire-line communications power supply. It implements the logic of the WL_CPS's state machine. The states are configured so that other system tasks can be maintained while these tasks are waiting for an event to occur. The machine monitors the communication wire line current and voltage and will turn the supply off if an overcurrent or overvoltage condition occurs. Additional functions support commands and operations as needed.
Definition in file wl_cps.c.
Function Documentation
Adjust_WL_CPS_Voltage()
void Adjust_WL_CPS_Voltage (uint8_t target)
Function: void Adjust_WL_CPS_Voltage(uint8_t target)
Summary: Adjust the WL_CPS to the desired voltage.
Remarks: Refer to the wl_cps.h interface header for function usage details.
Definition at line 321 of file wl_cps.c.
Check_WL_CPS_Over_Current()
static void Check_WL_CPS_Over_Current (void) static
Function: static void Check_WL_CPS_Over_Current(void)
Summary: Checks the WL_CPS current for an over current condition and turns the WL_CPS supply off if more than 5 readings in a row occur.
Remarks: Refer to the wl_cps.h interface header for function usage details.
Definition at line 286 of file wl_cps.c.
Referenced by WL_CPS_Tasks().
Init_WL_CPS()
static void Init_WL_CPS (void) static
Function: static void init_WL_CPS(void)
Summary: This function initializes the wire-line communications power supply (WL_CPS).
Remarks: Refer to the wl_cps.h interface header for function usage details.
Definition at line 200 of file wl_cps.c.
Referenced by WL_CPS_Tasks().
Read_WL_CPS_V_I()
static void Read_WL_CPS_V_I (void) static
Function: static Read_WL_CPS_V_I(void)
Summary: This task reads the current and voltage A/D. It stores the max current value.
Remarks: Refer to the wl_cps.h interface header for function usage details.
Definition at line 236 of file wl_cps.c.
Referenced by WL_CPS_Tasks().
Set_WL_CPS_CurrentLimit()
void Set_WL_CPS_CurrentLimit (uint8_t value)
Function: void Set_WL_CPS_CurrentLimit(uint16_t value)
Summary: Sets the WL_CPS current limit.
Remarks: Refer to the wl_cps.h interface header for function usage details.
Definition at line 351 of file wl_cps.c.
Referenced by Execute_Protocol_A().
WL_CPS_Tasks()
void WL_CPS_Tasks (void)
Function:
void WL_CPS_Tasks(void)
Summary: WL_CPS_Tasks function
Description: This routine is the WL_SPS_Tasks function. It defines the WL_SPS_Tasks state machine and core logic. This machine is used to monitor the wire-line communication power supply (WL_CPS) voltage and current and will set flags when those limits are exceeded.
Precondition: The system ("SYS_Initialize") and application ("APP_Initialize")initialization should be called before calling this.
Parameters: None.
Returns: None.
Remarks: This routine must be called from the APP_Tasks() routine.
Example: WL_CPS_Tasks()
Definition at line 101 of file wl_cps.c.
Variable Documentation
CP_STATES
WL_CPS_STATES CP_STATES static
Definition at line 58 of file wl_cps.c.
WL_CPS
WL_CPS_DATA WL_CPS
Definition at line 56 of file wl_cps.c.
Referenced by Adjust_WL_CPS_Voltage(), Calc_Auto_Bias(), Check_WL_CPS_Over_Current(), Execute_Protocol_A(), Init_WL_CPS(), Read_WL_CPS_V_I(), Set_WL_CPS_CurrentLimit(), and WL_CPS_Tasks().